### ISSUE TITLE
Failed to create project: could not resolve LATEST from any configured repositories

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#1010]
On brand new installation with 1.0b4, attempt to create new _Maven-based App Engine Standard Project_ fails:

<img width="605" alt="screen shot 2016-11-23 at 10 10 43 am" src="https://cloud.githubusercontent.com/assets/202851/20567004/1ba56454-b165-11e6-8f4e-1cea852ff7a9.PNG">

Log shows:
```
!ENTRY com.google.cloud.tools.eclipse.appengine.newproject.maven 4 0 2016-11-23 10:09:08.947
!MESSAGE Failed to create project: Could not resolve archetype com.google.appengine.archetypes:appengine-standard-archetype:LATEST from any of the configured repositories.
!STACK 1
org.eclipse.core.runtime.CoreException: Could not resolve archetype com.google.appengine.archetypes:appengine-standard-archetype:LATEST from any of the configured repositories.
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.resolveArchetype(ProjectConfigurationManager.java:877)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.createArchetypeProjects0(ProjectConfigurationManager.java:784)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$5.call(ProjectConfigurationManager.java:760)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$5.call(ProjectConfigurationManager.java:1)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1355)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.createArchetypeProjects(ProjectConfigurationManager.java:758)
	at com.google.cloud.tools.eclipse.appengine.newproject.maven.CreateMavenBasedAppEngineStandardProject.execute(CreateMavenBasedAppEngineStandardProject.java:80)
	at org.eclipse.ui.actions.WorkspaceModifyOperation$1.run(WorkspaceModifyOperation.java:108)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2241)
	at org.eclipse.ui.actions.WorkspaceModifyOperation.run(WorkspaceModifyOperation.java:130)
	at com.google.cloud.tools.eclipse.appengine.newproject.maven.MavenArchetypeProjectWizard$1.run(MavenArchetypeProjectWizard.java:91)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
Caused by: org.eclipse.core.runtime.CoreException: Could not resolve artifact com.google.appengine.archetypes:appengine-standard-archetype:pom:LATEST
	at org.eclipse.m2e.core.internal.embedder.MavenImpl$5.call(MavenImpl.java:776)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl$5.call(MavenImpl.java:1)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.resolve(MavenImpl.java:743)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.resolve(MavenImpl.java:720)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.resolveArchetype(ProjectConfigurationManager.java:870)
	... 14 more
!SUBENTRY 1 org.eclipse.m2e.core 4 -1 2016-11-23 10:09:08.949
!MESSAGE Could not resolve archetype com.google.appengine.archetypes:appengine-standard-archetype:LATEST from any of the configured repositories.
!STACK 1
org.eclipse.core.runtime.CoreException: Could not resolve artifact com.google.appengine.archetypes:appengine-standard-archetype:pom:LATEST
	at org.eclipse.m2e.core.internal.embedder.MavenImpl$5.call(MavenImpl.java:776)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl$5.call(MavenImpl.java:1)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.resolve(MavenImpl.java:743)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.resolve(MavenImpl.java:720)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.resolveArchetype(ProjectConfigurationManager.java:870)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.createArchetypeProjects0(ProjectConfigurationManager.java:784)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$5.call(ProjectConfigurationManager.java:760)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$5.call(ProjectConfigurationManager.java:1)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1355)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.createArchetypeProjects(ProjectConfigurationManager.java:758)
	at com.google.cloud.tools.eclipse.appengine.newproject.maven.CreateMavenBasedAppEngineStandardProject.execute(CreateMavenBasedAppEngineStandardProject.java:80)
	at org.eclipse.ui.actions.WorkspaceModifyOperation$1.run(WorkspaceModifyOperation.java:108)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2241)
	at org.eclipse.ui.actions.WorkspaceModifyOperation.run(WorkspaceModifyOperation.java:130)
	at com.google.cloud.tools.eclipse.appengine.newproject.maven.MavenArchetypeProjectWizard$1.run(MavenArchetypeProjectWizard.java:91)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
Contains: Failed to resolve version for com.google.appengine.archetypes:appengine-standard-archetype:pom:LATEST: Could not find metadata com.google.appengine.archetypes:appengine-standard-archetype/maven-metadata.xml in local (/Users/bsd/.m2/repository)
org.eclipse.aether.resolution.VersionResolutionException: Failed to resolve version for com.google.appengine.archetypes:appengine-standard-archetype:pom:LATEST: Could not find metadata com.google.appengine.archetypes:appengine-standard-archetype/maven-metadata.xml in local (/Users/bsd/.m2/repository)
	at org.apache.maven.repository.internal.DefaultVersionResolver.resolveVersion(DefaultVersionResolver.java:313)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:302)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:294)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl$5.call(MavenImpl.java:753)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl$5.call(MavenImpl.java:1)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.resolve(MavenImpl.java:743)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.resolve(MavenImpl.java:720)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.resolveArchetype(ProjectConfigurationManager.java:870)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.createArchetypeProjects0(ProjectConfigurationManager.java:784)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$5.call(ProjectConfigurationManager.java:760)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$5.call(ProjectConfigurationManager.java:1)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1355)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.createArchetypeProjects(ProjectConfigurationManager.java:758)
	at com.google.cloud.tools.eclipse.appengine.newproject.maven.CreateMavenBasedAppEngineStandardProject.execute(CreateMavenBasedAppEngineStandardProject.java:80)
	at org.eclipse.ui.actions.WorkspaceModifyOperation$1.run(WorkspaceModifyOperation.java:108)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2241)
	at org.eclipse.ui.actions.WorkspaceModifyOperation.run(WorkspaceModifyOperation.java:130)
	at com.google.cloud.tools.eclipse.appengine.newproject.maven.MavenArchetypeProjectWizard$1.run(MavenArchetypeProjectWizard.java:91)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
Caused by: org.eclipse.aether.transfer.MetadataNotFoundException: Could not find metadata com.google.appengine.archetypes:appengine-standard-archetype/maven-metadata.xml in local (/Users/bsd/.m2/repository)
	at org.eclipse.aether.internal.impl.DefaultMetadataResolver.resolve(DefaultMetadataResolver.java:247)
	at org.eclipse.aether.internal.impl.DefaultMetadataResolver.resolveMetadata(DefaultMetadataResolver.java:205)
	at org.apache.maven.repository.internal.DefaultVersionResolver.resolveVersion(DefaultVersionResolver.java:250)
	... 26 more
!SUBENTRY 2 org.eclipse.m2e.core 4 -1 2016-11-23 10:09:08.950
!MESSAGE Could not resolve artifact com.google.appengine.archetypes:appengine-standard-archetype:pom:LATEST
!SUBENTRY 3 org.eclipse.m2e.core 4 -1 2016-11-23 10:09:08.950
!MESSAGE Failed to resolve version for com.google.appengine.archetypes:appengine-standard-archetype:pom:LATEST: Could not find metadata com.google.appengine.archetypes:appengine-standard-archetype/maven-metadata.xml in local (/Users/bsd/.m2/repository)
!STACK 0
org.eclipse.aether.resolution.VersionResolutionException: Failed to resolve version for com.google.appengine.archetypes:appengine-standard-archetype:pom:LATEST: Could not find metadata com.google.appengine.archetypes:appengine-standard-archetype/maven-metadata.xml in local (/Users/bsd/.m2/repository)
	at org.apache.maven.repository.internal.DefaultVersionResolver.resolveVersion(DefaultVersionResolver.java:313)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:302)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:294)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl$5.call(MavenImpl.java:753)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl$5.call(MavenImpl.java:1)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.resolve(MavenImpl.java:743)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.resolve(MavenImpl.java:720)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.resolveArchetype(ProjectConfigurationManager.java:870)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.createArchetypeProjects0(ProjectConfigurationManager.java:784)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$5.call(ProjectConfigurationManager.java:760)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$5.call(ProjectConfigurationManager.java:1)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1355)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.createArchetypeProjects(ProjectConfigurationManager.java:758)
	at com.google.cloud.tools.eclipse.appengine.newproject.maven.CreateMavenBasedAppEngineStandardProject.execute(CreateMavenBasedAppEngineStandardProject.java:80)
	at org.eclipse.ui.actions.WorkspaceModifyOperation$1.run(WorkspaceModifyOperation.java:108)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2241)
	at org.eclipse.ui.actions.WorkspaceModifyOperation.run(WorkspaceModifyOperation.java:130)
	at com.google.cloud.tools.eclipse.appengine.newproject.maven.MavenArchetypeProjectWizard$1.run(MavenArchetypeProjectWizard.java:91)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
Caused by: org.eclipse.aether.transfer.MetadataNotFoundException: Could not find metadata com.google.appengine.archetypes:appengine-standard-archetype/maven-metadata.xml in local (/Users/bsd/.m2/repository)
	at org.eclipse.aether.internal.impl.DefaultMetadataResolver.resolve(DefaultMetadataResolver.java:247)
	at org.eclipse.aether.internal.impl.DefaultMetadataResolver.resolveMetadata(DefaultMetadataResolver.java:205)
	at org.apache.maven.repository.internal.DefaultVersionResolver.resolveVersion(DefaultVersionResolver.java:250)
	... 26 more

```

**Comment by elharo** [comment]
Assigning to @lesv in case there's something up with the archetypes, though that may not be where the bug lies.

**Comment by elharo** [comment]
I am not able to immediately reproduce. It worked for me in Neon a moment ago.

**Comment by briandealwis** [comment]
It's weird as the Guestbook demo works.

**Comment by briandealwis** [comment]
It was a local configuration error.  My local repository had a marker indicating that the archetype couldn't be resolved (`~/.m2/repository/com/google/appengine/archetypes/appengine-standard-archetype/resolver-status.properties`):
```
maven-metadata-appengine-standard-archetype-repo.xml.error=Could not transfer metadata com.google.appengine.archetypes\:appengine-standard-archetype/maven-metadata.xml from/to appengine-standard-archetype-repo (remote)\: Cannot access remote with type default using the available connector factories\: AetherRepositoryConnectorFactory, BasicRepositoryConnectorFactory
```
Removing that file did the trick.
