### ISSUE TITLE
Warnings about undefined facet `com.google.cloud.tools.eclipse.appengine.facets.flex`

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#1011]
I see these warnings when creating new projects.
```
!ENTRY org.eclipse.wst.common.project.facet.core 4 0 2016-11-23 15:09:09.546
!MESSAGE Project facet com.google.cloud.tools.eclipse.appengine.facets.flex has not been defined. It is used in plugin com.google.cloud.tools.eclipse.appengine.facets.
```

**Comment by elharo** [comment]
at head or in the release?

**Comment by briandealwis** [comment]
Hmm, that was with 1.0b4 but I see them with HEAD too.

**Comment by elharo** [comment]
I see this too. Fortunately I don't think it breaks any of our functionality.

@nbashirbello I think we have to take out all references to the flex facet until it's actually checked in and available. We can move that work onto another branch if need be.

**Comment by elharo** [comment]
Just noticed this is getting logged to Eclipse aeri:

The following report will be sent to Eclipse:

------
STATUS
------
pluginId            org.eclipse.wst.common.project.facet.core
pluginVersion       1.4.300.v201111030423
code                0
severity            4
message             Project facet com.google.cloud.tools.eclipse.appengine.facets.flex has not been defined. It is used in plugin com.google.cloud.tools.eclipse.appengine.facets.
fingerprint         1fcac441efe94b972239d538db2a19e5

Exception:org.eclipse.epp.logging.aeri.core.util.NoStackTrace: This event was logged without a stack trace. A synthetic stack trace was hence inserted.
	 at org.eclipse.wst.common.project.facet.core.internal.FacetCorePlugin.log(FacetCorePlugin.java:68)
	 at org.eclipse.wst.common.project.facet.core.internal.FacetCorePlugin.logError(FacetCorePlugin.java:91)
	 at org.eclipse.wst.common.project.facet.core.internal.ProblemLog.reportMissingFacet(ProblemLog.java:144)
	 at org.eclipse.wst.common.project.facet.core.internal.ProblemLog.reportMissingFacet(ProblemLog.java:131)
	 at org.eclipse.wst.common.project.facet.core.internal.FacetedProjectFrameworkImpl.readAction(FacetedProjectFrameworkImpl.java:1817)
	 at org.eclipse.wst.common.project.facet.core.internal.FacetedProjectFrameworkImpl.readMetadata(FacetedProjectFrameworkImpl.java:1410)
	 at org.eclipse.wst.common.project.facet.core.internal.FacetedProjectFrameworkImpl.<init>(FacetedProjectFrameworkImpl.java:188)
	 at org.eclipse.wst.common.project.facet.core.internal.FacetedProjectFrameworkImpl.getInstance(FacetedProjectFrameworkImpl.java:211)
	 at org.eclipse.wst.common.project.facet.core.ProjectFacetsManager.<clinit>(ProjectFacetsManager.java:37)
	 at com.google.cloud.tools.eclipse.appengine.newproject.CreateAppEngineStandardWtpProject.execute(CreateAppEngineStandardWtpProject.java:89)
	 at org.eclipse.ui.actions.WorkspaceModifyOperation$1.run(WorkspaceModifyOperation.java:108)
	 at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2241)
	 at org.eclipse.ui.actions.WorkspaceModifyOperation.run(WorkspaceModifyOperation.java:130)
	 at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)

------
REPORT
------
anonymousId         e8b553d4-2494-4fc5-a56e-3802d79da5ad
name                
email               
comment             
eclipseBuildId      4.5.2.M20160212-1500
eclipseProduct      org.eclipse.epp.package.java.product
javaRuntimeVersion  1.8.0_45-b14
osgiWs              cocoa
osgiOs              MacOSX
osgiOsVersion       10.9.5
osgiArch            x86_64
severity            UNKNOWN

-------
BUNDLES
-------
name                com.google.cloud.tools.eclipse.appengine.newproject
version             0.1.0.201612060506

name                org.eclipse.core.resources
version             3.10.1.v20150725-1910

name                org.eclipse.jface
version             3.11.1.v20160128-1644

name                org.eclipse.ui
version             3.107.0.v20150507-1945

name                org.eclipse.wst.common.project.facet.core
version             1.4.300.v201111030423

We shouldn't do that. Bumping the priority.
