### ISSUE TITLE
NewMavenBasedAppEngineProjectWizardTest is flaky again

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1048]
NewMavenBasedAppEngineProjectWizardTest has gotten very flaky today, possibly (circumstantial evidence) since we upgraded to appengine-plugins-core 0.2.1. Any ideas?

StandardProjectWizardTest and NewNativeAppEngineStandardProjectTest have also been looking flaky. 

```
Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 37.757 sec <<< FAILURE! - in com.google.cloud.tools.eclipse.integration.appengine.NewMavenBasedAppEngineProjectWizardTest
testHelloWorldInTemp(com.google.cloud.tools.eclipse.integration.appengine.NewMavenBasedAppEngineProjectWizardTest)  Time elapsed: 10.705 sec
testGuestbookExample(com.google.cloud.tools.eclipse.integration.appengine.NewMavenBasedAppEngineProjectWizardTest)  Time elapsed: 11.297 sec  <<< ERROR!
org.eclipse.swtbot.swt.finder.exceptions.WidgetNotFoundException: Could not find widget matching: (of type 'Button' and with mnemonic 'Create project in workspace' and with style 'SWT.CHECK')
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:437)
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:411)
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:399)
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntilWidgetAppears(SWTBotFactory.java:381)
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.widget(SWTBotFactory.java:334)
	at org.eclipse.swtbot.swt.finder.SWTBot.checkBox(SWTBot.java:572)
	at org.eclipse.swtbot.swt.finder.SWTBot.checkBox(SWTBot.java:560)
	at com.google.cloud.tools.eclipse.integration.appengine.SwtBotAppEngineActions.createMavenWebAppProject(SwtBotAppEngineActions.java:89)
	at com.google.cloud.tools.eclipse.integration.appengine.NewMavenBasedAppEngineProjectWizardTest.createAndCheck(NewMavenBasedAppEngineProjectWizardTest.java:91)
	at com.google.cloud.tools.eclipse.integration.appengine.NewMavenBasedAppEngineProjectWizardTest.testGuestbookExample(NewMavenBasedAppEngineProjectWizardTest.java:72)
```

**Comment by elharo** [comment]
Some of this is due to version checks. In particular CloudSdk.getVersion fails. Look into appengine-plugins-core and see how reliable the version loading really is.

com.google.cloud.tools.eclipse.integration.appengine.NewNativeAppEngineStandardProjectTest
com.google.cloud.tools.eclipse.integration.appengine.NewNativeAppEngineStandardProjectTest  Time elapsed: 0.566 sec  <<< ERROR!
java.lang.IllegalArgumentException: null
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:111)
	at com.google.cloud.tools.appengine.cloudsdk.serialization.CloudSdkVersion.<init>(CloudSdkVersion.java:52)
	at com.google.cloud.tools.appengine.cloudsdk.CloudSdk.getVersion(CloudSdk.java:296)
	at com.google.cloud.tools.appengine.cloudsdk.CloudSdk.validateCloudSdkVersion(CloudSdk.java:390)
	at com.google.cloud.tools.appengine.cloudsdk.CloudSdk.validateCloudSdk(CloudSdk.java:385)
	at com.google.cloud.tools.eclipse.integration.appengine.AbstractProjectTests.setUp(AbstractProjectTests.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

**Comment by elharo** [comment]
I may have found a race condition that is causing our observed behavior:

https://github.com/GoogleCloudPlatform/appengine-plugins-core/issues/269

**Comment by briandealwis** [comment]
The first issue also looks like #1383.  Haven't seen the others, so closing and we can re-open if it re-occurs.
