### ISSUE TITLE
Flaky CreateAppEngineStandardWtpProjectTest

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1086]
This failure is clearly flaky--The only change was to a README--But it happens a lot.  Figure out why and prevent it. 

```
Tests run: 4, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 6.753 sec <<< FAILURE! - in com.google.cloud.tools.eclipse.appengine.newproject.CreateAppEngineStandardWtpProjectTest
testAppEngineLibrariesAdded(com.google.cloud.tools.eclipse.appengine.newproject.CreateAppEngineStandardWtpProjectTest)  Time elapsed: 5.908 sec  <<< ERROR!
org.eclipse.core.runtime.CoreException: Primary runtime has to be one of the targeted runtimes.
	at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.setPrimaryRuntimeInternal(FacetedProject.java:864)
	at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.access$5(FacetedProject.java:837)
	at org.eclipse.wst.common.project.facet.core.internal.FacetedProject$4.run(FacetedProject.java:819)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2241)
	at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.setPrimaryRuntime(FacetedProject.java:829)
	at com.google.cloud.tools.eclipse.appengine.facets.AppEngineStandardFacet.installAllAppEngineRuntimes(AppEngineStandardFacet.java:171)
	at com.google.cloud.tools.eclipse.appengine.newproject.CreateAppEngineStandardWtpProject.execute(CreateAppEngineStandardWtpProject.java:94)
	at com.google.cloud.tools.eclipse.appengine.newproject.CreateAppEngineStandardWtpProjectTest.testAppEngineLibrariesAdded(CreateAppEngineStandardWtpProjectTest.java:102)
```

**Comment by briandealwis** [comment]
@chanseokoh: I suspect there's some interaction with `AppEngineStandardRuntimeChangeListener`, which has code to remove a target runtime.

**Comment by chanseokoh** [comment]
@briandealwis That's interesting. It's still puzzling to me though. I believe the listener is called synchronously inside `setPrimaryRuntime()` after it successfully sets a primary runtime (which is App Engine runtime) in normal test executions. That is, I think the error was thrown before the listener can have a chance to run. Moreover, there is another guard in our listener that prevents from running the job that removes our runtime:

```java
    if (AppEngineStandardFacet.hasAppEngineFacet(facetedProject)) {
      return;
    }
 ```

The project certainly has (and normally should have) the App Engine facet installed.

**Comment by briandealwis** [comment]
The listener is [triggering a job](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/master/plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/AppEngineStandardRuntimeChangeListener.java#L65), and so the [removeTargetedRuntime()](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/master/plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/AppEngineStandardRuntimeChangeListener.java#L81) could happen any time.

**Comment by briandealwis** [comment]
You could try setting `JobManager.DEBUG` to see if there's any useful information.

**Comment by chanseokoh** [comment]
I doubt. If that job can be triggered, then yes, the removal can happen any time, but in order to be triggered, `setPrimaryRuntime()` needs to successfully set a primary runtime and notify the listeners (this happens synchronously). And as I said, even if the listener is notified and run, if the project has the App Engine facet, then the job is not triggered.

**Comment by chanseokoh** [comment]
This is one possible outcome of #1155, and we know why this happens. Closing.
