### ISSUE TITLE
Tons of "Event Admin service not available" errors when doing 'mvn verify'

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#1105]
Tons of error messages severely clutter test output. Doesn't affect test success though.

```
!ENTRY org.eclipse.e4.ui.workbench 4 0 2016-12-12 16:36:10.871
!MESSAGE Event Admin service is not available, unable to publish event org.osgi.service.event.Event [topic=org/eclipse/e4/ui/model/ui/UIElement/widget/SET] {ChangedElement=org.eclipse.e4.ui.model.application.ui.menu.impl.HandledMenuItemImpl@290c7ca (elementId: resetPerspective, tags: null, contributorURI: null) (widget: null, renderer: org.eclipse.e4.ui.workbench.renderers.swt.MenuManagerRenderer@4909c8df, toBeRendered: true, onTop: false, visible: true, containerData: null, accessibilityPhrase: null) (label: &Reset Perspective..., iconURI: null, tooltip: null, enabled: false, selected: false, type: Push) (mnemonics: null) (wbCommand: ParameterizedCommand(Command(org.eclipse.ui.window.resetPerspective,Reset Perspective,
                Reset the current perspective to its default state,
                Category(org.eclipse.ui.category.window,Window,null,true),
                org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@41d42a35,
                ,,true),null)), EventType=SET, AttName=widget, OldValue=MenuItem {&Reset Perspective...}, Widget=null}.

!ENTRY org.eclipse.e4.ui.workbench 4 0 2016-12-12 16:36:10.871
!MESSAGE Event Admin service is not available, unable to publish event org.osgi.service.event.Event [topic=org/eclipse/e4/ui/model/ui/UIElement/widget/SET] {ChangedElement=org.eclipse.e4.ui.model.application.ui.menu.impl.MenuImpl@6bb342eb (elementId: shortcuts, tags: [], contributorURI: null) (widget: null, renderer: null, toBeRendered: true, onTop: false, visible: true, containerData: null, accessibilityPhrase: null) (label: Navi&gation, iconURI: null, tooltip: null, mnemonics: null) (enabled: true), EventType=SET, AttName=widget, OldValue=Menu {Show &System Menu       Alt+-, Show View &Menu  Ctrl+F10, &Quick Access Ctrl+3, |, Maximize Active View or Editor       Ctrl+M, Minimize Active View or Editor, |, &Activate Editor        F12, Next &Editor       Ctrl+F6, P&revious Editor       Shift+Ctrl+F6, S&witch to Editor...     Shift+Ctrl+E, |, Next &View        Ctrl+F7, Previ&ous View Shift+Ctrl+F7, |, Next &Perspective     Ctrl+F8, Previo&us Perspective  Shift+Ctrl+F8}, Widget=null}.

!ENTRY org.eclipse.e4.ui.workbench 4 0 2016-12-12 16:36:10.872
!MESSAGE Event Admin service is not available, unable to publish event org.osgi.service.event.Event [topic=org/eclipse/e4/ui/model/ui/UIElement/widget/SET] {ChangedElement=org.eclipse.e4.ui.model.application.ui.menu.impl.MenuImpl@10b5a8f9 (elementId: help, tags: [], contributorURI: null) (widget: null, renderer: null, toBeRendered: true, onTop: false, visible: true, containerData: null, accessibilityPhrase: null) (label: &Help, iconURI: null, tooltip: null, mnemonics: null) (enabled: true), EventType=SET, AttName=widget, OldValue=Menu {&Help Contents, S&earch, &Dynamic Help, |, &About }, Widget=null}.

!ENTRY org.eclipse.e4.ui.workbench 4 0 2016-12-12 16:36:10.881
!MESSAGE Event Admin service is not available, unable to publish event org.osgi.service.event.Event [topic=org/eclipse/e4/ui/renderer/requestEnablementUpdate] {org.eclipse.e4.data=ALL}.

!ENTRY org.eclipse.e4.ui.workbench 4 0 2016-12-12 16:36:10.882
!MESSAGE Event Admin service is not available, unable to publish event org.osgi.service.event.Event [topic=org/eclipse/e4/ui/model/ui/Context/context/SET] {ChangedElement=org.eclipse.e4.ui.model.application.ui.basic.impl.TrimmedWindowImpl@5e854128 (elementId: IDEWindow, tags: [topLevel], contributorURI: platform:/plugin/org.eclipse.ui.workbench) (widget: null, renderer: null, toBeRendered: true, onTop: false, visible: true, containerData: null, accessibilityPhrase: null) (label: null, iconURI: null, tooltip: null, context: null, variables: [], x: 75, y: 34, width: 1024, height: 768), EventType=SET, AttName=context, OldValue=TrimmedWindowImpl (IDEWindow) Context, Widget=null}.

!ENTRY org.eclipse.e4.ui.workbench 4 0 2016-12-12 16:36:10.887
!MESSAGE Event Admin service is not available, unable to publish event org.osgi.service.event.Event [topic=org/eclipse/e4/ui/model/application/ApplicationElement/persistedState/ADD] {NewValue=org.eclipse.e4.ui.model.application.impl.StringToStringMapImpl@6e0092d1 (key: show_in_time, value: <?xml version="1.0" encoding="UTF-8"?>
<show_in_time/>), Position=2, ChangedElement=org.eclipse.e4.ui.model.application.ui.basic.impl.TrimmedWindowImpl@5e854128 (elementId: IDEWindow, tags: [topLevel], contributorURI: platform:/plugin/org.eclipse.ui.workbench) (widget: null, renderer: null, toBeRendered: true, onTop: false, visible: true, containerData: null, accessibilityPhrase: null) (label: null, iconURI: null, tooltip: null, context: null, variables: [], x: 75, y: 34, width: 1024, height: 768), EventType=ADD, AttName=persistedState, Widget=null}.

!ENTRY org.eclipse.e4.ui.workbench 4 0 2016-12-12 16:36:10.888
!MESSAGE Event Admin service is not available, unable to publish event org.osgi.service.event.Event [topic=org/eclipse/e4/ui/model/application/ApplicationElement/persistedState/ADD] {NewValue=org.eclipse.e4.ui.model.application.impl.StringToStringMapImpl@67a70fc2 (key: workingSets, value: <?xml version="1.0" encoding="UTF-8"?>
<workingSets/>), Position=3, ChangedElement=org.eclipse.e4.ui.model.application.ui.basic.impl.TrimmedWindowImpl@5e854128 (elementId: IDEWindow, tags: [topLevel], contributorURI: platform:/plugin/org.eclipse.ui.workbench) (widget: null, renderer: null, toBeRendered: true, onTop: false, visible: true, containerData: null, accessibilityPhrase: null) (label: null, iconURI: null, tooltip: null, context: null, variables: [], x: 75, y: 34, width: 1024, height: 768), EventType=ADD, AttName=persistedState, Widget=null}.
```

This may or may not related, but when running `StandardFacetInstallationTest` inside Eclipse by _Debug As_ > _JUnit Plug-in Test_, it throws a `NullPointerException`. The cause is that `PlatformUI.getWorkbench().getExtensionTracker()` returns null inside the `StatusHandlerRegistry` constructor.

```
!ENTRY org.eclipse.ui 4 0 2016-12-12 16:35:05.733
!MESSAGE Error occurred during status handling
!STACK 0
java.lang.NullPointerException
	at org.eclipse.ui.internal.statushandlers.StatusHandlerRegistry.<init>(StatusHandlerRegistry.java:72)
	at org.eclipse.ui.internal.statushandlers.StatusHandlerRegistry.getDefault(StatusHandlerRegistry.java:91)
	at org.eclipse.ui.statushandlers.StatusManager.getStatusHandler(StatusManager.java:135)
	at org.eclipse.ui.statushandlers.StatusManager.handle(StatusManager.java:189)
	at org.eclipse.ui.statushandlers.StatusManager.handle(StatusManager.java:231)
	at org.eclipse.ui.statushandlers.StatusManager$StatusManagerLogListener.logging(StatusManager.java:302)
	at org.eclipse.core.internal.runtime.RuntimeLog.logToListeners(RuntimeLog.java:161)
	at org.eclipse.core.internal.runtime.PlatformLogWriter.logged(PlatformLogWriter.java:103)
	at org.eclipse.osgi.internal.log.ExtendedLogReaderServiceFactory.safeLogged(ExtendedLogReaderServiceFactory.java:88)
	at org.eclipse.osgi.internal.log.ExtendedLogReaderServiceFactory.logPrivileged(ExtendedLogReaderServiceFactory.java:217)
	at org.eclipse.osgi.internal.log.ExtendedLogReaderServiceFactory.log(ExtendedLogReaderServiceFactory.java:189)
	at org.eclipse.osgi.internal.log.ExtendedLogServiceFactory.log(ExtendedLogServiceFactory.java:65)
	at org.eclipse.osgi.internal.log.ExtendedLogServiceImpl.log(ExtendedLogServiceImpl.java:87)
	at org.eclipse.osgi.internal.log.LoggerImpl.log(LoggerImpl.java:54)
	at org.eclipse.core.internal.runtime.Log.log(Log.java:65)
	at org.eclipse.core.internal.utils.Policy.log(Policy.java:159)
	at org.eclipse.core.internal.resources.SaveManager.reportSnapshotRequestor(SaveManager.java:655)
	at org.eclipse.core.internal.resources.Workspace.close(Workspace.java:576)
	at org.eclipse.core.resources.ResourcesPlugin.stop(ResourcesPlugin.java:433)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$4.run(BundleContextImpl.java:827)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$4.run(BundleContextImpl.java:1)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.stop(BundleContextImpl.java:820)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.stopWorker0(EquinoxBundle.java:955)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.stopWorker(EquinoxBundle.java:323)
	at org.eclipse.osgi.container.Module.doStop(Module.java:626)
	at org.eclipse.osgi.container.Module.stop(Module.java:488)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.decStartLevel(ModuleContainer.java:1623)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1542)
	at org.eclipse.osgi.container.SystemModule.stopWorker(SystemModule.java:248)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule.stopWorker(EquinoxBundle.java:144)
	at org.eclipse.osgi.container.Module.doStop(Module.java:626)
	at org.eclipse.osgi.container.Module.stop(Module.java:488)
	at org.eclipse.osgi.container.SystemModule.stop(SystemModule.java:186)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule$1.run(EquinoxBundle.java:159)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by briandealwis** [comment]
The _ Event Admin service_ is in the `org.eclipse.equinox.event` bundle and needs to be included as a dependency.  It should be included if you specify the `org.eclipse.platorm.ide` product, or if you include the `org.eclipse.rcp` feature.

**Comment by chanseokoh** [comment]
This is happening again. I'm suspecting `appengine.ui.test` is causing this.

**Comment by briandealwis** [comment]
I was wrong in the above:
> [The Event Admin service] should be included if you specify the org.eclipse.platorm.ide product

The `org.eclipse.platform.ide` and `org.eclipse.sdk.ide` products aren't full Eclipse products — they only provide product branding and an `IApplication` (main class), but don't include the product definition with features, etc to be included.

We need to add the `org.eclipse.rcp` feature to these `uiHarness`-type tests using the mechanism shown in [`com.google.cloud.tools.eclipse.appengine.deploy.ui.test`'s use of the `target-platform-configuration` plugin](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/master/plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui.test/pom.xml#L32).

(I wonder why this just started again?)

**Comment by chanseokoh** [comment]
> (I wonder why this just started again?)

No clue. Either I had missed the `.appengine.ui.test` bundle last time (I fixed `.appengine.newproject.maven.test only), or the `.appengine.ui.test` bundle has evolved to cause this problem since then.

**Comment by chanseokoh** [comment]
Alright, so I guess we need to revert #1110 and do the right thing.
