### ISSUE TITLE
 When deploying to App Engine in Cloud Tools for Eclipse on Mac OS X, a dialog pops up telling me to install git 

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1187]
When on Mac OS X and I'm using Cloud Tools for Eclipse, during the deployment of an App Engine App, I get the attached error message.

I think more info on this issue can be found here: http://superuser.com/questions/666086/issues-installing-git-under-mac-os-x-10-9-mavericks

![image](https://cloud.githubusercontent.com/assets/1005544/21692880/d12502cc-d34c-11e6-95b3-635204b57e7b.png)

**Comment by chanseokoh** [comment]
Your machine does not have git installed? Can you reproduce this with the Maven plugin? I wonder if it is the staging step that tries to use git.

**Comment by elharo** [comment]
This issue is from @rdayal I just copied it over here.

My first guess is that this has nothing to do with us, and just happened to occur at the same time due to other things in a new Eclipse install.

**Comment by chanseokoh** [comment]
I remember having seen this in one of the UX sessions we conducted. Like in this case, this happened when the user clicked on the _Deploy to App Engine Standard..._ menu to start deploying.

**Comment by rdayal** [comment]
Yes, I think it may be related to something we are doing. I can reproduce it on my machine consistently, and the install of Eclipse is no longer new. 

This possibly has better information:
https://modulesunraveled.com/installing-git/installing-git-if-you-do-not-have-xcode-or-command-line-developer-tools-installed

Is the git binary being called as part of 'gcloud app deploy', or as part of deployment in the common library?

@patflynn

**Comment by elharo** [comment]
I certainly didn't think it was being called, but I don't know. Maybe something in gcloud? We'll have to dig into the code and see.

**Comment by elharo** [comment]
@rdayal How do you create the project you're trying to deploy? Was it with either the native or maven wizard?

**Comment by elharo** [comment]
Maybe gcloud does something with cloud source repositories on deploy? That would explain the need for git.

**Comment by rdayal** [comment]
I've tracked this down a bit farther - still digging. 

Talking to Patrick, it definitely seems like gcloud app deploy calls out to git on deploy to possibly generate source context information. 

On a Mac OS X image without git explicitly installed, if you call /usr/bin/git, then this dialog pops up. So you're right that it's not something specific to Cloud Tools for Eclipse necessarily - however I want to do a bit more digging to see what's happening here. I'm surprised we haven't heard reports of this on IntelliJ as yet. 

I'll try this from the command line (gcloud app deploy) and see if I can repro the behavior.

**Comment by rdayal** [comment]
Ok, I think I may know what the issue is..

If I type 'git', on the command line, this problem doesn't happen, because the git being used on the PATH is /usr/local/git/current/bin/git.  

However, running /usr/bin/git from the command line results in this popup.

I'm wondering if the issue has something to do with how we're invoking the common library in Cloud Tools for Eclipse. Are we passing the current environment (i.e. the current PATH) when we invoke the call to 'gcloud app deploy'?

**Comment by rdayal** [comment]
(and on my PATH, I do have /usr/local/git/current/bin)

**Comment by rdayal** [comment]
@loosebazooka

**Comment by ludoch** [comment]
I got this as well on my new Mac, and I was quite annoyed with that. XCode
is around 5Gb? and yes, it seems related to Cloud source... (that very few
people are currently using)...

**Comment by ludoch** [comment]
(BTW, I was not on Eclipse but NetBeans of course:-)

**Comment by rdayal** [comment]
Further digging (down this hole), I think the problem has to do with the PATH setting being respected by Eclipse when it's run via Finder instead of from the terminal:

https://www.vscentrum.be/client/macosx/eclipse-on-osx

It seems like the PATH variable is not set in the same way in Eclipse as it would be if you were in the terminal - which results in this issue.

There are a couple of ways I can think of to mitigate this issue..
--#1 - introduce an option into 'gcloud app deploy' which prevents source context generation (and therefore git). We can then expose this in the deploy UI and keep this unchecked by default. If the user decides to check it, we can have some verbiage that links them over to instructions on how to deal with this problem. 
--#2 - figure out what the REAL path should be (based on .bash_profile) and set it before invoking 'gcloud app deploy' via the common library.

**Comment by ludoch** [comment]
Please, file an internal bug to improve com
<https://cs.corp.google.com/piper///depot/google3/java/com/>/google
<https://cs.corp.google.com/piper///depot/google3/java/com/google/>/
appengine
<https://cs.corp.google.com/piper///depot/google3/java/com/google/appengine/>
/tools
<https://cs.corp.google.com/piper///depot/google3/java/com/google/appengine/tools/>
/admin
<https://cs.corp.google.com/piper///depot/google3/java/com/google/appengine/tools/admin/>/
RepoInfo.java

**Comment by rdayal** [comment]
Actually, there is a way you can almost know, on Mac OS X (though it might break in the future). If you're executing git in /usr/bin/git and it's a small binary (i.e. less than 100k), it's highly likely that this is not actually git. git's binary size on Mac OS X is over 2MB. 

That being said, your point stands - knowing the REAL path may not fix anything. Option #1 seems to be the most practical. Even if you implement Option #1, you don't have to know/check whether or not git works. You basically expose the option to the user and have it off by default. If the user chooses to enable source context generation, a tooltip/link can point them over to help on how to get around this problem if that dialog pops up.

**Comment by elharo** [comment]
Wild idea: is there an Eclipse plugin that includes git we could depend on?

**Comment by patflynn** [comment]
Don't you guys think this sounds like something that needs to be fixed in
the Cloud SDK?

**Comment by chanseokoh** [comment]
I agree. The Cloud SDK could use a git library instead of running an actual git binary?

**Comment by patflynn** [comment]
whatever works for them :).  But this is a problem for all gcloud app
deploy users, not just our IDE plugin users.

**Comment by rdayal** [comment]
Actually, it's not that simple. 

This problem doesn't manifest on the command line in the example I'm trying. It does manifest in Eclipse though, due to it not respecting the PATH of the environment.

So while it's fine for the SDK team to look into this issue and come up with a fix, I wouldn't block on them. The problem is exacerbated in Eclipse due to the way it functions.

**Comment by rdayal** [comment]
(I will file an issue in their tracker though)

**Comment by patflynn** [comment]
It doesn't manifest because you're using an eng laptop with git
pre-installed though right?  A normal OS X install would get this same
experience if they tried to gcloud app deploy from the terminal.

**Comment by rdayal** [comment]
Perhaps - not sure what comes by default on a normal OSX install. 

We haven't seen any reports of this on the Cloud SDK issue tracker, and I imagine that if this was the case, we'd see lots of bugs on that. Either that or people just click "Install" and move forward.

**Comment by rdayal** [comment]
Yep, was able to reproduce it on the command line when I removed the 'real' git's install directory from the PATH.

**Comment by rdayal** [comment]
Filed:
https://code.google.com/p/google-cloud-sdk/issues/detail?id=1453

**Comment by elharo** [comment]
I wonder what `gcloud app deploy` does on Windows or Linux if there's no git anywhere? I should probably spin up a GCE instance and find out.

**Comment by elharo** [comment]
FYI, the Flex environment quickstart lists git as a prerequisite:

https://cloud.google.com/appengine/docs/flexible/java/quickstart

The standard environment docs do not say that, but do begin with a git command anyway:

https://cloud.google.com/appengine/docs/java/quickstart

**Comment by elharo** [comment]
I had to go through maven because `gcloud app deploy` doesn't support appengine-web.xml and looks like it does this:

[INFO] Running --oauth2 update /home/elharo/java-docs-samples-master/appengine/helloworld/target/appengine-helloworld-1.0-SNAPSHOT
Reading application configuration data...


Beginning interaction for module default...

java.lang.NullPointerException
Unable to update app: null
Please see the logs [/tmp/appcfg8132693592643219565.log] for further information.

Unable to update:
java.lang.NullPointerException
	at java.net.URLEncoder.encode(URLEncoder.java:205)
	at com.google.appengine.tools.admin.AbstractServerConnection.buildQuery(
AbstractServerConnection.java:117)
	at com.google.appengine.tools.admin.AbstractServerConnection.send1(Abstr
actServerConnection.java:303)
	at com.google.appengine.tools.admin.AbstractServerConnection.send(Abstra
ctServerConnection.java:289)
	at com.google.appengine.tools.admin.AbstractServerConnection.post(Abstra
ctServerConnection.java:268)
	at com.google.appengine.tools.admin.LoggingClientDeploySender.send(Loggi
ngClientDeploySender.java:47)
	at com.google.appengine.tools.admin.ResourceLimits.remoteRequest(Resourc
eLimits.java:174)
	at com.google.appengine.tools.admin.ResourceLimits.request(ResourceLimit
s.java:139)
	at com.google.appengine.tools.admin.AppAdminImpl.doUpdate(AppAdminImpl.j
ava:566)
	at com.google.appengine.tools.admin.AppAdminImpl.update(AppAdminImpl.jav
a:57)
	at com.google.appengine.tools.admin.AppCfg$UpdateAction.execute(AppCfg.j
ava:1526)
	at com.google.appengine.tools.admin.AppCfg.executeAction(AppCfg.java:393
)
	at com.google.appengine.tools.admin.AppCfg.<init>(AppCfg.java:216)
	at com.google.appengine.tools.admin.AppCfg.<init>(AppCfg.java:116)
	at com.google.appengine.tools.admin.AppCfg.main(AppCfg.java:112)
	at com.google.appengine.appcfg.AbstractAppCfgMojo.executeAppCfgCommand(A
bstractAppCfgMojo.java:259)
	at com.google.appengine.appcfg.Update.execute(Update.java:36)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(Default
BuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProje
ct(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProje
ct(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThre
adedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(Lifecycl
eStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Laun
cher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.jav
a:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(La
uncher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:
356)
com.google.appengine.tools.admin.AdminException: Unable to update app: null
	at com.google.appengine.tools.admin.AppAdminImpl.doUpdate(AppAdminImpl.j
ava:578)
	at com.google.appengine.tools.admin.AppAdminImpl.update(AppAdminImpl.jav
a:57)
	at com.google.appengine.tools.admin.AppCfg$UpdateAction.execute(AppCfg.j
ava:1526)
	at com.google.appengine.tools.admin.AppCfg.executeAction(AppCfg.java:393
)
	at com.google.appengine.tools.admin.AppCfg.<init>(AppCfg.java:216)
	at com.google.appengine.tools.admin.AppCfg.<init>(AppCfg.java:116)
	at com.google.appengine.tools.admin.AppCfg.main(AppCfg.java:112)
	at com.google.appengine.appcfg.AbstractAppCfgMojo.executeAppCfgCommand(A
bstractAppCfgMojo.java:259)
	at com.google.appengine.appcfg.Update.execute(Update.java:36)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(Default
BuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProje
ct(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProje
ct(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThre
adedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(Lifecycl
eStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Laun
cher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.jav
a:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(La
uncher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:
356)
Caused by: java.lang.NullPointerException
	at java.net.URLEncoder.encode(URLEncoder.java:205)
	at com.google.appengine.tools.admin.AbstractServerConnection.buildQuery(
AbstractServerConnection.java:117)
	at com.google.appengine.tools.admin.AbstractServerConnection.send1(Abstr
actServerConnection.java:303)
	at com.google.appengine.tools.admin.AbstractServerConnection.send(Abstra
ctServerConnection.java:289)
	at com.google.appengine.tools.admin.AbstractServerConnection.post(Abstra
ctServerConnection.java:268)
	at com.google.appengine.tools.admin.LoggingClientDeploySender.send(Loggi
ngClientDeploySender.java:47)
	at com.google.appengine.tools.admin.ResourceLimits.remoteRequest(Resourc
eLimits.java:174)
	at com.google.appengine.tools.admin.ResourceLimits.request(ResourceLimit
s.java:139)
	at com.google.appengine.tools.admin.AppAdminImpl.doUpdate(AppAdminImpl.j
ava:566)
	... 30 more

**Comment by elharo** [comment]
ERROR] Failed to execute goal com.google.cloud.tools:appengine-maven-plugin:1.0.0:deploy (default-cli) on project appengine-helloworld: Execution default-cli of goal com.google.cloud.tools:appengine-maven-plugin:1.0.0:deploy failed: Validation Error: Java App Engine components not installed. Fix by running 'gcloud components install app-engine-java' on command-line. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
elharo@gittest:~/java-docs-samples-master/appengine/helloworld$ gcloud components install app-engine-java
You cannot perform this action because this Cloud SDK installation is 
managed by an external package manager.  If you would like to get the 
latest version, please see our main download page at:
  
https://cloud.google.com/sdk/

ERROR: (gcloud.components.install) The component manager is disabled for this installation

**Comment by elharo** [comment]
OK, finally got it to work. No git error messages.

**Comment by patflynn** [comment]
Yeah, the tool just emits a warning if it can't generate a source context.
The problem was specific to OS X because they did their hackery to start
the XCode installer UI if git was called even when not installed.

**Comment by briandealwis** [comment]
> @ludoch: Please, file an internal bug to improve com/google/appengine/tools/admin/RepoInfo.java

FWIW RepoInfo could consider embedding [JGit](https://www.eclipse.org/jgit/) rather than calling out to `git`. JGit is standalone, doesn't require OSGi.

**Comment by ludoch** [comment]
34244147

**Comment by b-daniels** [comment]
Note that "gcloud app deploy" uses different (Python) code. The RepoInfo.java code runs as part of appcfg.java.

**Comment by chanseokoh** [comment]
@b-daniels In the end, this needs to be fixed in both Python and RepoInfo.java.

**Comment by elharo** [comment]
At this point, this needs to be fixed in Cloud SDK.

**Comment by diegomarquezp** [comment]
Closing as not planned.
