### ISSUE TITLE
Integration tests fail on Mac

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1314]
[com.google.cloud.tools.eclipse.integration.appengine.DebugNativeAppEngineStandardProjectTest.txt](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/files/737566/com.google.cloud.tools.eclipse.integration.appengine.DebugNativeAppEngineStandardProjectTest.txt)
[com.google.cloud.tools.eclipse.integration.appengine.DeployPropertyPageTest.txt](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/files/737568/com.google.cloud.tools.eclipse.integration.appengine.DeployPropertyPageTest.txt)
[com.google.cloud.tools.eclipse.integration.appengine.NewMavenBasedAppEngineProjectWizardTest.txt](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/files/737569/com.google.cloud.tools.eclipse.integration.appengine.NewMavenBasedAppEngineProjectWizardTest.txt)
[com.google.cloud.tools.eclipse.integration.appengine.NewNativeAppEngineStandardProjectTest.txt](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/files/737567/com.google.cloud.tools.eclipse.integration.appengine.NewNativeAppEngineStandardProjectTest.txt)

**Comment by elharo** [comment]
Typical failure:

-------------------------------------------------------------------------------
Test set: com.google.cloud.tools.eclipse.integration.appengine.DeployPropertyPageTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.566 sec <<< FAILURE! - in com.google.cloud.tools.eclipse.integration.appengine.DeployPropertyPageTest
testPropertyPageTitle_standardProject(com.google.cloud.tools.eclipse.integration.appengine.DeployPropertyPageTest)  Time elapsed: 0.56 sec  <<< ERROR!
org.eclipse.swtbot.swt.finder.exceptions.WidgetNotFoundException: The widget was null.
	at org.eclipse.swtbot.swt.finder.widgets.AbstractSWTBot.<init>(AbstractSWTBot.java:104)
	at org.eclipse.swtbot.swt.finder.widgets.AbstractSWTBotControl.<init>(AbstractSWTBotControl.java:47)
	at org.eclipse.swtbot.swt.finder.widgets.SWTBotShell.<init>(SWTBotShell.java:49)
	at org.eclipse.swtbot.swt.finder.widgets.SWTBotShell.<init>(SWTBotShell.java:38)
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.activeShell(SWTBotFactory.java:376)
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.menu(SWTBotFactory.java:210)
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.menu(SWTBotFactory.java:200)
	at com.google.cloud.tools.eclipse.integration.appengine.SwtBotAppEngineActions.createNativeWebAppProject(SwtBotAppEngineActions.java:48)
	at com.google.cloud.tools.eclipse.integration.appengine.DeployPropertyPageTest.testPropertyPageTitle_standardProject(DeployPropertyPageTest.java:35)

**Comment by elharo** [comment]
When running inside Eclipse typically gets here and stops:

![image](https://cloud.githubusercontent.com/assets/1005544/22404819/913468de-e606-11e6-86b9-19416a7a8dd7.png)

**Comment by elharo** [comment]
FYI we've been here before: https://github.com/GoogleCloudPlatform/google-cloud-eclipse/pull/612

**Comment by briandealwis** [comment]
I suspect this was because of the use of [*WaitForWindowChange()](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/pull/1383#issuecomment-279025179) was causing the project creation to complete too early.  They pass now with the changes in #1383.
