### ISSUE TITLE
Builds failing with deadlocks on Oxygen

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#1345]
Oxygen builds are frequently failing on Travis:

```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
```

From the [failed build logs](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/files/753310/failedbuild.txt), it seems to be happening in the integration tests, and there are a lot of puzzling output.

It may be related to #1314

Update: turns out to be a deadlock introduced in WTP in Oxygen M4/M5 ([bug 511793](https://bugs.eclipse.org/511793)).  A workaround is to temporarily disable its background dependency graph updating.

**Comment by briandealwis** [comment]
Running the tests under docker, it seems like we hit a couple of issues:
- our use of SWTBot's `resetWorkbench()` tickles [bug 511729](https://bugs.eclipse.org/bugs/show_bug.cgi?id=511729) in Oxygen.
- there are some hangs in `SwtBotWorkbenchActions.waitForIdle()` as it loops repeatedly on the while loop for `!Job.getJobManager().isIdle()`, and there are some long-lived jobs
  - there is some slowdown when creating a project, as it triggers a _Update Java Indexes_ job which can take a while (in my docker image, at least)
  - when I ran in Docker, I once saw a hang in `DebugNativeAppEngineStandardProjectTest` where it was waiting on a _Waiting for VM to connect_ process. This process should have been terminated.

**Comment by chanseokoh** [comment]
FYI, I know a lot of the following `IllegalArgumentException: Argument not valid` errors during the integrate test are happening in Mars and Neon too. Those errors may be deceiving for the matter of the Oxygen build timeouts.

```
!ENTRY org.eclipse.ui 4 0 2017-02-05 16:02:12.679
!MESSAGE Unhandled event loop exception
!STACK 0
org.eclipse.e4.core.di.InjectionException: java.lang.IllegalArgumentException: Argument not valid
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:65)
	at org.eclipse.e4.ui.internal.di.UIEventObjectSupplier$UIEventHandler$1.run(UIEventObjectSupplier.java:61)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:233)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:144)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:5417)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application$1.syncExec(E4Application.java:212)
	at org.eclipse.e4.ui.internal.di.UIEventObjectSupplier$UIEventHandler.handleEvent(UIEventObjectSupplier.java:58)
	at org.eclipse.equinox.internal.event.EventHandlerWrapper.handleEvent(EventHandlerWrapper.java:201)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:197)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	at org.eclipse.equinox.internal.event.EventAdminImpl.dispatchEvent(EventAdminImpl.java:135)
	at org.eclipse.equinox.internal.event.EventAdminImpl.sendEvent(EventAdminImpl.java:78)
	at org.eclipse.equinox.internal.event.EventComponent.sendEvent(EventComponent.java:39)
	at org.eclipse.e4.ui.services.internal.events.EventBroker.send(EventBroker.java:52)
	at org.eclipse.e4.ui.internal.workbench.UIEventPublisher.notifyChanged(UIEventPublisher.java:60)
	at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:374)
	at org.eclipse.e4.ui.model.application.ui.impl.UIElementImpl.setVisible(UIElementImpl.java:345)
	at org.eclipse.e4.ui.workbench.renderers.swt.TrimBarLayout.hideManagedTB(TrimBarLayout.java:214)
	at org.eclipse.e4.ui.workbench.renderers.swt.TrimBarLayout$$Lambda$114/205284289.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.eclipse.e4.ui.workbench.renderers.swt.TrimBarLayout.computeSize(TrimBarLayout.java:124)
	at org.eclipse.swt.widgets.Composite.computeSizeInPixels(Composite.java:217)
	at org.eclipse.swt.widgets.Control.computeSize(Control.java:739)
	at org.eclipse.e4.ui.workbench.renderers.swt.TrimmedPartLayout.layout(TrimmedPartLayout.java:116)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1721)
	at org.eclipse.swt.widgets.Composite.setLayoutDeferred(Composite.java:1566)
	at org.eclipse.swt.widgets.Display.runDeferredLayouts(Display.java:4524)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4072)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1133)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:698)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
	at org.eclipse.tycho.surefire.osgibooter.UITestApplication.runApplication(UITestApplication.java:31)
	at org.eclipse.tycho.surefire.osgibooter.AbstractUITestApplication.run(AbstractUITestApplication.java:120)
	at org.eclipse.tycho.surefire.osgibooter.UITestApplication.start(UITestApplication.java:37)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
Caused by: java.lang.IllegalArgumentException: Argument not valid
	at org.eclipse.swt.SWT.error(SWT.java:4514)
	at org.eclipse.swt.SWT.error(SWT.java:4448)
	at org.eclipse.swt.SWT.error(SWT.java:4419)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:487)
	at org.eclipse.swt.widgets.Control.setParent(Control.java:4844)
	at org.eclipse.e4.ui.workbench.addons.cleanupaddon.CleanupAddon.subscribeVisibilityChanged(CleanupAddon.java:247)
	at sun.reflect.GeneratedMethodAccessor26.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
	... 54 more
```

**Comment by briandealwis** [comment]
Those `IllegalArgumentException`s seem due to SWTBot's `resetWorkbench()`: it closes down all `Shell`s that aren't the active workbench window, including an internal `Shell` used by the workbench to host hidden parts.

I agree that it doesn't seem to be the real issue here though.

**Comment by chanseokoh** [comment]
FYI, I did see the exactly same timeout issue on a Mars build in one of the PRs last week. (Can't find it now. I'm certain the PR was @briandealwis'.) The timeout happened by `AppEngineStandardProjectConvertJobTest`, as in https://github.com/GoogleCloudPlatform/google-cloud-eclipse/pull/1340#issuecomment-277716681. So, it may not be Oxygen-specific.

**Comment by chanseokoh** [comment]
`LocalAppEngineServerDelegateTest`: https://github.com/GoogleCloudPlatform/google-cloud-eclipse/pull/1344

`DebugNativeAppEngineStandardProjectTest`: https://github.com/GoogleCloudPlatform/google-cloud-eclipse/pull/1342

**Comment by chanseokoh** [comment]
So far, the timeout happened on `LocalAppEngineServerDelegateTest`, `DebugNativeAppEngineStandardProjectTest`, `AppEngineStandardProjectConvertJobTest`, `AppEngineStandardProjectConvertJobTest`, and `AppEngineStandardProjectConvertCommandHandlerTest`. Some of them are not integration tests. It also happened on Mars, but only once.

**Comment by briandealwis** [comment]
I wish `JobManager` provided some more useful diagnostics.

**Comment by briandealwis** [comment]
I've built a little _JobMonitor_ class that listens for job changes.  As we're installing the _App Engine Standard facet_ via `FacetedProject.modify()`, we're blocked waiting for a `org.eclipse.wst.common.componentcore.internal.builder.DependencyGraphImpl$GraphUpdateJob` job to complete.  It's a system job, and hence why looping on idle jobs was necessary.

```
Object.wait(long) line: not available [native method]	
Semaphore.acquire(long) line: 39	
OrderedLock.doAcquire(Semaphore, long) line: 170	
OrderedLock.acquire(long) line: 106	
OrderedLock.acquire() line: 82	
StructureEdit.getComponentModelRoot() line: 467	
StructureEdit.getWorkbenchModules() line: 506	
StructureEdit.getComponent() line: 949	
VirtualComponent.createResource() line: 124	
VirtualComponent.addManagedResource() line: 100	
VirtualComponent.initializeResource() line: 114	
VirtualComponent.<init>(IProject, IPath) line: 148	
ComponentImplManager.createComponent(IProject, boolean) line: 250	
ComponentCore.createComponent(IProject, boolean) line: 84	
WebFacetInstallDelegate.setContentPropertyIfNeeded(IDataModel, IPath, IProject) line: 221	
WebFacetInstallDelegate.execute(IProject, IProjectFacetVersion, Object, IProgressMonitor) line: 86	
FacetedProject.callDelegate(IProjectFacetVersion, IDelegate, Object, Object, IProgressMonitor) line: 1477	
FacetedProject.modifyInternal(Set<Action>, IProgressMonitor) line: 441	
FacetedProject.mergeChangesInternal(IFacetedProjectWorkingCopy, IProgressMonitor) line: 1181	
FacetedProject.access$2(FacetedProject, IFacetedProjectWorkingCopy, IProgressMonitor) line: 1117	
FacetedProject$1.run(IProgressMonitor) line: 324	
Workspace.run(ICoreRunnable, ISchedulingRule, int, IProgressMonitor) line: 2240	
Workspace.run(IWorkspaceRunnable, ISchedulingRule, int, IProgressMonitor) line: 2267	
FacetedProject.modify(Set<Action>, IProgressMonitor) line: 339	
AppEngineStandardFacet.installAppEngineFacet(IFacetedProject, boolean, IProgressMonitor) line: 150	
CreateAppEngineStandardWtpProject.execute(IProgressMonitor) line: 103	
CreateAppEngineStandardWtpProject(WorkspaceModifyOperation).lambda$0(InvocationTargetException[], IProgressMonitor) line: 107	
```

**Comment by briandealwis** [comment]
There's a deadlock between our installing the App Engine facet and that dependency graph updating job spawned by WTP on project changes.  I've filed it as [bug 511793](https://bugs.eclipse.org/bugs/show_bug.cgi?id=511793).  I think we need to move our facet-installation code into the project creation.

**Comment by briandealwis** [comment]
#1343 is my playground.  #1348 is the attempt to create a minimal fix.  #1348 is almost working, but some tests seem to take a long time.  From running them locally, much of the time is taken in `waitForIdle()`, looping waiting for the _JobManager_ to go idle. Opening the _Progress_ view, it's the _Update Java Index_ job, which doesn't actually affect us.

I think we'll need to make `waitForIdle()` more clever. Instead of waiting for the JobManager to be idle, it should loop until the project is free of errors, in addition to the various `join()`s.

**Comment by chanseokoh** [comment]
> I think we'll need to make waitForIdle() more clever. Instead of waiting for the JobManager to be idle, it should loop until the project is free of errors, in addition to the various join()s.

Also, we need to ensure completion of the App Engine post-facet install job that installs the App Engine runtime. (Having no errors won't be enough.) Waiting for this may go into a separate method?

**Comment by briandealwis** [comment]
Hmm, we should make our jobs belong to a family to simplify things.  Or perhaps we could latch onto the `J2EEElementChangedListener.PROJECT_COMPONENT_UPDATE_JOB_FAMILY`.

**Comment by briandealwis** [comment]
Suspending the _JobManager_ isn't sufficient as the DependencyGraphImpl listens for resource changes and will forcibly resume the _JobManager_.

I wonder if we can somehow suspend the resource notifications.

**Comment by briandealwis** [comment]
A few notes:
- No, we can't suspend the resource notifications.
- No, we can't use the `NonSystemJobSuspender` approach from #1167 to temporarily suspend the WTP _DependencyGraph_ update job as it is explicitly triggered and waited for as part of the process of an `IFacetedProject.modify()` operation. Besides, the job is explicitly resumed by the `DependencyGraphJob` itself.
- Fortunately we can suspend the dependency graph updating on project changes. Unfortunately we have to find the actions the trigger these project changes that may lead to contention.

**Comment by briandealwis** [comment]
As part of #1362, I created an opt-in watchdog timer for JUnit tests that will periodically output stack traces for all interesting threads to stdout.  It uses the JMX _ThreadMXBean_ to produce `jstack`-like output, including acquired and waiting locks.

**Comment by briandealwis** [comment]
https://github.com/GoogleCloudPlatform/google-cloud-eclipse/pull/1377#issuecomment-278762390
