### ISSUE TITLE
Error creating project VERSION 2_3_25

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1370]
![image](https://cloud.githubusercontent.com/assets/1005544/22785773/a99c63ae-eea3-11e6-9ac4-b61bfebd05be.png)

```
eclipse.buildId=4.6.2.M20161124-1400
java.version=1.8.0_112
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product -keyring /Users/elharo/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product -data file:/Users/elharo/Documents/neonworkspace/ -product org.eclipse.epp.package.jee.product -keyring /Users/elharo/.eclipse_keyring

org.eclipse.equinox.p2.core
Error
Thu Feb 09 08:38:50 EST 2017
Provisioning exception

org.eclipse.equinox.p2.core.ProvisionException: No repository found at https://storage.googleapis.com/cloud-tools-for-eclipse/1.0-Beta-12/.
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.fail(AbstractRepositoryManager.java:395)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.oomph.util.ReflectUtil.invokeMethod(ReflectUtil.java:117)
	at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager.fail(CachingRepositoryManager.java:333)
	at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager.loadRepository(CachingRepositoryManager.java:236)
	at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager$Metadata.loadRepository(CachingRepositoryManager.java:456)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:96)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:92)
	at org.eclipse.equinox.p2.ui.LoadMetadataRepositoryJob.doLoad(LoadMetadataRepositoryJob.java:117)
	at org.eclipse.equinox.p2.ui.LoadMetadataRepositoryJob.runModal(LoadMetadataRepositoryJob.java:102)
	at org.eclipse.equinox.internal.p2.ui.sdk.PreloadingRepositoryHandler$2.runModal(PreloadingRepositoryHandler.java:83)
	at org.eclipse.equinox.p2.operations.ProvisioningJob.run(ProvisioningJob.java:177)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by elharo** [comment]
Things to note:

https://storage.googleapis.com/cloud-tools-for-eclipse/1.0-Beta-12/

does not actually exist. The correct repo URL is https://storage.googleapis.com/cloud-tools-for-eclipse/1.0-beta-12/ (i.e. lower case beta).

I initially added the incorrect repo URL with the upper case Beta when trying to install the plugin for testing. 

However I don't see why a bad repo URL should prevent me from creating a new app engine project.

Also, I selected all the libraries and added a service name when creating the project.

**Comment by elharo** [comment]
Project files were created despite this exception, but was not configured to build.

**Comment by elharo** [comment]
Leaving all values at default (not including extra libraries) gives same error.

**Comment by elharo** [comment]
Maven projects work.

**Comment by elharo** [comment]
After removing the nonexistent update site it still fails but with a different exception:

eclipse.buildId=4.6.2.M20161124-1400
java.version=1.8.0_112
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product -keyring /Users/elharo/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product -data file:/Users/elharo/Documents/neonworkspace/ -product org.eclipse.epp.package.jee.product -keyring /Users/elharo/.eclipse_keyring

com.google.cloud.tools.eclipse.appengine.newproject
Error
Thu Feb 09 08:55:54 EST 2017
Failed to create project: VERSION_2_3_25

java.lang.NoSuchFieldError: VERSION_2_3_25
	at com.google.cloud.tools.eclipse.util.templates.appengine.AppEngineTemplateUtility.createConfiguration(AppEngineTemplateUtility.java:85)
	at com.google.cloud.tools.eclipse.util.templates.appengine.AppEngineTemplateUtility.createFileContent(AppEngineTemplateUtility.java:54)
	at com.google.cloud.tools.eclipse.appengine.newproject.CodeTemplates.createChildFile(CodeTemplates.java:149)
	at com.google.cloud.tools.eclipse.appengine.newproject.CodeTemplates.materialize(CodeTemplates.java:72)
	at com.google.cloud.tools.eclipse.appengine.newproject.CreateAppEngineStandardWtpProject.execute(CreateAppEngineStandardWtpProject.java:88)
	at org.eclipse.ui.actions.WorkspaceModifyOperation.lambda$0(WorkspaceModifyOperation.java:107)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2267)
	at org.eclipse.ui.actions.WorkspaceModifyOperation.run(WorkspaceModifyOperation.java:128)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)

**Comment by elharo** [comment]
Looks like Neon has an older version of Freemarker installed:

![image](https://cloud.githubusercontent.com/assets/1005544/22786419/6f4c9298-eea6-11e6-8480-aa511d659ec4.png)

**Comment by chanseokoh** [comment]
FWIW, Beta 11 was fine, and I'm sure we cut Beta 11 after we OSGi-fied freemarker (which was merged 16 days ago). Could this be your specific IDE environment? In any case, I agree the new version should come together and it should just work.

**Comment by briandealwis** [comment]
The Orbit freemarker seems to be pulled in by two things:
  - CDT's CMake support via a bundle `org.eclipse.tools.templates.freemarker`
  - ObjectTeams

The version in Orbit isn't a singleton bundle, so we should be able to co-exist.

The culprit is `com.google.cloud.tools.eclipse.util`'s MANIFEST.MF doesn't put a lower bound on its _Import-Package: freemarker.template_, so p2 ignores the Freemarker on our site since we can be satisfied by what is already present.
