### ISSUE TITLE
Deadlock in NonSystemJobSuspender 

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#1373]
NonSystemJobSuspender is performing job operations with its monitor held.  These job operations may fire events.
```
+-------------------------------------------------------------------------------
| STACK DUMP @ 4.001 min: testCheckConflictingId_differentServiceIds(com.google.cloud.tools.eclipse.appengine.localserver.server.LocalAppEngineServerDelegateTest)
|
| "main" [1] BLOCKED on java.lang.Class@453674ff owned by 'Worker-3 [id:37]
|     at com.google.cloud.tools.eclipse.appengine.facets.NonSystemJobSuspender.suspendJob(NonSystemJobSuspender.java:77)
|     - blocked on java.lang.Class@453674ff
|     at com.google.cloud.tools.eclipse.appengine.facets.NonSystemJobScheduleListener.scheduled(NonSystemJobScheduleListener.java:29)
|     at org.eclipse.core.internal.jobs.JobListeners$5.notify(JobListeners.java:54)
|     at org.eclipse.core.internal.jobs.JobListeners.doNotify(JobListeners.java:102)
|     at org.eclipse.core.internal.jobs.JobListeners.scheduled(JobListeners.java:161)
|     at org.eclipse.core.internal.jobs.JobManager.schedule(JobManager.java:1259)
|     at org.eclipse.core.internal.jobs.JobManager.endJob(JobManager.java:697)
|     at org.eclipse.core.internal.jobs.InternalJob.done(InternalJob.java:198)
|     at org.eclipse.core.runtime.jobs.Job.done(Job.java:253)
|     at org.eclipse.ui.progress.UIJob$1.run(UIJob.java:110)
|     at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
|     at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
|     - locked org.eclipse.swt.widgets.RunnableLock@5807c62e
|     at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4024)
|     at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3700)
|     at org.eclipse.ui.internal.dialogs.EventLoopProgressMonitor.runEventLoop(EventLoopProgressMonitor.java:125)
|     at org.eclipse.ui.internal.dialogs.EventLoopProgressMonitor.isCanceled(EventLoopProgressMonitor.java:99)
|     at org.eclipse.core.internal.jobs.JobManager.join(JobManager.java:998)
|     at com.google.cloud.tools.eclipse.test.util.project.ProjectUtils.waitForProjects(ProjectUtils.java:183)
|     at com.google.cloud.tools.eclipse.test.util.project.ProjectUtils.waitForProjects(ProjectUtils.java:176)
|     at com.google.cloud.tools.eclipse.test.util.project.TestProjectCreator.addFacets(TestProjectCreator.java:148)
|     at com.google.cloud.tools.eclipse.test.util.project.TestProjectCreator.createJavaProject(TestProjectCreator.java:112)
|     at com.google.cloud.tools.eclipse.test.util.project.TestProjectCreator.before(TestProjectCreator.java:75)
|     at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)
|     at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
|     at com.google.cloud.tools.eclipse.test.util.ThreadDumpingWatchdog$1.evaluate(ThreadDumpingWatchdog.java:60)
|     at org.junit.rules.RunRules.evaluate(RunRules.java:20)
|     at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
|     at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
|     at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
|     at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
|     at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
|     at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
|     at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
|     at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
|     at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
|     at org.mockito.internal.runners.JUnit45AndHigherRunnerImpl.run(JUnit45AndHigherRunnerImpl.java:37)
|     at org.mockito.runners.MockitoJUnitRunner.run(MockitoJUnitRunner.java:62)
|     at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
|     at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
|     at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
|     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
|     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
|     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
|     at java.lang.reflect.Method.invoke(Method.java:498)
|     at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
|     at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:156)
|     at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:82)
|     at org.eclipse.tycho.surefire.osgibooter.OsgiSurefireBooter.run(OsgiSurefireBooter.java:91)
|     at org.eclipse.tycho.surefire.osgibooter.AbstractUITestApplication$1.run(AbstractUITestApplication.java:35)
|     at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
|     at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
|     - locked org.eclipse.swt.widgets.RunnableLock@10156a2b
|     at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4024)
|     at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3700)
|     at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
|     at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
|     at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
|     at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
|     at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:694)
|     at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
|     at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:606)
|     at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
|     at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
|     at org.eclipse.tycho.surefire.osgibooter.UITestApplication.runApplication(UITestApplication.java:31)
|     at org.eclipse.tycho.surefire.osgibooter.AbstractUITestApplication.run(AbstractUITestApplication.java:120)
|     at org.eclipse.tycho.surefire.osgibooter.UITestApplication.start(UITestApplication.java:37)
|     at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
|     at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
|     at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
|     at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
|     at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
|     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
|     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
|     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
|     at java.lang.reflect.Method.invoke(Method.java:498)
|     at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
|     at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
|     at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
|     at org.eclipse.equinox.launcher.Main.main(Main.java:1488)
| 
| "Worker-3" [37] TIMED_WAITING on org.eclipse.core.internal.jobs.Semaphore@6ae3675d
|     at java.lang.Object.wait(Native Method)
|     - waiting on org.eclipse.core.internal.jobs.Semaphore@6ae3675d
|     at org.eclipse.core.internal.jobs.Semaphore.acquire(Semaphore.java:39)
|     at org.eclipse.core.internal.jobs.OrderedLock.doAcquire(OrderedLock.java:170)
|     at org.eclipse.core.internal.jobs.OrderedLock.acquire(OrderedLock.java:106)
|     at org.eclipse.core.internal.jobs.OrderedLock.acquire(OrderedLock.java:82)
|     at org.eclipse.core.internal.resources.WorkManager.checkIn(WorkManager.java:121)
|     at org.eclipse.core.internal.resources.Workspace.prepareOperation(Workspace.java:2189)
|     at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2236)
|     at org.eclipse.wst.validation.internal.operations.ValidationOperation$1.done(ValidationOperation.java:1447)
|     at org.eclipse.core.internal.jobs.JobListeners$3.notify(JobListeners.java:42)
|     at org.eclipse.core.internal.jobs.JobListeners.doNotify(JobListeners.java:113)
|     at org.eclipse.core.internal.jobs.JobListeners.done(JobListeners.java:151)
|     at org.eclipse.core.internal.jobs.JobManager.cancel(JobManager.java:346)
|     at org.eclipse.core.internal.jobs.InternalJob.cancel(InternalJob.java:185)
|     at org.eclipse.core.runtime.jobs.Job.cancel(Job.java:220)
|     at com.google.cloud.tools.eclipse.appengine.facets.NonSystemJobSuspender.suspendJob(NonSystemJobSuspender.java:79)
|     - locked java.lang.Class@453674ff
|     at com.google.cloud.tools.eclipse.appengine.facets.NonSystemJobScheduleListener.scheduled(NonSystemJobScheduleListener.java:29)
|     at org.eclipse.core.internal.jobs.JobListeners$5.notify(JobListeners.java:54)
|     at org.eclipse.core.internal.jobs.JobListeners.doNotify(JobListeners.java:102)
|     at org.eclipse.core.internal.jobs.JobListeners.scheduled(JobListeners.java:161)
|     at org.eclipse.core.internal.jobs.JobManager.schedule(JobManager.java:1259)
|     at org.eclipse.core.internal.jobs.InternalJob.schedule(InternalJob.java:382)
|     at org.eclipse.core.runtime.jobs.Job.schedule(Job.java:575)
|     at org.eclipse.wst.validation.internal.operations.ValidationOperation$ValidationLauncherJob.run(ValidationOperation.java:106)
|     - locked java.util.LinkedList@48173d7
|     at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
| 
| "Worker-8" [93] WAITING on java.lang.Object@acc9812
|     at java.lang.Object.wait(Native Method)
|     - waiting on java.lang.Object@acc9812
|     at java.lang.Object.wait(Object.java:502)
|     at org.eclipse.core.internal.jobs.ThreadJob.waitForRun(ThreadJob.java:270)
|     at org.eclipse.core.internal.jobs.ThreadJob.joinRun(ThreadJob.java:197)
|     at org.eclipse.core.internal.jobs.ImplicitJobs.begin(ImplicitJobs.java:92)
|     at org.eclipse.core.internal.jobs.JobManager.beginRule(JobManager.java:307)
|     at org.eclipse.core.internal.resources.WorkManager.checkIn(WorkManager.java:120)
|     at org.eclipse.core.internal.resources.Workspace.prepareOperation(Workspace.java:2189)
|     at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2236)
|     at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.setTargetedRuntimes(FacetedProject.java:655)
|     at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.addTargetedRuntime(FacetedProject.java:771)
|     at com.google.cloud.tools.eclipse.appengine.facets.AppEngineStandardFacet.installAllAppEngineRuntimes(AppEngineStandardFacet.java:198)
|     at com.google.cloud.tools.eclipse.appengine.facets.StandardFacetInstallDelegate$AppEngineRuntimeInstallJob.run(StandardFacetInstallDelegate.java:112)
|     at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
| 
| "Worker-10" [126] BLOCKED on java.lang.Class@453674ff owned by 'Worker-3 [id:37]
|     at com.google.cloud.tools.eclipse.appengine.facets.NonSystemJobSuspender.suspendJob(NonSystemJobSuspender.java:77)
|     - blocked on java.lang.Class@453674ff
|     at com.google.cloud.tools.eclipse.appengine.facets.NonSystemJobScheduleListener.scheduled(NonSystemJobScheduleListener.java:29)
|     at org.eclipse.core.internal.jobs.JobListeners$5.notify(JobListeners.java:54)
|     at org.eclipse.core.internal.jobs.JobListeners.doNotify(JobListeners.java:102)
|     at org.eclipse.core.internal.jobs.JobListeners.scheduled(JobListeners.java:161)
|     at org.eclipse.core.internal.jobs.JobManager.schedule(JobManager.java:1259)
|     at org.eclipse.core.internal.jobs.InternalJob.schedule(InternalJob.java:382)
|     at org.eclipse.core.runtime.jobs.Job.schedule(Job.java:575)
|     at org.eclipse.jst.j2ee.refactor.listeners.J2EEElementChangedListener.processJavaProject(J2EEElementChangedListener.java:146)
|     at org.eclipse.jst.j2ee.refactor.listeners.J2EEElementChangedListener.processJavaElementDelta(J2EEElementChangedListener.java:87)
|     at org.eclipse.jst.j2ee.refactor.listeners.J2EEElementChangedListener.processJavaElementDelta(J2EEElementChangedListener.java:80)
|     at org.eclipse.jst.j2ee.refactor.listeners.J2EEElementChangedListener.elementChanged(J2EEElementChangedListener.java:67)
|     at org.eclipse.jdt.internal.core.DeltaProcessor$3.run(DeltaProcessor.java:1662)
|     at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
|     at org.eclipse.jdt.internal.core.DeltaProcessor.notifyListeners(DeltaProcessor.java:1652)
|     at org.eclipse.jdt.internal.core.DeltaProcessor.firePostChangeDelta(DeltaProcessor.java:1486)
|     at org.eclipse.jdt.internal.core.DeltaProcessor.fire(DeltaProcessor.java:1462)
|     at org.eclipse.jdt.internal.core.DeltaProcessor.resourceChanged(DeltaProcessor.java:2074)
|     at org.eclipse.jdt.internal.core.DeltaProcessingState.resourceChanged(DeltaProcessingState.java:477)
|     at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:299)
|     at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
|     at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:289)
|     at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:152)
|     at org.eclipse.core.internal.resources.Workspace.broadcastPostChange(Workspace.java:373)
|     at org.eclipse.core.internal.resources.Workspace.endOperation(Workspace.java:1470)
|     at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:46)
|     at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by chanseokoh** [comment]
Looks like "main" is waiting on "Worker-3", which is in turn waiting on a semaphore. Is it possible to know from the log what this semaphore is? (From the above log, it doesn't seem like that "main" and "Worker-3" are mutually waiting on each other.)

`"Worker-3" [37] TIMED_WAITING on org.eclipse.core.internal.jobs.Semaphore@6ae3675d`

**Comment by briandealwis** [comment]
That lock is listed as from `org.eclipse.core.internal.resources.WorkManager`:
```java
	/**
	 * The primary workspace lock. This lock must be held by any thread
	 * modifying the workspace tree.
	 */
	private final ILock lock;
```
Unfortunately the way Eclipse implements these locks creates a per-thread semaphore to wait on, so it's hard to see who has the lock.

The lock itself is acquired in `WorkManager#checkIn()` as you can see in the traces.  The lock is released by a call to `WorkManager#checkOut()` that happens in `Workspace#endOperation()` on line 1481.  That happens _after_ `endOperation()` calls `broadcastPostChange()` at line 1469 broadcasts any post-changes notifications. So those notifications are performed with the lock held. You can see _Worker-10_ has done that.

So ultimately the problem here is that `NonSystemJobSuspender` was in the midst cancelling a job (`Job.cancel()`) on _Worker-3_, which has triggered an event (which is trying to do some workspace-related thing and thus trying to acquire the workspace lock), while holding its object monitor (since `suspendJob()` is synchronized). _Worker-10_ is trying to schedule a job, which is being examined the `NonSystemJobSuspender`, while holding the workspace lock.

I have a patch that reduces the synchronized regions in `NonSystemJobSuspender`, such that the `Job.cancel()` and `Job.schedule()` calls are done without the object monitor.

**Comment by briandealwis** [comment]
[Full dump of _testCheckConflictingId_differentServiceIds_](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/files/764612/fulldump.txt)
