### ISSUE TITLE
ProjectUtils.waitForProjects() needs to wait for M2E/WTP configuration jobs.

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#1379]
We have occasional failures in `NewMavenBasedAppEngineProjectWizardTest` that suggests that we need to wait for a M2E/WTP job in our `waitForProjects()`.
```
testHelloWorld(com.google.cloud.tools.eclipse.integration.appengine.NewMavenBasedAppEngineProjectWizardTest)  Time elapsed: 7.182 sec  <<< FAILURE!
java.lang.AssertionError: Project does not have standard facet
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.google.cloud.tools.eclipse.integration.appengine.NewMavenBasedAppEngineProjectWizardTest.createAndCheck(NewMavenBasedAppEngineProjectWizardTest.java:107)
	at com.google.cloud.tools.eclipse.integration.appengine.NewMavenBasedAppEngineProjectWizardTest.testHelloWorld(NewMavenBasedAppEngineProjectWizardTest.java:58)
```

**Comment by briandealwis** [comment]
Fixed by #1383, to properly wait for window _closes_.
