### ISSUE TITLE
Tests occasionally fail with ArrayIndexOutOfBoundsException in ProcessEnvironment.environ()

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#1445]
We've seen very occasional test failures to do with errors in `java.lang.ProcessEnvironment.environ()`, a native method.  I wonder if it's due to an old version of Java8?
```
Caused by: java.lang.ExceptionInInitializerError
	at java.lang.System.getenv(System.java:894)
	at org.apache.felix.gogo.options.Options.<init>(Options.java:309)
	at org.apache.felix.gogo.options.Options.compile(Options.java:118)
	at org.apache.felix.gogo.shell.Shell.gosh(Shell.java:71)
	... 14 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 165
	at java.lang.ProcessEnvironment.environ(Native Method)
	at java.lang.ProcessEnvironment.<clinit>(ProcessEnvironment.java:70)
	… 18 more
```

**Comment by briandealwis** [comment]
Seen in Oxygen on Travis.  In this case, the test setup failed:
```
!SESSION 2017-02-18 19:10:02.933 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_31
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -application org.eclipse.tycho.surefire.osgibooter.uitest -testproperties /home/travis/build/GoogleCloudPlatform/google-cloud-eclipse/plugins/com.google.cloud.tools.eclipse.appengine.ui.test/target/surefire.properties -product org.eclipse.platform.ide
Command-line arguments:  -debug -consolelog -data /home/travis/build/GoogleCloudPlatform/google-cloud-eclipse/plugins/com.google.cloud.tools.eclipse.appengine.ui.test/target/work/data -application org.eclipse.tycho.surefire.osgibooter.uitest -testproperties /home/travis/build/GoogleCloudPlatform/google-cloud-eclipse/plugins/com.google.cloud.tools.eclipse.appengine.ui.test/target/surefire.properties -product org.eclipse.platform.ide
!ENTRY org.eclipse.equinox.app 0 0 2017-02-18 19:10:04.992
!MESSAGE Product org.eclipse.platform.ide could not be found.
gogo: InvocationTargetException: null
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.apache.felix.gogo.runtime.Reflective.invoke(Reflective.java:137)
	at org.apache.felix.gogo.runtime.CommandProxy.execute(CommandProxy.java:82)
	at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:477)
	at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:403)
	at org.apache.felix.gogo.runtime.Pipe.run(Pipe.java:108)
	at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:183)
	at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:120)
	at org.apache.felix.gogo.runtime.CommandSessionImpl.execute(CommandSessionImpl.java:89)
	at org.apache.felix.gogo.shell.Activator.run(Activator.java:75)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ExceptionInInitializerError
	at java.lang.System.getenv(System.java:894)
	at org.apache.felix.gogo.options.Options.<init>(Options.java:309)
	at org.apache.felix.gogo.options.Options.compile(Options.java:118)
	at org.apache.felix.gogo.shell.Shell.gosh(Shell.java:71)
	... 14 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 165
	at java.lang.ProcessEnvironment.environ(Native Method)
	at java.lang.ProcessEnvironment.<clinit>(ProcessEnvironment.java:70)
	… 18 more
```
which results in the later failure of loading `org.eclipse.core.net`
```
!ENTRY org.eclipse.osgi 4 0 2017-02-18 19:10:06.830
!MESSAGE An error occurred while automatically activating bundle org.eclipse.core.net (89).
!STACK 0
org.osgi.framework.BundleException: Exception in org.eclipse.core.internal.net.Activator.start() of bundle org.eclipse.core.net.
[…]
Root exception:
java.lang.NoClassDefFoundError: Could not initialize class java.lang.ProcessEnvironment
	at java.lang.System.getenv(System.java:894)
	at org.eclipse.equinox.internal.security.storage.SecurePreferencesMapper.open(SecurePreferencesMapper.java:95)
	at org.eclipse.equinox.internal.security.storage.SecurePreferencesMapper.getDefault(SecurePreferencesMapper.java:52)
	at org.eclipse.equinox.security.storage.SecurePreferencesFactory.getDefault(SecurePreferencesFactory.java:49)
	at org.eclipse.core.internal.net.ProxyType.getNode(ProxyType.java:523)
	at org.eclipse.core.internal.net.ProxyType.loadProxyAuth(ProxyType.java:533)
	at org.eclipse.core.internal.net.ProxyType.createProxyData(ProxyType.java:138)
	at org.eclipse.core.internal.net.ProxyType.getProxyData(ProxyType.java:127)
	at org.eclipse.core.internal.net.PreferenceManager.migrateInstanceScopePreferences(PreferenceManager.java:292)
	at org.eclipse.core.internal.net.PreferenceManager.migrate(PreferenceManager.java:260)
	at org.eclipse.core.internal.net.ProxyManager.checkMigrated(ProxyManager.java:399)
	at org.eclipse.core.internal.net.ProxyManager.initialize(ProxyManager.java:269)
	at org.eclipse.core.internal.net.Activator.start(Activator.java:175)
[…]
```
which leads to the failure of the workbench:
```
!ENTRY org.eclipse.osgi 4 0 2017-02-18 19:10:06.882
!MESSAGE Application error
!STACK 1
java.lang.NoClassDefFoundError: org/eclipse/core/net/proxy/IProxyService
	at org.eclipse.ui.internal.ide.application.IDEWorkbenchAdvisor.activateProxyService(IDEWorkbenchAdvisor.java:278)
	at org.eclipse.ui.internal.ide.application.IDEWorkbenchAdvisor.postStartup(IDEWorkbenchAdvisor.java:258)
	at org.eclipse.ui.internal.Workbench.lambda$17(Workbench.java:2874)
	at org.eclipse.ui.internal.Workbench$$Lambda$81/2008619427.run(Unknown Source)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1088)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:684)
	at org.eclipse.ui.internal.Workbench$$Lambda$18/1793899405.run(Unknown Source)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:598)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
```
The build notes:
```
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-surefire-plugin:0.24.0:test (default-test) on project com.google.cloud.tools.eclipse.appengine.ui.test: An unexpected error occured while launching the test runtime (return code 13). See log for details. -> [Help 1]```

**Comment by elharo** [comment]
seems to be cured these days, at least on travis

**Comment by hawicz** [comment]
If another thread is using setenv() or putenv() (from native code), there's a potential race in System.getenv(), which calls ProcessEnvironment.environ().  If the environ array changes in between the two loops in the environ() native code then it can overrun the array it allocates.
