### ISSUE TITLE
AppEngineLibrariesInPluginXmlTest flaky

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1477]
I think; so far this has only been detected in one, non-merged PR.

com.google.cloud.tools.eclipse.appengine.libraries.AppEngineLibrariesInPluginXmlTest
testObjectifyLibraryConfig(com.google.cloud.tools.eclipse.appengine.libraries.AppEngineLibrariesInPluginXmlTest)  Time elapsed: 0.003 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: is <http://static.javadoc.io/com.googlecode.objectify/objectify/5.1.14/>
     but: was null
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at com.google.cloud.tools.eclipse.appengine.libraries.AppEngineLibrariesInPluginXmlTest.testObjectifyLibraryConfig(AppEngineLibrariesInPluginXmlTest.java:148)

testAppEngineApiLibraryConfig(com.google.cloud.tools.eclipse.appengine.libraries.AppEngineLibrariesInPluginXmlTest)  Time elapsed: 0 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: is <https://cloud.google.com/appengine/docs/java/javadoc/>
     but: was null
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at com.google.cloud.tools.eclipse.appengine.libraries.AppEngineLibrariesInPluginXmlTest.testAppEngineApiLibraryConfig(AppEngineLibrariesInPluginXmlTest.java:69)

testEndpointsLibraryConfig(com.google.cloud.tools.eclipse.appengine.libraries.AppEngineLibrariesInPluginXmlTest)  Time elapsed: 0 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: is <https://cloud.google.com/appengine/docs/java/endpoints/javadoc/>
     but: was null
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at com.google.cloud.tools.eclipse.appengine.libraries.AppEngineLibrariesInPluginXmlTest.testEndpointsLibraryConfig(AppEngineLibrariesInPluginXmlTest.java:113)

**Comment by elharo** [comment]
In order to get to the failing assertions, the library must have successfully loaded. It's the library file in the library that is having problems:

```
    assertThat(objectifyLibrary.getLibraryFiles().size(), is(2));
    LibraryFile objectifyLibraryFile = objectifyLibrary.getLibraryFiles().get(0);
    assertThat(objectifyLibraryFile.getJavadocUri(), 
        is(new URI("http://static.javadoc.io/com.googlecode.objectify/objectify/5.1.14/")));
```

I wonder if the extension registry is being parsed asynchronously.

**Comment by elharo** [comment]
The real question is whether this might return while elements are still being initialized:

```
    IConfigurationElement[] elements = RegistryFactory.getRegistry().getConfigurationElementsFor(
        "com.google.cloud.tools.eclipse.appengine.libraries");
```

One solution might be to not use the extension registry here, and just parse the XML directly.
