### ISSUE TITLE
Removing module from Server is not possible. 

### ISSUE THREAD

**Issue by branflake2267** [GoogleCloudPlatform/google-cloud-eclipse#1503]
Removing a module from the App Engine Standard Server is not possible. 

1. After running server

2. right click on module to be removed and choose remove, then ok. 
![screen shot 2017-02-28 at 3 44 09 pm](https://cloud.githubusercontent.com/assets/1326504/23439744/08c0b2a8-fdcd-11e6-8fad-502cd3c63713.png)

3. The module will not be removed. 

Version Used to replicate this. 
![screen shot 2017-02-28 at 3 44 02 pm](https://cloud.githubusercontent.com/assets/1326504/23439750/0d3e329c-fdcd-11e6-808d-604a502a66f6.png)

**Comment by briandealwis** [comment]
It works for me @branflake226.  Do you get an error or see anything logged?

**Comment by branflake2267** [comment]
Hm, I'll close it then. I didn't notice anything. I'll report back if I can get more data.

**Comment by branflake2267** [comment]
1. I'm getting an exception selecting the module to begin with below. 
2. And then I get another round of exceptions when removal is excepted. 
3. The module is removed after the two rounds of exception today. 

1. first round of exceptions - on selection of module
```
Mar 01, 2017 1:58:01 PM com.google.cloud.tools.eclipse.appengine.localserver.server.ModuleUtils getServiceId
WARNING: Unable to read /gwt-basic-rpc-appengine/target/m2e-wtp/web-resources/WEB-INF/appengine-web.xml
org.eclipse.core.internal.resources.ResourceException: Resource is out of sync with the file system: '/gwt-basic-rpc-appengine/target/m2e-wtp/web-resources/WEB-INF/appengine-web.xml'.
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.read(FileSystemResourceManager.java:849)
	at org.eclipse.core.internal.resources.File.getContents(File.java:277)
	at org.eclipse.core.internal.resources.File.getContents(File.java:268)
	at com.google.cloud.tools.eclipse.appengine.localserver.server.ModuleUtils.getServiceId(ModuleUtils.java:46)
	at com.google.cloud.tools.eclipse.appengine.localserver.server.LocalAppEngineServerDelegate.getServiceId(LocalAppEngineServerDelegate.java:165)
	at com.google.cloud.tools.eclipse.appengine.localserver.server.LocalAppEngineServerDelegate.checkConflictingServiceIds(LocalAppEngineServerDelegate.java:145)
	at com.google.cloud.tools.eclipse.appengine.localserver.server.LocalAppEngineServerDelegate.canModifyModules(LocalAppEngineServerDelegate.java:87)
	at org.eclipse.wst.server.core.internal.Server.canModifyModules(Server.java:2509)
	at org.eclipse.wst.server.ui.internal.view.servers.ModuleSloshAction.perform(ModuleSloshAction.java:84)
	at org.eclipse.wst.server.ui.internal.view.servers.AbstractServerAction.run(AbstractServerAction.java:64)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:473)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:565)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:397)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4256)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1501)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1524)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1509)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1313)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4080)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3706)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:693)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1492)

Mar 01, 2017 1:58:01 PM com.google.cloud.tools.eclipse.appengine.localserver.server.ModuleUtils getServiceId
WARNING: Unable to read /gwt-basic-rpc-appengine/target/m2e-wtp/web-resources/WEB-INF/appengine-web.xml
org.eclipse.core.internal.resources.ResourceException: Resource is out of sync with the file system: '/gwt-basic-rpc-appengine/target/m2e-wtp/web-resources/WEB-INF/appengine-web.xml'.
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.read(FileSystemResourceManager.java:849)
	at org.eclipse.core.internal.resources.File.getContents(File.java:277)
	at org.eclipse.core.internal.resources.File.getContents(File.java:268)
	at com.google.cloud.tools.eclipse.appengine.localserver.server.ModuleUtils.getServiceId(ModuleUtils.java:46)
	at com.google.cloud.tools.eclipse.appengine.localserver.server.LocalAppEngineServerDelegate.getServiceId(LocalAppEngineServerDelegate.java:165)
	at com.google.cloud.tools.eclipse.appengine.localserver.server.LocalAppEngineServerDelegate.checkConflictingServiceIds(LocalAppEngineServerDelegate.java:145)
	at com.google.cloud.tools.eclipse.appengine.localserver.server.LocalAppEngineServerDelegate.canModifyModules(LocalAppEngineServerDelegate.java:87)
	at org.eclipse.wst.server.core.internal.Server.canModifyModules(Server.java:2509)
	at org.eclipse.wst.server.ui.internal.wizard.page.ModifyModulesComposite.setServer(ModifyModulesComposite.java:335)
	at org.eclipse.wst.server.ui.internal.wizard.fragment.ModifyModulesWizardFragment.updateModules(ModifyModulesWizardFragment.java:81)
	at org.eclipse.wst.server.ui.internal.wizard.fragment.ModifyModulesWizardFragment.enter(ModifyModulesWizardFragment.java:72)
	at org.eclipse.wst.server.ui.internal.wizard.TaskWizard.switchWizardFragment(TaskWizard.java:307)
	at org.eclipse.wst.server.ui.internal.wizard.TaskWizardPage.setVisible(TaskWizardPage.java:99)
	at org.eclipse.jface.wizard.WizardDialog.showStartingPage(WizardDialog.java:1242)
	at org.eclipse.jface.wizard.WizardDialog.createContents(WizardDialog.java:590)
	at org.eclipse.jface.window.Window.create(Window.java:426)
	at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1095)
	at org.eclipse.jface.window.Window.open(Window.java:783)
	at org.eclipse.wst.server.ui.internal.view.servers.ModuleSloshAction.perform(ModuleSloshAction.java:98)
	at org.eclipse.wst.server.ui.internal.view.servers.AbstractServerAction.run(AbstractServerAction.java:64)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:473)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:565)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:397)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4256)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1501)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1524)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1509)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1313)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4080)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3706)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:693)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1492)

Mar 01, 2017 1:58:06 PM com.google.cloud.tools.eclipse.appengine.localserver.server.ModuleUtils getServiceId
WARNING: Unable to read /gwt-basic-rpc-appengine/target/m2e-wtp/web-resources/WEB-INF/appengine-web.xml
org.eclipse.core.internal.resources.ResourceException: Resource is out of sync with the file system: '/gwt-basic-rpc-appengine/target/m2e-wtp/web-resources/WEB-INF/appengine-web.xml'.
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.read(FileSystemResourceManager.java:849)
	at org.eclipse.core.internal.resources.File.getContents(File.java:277)
	at org.eclipse.core.internal.resources.File.getContents(File.java:268)
	at com.google.cloud.tools.eclipse.appengine.localserver.server.ModuleUtils.getServiceId(ModuleUtils.java:46)
	at com.google.cloud.tools.eclipse.appengine.localserver.server.LocalAppEngineServerDelegate.getServiceId(LocalAppEngineServerDelegate.java:165)
	at com.google.cloud.tools.eclipse.appengine.localserver.server.LocalAppEngineServerDelegate.checkConflictingServiceIds(LocalAppEngineServerDelegate.java:145)
	at com.google.cloud.tools.eclipse.appengine.localserver.server.LocalAppEngineServerDelegate.canModifyModules(LocalAppEngineServerDelegate.java:87)
	at org.eclipse.wst.server.core.internal.Server.canModifyModules(Server.java:2509)
	at org.eclipse.wst.server.core.internal.ServerWorkingCopy.modifyModules(ServerWorkingCopy.java:545)
	at org.eclipse.wst.server.ui.internal.wizard.WizardTaskUtil.modifyModules(WizardTaskUtil.java:226)
	at org.eclipse.wst.server.ui.internal.wizard.fragment.ModifyModulesWizardFragment.performFinish(ModifyModulesWizardFragment.java:141)
	at org.eclipse.wst.server.ui.internal.wizard.TaskWizard.executeTask(TaskWizard.java:268)
	at org.eclipse.wst.server.ui.internal.wizard.TaskWizard$2.run(TaskWizard.java:215)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2262)
	at org.eclipse.wst.server.ui.internal.wizard.page.WorkspaceRunnableAdapter.run(WorkspaceRunnableAdapter.java:35)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
```

2. round of exceptions - on removal
```
WARNING: Unable to read /gwt-basic-rpc-appengine/target/m2e-wtp/web-resources/WEB-INF/appengine-web.xml
org.eclipse.core.internal.resources.ResourceException: Resource is out of sync with the file system: '/gwt-basic-rpc-appengine/target/m2e-wtp/web-resources/WEB-INF/appengine-web.xml'.
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.read(FileSystemResourceManager.java:849)
	at org.eclipse.core.internal.resources.File.getContents(File.java:277)
	at org.eclipse.core.internal.resources.File.getContents(File.java:268)
	at com.google.cloud.tools.eclipse.appengine.localserver.server.ModuleUtils.getServiceId(ModuleUtils.java:46)
	at com.google.cloud.tools.eclipse.appengine.localserver.server.LocalAppEngineServerDelegate.getServiceId(LocalAppEngineServerDelegate.java:165)
	at com.google.cloud.tools.eclipse.appengine.localserver.server.LocalAppEngineServerDelegate.checkConflictingServiceIds(LocalAppEngineServerDelegate.java:122)
	at com.google.cloud.tools.eclipse.appengine.localserver.server.LocalAppEngineServerDelegate.canModifyModules(LocalAppEngineServerDelegate.java:87)
	at org.eclipse.wst.server.core.internal.Server.canModifyModules(Server.java:2509)
	at org.eclipse.wst.server.core.internal.ServerWorkingCopy.modifyModules(ServerWorkingCopy.java:545)
	at org.eclipse.wst.server.ui.internal.view.servers.RemoveModuleAction$1.run(RemoveModuleAction.java:91)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)

Mar 01, 2017 2:01:10 PM com.google.cloud.tools.eclipse.appengine.localserver.server.ModuleUtils getServiceId
WARNING: Unable to read /gwt-basic-rpc-appengine/target/m2e-wtp/web-resources/WEB-INF/appengine-web.xml
org.eclipse.core.internal.resources.ResourceException: Resource is out of sync with the file system: '/gwt-basic-rpc-appengine/target/m2e-wtp/web-resources/WEB-INF/appengine-web.xml'.
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.read(FileSystemResourceManager.java:849)
	at org.eclipse.core.internal.resources.File.getContents(File.java:277)
	at org.eclipse.core.internal.resources.File.getContents(File.java:268)
	at com.google.cloud.tools.eclipse.appengine.localserver.server.ModuleUtils.getServiceId(ModuleUtils.java:46)
	at com.google.cloud.tools.eclipse.appengine.localserver.server.LocalAppEngineServerDelegate.getServiceId(LocalAppEngineServerDelegate.java:165)
	at com.google.cloud.tools.eclipse.appengine.localserver.server.LocalAppEngineServerDelegate.checkConflictingServiceIds(LocalAppEngineServerDelegate.java:134)
	at com.google.cloud.tools.eclipse.appengine.localserver.server.LocalAppEngineServerDelegate.canModifyModules(LocalAppEngineServerDelegate.java:87)
	at org.eclipse.wst.server.core.internal.Server.canModifyModules(Server.java:2509)
	at org.eclipse.wst.server.core.internal.ServerWorkingCopy.modifyModules(ServerWorkingCopy.java:545)
	at org.eclipse.wst.server.ui.internal.view.servers.RemoveModuleAction$1.run(RemoveModuleAction.java:91)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)

```

**Comment by branflake2267** [comment]
Resource out of sync, this could be a dev env issue. After project refresh it works as it should. Do you think I should close?

**Comment by chanseokoh** [comment]
@branflake2267 Just in case, have you ever used the quick-fix on `appengine-web.xml`? We had [this issue](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/1420), whose fix is not in the latest release.

**Comment by branflake2267** [comment]
Ah nice. The fix for me was a refresh, the eclipse directory listings were out of date, compared to the physical files. A refresh updated. I'm not sure if that caused the issue. Since I'm running RCP IDE, with a target on the testing repo, with a recent update, I think it was a hard close that caused the files to be out of sync. I think I'll close this for now, seems more likely I caused the issue.
