### ISSUE TITLE
WTP DependencyGraph-related deadlock in new Maven project wizard

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#1612]
A deadlock between the `DepedencyGraph` update job and `WorkspaceModifyOperation` at `CreateMavenBasedAppEngineStandardProject.createArchetypeProjects()`.

```
| "Worker-6" [94] BLOCKED on org.eclipse.wst.common.componentcore.internal.util.ComponentImplManager@27cc2cb2 owned by 'ModalContext [id:233]
|     at org.eclipse.wst.common.componentcore.internal.util.ComponentImplManager.createComponent(ComponentImplManager.java)
|     - blocked on org.eclipse.wst.common.componentcore.internal.util.ComponentImplManager@27cc2cb2
|     at org.eclipse.wst.common.componentcore.internal.util.ComponentImplManager.createComponent(ComponentImplManager.java:212)
|     at org.eclipse.wst.common.componentcore.ComponentCore.createComponent(ComponentCore.java:64)
|     at org.eclipse.wst.common.componentcore.internal.builder.DependencyGraphImpl$GraphUpdateJob$1.run(DependencyGraphImpl.java:494)
|     at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
|     at org.eclipse.wst.common.componentcore.internal.builder.DependencyGraphImpl$GraphUpdateJob.run(DependencyGraphImpl.java:462)
|     at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
```

- `ModalContext` is already in the `ComponentImplManager.createComponent()`:
```
| "ModalContext" [233] TIMED_WAITING on org.eclipse.core.internal.jobs.Semaphore@2ad03894
|     at java.lang.Object.wait(Native Method)
|     - waiting on org.eclipse.core.internal.jobs.Semaphore@2ad03894
|     at org.eclipse.core.internal.jobs.Semaphore.acquire(Semaphore.java:39)
|     at org.eclipse.core.internal.jobs.OrderedLock.doAcquire(OrderedLock.java:170)
|     at org.eclipse.core.internal.jobs.OrderedLock.acquire(OrderedLock.java:106)
|     at org.eclipse.core.internal.jobs.OrderedLock.acquire(OrderedLock.java:82)
|     at org.eclipse.wst.common.componentcore.internal.StructureEdit.getComponentModelRoot(StructureEdit.java:467)
|     at org.eclipse.wst.common.componentcore.internal.StructureEdit.getWorkbenchModules(StructureEdit.java:506)
|     at org.eclipse.wst.common.componentcore.internal.StructureEdit.getComponent(StructureEdit.java:949)
|     at org.eclipse.wst.common.componentcore.internal.resources.VirtualComponent.createResource(VirtualComponent.java:124)
|     at org.eclipse.wst.common.componentcore.internal.resources.VirtualComponent.addManagedResource(VirtualComponent.java:100)
|     at org.eclipse.wst.common.componentcore.internal.resources.VirtualComponent.initializeResource(VirtualComponent.java:114)
|     at org.eclipse.wst.common.componentcore.internal.resources.VirtualComponent.<init>(VirtualComponent.java:148)
|     at org.eclipse.wst.common.componentcore.internal.util.ComponentImplManager.createComponent(ComponentImplManager.java:250)
|     - locked org.eclipse.wst.common.componentcore.internal.util.ComponentImplManager@27cc2cb2
|     at org.eclipse.wst.common.componentcore.ComponentCore.createComponent(ComponentCore.java:84)
|     at org.eclipse.jst.j2ee.web.project.facet.WebFacetInstallDelegate.setContentPropertyIfNeeded(WebFacetInstallDelegate.java:221)
|     at org.eclipse.jst.j2ee.web.project.facet.WebFacetInstallDelegate.execute(WebFacetInstallDelegate.java:86)
|     at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.callDelegate(FacetedProject.java:1477)
|     at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.modifyInternal(FacetedProject.java:441)
|     at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.mergeChangesInternal(FacetedProject.java:1181)
|     at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.access$2(FacetedProject.java:1117)
|     at org.eclipse.wst.common.project.facet.core.internal.FacetedProject$1.run(FacetedProject.java:324)
|     at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
|     at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2267)
|     at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.modify(FacetedProject.java:339)
|     at org.eclipse.m2e.wtp.WebProjectConfiguratorDelegate.configure(WebProjectConfiguratorDelegate.java:136)
|     at org.eclipse.m2e.wtp.AbstractProjectConfiguratorDelegate.configureProject(AbstractProjectConfiguratorDelegate.java:94)
|     at org.eclipse.m2e.wtp.WTPProjectConfigurator.configure(WTPProjectConfigurator.java:68)
|     at org.eclipse.m2e.core.project.configurator.AbstractLifecycleMapping.configure(AbstractLifecycleMapping.java:120)
|     at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$3.call(ProjectConfigurationManager.java:508)
|     at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$3.call(ProjectConfigurationManager.java:1)
|     at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
|     at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
|     at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration(ProjectConfigurationManager.java:501)
|     at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.configureNewMavenProjects(ProjectConfigurationManager.java:288)
|     at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$1.call(ProjectConfigurationManager.java:175)
|     at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$1.call(ProjectConfigurationManager.java:1)
|     at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
|     at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112)
|     at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
|     at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1355)
|     at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.importProjects(ProjectConfigurationManager.java:143)
|     at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.createArchetypeProjects0(ProjectConfigurationManager.java:862)
|     at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$5.call(ProjectConfigurationManager.java:791)
|     at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$5.call(ProjectConfigurationManager.java:1)
|     at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
|     at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
|     at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
|     at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1355)
|     at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.createArchetypeProjects(ProjectConfigurationManager.java:789)
|     at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.createArchetypeProjects(ProjectConfigurationManager.java:775)
|     at com.google.cloud.tools.eclipse.appengine.newproject.maven.CreateMavenBasedAppEngineStandardProject.execute(CreateMavenBasedAppEngineStandardProject.java:106)
|     at org.eclipse.ui.actions.WorkspaceModifyOperation.lambda$0(WorkspaceModifyOperation.java:107)
|     at org.eclipse.ui.actions.WorkspaceModifyOperation$$Lambda$311/492025551.run(Unknown Source)
|     at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
|     at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2267)
|     at org.eclipse.ui.actions.WorkspaceModifyOperation.run(WorkspaceModifyOperation.java:128)
|     - locked com.google.cloud.tools.eclipse.appengine.newproject.maven.CreateMavenBasedAppEngineStandardProject@2417c266
|     at com.google.cloud.tools.eclipse.appengine.newproject.maven.MavenArchetypeProjectWizard$1.run(MavenArchetypeProjectWizard.java:105)
|     at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
```

**Comment by chanseokoh** [comment]
The log is from https://travis-ci.org/GoogleCloudPlatform/google-cloud-eclipse/builds/212205748.
