### ISSUE TITLE
JacksonFactory not found in Dataflow new project wizard

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1745]
```

!STACK 0
java.lang.NoClassDefFoundError: com/google/api/client/json/jackson2/JacksonFactory
	at com.google.api.client.googleapis.util.Utils.getDefaultJsonFactory(Utils.java:36)
	at com.google.api.client.googleapis.auth.oauth2.GoogleCredential.getApplicationDefault(GoogleCredential.java:191)
	at com.google.cloud.tools.eclipse.dataflow.core.util.Transport.newStorageClient(Transport.java:44)
	at com.google.cloud.tools.eclipse.dataflow.core.project.GcsDataflowProjectClient.createWithDefaultClient(GcsDataflowProjectClient.java:47)
	at com.google.cloud.tools.eclipse.dataflow.ui.preferences.RunOptionsDefaultsComponent.setupGcsClient(RunOptionsDefaultsComponent.java:142)
	at com.google.cloud.tools.eclipse.dataflow.ui.preferences.RunOptionsDefaultsComponent.<init>(RunOptionsDefaultsComponent.java:85)
	at com.google.cloud.tools.eclipse.dataflow.ui.page.NewDataflowProjectWizardDefaultRunOptionsPage.createControl(NewDataflowProjectWizardDefaultRunOptionsPage.java:57)
	at org.eclipse.jface.wizard.Wizard.createPageControls(Wizard.java:175)
	at org.eclipse.jface.wizard.WizardDialog.createPageControls(WizardDialog.java:705)
	at org.eclipse.jface.wizard.WizardDialog.setWizard(WizardDialog.java:1153)
	at org.eclipse.jface.wizard.WizardDialog.updateForPage(WizardDialog.java:1211)
	at org.eclipse.jface.wizard.WizardDialog.access$4(WizardDialog.java:1208)
	at org.eclipse.jface.wizard.WizardDialog$8.run(WizardDialog.java:1197)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.jface.wizard.WizardDialog.showPage(WizardDialog.java:1194)
	at org.eclipse.jface.wizard.WizardDialog.nextPressed(WizardDialog.java:885)
	at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:425)
	at org.eclipse.jface.dialogs.Dialog$2.widgetSelected(Dialog.java:619)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:248)
```

**Comment by elharo** [comment]
Looks like there might be a race condition of some kind. Second try often succeeds. Is it downloading this from Maven central

**Comment by elharo** [comment]
This appears to be needed only for login, so switching over to `com.google.cloud.tools.eclipse.login` may make it moot.

**Comment by elharo** [comment]
I think see what we need. `Transport.newStorageClient` needs to pull this from `IGoogleApiFactory` rather than setting up the client directly.
