### ISSUE TITLE
Possibly flaky test: XmlValidatorTest.testXsdValidation()

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#1801]
```
testXsdValidation(com.google.cloud.tools.eclipse.appengine.validation.XmlValidatorTest)  Time elapsed: 4.222 sec  <<< FAILURE!
java.lang.AssertionError: expected:<1> but was:<2>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.google.cloud.tools.eclipse.appengine.validation.XmlValidatorTest.testXsdValidation(XmlValidatorTest.java:158)
```

**Comment by chanseokoh** [comment]
#1803 to log more debugging messages paid off! Investigate https://travis-ci.org/GoogleCloudPlatform/google-cloud-eclipse/jobs/223288050.

**Comment by chanseokoh** [comment]
Copying the log here just in case the log gets lost:

testXsdValidation(com.google.cloud.tools.eclipse.appengine.validation.XmlValidatorTest)  Time elapsed: 9.626 sec  <<< FAILURE!
java.lang.AssertionError: Expected 1 marker, got 2 markers with messages: cvc-complex-type.2.4.a: Invalid content was found starting with element 'foo'. One of '{"http://appengine.google.com/ns/1.0":application, "http://appengine.google.com/ns/1.0":version, "http://appengine.google.com/ns/1.0":runtime, "http://appengine.google.com/ns/1.0":module, "http://appengine.google.com/ns/1.0":service, "http://appengine.google.com/ns/1.0":instance-class, "http://appengine.google.com/ns/1.0":automatic-scaling, "http://appengine.google.com/ns/1.0":manual-scaling, "http://appengine.google.com/ns/1.0":basic-scaling, "http://appengine.google.com/ns/1.0":static-files, "http://appengine.google.com/ns/1.0":resource-files, "http://appengine.google.com/ns/1.0":system-properties, "http://appengine.google.com/ns/1.0":vm-settings, "http://appengine.google.com/ns/1.0":beta-settings, "http://appengine.google.com/ns/1.0":vm-health-check, "http://appengine.google.com/ns/1.0":health-check, "http://appengine.google.com/ns/1.0":resources, "http://appengine.google.com/ns/1.0":network, "http://appengine.google.com/ns/1.0":env-variables, "http://appengine.google.com/ns/1.0":ssl-enabled, "http://appengine.google.com/ns/1.0":sessions-enabled, "http://appengine.google.com/ns/1.0":async-session-persistence, "http://appengine.google.com/ns/1.0":user-permissions, "http://appengine.google.com/ns/1.0":public-root, "http://appengine.google.com/ns/1.0":inbound-services, "http://appengine.google.com/ns/1.0":precompilation-enabled, "http://appengine.google.com/ns/1.0":admin-console, "http://appengine.google.com/ns/1.0":static-error-handlers, "http://appengine.google.com/ns/1.0":warmup-requests-enabled, "http://appengine.google.com/ns/1.0":threadsafe, "http://appengine.google.com/ns/1.0":auto-id-policy, "http://appengine.google.com/ns/1.0":code-lock, "http://appengine.google.com/ns/1.0":vm, "http://appengine.google.com/ns/1.0":env, "http://appengine.google.com/ns/1.0":class-loader-config, "http://appengine.google.com/ns/1.0":url-stream-handler, "http://appengine.google.com/ns/1.0":use-google-connector-j, "http://appengine.google.com/ns/1.0":api-config}' is expected.
cvc-complex-type.2.4.a: Invalid content was found starting with element 'foo'. One of '{"http://appengine.google.com/ns/1.0":application, "http://appengine.google.com/ns/1.0":version, "http://appengine.google.com/ns/1.0":runtime, "http://appengine.google.com/ns/1.0":module, "http://appengine.google.com/ns/1.0":service, "http://appengine.google.com/ns/1.0":instance-class, "http://appengine.google.com/ns/1.0":automatic-scaling, "http://appengine.google.com/ns/1.0":manual-scaling, "http://appengine.google.com/ns/1.0":basic-scaling, "http://appengine.google.com/ns/1.0":static-files, "http://appengine.google.com/ns/1.0":resource-files, "http://appengine.google.com/ns/1.0":system-properties, "http://appengine.google.com/ns/1.0":vm-settings, "http://appengine.google.com/ns/1.0":beta-settings, "http://appengine.google.com/ns/1.0":vm-health-check, "http://appengine.google.com/ns/1.0":health-check, "http://appengine.google.com/ns/1.0":resources, "http://appengine.google.com/ns/1.0":network, "http://appengine.google.com/ns/1.0":env-variables, "http://appengine.google.com/ns/1.0":ssl-enabled, "http://appengine.google.com/ns/1.0":sessions-enabled, "http://appengine.google.com/ns/1.0":async-session-persistence, "http://appengine.google.com/ns/1.0":user-permissions, "http://appengine.google.com/ns/1.0":public-root, "http://appengine.google.com/ns/1.0":inbound-services, "http://appengine.google.com/ns/1.0":precompilation-enabled, "http://appengine.google.com/ns/1.0":admin-console, "http://appengine.google.com/ns/1.0":static-error-handlers, "http://appengine.google.com/ns/1.0":warmup-requests-enabled, "http://appengine.google.com/ns/1.0":threadsafe, "http://appengine.google.com/ns/1.0":auto-id-policy, "http://appengine.google.com/ns/1.0":code-lock, "http://appengine.google.com/ns/1.0":vm, "http://appengine.google.com/ns/1.0":env, "http://appengine.google.com/ns/1.0":class-loader-config, "http://appengine.google.com/ns/1.0":url-stream-handler, "http://appengine.google.com/ns/1.0":use-google-connector-j, "http://appengine.google.com/ns/1.0":api-config}' is expected.
 expected:<1> but was:<2>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.google.cloud.tools.eclipse.appengine.validation.XmlValidatorTest.testXsdValidation(XmlValidatorTest.java:163)

**Comment by chanseokoh** [comment]
Finally, I found a way to reproduce this. Give some time to the workbench before calling `findMarkers()`:

```java
    IFile file = project.getFile("src/main/webapp/WEB-INF/appengine-web.xml");
    file.create(new ByteArrayInputStream(xml.getBytes(StandardCharsets.UTF_8)), true, null);
    validator.xsdValidation(file);
    for (int i = 0; i < 300; i++) {
      while (Display.getCurrent().readAndDispatch()) ;
      Thread.sleep(10);
    }
    String problemMarker = "org.eclipse.core.resources.problemmarker";
    IMarker[] markers = file.findMarkers(problemMarker, true, IResource.DEPTH_ZERO);
```

Still not clear why it will end up having two, identical markers.

**Comment by chanseokoh** [comment]
Interestingly, commenting out the validator and even not calling `validator.xsdValidation(file)` entirely still gives us two markers.

```java
    //XmlValidator validator = new XmlValidator();
    //validator.setHelper(new AppEngineWebXmlValidator());
    IProject project = appEngineStandardProjectCreator.getProject();
    ResourceUtils.createFolders(project.getFolder("src/main/webapp/WEB-INF"), null);
    IFile file = project.getFile("src/main/webapp/WEB-INF/appengine-web.xml");
    file.create(new ByteArrayInputStream(xml.getBytes(StandardCharsets.UTF_8)), true, null);
    //validator.xsdValidation(file);
    for (int i = 0; i < 300; i++) {
      while (Display.getCurrent().readAndDispatch()) ;
      Thread.sleep(10);
    }
```

**Comment by chanseokoh** [comment]
Looks like we don't have to create the marker ourselves and even call `xsdValidation()` in `XmlValidator.validate()`.
