### ISSUE TITLE
BlockingDataflowPipelineRunner expected a valid 'gs://' path but was given 'gs://SET_YOUR_BUCKET_NAME_HERE/AND_STAGING_DIRECTORY'

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1814]
When attempting to run example pipeline

```
Exception in thread "main" java.lang.RuntimeException: Failed to construct instance from factory method BlockingDataflowPipelineRunner#fromOptions(interface com.google.cloud.dataflow.sdk.options.PipelineOptions)
	at com.google.cloud.dataflow.sdk.util.InstanceBuilder.buildFromMethod(InstanceBuilder.java:234)
	at com.google.cloud.dataflow.sdk.util.InstanceBuilder.build(InstanceBuilder.java:163)
	at com.google.cloud.dataflow.sdk.runners.PipelineRunner.fromOptions(PipelineRunner.java:58)
	at com.google.cloud.dataflow.sdk.Pipeline.create(Pipeline.java:135)
	at com.google.cloud.dataflow.examples.MinimalWordCount.main(MinimalWordCount.java:72)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.google.cloud.dataflow.sdk.util.InstanceBuilder.buildFromMethod(InstanceBuilder.java:223)
	... 4 more
Caused by: java.lang.IllegalArgumentException: BlockingDataflowPipelineRunner expected a valid 'gs://' path but was given 'gs://SET_YOUR_BUCKET_NAME_HERE/AND_STAGING_DIRECTORY'
	at com.google.cloud.dataflow.sdk.util.DataflowPathValidator.getGcsPath(DataflowPathValidator.java:93)
	at com.google.cloud.dataflow.sdk.util.DataflowPathValidator.verifyPath(DataflowPathValidator.java:69)
	at com.google.cloud.dataflow.sdk.util.DataflowPathValidator.validateOutputFilePrefixSupported(DataflowPathValidator.java:62)
	at com.google.cloud.dataflow.sdk.runners.DataflowPipelineRunner.fromOptions(DataflowPipelineRunner.java:274)
	at com.google.cloud.dataflow.sdk.runners.BlockingDataflowPipelineRunner.fromOptions(BlockingDataflowPipelineRunner.java:82)
	... 9 more
Caused by: java.lang.IllegalArgumentException: GCS bucket names must contain only lowercase letters, numbers, dashes (-), underscores (_), and dots (.). Bucket names must start and end with a number or letter. See https://developers.google.com/storage/docs/bucketnaming for more details.  Bucket name: SET_YOUR_BUCKET_NAME_HERE
	at com.google.cloud.dataflow.sdk.repackaged.com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
	at com.google.cloud.dataflow.sdk.util.gcsfs.GcsPath.<init>(GcsPath.java:207)
	at com.google.cloud.dataflow.sdk.util.gcsfs.GcsPath.fromUri(GcsPath.java:121)
	at com.google.cloud.dataflow.sdk.util.DataflowPathValidator.getGcsPath(DataflowPathValidator.java:91)
	... 13 more
```

**Comment by elharo** [comment]
Staging location appears to be set

![image](https://cloud.githubusercontent.com/assets/1005544/25093381/0e80e25e-2360-11e7-82ee-48d953e11053.png)

**Comment by elharo** [comment]
FYI I've reporduced this in the old dataflow plugin 1.2.0. It's not a recent change.

**Comment by tgroh** [comment]
The exception suggests it's because `UniqueName` isn't a valid GCS location (`uniquename` or `unique_name` would be)

**Comment by elharo** [comment]
relevant field to validate is `RunOptionsDefaultComponent.stagingLocationInput`

**Comment by elharo** [comment]
```
  private class EnableCreateButton implements ModifyListener {

    @Override
    public void modifyText(ModifyEvent event) {
      boolean enabled = !stagingLocationInput.getText().trim().isEmpty();
      createButton.setEnabled(enabled);
    }

  }
```

This needs to change so we check if the field is valid, not just empty. Also need to disable the finish button.

**Comment by elharo** [comment]
see
`com.google.cloud.tools.eclipse.ui.util.databinding.BucketNameValidator`

**Comment by elharo** [comment]
@tgroh this is still happening. The problem seems to be that the cloud storage saving locaiton set in the wizard doesn't make it's way into the project:

![dataflow1814](https://cloud.githubusercontent.com/assets/1005544/26457088/f492a09e-413c-11e7-9203-a7e259367219.png)

**Comment by elharo** [comment]
Looks like the example is not pulling the bucket and project from the project properties:

```
  public static void main(String[] args) {
    // Create a DataflowPipelineOptions object. This object lets us set various execution
    // options for our pipeline, such as the associated Cloud Platform project and the location
    // in Google Cloud Storage to stage files.
    DataflowPipelineOptions options = PipelineOptionsFactory.create()
      .as(DataflowPipelineOptions.class);
    options.setRunner(BlockingDataflowPipelineRunner.class);
    // CHANGE 1/3: Your project ID is required in order to run your pipeline on the Google Cloud.
    options.setProject("SET_YOUR_PROJECT_ID_HERE");
    // CHANGE 2/3: Your Google Cloud Storage path is required for staging local files.
    options.setStagingLocation("gs://SET_YOUR_BUCKET_NAME_HERE/AND_STAGING_DIRECTORY");
```

**Comment by elharo** [comment]
@tgroh The quickstart completely omits the choice of main class although this seems to be a mandatory step. I filed a P1 internal doc bug on this someone should take a look at. I think you're cc'd.

**Comment by elharo** [comment]
Using the non-minimal Wordcount example we get:

```
Caused by: java.lang.IllegalArgumentException: Missing required value: at least one of tempLocation or stagingLocation must be set.
	at com.google.cloud.dataflow.sdk.repackaged.com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
	at com.google.cloud.dataflow.sdk.runners.DataflowPipelineRunner.fromOptions(DataflowPipelineRunner.java:269)
	at com.google.cloud.dataflow.sdk.runners.BlockingDataflowPipelineRunner.fromOptions(BlockingDataflowPipelineRunner.java:82)
	... 9 more
```

The plugin doesn't have an obvious means of setting these parameters.

**Comment by elharo** [comment]
Also

```
INFO: Inferred default GCP project 'tutorialfu' from gcloud. If this is the incorrect project, please cancel this Pipeline and specify the command-line argument --project.
```

It's not reading the project from the properties.

**Comment by elharo** [comment]
We've now run this end-to-end. Opening separate bugs for individual problems discovered along the way.
