### ISSUE TITLE
NPE in LaunchHelper.findExistingServers()

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#1852]
http://stackoverflow.com/questions/43613696/google-app-engine-fails-to-launch-in-eclipse

```
java.lang.NullPointerException
    at com.google.cloud.tools.eclipse.appengine.localserver.launching.LaunchHelper.findExistingServers(LaunchHelper.java:110)
    at com.google.cloud.tools.eclipse.appengine.localserver.launching.LaunchHelper.launch(LaunchHelper.java:61)
    at com.google.cloud.tools.eclipse.appengine.localserver.launching.LocalAppEngineStandardLaunchShortcut.launch(LocalAppEngineStandardLaunchShortcut.java:44)
    at org.eclipse.debug.internal.ui.launchConfigurations.LaunchShortcutExtension.launch(LaunchShortcutExtension.java:431)
    at org.eclipse.debug.internal.ui.actions.LaunchShortcutAction.run(LaunchShortcutAction.java:74)
    at org.eclipse.debug.internal.ui.actions.LaunchShortcutAction.runWithEvent(LaunchShortcutAction.java:123)
    at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:595)
    at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:511)
    at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:420)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4362)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1113)
```

**Comment by briandealwis** [comment]
Sounds like the server's server-type or the server-type's id must be null?  [Line 110](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/master/plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/launching/LaunchHelper.java#L110):
```
      if (!LocalAppEngineServerDelegate.SERVER_TYPE_ID.equals(server.getServerType().getId())) {
```

**Comment by briandealwis** [comment]
[Greg replied](http://stackoverflow.com/questions/43613696/google-app-engine-fails-to-launch-in-eclipse#comment74285969_43615905):
> I had a server from the old Google Plugin for Eclipse hanging around. Removing this server does indeed fix the problem. Sorry, but I removed it before I saw your comment. Consequently, I am not able to provide you with the old servers.xml file.

**Comment by briandealwis** [comment]
Found an old `server.xml` that references a non-existent server.  The problem is `server.getServerType()` == null.

[serverxml.zip](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/files/958830/serverxml.zip)
