### ISSUE TITLE
should this error be severe? or an error?

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1885]
I edited my appengine-web.xml file so that it was malformed and saved (not uncommon during development). This stack trace showed up in the console. I'm not sure this should be a severe error. 

For comparison, a syntax error in a Java file does not log a similar exception message. 

Eclipse does put up a problem for this in the problems view. I suggest we leave it at that and not log here.

```
Apr 29, 2017 6:44:38 AM com.google.cloud.tools.eclipse.appengine.standard.java8.AppEngineWebBuilder checkRuntimeElement
SEVERE: P/fred: error updating facets
java.io.IOException: Cannot parse appengine-web.xml
	at com.google.cloud.tools.appengine.AppEngineDescriptor.parse(AppEngineDescriptor.java:55)
	at com.google.cloud.tools.eclipse.appengine.standard.java8.AppEngineWebBuilder.checkRuntimeElement(AppEngineWebBuilder.java:82)
	at com.google.cloud.tools.eclipse.appengine.standard.java8.AppEngineWebBuilder.build(AppEngineWebBuilder.java:71)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:205)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:245)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:300)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:303)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:359)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:382)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: org.xml.sax.SAXParseException; lineNumber: 5; columnNumber: 19; The element type "runtime" must be terminated by the matching end-tag "</runtime>".
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:347)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
	at com.google.cloud.tools.appengine.AppEngineDescriptor.parse(AppEngineDescriptor.java:53)
	... 14 more
```

**Comment by elharo** [comment]
Blocked on next release of appengine-plugins-core
