### ISSUE TITLE
Flaky test: StandardStagingDelegateTest.testStage()

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#1891]
Saw this on Kokoro and Travis today.

The test basically shells out to Cloud SDK App Engine standard staging (via `appengine-tools-api.jar`) and checks if Cloud SDK successfully created necessary files.

I'm not sure if the first error that fails to install the App Engine runtime is related.

```
May 01, 2017 1:23:11 PM com.google.cloud.tools.eclipse.appengine.facets.AppEngineStandardFacet createAppEngineServerRuntime
WARNING: RuntimeTypes: RuntimeType[org.eclipse.jst.server.core.runtimeType, J2EE Runtime Library]

!ENTRY org.eclipse.core.jobs 4 2 2017-05-01 13:23:11.916
!MESSAGE An internal error occurred during: "Install App Engine runtimes in "test0.9810407428657909"".
!STACK 0
java.lang.NullPointerException: Could not find App Engine Standard runtime type
	at com.google.cloud.tools.eclipse.appengine.facets.AppEngineStandardFacet.createAppEngineServerRuntime(AppEngineStandardFacet.java:256)
	at com.google.cloud.tools.eclipse.appengine.facets.AppEngineStandardFacet.createAppEngineFacetRuntime(AppEngineStandardFacet.java:268)
	at com.google.cloud.tools.eclipse.appengine.facets.AppEngineStandardFacet.installAllAppEngineRuntimes(AppEngineStandardFacet.java:237)
	at com.google.cloud.tools.eclipse.appengine.facets.StandardFacetInstallDelegate$AppEngineRuntimeInstallJob.run(StandardFacetInstallDelegate.java:115)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
May 01, 2017 1:23:14 PM com.google.cloud.tools.appengine.cloudsdk.CloudSdk logCommand
INFO: submitting command: C:\Program Files\Java\jdk1.8.0_121\jre\bin\java.exe -cp t:\google\google-cloud-sdk\platform\google_appengine\google\appengine\tools\java\lib\appengine-tools-api.jar com.google.appengine.tools.admin.AppCfg --disable_update_check --enable_jar_splitting stage T:\src\github\google-cloud-eclipse\plugins\com.google.cloud.tools.eclipse.appengine.deploy.test\target\work\data\test0.9810407428657909\safe-work-directory T:\src\github\google-cloud-eclipse\plugins\com.google.cloud.tools.eclipse.appengine.deploy.test\target\work\data\test0.9810407428657909\staging-result
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 24.809 sec <<< FAILURE! - in com.google.cloud.tools.eclipse.appengine.deploy.standard.StandardStagingDelegateTest
testStage(com.google.cloud.tools.eclipse.appengine.deploy.standard.StandardStagingDelegateTest)  Time elapsed: 17.127 sec  <<< FAILURE!
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.google.cloud.tools.eclipse.appengine.deploy.standard.StandardStagingDelegateTest.testStage(StandardStagingDelegateTest.java:60)
```

**Comment by chanseokoh** [comment]
Dup of #1848.
