### ISSUE TITLE
requested api_version (1.0) is not supported by the java8 runtime in this release of the SDK. The supported api_versions are ['1'].

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1918]
This is with a new hello world project + App Engine API library run from the command line by dev_appserver.py

```
$ /opt/google-cloud-sdk/platform/google_appengine/dev_appserver.py src/main/webapp
ERROR    2017-05-06 12:43:08,895 sdk_update_checker.py:201] The requested api_version (1.0) is not supported by the java8 runtime in this release of the SDK. The supported api_versions are ['1'].
```

Not immediately clear if bug is in dev_appserver.py or how we set up the project.

**Comment by elharo** [comment]
May be because I ran it from a funny ,location:

```
MultiException[javax.servlet.UnavailableException: Class loading error for holder HelloAppEngine@53f22331==HelloAppEngine,jsp=null,order=-1,inst=false, javax.servlet.UnavailableException: Class loading error for holder HelloAppEngine@53f22331==HelloAppEngine,jsp=null,order=-1,inst=false]
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:863)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:349)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1404)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1366)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:778)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:262)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:520)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	at org.eclipse.jetty.server.Server.start(Server.java:422)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:389)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at com.google.appengine.tools.development.jetty9.JettyContainerService.startContainer(JettyContainerService.java:345)
	at com.google.appengine.tools.development.AbstractContainerService.startup(AbstractContainerService.java:284)
	at com.google.appengine.tools.development.AutomaticInstanceHolder.startUp(AutomaticInstanceHolder.java:26)
	at com.google.appengine.tools.development.AbstractModule.startup(AbstractModule.java:87)
	at com.google.appengine.tools.development.Modules.startup(Modules.java:105)
	at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl.doStart(DevAppServer2Impl.java:250)
	at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl.access$000(DevAppServer2Impl.java:52)
	at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl$1.run(DevAppServer2Impl.java:216)
	at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl$1.run(DevAppServer2Impl.java:214)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl.start(DevAppServer2Impl.java:214)
	at com.google.appengine.tools.development.devappserver2.StandaloneInstance$StartAction.apply(StandaloneInstance.java:131)
	at com.google.appengine.tools.development.devappserver2.StandaloneInstance$StartAction.apply(StandaloneInstance.java:83)
	at com.google.appengine.tools.util.Parser$ParseResult.applyArgs(Parser.java:47)
	at com.google.appengine.tools.development.devappserver2.StandaloneInstance.run(StandaloneInstance.java:67)
	at com.google.appengine.tools.development.devappserver2.StandaloneInstance.main(StandaloneInstance.java:45)
Suppressed: 
	|javax.servlet.UnavailableException: Class loading error for holder HelloAppEngine@53f22331==HelloAppEngine,jsp=null,order=-1,inst=false
	|	at org.eclipse.jetty.servlet.BaseHolder.doStart(BaseHolder.java:102)
	|	at org.eclipse.jetty.servlet.ServletHolder.doStart(ServletHolder.java:363)
	|	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	|	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:909)
	|	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:349)
	|	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1404)
	|	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1366)
	|	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:778)
	|	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:262)
	|	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:520)
	|	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	|	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	|	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
	|	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	|	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	|	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	|	at org.eclipse.jetty.server.Server.start(Server.java:422)
	|	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
	|	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	|	at org.eclipse.jetty.server.Server.doStart(Server.java:389)
	|	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	|	at com.google.appengine.tools.development.jetty9.JettyContainerService.startContainer(JettyContainerService.java:345)
	|	at com.google.appengine.tools.development.AbstractContainerService.startup(AbstractContainerService.java:284)
	|	at com.google.appengine.tools.development.AutomaticInstanceHolder.startUp(AutomaticInstanceHolder.java:26)
	|	at com.google.appengine.tools.development.AbstractModule.startup(AbstractModule.java:87)
	|	at com.google.appengine.tools.development.Modules.startup(Modules.java:105)
	|	at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl.doStart(DevAppServer2Impl.java:250)
	|	at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl.access$000(DevAppServer2Impl.java:52)
	|	at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl$1.run(DevAppServer2Impl.java:216)
	|	at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl$1.run(DevAppServer2Impl.java:214)
	|	at java.security.AccessController.doPrivileged(Native Method)
	|	at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl.start(DevAppServer2Impl.java:214)
	|	at com.google.appengine.tools.development.devappserver2.StandaloneInstance$StartAction.apply(StandaloneInstance.java:131)
	|	at com.google.appengine.tools.development.devappserver2.StandaloneInstance$StartAction.apply(StandaloneInstance.java:83)
	|	at com.google.appengine.tools.util.Parser$ParseResult.applyArgs(Parser.java:47)
	|	at com.google.appengine.tools.development.devappserver2.StandaloneInstance.run(StandaloneInstance.java:67)
	|	at com.google.appengine.tools.development.devappserver2.StandaloneInstance.main(StandaloneInstance.java:45)
Caused by: 
javax.servlet.UnavailableException: Class loading error for holder HelloAppEngine@53f22331==HelloAppEngine,jsp=null,order=-1,inst=false
	at org.eclipse.jetty.servlet.BaseHolder.doStart(BaseHolder.java:102)
	at org.eclipse.jetty.servlet.ServletHolder.doStart(ServletHolder.java:363)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:891)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:349)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1404)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1366)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:778)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:262)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:520)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	at org.eclipse.jetty.server.Server.start(Server.java:422)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:389)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at com.google.appengine.tools.development.jetty9.JettyContainerService.startContainer(JettyContainerService.java:345)
	at com.google.appengine.tools.development.AbstractContainerService.startup(AbstractContainerService.java:284)
	at com.google.appengine.tools.development.AutomaticInstanceHolder.startUp(AutomaticInstanceHolder.java:26)
	at com.google.appengine.tools.development.AbstractModule.startup(AbstractModule.java:87)
	at com.google.appengine.tools.development.Modules.startup(Modules.java:105)
	at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl.doStart(DevAppServer2Impl.java:250)
	at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl.access$000(DevAppServer2Impl.java:52)
	at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl$1.run(DevAppServer2Impl.java:216)
	at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl$1.run(DevAppServer2Impl.java:214)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl.start(DevAppServer2Impl.java:214)
	at com.google.appengine.tools.development.devappserver2.StandaloneInstance$StartAction.apply(StandaloneInstance.java:131)
	at com.google.appengine.tools.development.devappserver2.StandaloneInstance$StartAction.apply(StandaloneInstance.java:83)
	at com.google.appengine.tools.util.Parser$ParseResult.applyArgs(Parser.java:47)
	at com.google.appengine.tools.development.devappserver2.StandaloneInstance.run(StandaloneInstance.java:67)
	at com.google.appengine.tools.development.devappserver2.StandaloneInstance.main(StandaloneInstance.java:45)
2017-05-06 12:47:34.906:INFO:oejs.AbstractConnector:main: Started NetworkTrafficSelectChannelConnector@524d6d96{HTTP/1.1,[http/1.1]}{localhost:49582}
2017-05-06 12:47:34.912:INFO:oejs.Server:main: Started @1218ms
May 06, 2017 12:47:34 PM com.google.appengine.tools.development.AbstractModule startup
INFO: Module instance default is running at http://localhost:49582/
May 06, 2017 12:47:34 PM com.google.appengine.tools.development.AbstractModule startup
INFO: The admin console is running at http://localhost:49582/_ah/admin
May 06, 2017 12:47:34 PM com.google.appengine.tools.development.devappserver2.DevAppServer2Impl doStart
```
