### ISSUE TITLE
Classpath Dependency Validator warning - fix or suppress?

### ISSUE THREAD

**Issue by Rob46** [GoogleCloudPlatform/google-cloud-eclipse#2015]
- Cloud Tools for Eclipse Version: 1.1.0.201705161607
- OS: Windows 10 10.0
- Java Version: 1.8.0_121

Since upgrading to CT4E I'm getting a set of warnings as below. 
Do I need to change anything? 
If not, how do I suppress these warnings?

Classpath Dependency Validator Message:
Description	Resource	Path	Location	Type
Classpath entry com.google.gdt.eclipse.managedapis.MANAGED_API_CONTAINER/compute-v1r147lv1.21.0 will not be exported or published. Runtime ClassNotFoundExceptions may result.  	ParaSQL		P/ParaSQL	Classpath Dependency Validator Message
Classpath entry com.google.gdt.eclipse.managedapis.MANAGED_API_CONTAINER/sqladmin-v1beta4r39lv1.21.0 will not be exported or published. Runtime ClassNotFoundExceptions may result.  	ParaSQL		P/ParaSQL	Classpath Dependency Validator Message
Classpath entry com.google.gdt.eclipse.managedapis.MANAGED_API_CONTAINER/storage-v1r105lv1.21.0 will not be exported or published. Runtime ClassNotFoundExceptions may result.  	ParaSQL		P/ParaSQL	Classpath Dependency Validator Message

**Comment by elharo** [comment]
Are you using those APIs in your project?

**Comment by Rob46** [comment]
Yes, we use the compute engine api, the sqladmin api and the storage api.

**Comment by Rob46** [comment]
With the old plugin, they were shown and every so often you would right click on them to update them.

**Comment by elharo** [comment]
In that case, it sounds like those warnings are relevant; and you'll need to add the relevant jars to your project. I think those versions are a little out of date so you should probably grab the new ones while you're at it.

**Comment by Rob46** [comment]
Are you talking manually download from somewhere and add, or is the a way to add that as a Google API and have it prompt to keep them up to date?

**Comment by Rob46** [comment]
I have deleted those three entries that were generating warnings, but now I have errors.
I was able to Add Library ... for the Google Cloud Storage library (and its dependencies). That seems to work fine. But how do I add the libraries for Compute and SQLAdmin to fix the following failed imports? The plugin had a Add Google API... option that I don't see.

import com.google.api.services.sqladmin.SQLAdmin;
import com.google.api.services.compute.Compute;

**Comment by elharo** [comment]
ATM you'll need to add those libraries the same way you'd add any other external dependency. I.e. download the relevant jars and add them to your classpath.

**Comment by Rob46** [comment]
Does ATM mean "at the moment" as in this will change and these libraries will be added like the Cloud Storage API is?

I am still stuck adding the Compute API manually. I've added the jar and its dependencies to WEB-INF/lib, I've added the main jar as a library, and I've added the entire WEB-INF/lib folder as well. When I deploy and try and run the app, any call to the Compute gets a 500 error.

From app engine log:

Error for /start
java.lang.NoSuchMethodError: com.google.api.client.googleapis.auth.oauth2.GoogleCredential.getApplicationDefault()Lcom/google/api/client/googleapis/auth/oauth2/GoogleCredential;
	at com.parasql.util.ComputeEngineManager.<init>(ComputeEngineManager.java:42)
	at com.parasql.StartPageServlet.doInstanceReset(StartPageServlet.java:634)
	at com.parasql.StartPageServlet.doGet(StartPageServlet.java:139)
	at com.parasql.StartPageServlet.doPost(StartPageServlet.java:159)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:37)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:48)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:257)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
	at com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:76)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:145)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchServletRequest(JavaRuntime.java:644)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchRequest(JavaRuntime.java:604)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:574)
	at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:453)
	at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:460)
	at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:293)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:319)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:311)
	at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:457)
	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:238)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Rob46** [comment]
Please note everything was working great with the plugin. Zero issues.

**Comment by chanseokoh** [comment]
The error says that `com.parasql.util.ComputeEngineManager` at line 42 tries to call a method `GoogleCredential.getApplicationDefault()`, which doesn't exist.

This seems to imply incompatible library versions being used (or got loaded somehow by other libraries) between ParaSQL and `google-api-client`. (For example, https://stackoverflow.com/questions/43171896/googlecredentialas-getapplicationdefault-nosuchmethoderror.) I wonder upgrading both APIs to the latest may work. Does it also happen running locally?

**Comment by Rob46** [comment]
Have not tried when running locally as have issues I don't want to cross on that.

I'll try only keeping what looks like the latest libraries, and if that doesn't work I'll have to revert to the plugin which works perfectly. ugh

**Comment by Rob46** [comment]
I consider this closed for now.

The root problem is no documentation highlighting that under the plugin system tons of stuff is stored in WEB-INF/lib (basically all the google stuff) and so that got very, very polluted over a few year period (since 2013). Now all the CT4E stuff is managed externally to web-inf/lib so it can be cleaned out down to the core. So far in testing, everything works.

**Comment by chanseokoh** [comment]
Thanks for the feedback, @Rob46! I'll close this.

**Comment by chanseokoh** [comment]
FYI, we fixed #2018 and #2028, which will roll out in the next release of CT4E.

- #2018 removes the dangling Google Plugin for Eclipse (GPE) Managed API classpath container you saw earlier.
- #2028 let the converted project automatically recognized any JARs remaining in `WEB-INF/lib`. (However, I don't think putting JARs under `WEB-INF/lib` in a source repo is a good idea, and I think your decision to migrate the JARs out of `WEB-INF/lib` is much better.)

**Comment by Rob46** [comment]
RE "lets the converted project automatically recognized any JARs remaining in WEB-INF/lib"

That is a good idea, and that is a bad idea.  my two cents:

If the WEB-INF/lib is clean, I think its a great idea.... I could now have a single entry like that on mine, as there are only 4 jars remaining - sqladmin, compute, a special mariadb jdbc driver, and gson. So litterally two if sqladmin and compute become a managed api like storage is already (if that is the right word).

It is a bad idea if your tool doesn't automatically clean out all the old google stuff, especially stuff that may have been long ago forgotten... otherwise you will run into the problem of multiple versions of the same lib being on the class path.... i don't even know if that's allowed or how its resolved. On a new clean project, its a very good idea, on a migrated project, put a big highlighted note in the docs that you should manually clean it out. "if you didn't put it there, you can delete it" and auto remove all the known google related stuff. Still dodgy for migration I think.... just bring across their explicit lib includes, auto clean the google stuff out, and suggest that everything that doesn't have an explicit include or is a of one can be removed (i think that is a correct statement?).
