### ISSUE TITLE
Another deadlock by CreateAppEngineWtpProject.enableMavenNature()

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#2025]
The same location as in #2009, which I fixed just 2 days ago. The fix for #2009 certainly removed a potential deadlock by the WTP dependency graph update job, as can be seen below (the new dump doesn't have this job), but I see there is another workspace job that's causing a deadlock:

```
+-------------------------------------------------------------------------------
| STACK DUMP @ 8.000 min: testMavenNatureEnabled(com.google.cloud.tools.eclipse.appengine.newproject.flex.CreateAppEngineFlexWtpProjectTest)
|
| 
| Eclipse Locks:
|  :: 
|  R/,
|  Worker-4 :  1,
|  Worker-5 :  -1,
| -------
| 
| "main" [1] TIMED_WAITING on org.eclipse.core.internal.jobs.Semaphore@7f89c445
|     at java.lang.Object.wait(Native Method)
|     - waiting on org.eclipse.core.internal.jobs.Semaphore@7f89c445
|     at org.eclipse.core.internal.jobs.Semaphore.acquire(Semaphore.java:39)
|     at org.eclipse.core.internal.jobs.OrderedLock.doAcquire(OrderedLock.java:170)
|     at org.eclipse.core.internal.jobs.OrderedLock.acquire(OrderedLock.java:106)
|     at org.eclipse.core.internal.jobs.OrderedLock.acquire(OrderedLock.java:82)
|     at org.eclipse.wst.common.componentcore.internal.StructureEdit.getComponentModelRoot(StructureEdit.java:467)
|     at org.eclipse.wst.common.componentcore.internal.StructureEdit.getWorkbenchModules(StructureEdit.java:506)
|     at org.eclipse.wst.common.componentcore.internal.StructureEdit.getComponent(StructureEdit.java:949)
|     at org.eclipse.wst.common.componentcore.internal.resources.VirtualComponent.createResource(VirtualComponent.java:124)
|     at org.eclipse.wst.common.componentcore.internal.resources.VirtualComponent.initializeResource(VirtualComponent.java:113)
|     at org.eclipse.wst.common.componentcore.internal.resources.VirtualComponent.<init>(VirtualComponent.java:148)
|     at org.eclipse.jst.j2ee.componentcore.J2EEModuleVirtualComponent.<init>(J2EEModuleVirtualComponent.java:92)
|     at org.eclipse.jst.j2ee.componentcore.J2EEModuleVirtualComponent.createComponent(J2EEModuleVirtualComponent.java:96)
|     at org.eclipse.wst.common.componentcore.internal.util.ComponentImplManager.createComponent(ComponentImplManager.java:230)
|     - locked org.eclipse.wst.common.componentcore.internal.util.ComponentImplManager@5606a4ef
|     at org.eclipse.wst.common.componentcore.ComponentCore.createComponent(ComponentCore.java:84)
|     at org.eclipse.m2e.wtp.WebProjectConfiguratorDelegate.configure(WebProjectConfiguratorDelegate.java:163)
|     at org.eclipse.m2e.wtp.AbstractProjectConfiguratorDelegate.configureProject(AbstractProjectConfiguratorDelegate.java:94)
|     at org.eclipse.m2e.wtp.WTPProjectConfigurator.configure(WTPProjectConfigurator.java:68)
|     at org.eclipse.m2e.core.project.configurator.AbstractLifecycleMapping.configure(AbstractLifecycleMapping.java:120)
|     at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$3.call(ProjectConfigurationManager.java:508)
|     at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$3.call(ProjectConfigurationManager.java:1)
|     at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
|     at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
|     at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration(ProjectConfigurationManager.java:501)
|     at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.configureNewMavenProjects(ProjectConfigurationManager.java:288)
|     at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$4.run(ProjectConfigurationManager.java:528)
|     at org.eclipse.m2e.core.internal.embedder.AbstractRunnable.call(AbstractRunnable.java:26)
|     at org.eclipse.m2e.core.internal.embedder.AbstractRunnable.call(AbstractRunnable.java:1)
|     at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
|     at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
|     at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
|     at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1355)
|     at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.enableMavenNature(ProjectConfigurationManager.java:525)
|     at com.google.cloud.tools.eclipse.appengine.newproject.CreateAppEngineWtpProject.enableMavenNature(CreateAppEngineWtpProject.java:172)
|     at com.google.cloud.tools.eclipse.appengine.newproject.CreateAppEngineWtpProject.execute(CreateAppEngineWtpProject.java:121)
|     at com.google.cloud.tools.eclipse.appengine.newproject.flex.CreateAppEngineFlexWtpProjectTest.testMavenNatureEnabled(CreateAppEngineFlexWtpProjectTest.java:156)
|     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
|     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
|     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
|     at java.lang.reflect.Method.invoke(Method.java:483)
|     at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
|     at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
|     at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
|     at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
|     at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
|     at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
|     at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
|     at com.google.cloud.tools.eclipse.test.util.ThreadDumpingWatchdog$1.evaluate(ThreadDumpingWatchdog.java:69)
|     at org.junit.rules.RunRules.evaluate(RunRules.java:20)
|     at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
|     at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
|     at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
|     at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
|     at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
|     at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
|     at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
|     at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
|     at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
|     at org.mockito.internal.runners.JUnit45AndHigherRunnerImpl.run(JUnit45AndHigherRunnerImpl.java:37)
|     at org.mockito.runners.MockitoJUnitRunner.run(MockitoJUnitRunner.java:62)
|     at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
|     at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
|     at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
|     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
|     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
|     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
|     at java.lang.reflect.Method.invoke(Method.java:483)
|     at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
|     at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:156)
|     at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:82)
|     at org.eclipse.tycho.surefire.osgibooter.OsgiSurefireBooter.run(OsgiSurefireBooter.java:95)
|     at org.eclipse.tycho.surefire.osgibooter.AbstractUITestApplication$1.run(AbstractUITestApplication.java:35)
|     at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:37)
|     at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
|     - locked org.eclipse.swt.widgets.RunnableLock@4731c2a5
|     at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4468)
|     at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4081)
|     at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1133)
|     at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
|     at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
|     at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
|     at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:684)
|     at org.eclipse.ui.internal.Workbench$$Lambda$18/2030098711.run(Unknown Source)
|     at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
|     at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:598)
|     at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
|     at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
|     at org.eclipse.tycho.surefire.osgibooter.UITestApplication.runApplication(UITestApplication.java:31)
|     at org.eclipse.tycho.surefire.osgibooter.AbstractUITestApplication.run(AbstractUITestApplication.java:120)
|     at org.eclipse.tycho.surefire.osgibooter.UITestApplication.start(UITestApplication.java:37)
|     at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
|     at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
|     at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
|     at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
|     at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
|     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
|     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
|     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
|     at java.lang.reflect.Method.invoke(Method.java:483)
|     at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
|     at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
|     at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
|     at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
| 
| "Worker-JM" [61] TIMED_WAITING on java.util.ArrayList@62e40360
|     at java.lang.Object.wait(Native Method)
|     - waiting on java.util.ArrayList@62e40360
|     at org.eclipse.core.internal.jobs.InternalWorker.run(InternalWorker.java:59)
| 
| "EventAdmin Async Event Dispatcher Thread" [70] WAITING on org.eclipse.osgi.framework.eventmgr.EventManager$EventThread@3303da01
|     at java.lang.Object.wait(Native Method)
|     - waiting on org.eclipse.osgi.framework.eventmgr.EventManager$EventThread@3303da01
|     at java.lang.Object.wait(Object.java:502)
|     at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.getNextEvent(EventManager.java:400)
|     at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:336)
| 
| "WorkbenchTestable" [71] WAITING on org.eclipse.swt.widgets.RunnableLock@4731c2a5 owned by 'main [id:1]
|     at java.lang.Object.wait(Native Method)
|     - waiting on org.eclipse.swt.widgets.RunnableLock@4731c2a5
|     at java.lang.Object.wait(Object.java:502)
|     at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:250)
|     at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:144)
|     at org.eclipse.swt.widgets.Display.syncExec(Display.java:5410)
|     at org.eclipse.e4.ui.internal.workbench.swt.E4Testable.runTest(E4Testable.java:114)
|     at org.eclipse.tycho.surefire.osgibooter.AbstractUITestApplication.runTests(AbstractUITestApplication.java:32)
|     at org.eclipse.e4.ui.internal.workbench.swt.E4Testable.lambda$0(E4Testable.java:73)
|     at org.eclipse.e4.ui.internal.workbench.swt.E4Testable$$Lambda$104/297484187.run(Unknown Source)
|     at java.lang.Thread.run(Thread.java:745)
| 
| "Java indexing" [74] WAITING on org.eclipse.jdt.internal.core.search.indexing.IndexManager@47c96ab2
|     at java.lang.Object.wait(Native Method)
|     - waiting on org.eclipse.jdt.internal.core.search.indexing.IndexManager@47c96ab2
|     at java.lang.Object.wait(Object.java:502)
|     at org.eclipse.jdt.internal.core.search.processing.JobManager.run(JobManager.java:373)
|     at java.lang.Thread.run(Thread.java:745)
| 
| "JavaScript indexing" [90] WAITING on org.eclipse.wst.jsdt.internal.core.search.indexing.IndexManager@43f6f614
|     at java.lang.Object.wait(Native Method)
|     - waiting on org.eclipse.wst.jsdt.internal.core.search.indexing.IndexManager@43f6f614
|     at java.lang.Object.wait(Object.java:502)
|     at org.eclipse.wst.jsdt.internal.core.search.processing.JobManager.run(JobManager.java:370)
|     at java.lang.Thread.run(Thread.java:745)
| 
| "Worker-4" [91] BLOCKED on org.eclipse.wst.common.componentcore.internal.util.ComponentImplManager@5606a4ef owned by 'main [id:1]
|     at org.eclipse.wst.common.componentcore.internal.util.ComponentImplManager.createComponent(ComponentImplManager.java)
|     - blocked on org.eclipse.wst.common.componentcore.internal.util.ComponentImplManager@5606a4ef
|     at org.eclipse.wst.common.componentcore.internal.util.ComponentImplManager.createComponent(ComponentImplManager.java:212)
|     at org.eclipse.wst.common.componentcore.ComponentCore.createComponent(ComponentCore.java:64)
|     at org.eclipse.jst.j2ee.refactor.listeners.J2EEElementChangedListener.getNonJavaFolderMappings(J2EEElementChangedListener.java:243)
|     at org.eclipse.jst.j2ee.refactor.listeners.J2EEElementChangedListener.access$1(J2EEElementChangedListener.java:241)
|     at org.eclipse.jst.j2ee.refactor.listeners.J2EEElementChangedListener$1.runInWorkspace(J2EEElementChangedListener.java:118)
|     at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
|     at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
| 
| "Worker-5" [92] WAITING on java.lang.Object@c90b121
|     at java.lang.Object.wait(Native Method)
|     - waiting on java.lang.Object@c90b121
|     at java.lang.Object.wait(Object.java:502)
|     at org.eclipse.core.internal.jobs.ThreadJob.waitForRun(ThreadJob.java:304)
|     at org.eclipse.core.internal.jobs.ThreadJob.joinRun(ThreadJob.java:206)
|     at org.eclipse.core.internal.jobs.ImplicitJobs.begin(ImplicitJobs.java:92)
|     at org.eclipse.core.internal.jobs.JobManager.beginRule(JobManager.java:324)
|     at org.eclipse.core.internal.utils.StringPoolJob.run(StringPoolJob.java:98)
|     at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
| 
| "Worker-10" [141] TIMED_WAITING
|     at java.lang.Thread.sleep(Native Method)
|     at org.eclipse.ui.internal.decorators.DecorationScheduler$1.run(DecorationScheduler.java:289)
|     at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
| 
| "Thread Dumping Watchdog" [167] RUNNABLE
|     at sun.management.ThreadImpl.dumpThreads0(Native Method)
|     at sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:446)
|     at com.google.cloud.tools.eclipse.test.util.ThreadDumpingWatchdog.run(ThreadDumpingWatchdog.java:94)
|     at java.util.TimerThread.mainLoop(Timer.java:555)
|     at java.util.TimerThread.run(Timer.java:505)
| 
| Ignored threads:
|   "Reference Handler" [2] WAITING on java.lang.ref.Reference$Lock@167bc7da
|   "Finalizer" [3] WAITING on java.lang.ref.ReferenceQueue$Lock@208eb5db
|   "Signal Dispatcher" [4] RUNNABLE
|   "Active Thread: Equinox Container: 94da0afa-4026-4d17-9ec3-021ffd9baf37" [25] TIMED_WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@3b2cdeaf
|   "Framework Event Dispatcher: org.eclipse.osgi.internal.framework.EquinoxEventPublisher@1d4fb213" [27] WAITING on org.eclipse.osgi.framework.eventmgr.EventManager$EventThread@34d5ada
|   "Start Level: Equinox Container: 94da0afa-4026-4d17-9ec3-021ffd9baf37" [28] WAITING on org.eclipse.osgi.framework.eventmgr.EventManager$EventThread@66aa1d25
|   "Bundle File Closer" [29] WAITING on org.eclipse.osgi.framework.eventmgr.EventManager$EventThread@2417f5c4
|   "Refresh Thread: Equinox Container: 94da0afa-4026-4d17-9ec3-021ffd9baf37" [30] WAITING on org.eclipse.osgi.framework.eventmgr.EventManager$EventThread@6f7d5c1
|   "SCR Component Actor" [60] WAITING on java.util.LinkedList@2b09c173
|   "EMF Reference Cleaner" [67] WAITING on java.lang.ref.ReferenceQueue$Lock@3f13ba29
|   "Timer-0" [72] TIMED_WAITING on java.util.TaskQueue@2cbfc2f
|   "Worker-8" [96] TIMED_WAITING on org.eclipse.core.internal.jobs.WorkerPool@4d3101c2
| ELAPSED TIME: 18.06 ms
+-------------------------------------------------------------------------------
```

I think the job is about `org.eclipse.jst.j2ee.refactor.listeners.J2EEElementChangedListener`, as in the "Worker-4" above. In fact, the previous deadlock issue #2009 did have this job causing the deadlock (while the WTP graph job was also waiting to be run).

I think this is the first time we saw this job causing a deadlock. @briandealwis can we do a similar thing to defer this job temporarily?

**Comment by chanseokoh** [comment]
This occasionally fails builds. I've seen this twice on the Oxygen builds. Not sure if this happens only on Oxygen.

**Comment by briandealwis** [comment]
Oh no, there's another path that triggers this issue!? 😱

What platform are you seeing this on?  Oxygen, I hope?

A fix for the [`DependencyGraph` issue](https://bugs.eclipse.org/511793) was committed for Oxygen M7.  It looks like we're building against M5.

**Comment by chanseokoh** [comment]
So far on Oxygen builds, but we will see.

Maybe a proper (?) solution would be to grab a workspace lock before calling `enableMavenNature()`.

**Comment by chanseokoh** [comment]
I believe we won't see this after #2033 (hopefully).

**Comment by chanseokoh** [comment]
This came back. I've seen this a couple of times today on Neon.

[v3-job-400899372-log.txt](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/files/2171075/v3-job-400899372-log.txt)
[v3-job-400899424-log.txt](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/files/2171074/v3-job-400899424-log.txt)

Note that, although the deadlock occurs at the exact same location, this is different from #2009, which we fixed by deferring the WTP dependency graph update job. In #2009, the `DependencyGraphImpl` class can be seen in the log. Here, it isn't.

**Comment by chanseokoh** [comment]
I've only seen this on Neon, and as I said in https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/2025#issuecomment-307242927, we may be able to ignore this once we drop support for Neon. (See #3201.)

**Comment by briandealwis** [comment]
Seen again on Neon.  What's odd is that the main thread is blocked on an `ILock`, but it's not reported in the locks (only shows the Workspace Root `R/`).

**Comment by diegomarquezp** [comment]
Closing as not planned.
