### ISSUE TITLE
Kokoro flaky build failure: testGetProject()

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#2048]
This is the first time I saw this failure, so I think this happens pretty rarely.

```
testGetProject(com.google.cloud.tools.eclipse.appengine.validation.XmlSourceValidatorTest)  Time elapsed: 0.01 sec  <<< ERROR!
org.eclipse.core.internal.resources.ResourceException: Problems encountered while deleting resources.
	at org.eclipse.core.internal.resources.Resource.delete(Resource.java:773)
	at org.eclipse.core.internal.resources.Resource.delete(Resource.java:730)
	at com.google.cloud.tools.eclipse.appengine.validation.XmlSourceValidatorTest.testGetProject(XmlSourceValidatorTest.java:197)
```

**Comment by chanseokoh** [comment]
Blocked by #2049.

**Comment by chanseokoh** [comment]
Interestingly, just saw another Kokoro failure with this.

```
testGetFile(com.google.cloud.tools.eclipse.appengine.validation.XmlSourceValidatorTest)  Time elapsed: 0.016 sec  <<< ERROR!
org.eclipse.core.internal.resources.ResourceException: Problems encountered while deleting resources.
	at org.eclipse.core.internal.resources.Resource.delete(Resource.java:773)
	at org.eclipse.core.internal.resources.Resource.delete(Resource.java:730)
	at com.google.cloud.tools.eclipse.appengine.validation.XmlSourceValidatorTest.testGetFile(XmlSourceValidatorTest.java:175)

testGetProject(com.google.cloud.tools.eclipse.appengine.validation.XmlSourceValidatorTest)  Time elapsed: 0.016 sec  <<< ERROR!
org.eclipse.core.internal.resources.ResourceException: Resource '/test0.7604933568050114/testdata.xml' already exists.
	at org.eclipse.core.internal.resources.Resource.checkDoesNotExist(Resource.java:314)
	at org.eclipse.core.internal.resources.Resource.checkDoesNotExist(Resource.java:301)
	at org.eclipse.core.internal.resources.File.create(File.java:107)
	at com.google.cloud.tools.eclipse.appengine.validation.XmlSourceValidatorTest.testGetProject(XmlSourceValidatorTest.java:184)
```
