### ISSUE TITLE
Unable to create project from archetype [com.google.appengine.archetypes:appengine-standard-archetype:LATEST]

### ISSUE THREAD

**Issue by andryfailli** [GoogleCloudPlatform/google-cloud-eclipse#2056]
Hi, I get this error when I try to create a new maven appengine std project from Cloud Tools for Eclipse (neon3)

- Cloud Tools for Eclipse Version: 1.1.0.201705161607
- OS: Windows 7 6.1
- Java Version: 1.8.0_131

Failed to create project: Unable to create project from archetype [com.google.appengine.archetypes:appengine-standard-archetype:LATEST]
Unable to create project from archetype [com.google.appengine.archetypes:appengine-standard-archetype:LATEST]
Archetype com.google.appengine.archetypes:appengine-standard-archetype:1.0.0 is not configured
	Property java8 is missing.
	Property CloudSDK_Tooling is missing.
	Property service is missing.

eclipse.buildId=4.6.3.M20170301-0400
java.version=1.8.0_131
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=it_IT
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product

	
org.eclipse.core.runtime.CoreException: Unable to create project from archetype [com.google.appengine.archetypes:appengine-standard-archetype:LATEST]
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.createArchetypeProjects0(ProjectConfigurationManager.java:817)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$5.call(ProjectConfigurationManager.java:760)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$5.call(ProjectConfigurationManager.java:1)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1355)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.createArchetypeProjects(ProjectConfigurationManager.java:758)
	at com.google.cloud.tools.eclipse.appengine.newproject.maven.CreateMavenBasedAppEngineStandardProject.execute(CreateMavenBasedAppEngineStandardProject.java:126)
	at org.eclipse.ui.actions.WorkspaceModifyOperation.lambda$0(WorkspaceModifyOperation.java:107)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2267)
	at org.eclipse.ui.actions.WorkspaceModifyOperation.run(WorkspaceModifyOperation.java:128)
	at com.google.cloud.tools.eclipse.appengine.newproject.maven.MavenArchetypeProjectWizard$1.run(MavenArchetypeProjectWizard.java:105)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
Caused by: org.apache.maven.archetype.exception.ArchetypeNotConfigured: Archetype com.google.appengine.archetypes:appengine-standard-archetype:1.0.0 is not configured
	Property java8 is missing.
	Property CloudSDK_Tooling is missing.
	Property service is missing.
	at org.apache.maven.archetype.generator.DefaultFilesetArchetypeGenerator.generateArchetype(DefaultFilesetArchetypeGenerator.java:129)
	at org.apache.maven.archetype.generator.DefaultArchetypeGenerator.processFileSetArchetype(DefaultArchetypeGenerator.java:129)
	at org.apache.maven.archetype.generator.DefaultArchetypeGenerator.generateArchetype(DefaultArchetypeGenerator.java:100)
	at org.apache.maven.archetype.generator.DefaultArchetypeGenerator.generateArchetype(DefaultArchetypeGenerator.java:143)
	at org.apache.maven.archetype.generator.DefaultArchetypeGenerator.generateArchetype(DefaultArchetypeGenerator.java:169)
	at org.apache.maven.archetype.DefaultArchetypeManager.generateProjectFromArchetype(DefaultArchetypeManager.java:73)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.createArchetypeProjects0(ProjectConfigurationManager.java:811)
	... 14 more

**Comment by chanseokoh** [comment]
Hi, can you take a look at #2055? Thanks.

**Comment by andryfailli** [comment]
thanks, updating plugin fixed the problem ;)
