### ISSUE TITLE
Tests frequently fail with java.nio.channels.ClosedByInterruptException

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#2064]
Many (but not all) of the `com.google.cloud.tools.eclipse.integration.appengine` tests are failing on Travis with:
```
Running com.google.cloud.tools.eclipse.integration.appengine.DebugNativeAppEngineStandardProjectTest
[Watchdog] > testDebugLaunch(com.google.cloud.tools.eclipse.integration.appengine.DebugNativeAppEngineStandardProjectTest)
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x8012c9 (New Projec)
Window manager warning: meta_window_activate called by a pager with a 0 timestamp; the pager needs to be fixed.
23:16:38.264 [WorkbenchTestable] WARN  o.e.s.s.f.widgets.SWTBotTreeItem - Tree item TreeItem with text {Google Cloud Platform} is already expanded. Won't expand it again.
!ENTRY org.eclipse.ui 4 0 2017-06-14 23:16:38.288
!MESSAGE Unhandled event loop exception
!STACK 0
org.eclipse.swt.SWTException: Failed to execute runnable (com.google.cloud.tools.appengine.cloudsdk.CloudSdkVersionFileException: java.nio.channels.ClosedByInterruptException)
	at org.eclipse.swt.SWT.error(SWT.java:4533)
	at org.eclipse.swt.SWT.error(SWT.java:4448)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4536)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4154)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
	at org.eclipse.jface.window.Window.open(Window.java:794)
	at org.eclipse.ui.actions.NewProjectAction.run(NewProjectAction.java:115)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:473)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:565)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:397)
	at org.eclipse.jface.action.ActionContributionItem$$Lambda$40/533353383.handleEvent(Unknown Source)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5227)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1340)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1366)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1349)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1134)
	at org.eclipse.swtbot.swt.finder.widgets.AbstractSWTBot$2.run(AbstractSWTBot.java:165)
	at org.eclipse.swtbot.swt.finder.finders.UIThreadRunnable$5.doRun(UIThreadRunnable.java:221)
	at org.eclipse.swtbot.swt.finder.finders.UIThreadRunnable.run(UIThreadRunnable.java:78)
	at org.eclipse.swtbot.swt.finder.finders.UIThreadRunnable.asyncExec(UIThreadRunnable.java:223)
	at org.eclipse.swtbot.swt.finder.widgets.AbstractSWTBot.asyncExec(AbstractSWTBot.java:598)
	at org.eclipse.swtbot.swt.finder.widgets.AbstractSWTBot.notify(AbstractSWTBot.java:154)
	at org.eclipse.swtbot.swt.finder.widgets.AbstractSWTBot.notify(AbstractSWTBot.java:135)
	at org.eclipse.swtbot.swt.finder.widgets.AbstractSWTBot.notify(AbstractSWTBot.java:125)
	at org.eclipse.swtbot.swt.finder.widgets.SWTBotMenu$1.run(SWTBotMenu.java:86)
	at org.eclipse.swtbot.swt.finder.finders.UIThreadRunnable$5.doRun(UIThreadRunnable.java:221)
	at org.eclipse.swtbot.swt.finder.finders.UIThreadRunnable$1.run(UIThreadRunnable.java:89)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4536)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4154)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:693)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
	at org.eclipse.tycho.surefire.osgibooter.UITestApplication.runApplication(UITestApplication.java:31)
	at org.eclipse.tycho.surefire.osgibooter.AbstractUITestApplication.run(AbstractUITestApplication.java:120)
	at org.eclipse.tycho.surefire.osgibooter.UITestApplication.start(UITestApplication.java:37)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1492)
Caused by: com.google.cloud.tools.appengine.cloudsdk.CloudSdkVersionFileException: java.nio.channels.ClosedByInterruptException
	at com.google.cloud.tools.appengine.cloudsdk.CloudSdk.getVersion(CloudSdk.java:355)
	at com.google.cloud.tools.appengine.cloudsdk.CloudSdk.validateCloudSdkVersion(CloudSdk.java:463)
	at com.google.cloud.tools.appengine.cloudsdk.CloudSdk.validateCloudSdk(CloudSdk.java:456)
	at com.google.cloud.tools.eclipse.appengine.newproject.AppEngineProjectWizard.addPages(AppEngineProjectWizard.java:62)
	at org.eclipse.jface.wizard.WizardSelectionPage.getNextPage(WizardSelectionPage.java:116)
	at org.eclipse.ui.internal.dialogs.WorkbenchWizardSelectionPage.getNextPage(WorkbenchWizardSelectionPage.java:98)
	at org.eclipse.jface.wizard.WizardDialog.nextPressed(WizardDialog.java:869)
	at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:419)
	at org.eclipse.jface.dialogs.Dialog$2.widgetSelected(Dialog.java:618)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5227)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1340)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1366)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1349)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1134)
	at org.eclipse.swtbot.swt.finder.widgets.AbstractSWTBot$2.run(AbstractSWTBot.java:165)
	at org.eclipse.swtbot.swt.finder.finders.UIThreadRunnable$5.doRun(UIThreadRunnable.java:221)
	at org.eclipse.swtbot.swt.finder.finders.UIThreadRunnable$1.run(UIThreadRunnable.java:89)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	... 55 more
Caused by: java.nio.channels.ClosedByInterruptException
	at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202)
	at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:163)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:65)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:109)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:103)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.readLine(BufferedReader.java:324)
	at java.io.BufferedReader.readLine(BufferedReader.java:389)
	at java.nio.file.Files.readAllLines(Files.java:3205)
	at com.google.cloud.tools.appengine.cloudsdk.CloudSdk.getVersion(CloudSdk.java:348)
	... 75 more
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x80001b (data - Res)
Window manager warning: meta_window_activate called by a pager with a 0 timestamp; the pager needs to be fixed.
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 31.229 sec <<< FAILURE! - in com.google.cloud.tools.eclipse.integration.appengine.DebugNativeAppEngineStandardProjectTest
testDebugLaunch(com.google.cloud.tools.eclipse.integration.appengine.DebugNativeAppEngineStandardProjectTest)  Time elapsed: 31.221 sec  <<< ERROR!
org.eclipse.swtbot.swt.finder.exceptions.WidgetNotFoundException: Could not find widget matching: (of type 'Text' and with label (with mnemonic 'Project name:'))
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:522)
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:496)
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:484)
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntilWidgetAppears(SWTBotFactory.java:466)
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.widget(SWTBotFactory.java:419)
	at org.eclipse.swtbot.swt.finder.SWTBot.textWithLabel(SWTBot.java:1478)
	at org.eclipse.swtbot.swt.finder.SWTBot.textWithLabel(SWTBot.java:1466)
	at com.google.cloud.tools.eclipse.integration.appengine.SwtBotAppEngineActions.createWebAppProject(SwtBotAppEngineActions.java:80)
	at com.google.cloud.tools.eclipse.integration.appengine.SwtBotAppEngineActions.createNativeWebAppProject(SwtBotAppEngineActions.java:48)
	at com.google.cloud.tools.eclipse.integration.appengine.DebugNativeAppEngineStandardProjectTest.testDebugLaunch(DebugNativeAppEngineStandardProjectTest.java:83)
```

It's not due to the Tycho-Surefire `forkedProcessTimeoutInSeconds` as the individual tests are failing, not the forked test JVM, and the failures are happening after less than 5 minutes.

In this case, the first test (`NewNativeAppEngineStandardProjectTest#testWithPackage()`) works, but the remaining tests fail as per the above.

[We came across similar exceptions before](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/pull/1337#issuecomment-277336697) and apparently they're caused by a thread being interrupted.  But I'm not sure how that is happening here as `CloudSdk#getVersion()` simply reads the contents of `…google-cloud-sdk…/VERSION`, which isn't a large file.

~~Here's the full log of a run:
[java.nio.channels.ClosedByInterruptException.txt](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/files/1076443/java.nio.channels.ClosedByInterruptException.txt)~~

**Comment by briandealwis** [comment]
@chanseokoh [notes](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/pull/2062#issuecomment-308565681):
> I agree the failures are due to the thread running tests being interrupted. I've seen those failures somewhat often in the past few days. For some unknown reason, builds sometimes take over 40 or 50 minutes on Travis during regular work hours recently. The system seems to be overloaded. I think it is this system overload that sometimes causes this error.

**Comment by briandealwis** [comment]
I noticed that the Eclipse Workbench configures SWT with [a different `Synchronizer` on the `Display` instance](http://git.eclipse.org/c/platform/eclipse.platform.ui.git/tree/bundles/org.eclipse.ui.workbench/Eclipse%20UI/org/eclipse/ui/internal/Workbench.java?h=master#n2806).  The `Synchronizer` is a delegate used to dispatch events.  The `UISynchronizer` uses `Thread.interrupt()` to interrupt the SWT thread if [it thinks the SWT thread may be deadlocked](http://git.eclipse.org/c/platform/eclipse.platform.ui.git/tree/bundles/org.eclipse.ui.workbench/Eclipse%20UI/org/eclipse/ui/internal/UISynchronizer.java?h=master#n154).  Apparently [UISynchronizer#syncExec() was noted to leak the interrupt state](https://bugs.eclipse.org/bugs/show_bug.cgi?id=506169), which sounds like what we're hitting, which was fixed for 4.7 M3 (Oxygen).  It's worth noting where we see this bug should it recur.

The `UISynchronizer` can be disabled by running with the `-allowDeadlock` command-line flag.

**Comment by briandealwis** [comment]
Just happened in `com.google.cloud.tools.eclipse.integration.appengine` on the Neon target.
[interruptions.txt](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/files/1113454/interruptions.txt)r

**Comment by briandealwis** [comment]
Ah, from https://bugs.eclipse.org/bugs/show_bug.cgi?id=505920:

> JobManager.beginRule uses Thread.interrupt internally to react to progress monitor cancellation while waiting for the Job's rule. However, as discovered in bug 504502, it can also leave the Thread.interrupted() state set on the Thread after reacting to the cancellation.

Probably the easiest thing is to call `Thread#interrupted()` in `ThreadDumpingWatchdog#before()` to reset the thread interrupted state before the test is run.

**Comment by chanseokoh** [comment]
Not fixed, unfortunately.

https://travis-ci.org/GoogleCloudPlatform/google-cloud-eclipse/jobs/252270099

**Comment by briandealwis** [comment]
That was on Neon.  Maybe we should try clearing it in `AppEngineProjectWizard#addPages()`?

**Comment by briandealwis** [comment]
Closing as we haven't seen this for a while.
