### ISSUE TITLE
ProjectUtils.waitForProjects() not enough to wait for markers to appear/disappear, leading to flaky tests

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#2076]
We have a few places where we test our validation puts problem markers properly, e.g.,

- Tests in `XmlValidatorTest` such as `testXsdValidation_appengineWebXml()` and `testValidate_badXml()`
- [`XsltSourceQuickFixTest.testApply()`](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/v1.2.0B/plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/XsltSourceQuickFixTest.java#L86)
- `ToServlet25SourceQuickFixTest.testConvertServlet()`

We call `ProjectUtils.waitForProjects()` to give some time for the markers to be updated. However, it seems like we need to wait further, as the tests occasionally fail: https://github.com/GoogleCloudPlatform/google-cloud-eclipse/pull/2075#issuecomment-309565629 and https://github.com/GoogleCloudPlatform/google-cloud-eclipse/pull/2069#issuecomment-309488235.

This issue does not necessarily mean we want to overload `waitForProjects()` further to also cover marker updates. We could put some code to wait for markers in the tests themselves.

**Comment by briandealwis** [comment]
```
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 25.888 sec <<< FAILURE! - in com.google.cloud.tools.eclipse.appengine.validation.XsltSourceQuickFixTest
testApply(com.google.cloud.tools.eclipse.appengine.validation.XsltSourceQuickFixTest)  Time elapsed: 25.687 sec  <<< FAILURE!
java.lang.AssertionError: [/test0.06296464251836487/appengine-web.xml:2: Project ID should be specified at deploy time]
	at org.junit.Assert.fail(Assert.java:88)
	at com.google.cloud.tools.eclipse.test.util.ArrayAssertions.assertIsEmpty(ArrayAssertions.java:58)
	at com.google.cloud.tools.eclipse.test.util.ArrayAssertions.assertIsEmpty(ArrayAssertions.java:36)
	at com.google.cloud.tools.eclipse.appengine.validation.XsltSourceQuickFixTest.testApply(XsltSourceQuickFixTest.java:92)
```
It's like the old markers are being removed independently?

**Comment by briandealwis** [comment]
I wonder if it would be worth adding some calling info into `waitForProjects()` to indicate whether a build-error is expected or not.  We could dump info on the running jobs (essentially `ThreadDumpingWatchdog.run()`) to help diagnose what's else is going on.  Perhaps provide a `Predicate<Collection<IMarker>>` to determine expected/unexpected?

**Comment by chanseokoh** [comment]
I am more inclined to have a simple wait directly in tests:

```java
for (int i = 0; i < LIMIT; i++) {
  Thread.sleep(50);  // readAndDispatch() if required
  bool markerFound = ... assertion condition ...
  if (markerFound) {
    return;
  }
}
fail("timed out");
```

**Comment by chanseokoh** [comment]
A bit skeptical, but I am wondering if these failures have anything to do with `NonSystemJobSuspender`. A lot of jobs are non-system, including `AutoBuildJob` and `ValBuilderJob` that are responsible for creating a marker. Even if `NonSystemJobSyspender` is unrelated, I think it is better to suspend only `ConvertJob`, as discussed in https://github.com/GoogleCloudPlatform/google-cloud-eclipse/pull/2084#discussion_r123837495.

**Comment by chanseokoh** [comment]
Happened a bit earlier in `XsltSourceQuickFixTest.testApply()`, even before making any change to the XML. This suggests this flaky marker failure have nothing to do with the XML editor.

```
testApply(com.google.cloud.tools.eclipse.appengine.validation.XsltSourceQuickFixTest)  Time elapsed: 3.767 sec  <<< FAILURE!
java.lang.AssertionError: expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.google.cloud.tools.eclipse.appengine.validation.XsltSourceQuickFixTest.testApply(XsltSourceQuickFixTest.java:76)
```

**Comment by chanseokoh** [comment]
A bit skeptical, but I am wondering if these failures have anything to do with `NonSystemJobSuspender`. > A lot of jobs are non-system, including `AutoBuildJob` and `ValBuilderJob` that are responsible for creating a marker. Even if `NonSystemJobSyspender` is unrelated, I think it is better to suspend only `ConvertJob`, as discussed in https://github.com/GoogleCloudPlatform/google-cloud-eclipse/pull/2084#discussion_r123837495.

This failure happened after #2112, so the `NonSystemJobSuspender` wasn't related either.

**Comment by briandealwis** [comment]
Had this happen twice today, both in the Mars build.

**Comment by chanseokoh** [comment]
Happened to me quite often too.

**Comment by briandealwis** [comment]
> Happened a bit earlier in XsltSourceQuickFixTest.testApply(), even before making any change to the XML. This suggests this flaky marker failure have nothing to do with the XML editor.

Hmm, that seems important.

**Comment by chanseokoh** [comment]
I looked into this the other day, and my conclusion is that marker creation (and retrieval through `IResource.findMarkers()`) is not related to UI events. If I read and understood the Eclipse code correctly, if `AutoBuildJob()` is fired, it will eventually lead to adding markers to `IResource`. Actually, the job will schedule `ValBuilderJob`, which puts markers with relevant messages and severity after validation, if I remember correctly. (Can't remember if there was another job or so, but things work in this fashion anyway.)

However, that was the dead end. As long as we wait for any `AutoBuildJob`s, we will eventually wait for `ValBuilderJob` that they will schedule, so we should be covered. I couldn't see any flaw in here, so I am really perplexed how this can happen.

**Comment by chanseokoh** [comment]
Happened again. Can happen anywhere we check markers:

```
testConvertServlet(com.google.cloud.tools.eclipse.appengine.validation.ToServlet25SourceQuickFixTest)  Time elapsed: 28.02 sec  <<< FAILURE!
java.lang.AssertionError: expected:<0> but was:<1>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.google.cloud.tools.eclipse.appengine.validation.ToServlet25SourceQuickFixTest.testConvertServlet(ToServlet25SourceQuickFixTest.java:76)
```

**Comment by briandealwis** [comment]
I pushed up a patch that repeatedly calls `waitForProjects()` until a marker arrives (or it times out). I've seen one place where it waited twice.

**Comment by briandealwis** [comment]
With the call to ThreadDumpingWatchdog during the wait-for-error-marker, one instance found the ConvertJob running:
```
Running com.google.cloud.tools.eclipse.appengine.validation.XmlValidatorTest
1.115 s: 0 problem markers found
+-------------------------------------------------------------------------------
| STACK DUMP @ 1.196 s: Expected a problem marker
|
| 
| Eclipse Locks:
|  :: 
|  R/,
|  Worker-2 :  1,
| -------
| 
| [80.43 ms]
|
| "main" [1] RUNNABLE
|     at sun.management.ThreadImpl.dumpThreads0(Native Method)
|     at sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:446)
|     at com.google.cloud.tools.eclipse.test.util.ThreadDumpingWatchdog.run(ThreadDumpingWatchdog.java:122)
|     at com.google.cloud.tools.eclipse.test.util.ThreadDumpingWatchdog.report(ThreadDumpingWatchdog.java:72)
|     at com.google.cloud.tools.eclipse.appengine.validation.XmlValidatorTest.testValidate_badXml(XmlValidatorTest.java:118)
|     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
|     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
|     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
|     at java.lang.reflect.Method.invoke(Method.java:606)
|     at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
|     at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
|     at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
|     at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
|     at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
|     at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
|     at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
|     at org.junit.rules.RunRules.evaluate(RunRules.java:20)
|     at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
|     at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
|     at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
|     at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
|     at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
|     at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
|     at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
|     at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
|     at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
|     at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
|     at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
|     at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
|     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
|     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
|     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
|     at java.lang.reflect.Method.invoke(Method.java:606)
|     at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
|     at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:156)
|     at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:82)
|     at org.eclipse.tycho.surefire.osgibooter.OsgiSurefireBooter.run(OsgiSurefireBooter.java:95)
|     at org.eclipse.tycho.surefire.osgibooter.AbstractUITestApplication$1.run(AbstractUITestApplication.java:35)
|     at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
|     at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
|     - locked org.eclipse.swt.widgets.RunnableLock@6b6d5ace
|     at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3794)
|     at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3433)
|     at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
|     at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
|     at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
|     at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
|     at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:694)
|     at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
|     at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:606)
|     at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
|     at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
|     at org.eclipse.tycho.surefire.osgibooter.UITestApplication.runApplication(UITestApplication.java:31)
|     at org.eclipse.tycho.surefire.osgibooter.AbstractUITestApplication.run(AbstractUITestApplication.java:120)
|     at org.eclipse.tycho.surefire.osgibooter.UITestApplication.start(UITestApplication.java:37)
|     at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
|     at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
|     at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
|     at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
|     at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
|     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
|     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
|     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
|     at java.lang.reflect.Method.invoke(Method.java:606)
|     at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
|     at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
|     at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
|     at org.eclipse.equinox.launcher.Main.main(Main.java:1488)
| 
| "Framework Event Dispatcher: Equinox Container: f0d82d58-cb7e-0017-1d1f-9775c3877a60" [11] WAITING on org.eclipse.osgi.framework.eventmgr.EventManager$EventThread@6bb6ac39
|     at java.lang.Object.wait(Native Method)
|     - waiting on org.eclipse.osgi.framework.eventmgr.EventManager$EventThread@6bb6ac39
|     at java.lang.Object.wait(Object.java:503)
|     at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.getNextEvent(EventManager.java:400)
|     at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:336)
| 
| "[Timer] - Main Queue Handler" [16] TIMED_WAITING on java.lang.Object@511e0dc9
|     at java.lang.Object.wait(Native Method)
|     - waiting on java.lang.Object@511e0dc9
|     at org.eclipse.equinox.internal.util.impl.tpt.timer.TimerImpl.run(TimerImpl.java:141)
|     at java.lang.Thread.run(Thread.java:745)
| 
| "Worker-2" [24] RUNNABLE
|     at java.io.UnixFileSystem.getBooleanAttributes0(Native Method)
|     at java.io.UnixFileSystem.getBooleanAttributes(UnixFileSystem.java:242)
|     at java.io.File.exists(File.java:813)
|     at org.eclipse.core.internal.filesystem.local.LocalFile.internalDelete(LocalFile.java:231)
|     at org.eclipse.core.internal.filesystem.local.LocalFile.delete(LocalFile.java:133)
|     at org.eclipse.core.internal.resources.Workspace.clear(Workspace.java:259)
|     at org.eclipse.core.internal.resources.LocalMetaArea.clearOldDescription(LocalMetaArea.java:66)
|     at org.eclipse.core.internal.localstore.FileSystemResourceManager.internalWrite(FileSystemResourceManager.java:663)
|     at org.eclipse.core.internal.resources.Project.writeDescription(Project.java:1366)
|     at org.eclipse.core.internal.resources.Project.setDescription(Project.java:1258)
|     at org.eclipse.core.internal.resources.Project.setDescription(Project.java:1281)
|     at org.eclipse.wst.jsdt.internal.core.JavaProject.setJavaCommand(JavaProject.java:2857)
|     at org.eclipse.wst.jsdt.internal.core.JavaProject.addToBuildSpec(JavaProject.java:450)
|     at org.eclipse.wst.jsdt.internal.core.JavaProject.configure(JavaProject.java:785)
|     at org.eclipse.core.internal.resources.NatureManager$1.run(NatureManager.java:146)
|     at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
|     at org.eclipse.core.internal.resources.NatureManager.configureNature(NatureManager.java:162)
|     at org.eclipse.core.internal.resources.NatureManager.configureNatures(NatureManager.java:208)
|     at org.eclipse.core.internal.resources.Project.basicSetDescription(Project.java:101)
|     at org.eclipse.core.internal.resources.Project.setDescription(Project.java:1254)
|     at org.eclipse.core.internal.resources.Project.setDescription(Project.java:1281)
|     at org.eclipse.wst.jsdt.web.core.internal.project.JsWebNature.addJsNature(JsWebNature.java:70)
|     at org.eclipse.wst.jsdt.web.core.internal.project.JsWebNature.configure(JsWebNature.java:151)
|     at org.eclipse.wst.jsdt.web.core.internal.project.JsNatureInstaller.installNature(JsNatureInstaller.java:50)
|     at org.eclipse.wst.jsdt.web.core.internal.project.JsNatureInstaller.execute(JsNatureInstaller.java:37)
|     at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.callDelegate(FacetedProject.java:1477)
|     at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.modifyInternal(FacetedProject.java:441)
|     at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.mergeChangesInternal(FacetedProject.java:1181)
|     at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.access$2(FacetedProject.java:1117)
|     at org.eclipse.wst.common.project.facet.core.internal.FacetedProject$1.run(FacetedProject.java:324)
|     at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2241)
|     at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.modify(FacetedProject.java:339)
|     at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.installProjectFacet(FacetedProject.java:255)
|     at org.eclipse.wst.jsdt.web.core.internal.project.ConvertJob.runInWorkspace(ConvertJob.java:57)
|     at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
|     at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
| 
| "EventAdmin Async Event Dispatcher Thread" [26] WAITING on org.eclipse.swt.widgets.RunnableLock@5864c17b
|     at java.lang.Object.wait(Native Method)
|     - waiting on org.eclipse.swt.widgets.RunnableLock@5864c17b
|     at java.lang.Object.wait(Object.java:503)
|     at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:199)
|     at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:145)
|     at org.eclipse.swt.widgets.Display.syncExec(Display.java:4633)
|     at org.eclipse.e4.ui.internal.workbench.swt.E4Application$1.syncExec(E4Application.java:211)
|     at org.eclipse.e4.ui.internal.di.UIEventObjectSupplier$UIEventHandler.handleEvent(UIEventObjectSupplier.java:53)
|     at org.eclipse.equinox.internal.event.EventHandlerWrapper.handleEvent(EventHandlerWrapper.java:197)
|     at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:197)
|     at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:1)
|     at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
|     at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
| 
| "WorkbenchTestable" [27] WAITING on org.eclipse.swt.widgets.RunnableLock@6b6d5ace owned by 'main [id:1]
|     at java.lang.Object.wait(Native Method)
|     - waiting on org.eclipse.swt.widgets.RunnableLock@6b6d5ace
|     at java.lang.Object.wait(Object.java:503)
|     at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:199)
|     at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:145)
|     at org.eclipse.swt.widgets.Display.syncExec(Display.java:4633)
|     at org.eclipse.e4.ui.internal.workbench.swt.E4Testable.runTest(E4Testable.java:115)
|     at org.eclipse.tycho.surefire.osgibooter.AbstractUITestApplication.runTests(AbstractUITestApplication.java:32)
|     at org.eclipse.e4.ui.internal.workbench.swt.E4Testable$1.run(E4Testable.java:73)
|     at java.lang.Thread.run(Thread.java:745)
| 
| "Java indexing" [30] TIMED_WAITING
|     at java.lang.Thread.sleep(Native Method)
|     at org.eclipse.jdt.internal.core.search.processing.JobManager.run(JobManager.java:413)
|     at java.lang.Thread.run(Thread.java:745)
| 
| "process reaper" [32] TIMED_WAITING on java.util.concurrent.SynchronousQueue$TransferStack@61ae0ba4
|     at sun.misc.Unsafe.park(Native Method)
|     - waiting on java.util.concurrent.SynchronousQueue$TransferStack@61ae0ba4
|     at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:226)
|     at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460)
|     at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:359)
|     at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:942)
|     at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1068)
|     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
|     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
|     at java.lang.Thread.run(Thread.java:745)
| 
| "JavaScript indexing" [43] WAITING on org.eclipse.wst.jsdt.internal.core.search.indexing.IndexManager@6725c8fb
|     at java.lang.Object.wait(Native Method)
|     - waiting on org.eclipse.wst.jsdt.internal.core.search.indexing.IndexManager@6725c8fb
|     at java.lang.Object.wait(Object.java:503)
|     at org.eclipse.wst.jsdt.internal.core.search.processing.JobManager.run(JobManager.java:370)
|     at java.lang.Thread.run(Thread.java:745)
| 
| "Worker-6" [47] TIMED_WAITING
|     at java.lang.Thread.sleep(Native Method)
|     at org.eclipse.jdt.internal.core.search.processing.JobManager$1ProgressJob.run(JobManager.java:355)
|     at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
| 
| "[ThreadPool Manager] - Idle Thread" [92] WAITING on org.eclipse.equinox.internal.util.impl.tpt.threadpool.Executor@553a4f33
|     at java.lang.Object.wait(Native Method)
|     - waiting on org.eclipse.equinox.internal.util.impl.tpt.threadpool.Executor@553a4f33
|     at java.lang.Object.wait(Object.java:503)
|     at org.eclipse.equinox.internal.util.impl.tpt.threadpool.Executor.run(Executor.java:106)
| 
| Ignored threads:
|   "Reference Handler" [2] WAITING on java.lang.ref.Reference$Lock@57b0da1a
|   "Finalizer" [3] WAITING on java.lang.ref.ReferenceQueue$Lock@5fce2831
|   "Signal Dispatcher" [4] RUNNABLE
|   "Active Thread: Equinox Container: f0d82d58-cb7e-0017-1d1f-9775c3877a60" [9] TIMED_WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@25e5096e
|   "Start Level: Equinox Container: f0d82d58-cb7e-0017-1d1f-9775c3877a60" [12] WAITING on org.eclipse.osgi.framework.eventmgr.EventManager$EventThread@1fcebee
|   "Bundle File Closer" [13] WAITING on org.eclipse.osgi.framework.eventmgr.EventManager$EventThread@4d1c098b
|   "Refresh Thread: Equinox Container: f0d82d58-cb7e-0017-1d1f-9775c3877a60" [14] WAITING on org.eclipse.osgi.framework.eventmgr.EventManager$EventThread@c1b30ba
|   "Worker-JM" [17] WAITING on java.util.ArrayList@3228c22
|   "EMF Reference Cleaner" [21] WAITING on java.lang.ref.ReferenceQueue$Lock@3eda9f93
|   "Worker-0" [22] TIMED_WAITING on org.eclipse.core.internal.jobs.WorkerPool@278de706
|   "Worker-1" [23] TIMED_WAITING on org.eclipse.core.internal.jobs.WorkerPool@278de706
|   "Timer-0" [28] TIMED_WAITING on java.util.TaskQueue@697e6e15
|   "Worker-3" [44] TIMED_WAITING on org.eclipse.core.internal.jobs.WorkerPool@278de706
|   "Worker-4" [45] TIMED_WAITING on org.eclipse.core.internal.jobs.WorkerPool@278de706
|   "Worker-5" [46] TIMED_WAITING on org.eclipse.core.internal.jobs.WorkerPool@278de706
|   "Worker-7" [48] TIMED_WAITING on org.eclipse.core.internal.jobs.WorkerPool@278de706
|   "Worker-8" [90] TIMED_WAITING on org.eclipse.core.internal.jobs.WorkerPool@278de706
|   "Worker-9" [114] TIMED_WAITING on org.eclipse.core.internal.jobs.WorkerPool@278de706
| ELAPSED TIME: 81.80 ms
+-------------------------------------------------------------------------------
2.441 s: 1 problem markers found
```

**Comment by briandealwis** [comment]
Saw a failure in `testApply()`, and this is now after waiting on `ConvertJob` (#2260).
```
com.google.cloud.tools.eclipse.appengine.validation.XsltSourceQuickFixTest
testApply(com.google.cloud.tools.eclipse.appengine.validation.XsltSourceQuickFixTest)  Time elapsed: 22.61 sec  <<< FAILURE!
java.lang.AssertionError: [/test0.8039042893959618/appengine-web.xml:2: Project ID should be specified at deploy time]
	at org.junit.Assert.fail(Assert.java:88)
	at com.google.cloud.tools.eclipse.test.util.ArrayAssertions.assertIsEmpty(ArrayAssertions.java:58)
	at com.google.cloud.tools.eclipse.test.util.ArrayAssertions.assertIsEmpty(ArrayAssertions.java:36)
	at com.google.cloud.tools.eclipse.appengine.validation.XsltSourceQuickFixTest.testApply(XsltSourceQuickFixTest.java:101)
```

**Comment by briandealwis** [comment]
Closing as we haven't seen this for a while.
