### ISSUE TITLE
Make waitForProjects() wait for ConvertJob

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#2087]
Seen on Travis on #2086
```
Running com.google.cloud.tools.eclipse.appengine.validation.XmlValidatorTest
!ENTRY org.eclipse.wst.jsdt.web.core 4 4 2017-06-26 22:20:37.303
!MESSAGE Resource '/test0.9679344619702539' does not exist.
!STACK 1
org.eclipse.core.internal.resources.ResourceException: Resource '/test0.9679344619702539' does not exist.
	at org.eclipse.core.internal.resources.Resource.checkExists(Resource.java:335)
	at org.eclipse.core.internal.resources.Resource.checkAccessible(Resource.java:209)
	at org.eclipse.core.internal.resources.Project.checkAccessible(Project.java:141)
	at org.eclipse.core.internal.resources.Folder.assertCreateRequirements(Folder.java:33)
	at org.eclipse.core.internal.resources.Folder.create(Folder.java:93)
	at org.eclipse.core.internal.resources.Folder.create(Folder.java:121)
	at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.save(FacetedProject.java:1663)
	at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.setFixedProjectFacetsInternal(FacetedProject.java:545)
	at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.mergeChangesInternal(FacetedProject.java:1209)
	at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.access$2(FacetedProject.java:1117)
	at org.eclipse.wst.common.project.facet.core.internal.FacetedProject$5.run(FacetedProject.java:1099)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2267)
	at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.mergeChanges(FacetedProject.java:1109)
	at org.eclipse.wst.common.project.facet.core.internal.FacetedProjectWorkingCopy.commitChanges(FacetedProjectWorkingCopy.java:2020)
	at org.eclipse.wst.jsdt.web.core.internal.project.ConvertJob.runInWorkspace(ConvertJob.java:66)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
!SUBENTRY 1 org.eclipse.core.resources 4 368 2017-06-26 22:20:37.322
!MESSAGE Resource '/test0.9679344619702539' does not exist.
Tests run: 7, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 30.463 sec <<< FAILURE! - in com.google.cloud.tools.eclipse.appengine.validation.XmlValidatorTest
testCreateMarker(com.google.cloud.tools.eclipse.appengine.validation.XmlValidatorTest)  Time elapsed: 3.631 sec
testValidate_dynamicWebProject(com.google.cloud.tools.eclipse.appengine.validation.XmlValidatorTest)  Time elapsed: 2.505 sec
testValidate_badXml(com.google.cloud.tools.eclipse.appengine.validation.XmlValidatorTest)  Time elapsed: 0.376 sec  <<< FAILURE!
java.lang.AssertionError: expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.google.cloud.tools.eclipse.appengine.validation.XmlValidatorTest.testValidate_badXml(XmlValidatorTest.java:110)
```

**Comment by chanseokoh** [comment]
The `XmlValidatorTest.testValidate_badXml()` failure is a dup of #2076.

The first exception is from the second `ConvertJob`, which we may ignore in tests. If we really want to suppress it, we could do `waitForProjects()` in `tearDown()`, but I am not so inclined to do so.

**Comment by chanseokoh** [comment]
> The first exception is from the second `ConvertJob`, which we may ignore in tests. If we really want to suppress it, we could do `waitForProjects()` in `tearDown()`, but I am not so inclined to do so.

The `ConvertJob` does not define `belongsTo()`, so `waitForProjects()` may still slip it through.

**Comment by briandealwis** [comment]
I think we'd need to explicitly look for `ConvertJob`, but given this interference I think it would be a good thing to do.

**Comment by chanseokoh** [comment]
Since the flaky test is a dup of #2076, I have changed the title so that this issue is about `ConvertJob` trying to modify a project after the project has been deleted.
