### ISSUE TITLE
XML validation failures accessing `http://www.w3.org/2001/xml.xsd`

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#2091]
Seeing occasional failures on Travis relating to obtaining `http://www.w3.org/2001/xml.xsd` (stacktrace below).  It's odd as we weren't including this file previously in #2066, so I don't know why this is failing now.

We are including `org.eclipse.wst.standard.schemas`, but it turns out that `org.eclipse.wst.standard.schemas`'s `plugin.xml` has commented out the `http://www.w3.org/2001/xml.xsd` with:
```xml
 <!-- these are removed from the catalog, since they are -not- 
            the same as those in the xsd.ui plugin, which 
            point to the org.eclipse.xsd versions
            <uri
                name="http://www.w3.org/2001/XMLSchema"
                uri="dtdsAndSchemas/XMLSchema.dtd" />
                
            <system
                systemId="http://www.w3.org/2001/xml.xsd"
                uri="dtdsAndSchemas/xml.xsd" />
             —>
```
There are indeed copies in the `org.eclipse.xsd` bundle.  But the actual catalog entries are contributed `org.eclipse.wst.xsd.core` (not `org.eclipse.wst.xsd.ui` as per the comment), and which is a bit awkward as `org.eclipse.wst.xsd.core` provides functionality.

```
testStandardFacetInstallation(com.google.cloud.tools.eclipse.appengine.facets.StandardFacetInstallationTest)  Time elapsed: 2.447 sec  <<< FAILURE!
java.lang.AssertionError: Imported projects have errors
/test-dynamic-web-project/war/WEB-INF/web.xml:1: Referenced file contains errors (jar:file:/home/travis/.m2/repository/p2/osgi/bundle/org.eclipse.jst.standard.schemas/1.2.201.v201501151629/org.eclipse.jst.standard.schemas-1.2.201.v201501151629.jar!/dtdsAndSchemas/javaee_5.xsd).  For more information, right click on the message in the Problems View and select "Show Details..."
  jar:file:/home/travis/.m2/repository/p2/osgi/bundle/org.eclipse.jst.standard.schemas/1.2.201.v201501151629/org.eclipse.jst.standard.schemas-1.2.201.v201501151629.jar!/dtdsAndSchemas/javaee_5.xsd[77:57]: schema_reference.4: Failed to read schema document 'http://www.w3.org/2001/xml.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.
  jar:file:/home/travis/.m2/repository/p2/osgi/bundle/org.eclipse.jst.standard.schemas/1.2.201.v201501151629/org.eclipse.jst.standard.schemas-1.2.201.v201501151629.jar!/dtdsAndSchemas/javaee_5.xsd[135:33]: src-resolve: Cannot resolve the name 'xml:lang' to a(n) 'attribute declaration' component.
  jar:file:/home/travis/.m2/repository/p2/osgi/bundle/org.eclipse.jst.standard.schemas/1.2.201.v201501151629/org.eclipse.jst.standard.schemas-1.2.201.v201501151629.jar!/dtdsAndSchemas/javaee_5.xsd[135:33]: s4s-elt-invalid-content.1: The content of 'descriptionType' is invalid.  Element 'attribute' is invalid, misplaced, or occurs too often.
  jar:file:/home/travis/.m2/repository/p2/osgi/bundle/org.eclipse.jst.standard.schemas/1.2.201.v201501151629/org.eclipse.jst.standard.schemas-1.2.201.v201501151629.jar!/dtdsAndSchemas/javaee_5.xsd[182:33]: s4s-elt-invalid-content.1: The content of 'display-nameType' is invalid.  Element 'attribute' is invalid, misplaced, or occurs too often.
  jar:file:/home/travis/.m2/repository/p2/osgi/bundle/org.eclipse.jst.standard.schemas/1.2.201.v201501151629/org.eclipse.jst.standard.schemas-1.2.201.v201501151629.jar!/dtdsAndSchemas/javaee_5.xsd[683:36]: s4s-elt-invalid-content.1: The content of 'iconType' is invalid.  Element 'attribute' is invalid, misplaced, or occurs too often.
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.google.cloud.tools.eclipse.test.util.project.ProjectUtils.failIfBuildErrors(ProjectUtils.java:147)
	at com.google.cloud.tools.eclipse.test.util.project.ProjectUtils.failIfBuildErrors(ProjectUtils.java:141)
	at com.google.cloud.tools.eclipse.test.util.project.ProjectUtils.importProjects(ProjectUtils.java:127)
	at com.google.cloud.tools.eclipse.appengine.facets.StandardFacetInstallationTest.testStandardFacetInstallation(StandardFacetInstallationTest.java:71)
```

**Comment by briandealwis** [comment]
My guess is that WTP is fetching `http://www.w3.org/2001/xml.xsd` with an `Accept: */*` so that the remote is returning an HTML document?

**Comment by chanseokoh** [comment]
Is this always happening? If not, my guess is that it's a rare network problem?

**Comment by briandealwis** [comment]
I think it's the same rare network problem leading to sporadic failures like #1196.  What's odd is that in this particular case, all three platforms failed in the same way.

**Comment by briandealwis** [comment]
I've included a fix in [https://github.com/GoogleCloudPlatform/google-cloud-eclipse/tree/cloudsdk161].

**Comment by elharo** [comment]
I'm surprised this is pulled in at all. It isn't necessary.
