### ISSUE TITLE
IllegalArgumentException in IProject#delete() from TestProjectCreator#after()

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#2093]
Odd exception seen on Travis.  Note that it's failing to delete the `.settings` directory, which should almost certainly exist as it holds the `org.eclipse.wst.common.project.facet.core.xml` file with facet information.  There are a few bug reports tracing down to [bug 144458](https://bugs.eclipse.org/bugs/show_bug.cgi?id=144458#c5), but they all seem to be a problem with linked folders (aka aliases) which doesn't appear here.

```
testInvariantToModuleOrder(com.google.cloud.tools.eclipse.appengine.localserver.launching.LaunchHelperTest)  Time elapsed: 12.877 sec  <<< ERROR!
java.lang.IllegalArgumentException: Element not found: /test0.4247278297038244/.settings.
	at org.eclipse.core.internal.watson.ElementTree.elementNotFound(ElementTree.java:256)
	at org.eclipse.core.internal.watson.ElementTree.deleteElement(ElementTree.java:248)
	at org.eclipse.core.internal.resources.Workspace.deleteResource(Workspace.java:1427)
	at org.eclipse.core.internal.resources.Resource.deleteResource(Resource.java:876)
	at org.eclipse.core.internal.localstore.DeleteVisitor.delete(DeleteVisitor.java:68)
	at org.eclipse.core.internal.localstore.DeleteVisitor.visit(DeleteVisitor.java:151)
	at org.eclipse.core.internal.localstore.UnifiedTree.accept(UnifiedTree.java:109)
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.delete(FileSystemResourceManager.java:351)
	at org.eclipse.core.internal.resources.ResourceTree.internalDeleteFolder(ResourceTree.java:358)
	at org.eclipse.core.internal.resources.ResourceTree.internalDeleteProject(ResourceTree.java:393)
	at org.eclipse.core.internal.resources.ResourceTree.standardDeleteProject(ResourceTree.java:850)
	at org.eclipse.core.internal.resources.Resource.unprotectedDelete(Resource.java:1835)
	at org.eclipse.core.internal.resources.Resource.delete(Resource.java:781)
	at org.eclipse.core.internal.resources.Project.delete(Project.java:329)
	at com.google.cloud.tools.eclipse.test.util.project.TestProjectCreator.after(TestProjectCreator.java:95)
```

**Comment by briandealwis** [comment]
Oh, I [encountered this before](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/1196#issuecomment-276119355) in #1196.

**Comment by briandealwis** [comment]
My suspicion is that we have situations where we should be waiting:
```
        if (getFacetedProject().hasProjectFacet(WebFacetUtils.WEB_FACET)) {
          // Wait for the WTP validation job as it runs without the workspace protection lock
          ProjectUtils.waitForProjects(project);
        }
```

**Comment by briandealwis** [comment]
```
testInvariantToModuleOrder(com.google.cloud.tools.eclipse.appengine.localserver.launching.LaunchHelperTest)  Time elapsed: 11.66 sec  <<< ERROR!
java.lang.IllegalArgumentException: Element not found: /test0.8548791588419516/.settings.
	at org.eclipse.core.internal.watson.ElementTree.elementNotFound(ElementTree.java:256)
	at org.eclipse.core.internal.watson.ElementTree.deleteElement(ElementTree.java:248)
	at org.eclipse.core.internal.resources.Workspace.deleteResource(Workspace.java:1427)
	at org.eclipse.core.internal.resources.Resource.deleteResource(Resource.java:876)
	at org.eclipse.core.internal.localstore.DeleteVisitor.delete(DeleteVisitor.java:68)
	at org.eclipse.core.internal.localstore.DeleteVisitor.visit(DeleteVisitor.java:151)
	at org.eclipse.core.internal.localstore.UnifiedTree.accept(UnifiedTree.java:109)
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.delete(FileSystemResourceManager.java:351)
	at org.eclipse.core.internal.resources.ResourceTree.internalDeleteFolder(ResourceTree.java:358)
	at org.eclipse.core.internal.resources.ResourceTree.internalDeleteProject(ResourceTree.java:393)
	at org.eclipse.core.internal.resources.ResourceTree.standardDeleteProject(ResourceTree.java:850)
	at org.eclipse.core.internal.resources.Resource.unprotectedDelete(Resource.java:1835)
	at org.eclipse.core.internal.resources.Resource.delete(Resource.java:781)
	at org.eclipse.core.internal.resources.Project.delete(Project.java:329)
	at com.google.cloud.tools.eclipse.test.util.project.TestProjectCreator.after(TestProjectCreator.java:97)
```

Maybe we should acquire a lock…

**Comment by elharo** [comment]
This is in the `after` method. Should this fail the test or should we log and continue?

**Comment by diegomarquezp** [comment]
Closing as not planned.
