### ISSUE TITLE
Cannot launch dataflow project with _Track Dataflow Version_

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#2108]
**What did you do?**

  1. Create Dataflow project with _starter pipeline_
  2. Right-click on new project and select _Properties > Dataflow > Track Dataflow Version_
  3. Select _Run > Debug Configurations_
  4. Create new Dataflow Pipeline; this will populate a new configuration for the `StarterPipeline`.

See NPE in `PipelineArgumentsTab.updateRunnerButtons(MajorVersion)` as the argument is `MajorVersion.ALL`.

**What did you expect to see?**

A new launch configuration with a list of pipeline runners.

**What did you see instead?**

NPE logged (below); no runners in list of _Pipeline Arguments_ tab.  
```
!ENTRY org.eclipse.jface 4 2 2017-07-05 15:15:03.658
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.jface".
!STACK 0
java.lang.NullPointerException
	at com.google.cloud.tools.eclipse.dataflow.ui.launcher.PipelineArgumentsTab.updateRunnerButtons(PipelineArgumentsTab.java:338)
	at com.google.cloud.tools.eclipse.dataflow.ui.launcher.PipelineArgumentsTab.initializeFrom(PipelineArgumentsTab.java:310)
	at org.eclipse.debug.ui.AbstractLaunchConfigurationTabGroup.initializeFrom(AbstractLaunchConfigurationTabGroup.java:90)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationTabGroupWrapper.initializeFrom(LaunchConfigurationTabGroupWrapper.java:201)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationTabGroupViewer.displayInstanceTabs(LaunchConfigurationTabGroupViewer.java:766)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationTabGroupViewer$8.run(LaunchConfigurationTabGroupViewer.java:637)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationTabGroupViewer.inputChanged(LaunchConfigurationTabGroupViewer.java:654)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationTabGroupViewer.setInput0(LaunchConfigurationTabGroupViewer.java:615)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationTabGroupViewer.setInput(LaunchConfigurationTabGroupViewer.java:590)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationsDialog.handleLaunchConfigurationSelectionChanged(LaunchConfigurationsDialog.java:952)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationsDialog$3.selectionChanged(LaunchConfigurationsDialog.java:573)
```

**Comment by briandealwis** [comment]
The `PipelineRunner` static initiation block needs to populate for `MajorVersion.ALL`.

**Comment by briandealwis** [comment]
Should also null-proof `PipelineArgumentsTab#updateRunnerButtons()`.

**Comment by briandealwis** [comment]
Hmm, still get an error in _Update Hierarchy_:
> An internal error occurred during: "Update Hierarchy".
> Tried to create a TypeHierarchyPipelineOptionsHierarchy for a Java Project where no PipelineOptions type exists

Error logged:
```
!ENTRY org.eclipse.core.jobs 4 2 2017-07-05 15:52:33.981
!MESSAGE An internal error occurred during: "Update Hierarchy".
!STACK 0
java.lang.IllegalArgumentException: Tried to create a TypeHierarchyPipelineOptionsHierarchy for a Java Project where no PipelineOptions type exists
	at com.google.cloud.tools.eclipse.dataflow.core.launcher.options.JavaProjectPipelineOptionsHierarchy.<init>(JavaProjectPipelineOptionsHierarchy.java:72)
	at com.google.cloud.tools.eclipse.dataflow.core.launcher.ClasspathPipelineOptionsHierarchyFactory.forProject(ClasspathPipelineOptionsHierarchyFactory.java:54)
	at com.google.cloud.tools.eclipse.dataflow.ui.launcher.PipelineArgumentsTab.getPipelineOptionsHierarchy(PipelineArgumentsTab.java:372)
	at com.google.cloud.tools.eclipse.dataflow.ui.launcher.PipelineArgumentsTab.access$6(PipelineArgumentsTab.java:367)
	at com.google.cloud.tools.eclipse.dataflow.ui.launcher.PipelineArgumentsTab$3.run(PipelineArgumentsTab.java:351)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```
