### ISSUE TITLE
No error message if project location already exists when creating Dataflow project

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#2151]
Steps to reproduce
1. Create a new Dataflow project.
2. (Optional) Delete the project, but do not check _Delete project contents on disk (cannot be undone)_. when doing so.
3. Create another Dataflow project with the same name.

Nothing happens. No visible error message to users. Logs show the following exception.

```
!MESSAGE Unable to create project from archetype [com.google.cloud.dataflow:google-cloud-dataflow-java-archetypes-starter:1.9.0]
!STACK 0
org.apache.maven.archetype.exception.ProjectDirectoryExists: A Maven 2 project already exists in the directory < ... some directory ... >
	at org.apache.maven.archetype.generator.DefaultFilesetArchetypeGenerator.generateArchetype(DefaultFilesetArchetypeGenerator.java:192)
	at org.apache.maven.archetype.generator.DefaultArchetypeGenerator.processFileSetArchetype(DefaultArchetypeGenerator.java:129)
	at org.apache.maven.archetype.generator.DefaultArchetypeGenerator.generateArchetype(DefaultArchetypeGenerator.java:100)
	at org.apache.maven.archetype.generator.DefaultArchetypeGenerator.generateArchetype(DefaultArchetypeGenerator.java:143)
	at org.apache.maven.archetype.generator.DefaultArchetypeGenerator.generateArchetype(DefaultArchetypeGenerator.java:169)
	at org.apache.maven.archetype.DefaultArchetypeManager.generateProjectFromArchetype(DefaultArchetypeManager.java:73)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.createArchetypeProjects0(ProjectConfigurationManager.java:811)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$5.call(ProjectConfigurationManager.java:760)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$5.call(ProjectConfigurationManager.java:1)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1355)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.createArchetypeProjects(ProjectConfigurationManager.java:758)
	at com.google.cloud.tools.eclipse.dataflow.core.project.DataflowProjectCreator.run(DataflowProjectCreator.java:235)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
```

**Comment by elharo** [comment]
It shouldn't be an error message. It should use the existing source. This is how Eclipse handle this case with Java projects:

![image](https://user-images.githubusercontent.com/1005544/28268200-582164f8-6acb-11e7-9270-e0cd5fd54a1a.png)

**Comment by chanseokoh** [comment]
In our case, we create a new project from an archetype, so reusing the existing project doesn't make much sense. I think we should report the error to the user.
