### ISSUE TITLE
Flaky IProject.delete() in GpeConversionTest on Kokoro: Resource Problems encountered while deleting resources

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#2171]
From the log, I wonder if it isn't the case that a validation job is running when it tries to delete the project.

Another possibility is that if there was an open file. From our past experience, deleting a project can fail on Windows in this case.

```
Running com.google.cloud.tools.eclipse.appengine.standard.java8.GpeConversionTest

!ENTRY org.eclipse.core.jobs 4 2 2017-07-19 06:38:47.410
!MESSAGE An internal error occurred during: "Validating TaskQueueExamples".
Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 5.055 sec <<< FAILURE! - in com.google.cloud.tools.eclipse.appengine.standard.java8.GpeConversionTest
gpeFacetedProject(com.google.cloud.tools.eclipse.appengine.standard.java8.GpeConversionTest)  Time elapsed: 2.923 sec
gpeClassicProject(com.google.cloud.tools.eclipse.appengine.standard.java8.GpeConversionTest)  Time elapsed: 2.126 sec  <<< ERROR!
org.eclipse.core.internal.resources.ResourceException: Problems encountered while deleting resources.
	at org.eclipse.core.internal.resources.Resource.delete(Resource.java:773)
	at org.eclipse.core.internal.resources.Project.delete(Project.java:324)
	at com.google.cloud.tools.eclipse.appengine.standard.java8.GpeConversionTest.tearDown(GpeConversionTest.java:48)


Results :

Tests in error: 
  GpeConversionTest.tearDown:48 » Resource Problems encountered while deleting r...

Tests run: 8, Failures: 0, Errors: 1, Skipped: 0

!STACK 0
java.lang.IllegalStateException: Preference node "org.eclipse.wst.validation" has been removed.
	at org.eclipse.core.internal.preferences.EclipsePreferences.checkRemoved(EclipsePreferences.java:164)
	at org.eclipse.core.internal.resources.ProjectPreferences.internalGet(ProjectPreferences.java:429)
	at org.eclipse.core.internal.preferences.EclipsePreferences.get(EclipsePreferences.java:443)
	at org.eclipse.wst.validation.internal.PreferencesWrapper$PreferencesWrapperPersistent.get(PreferencesWrapper.java:114)
	at org.eclipse.wst.validation.internal.DisabledResourceManager.load(DisabledResourceManager.java:86)
	at org.eclipse.wst.validation.internal.DisabledResourceManager.isDisabled(DisabledResourceManager.java:121)
	at org.eclipse.wst.validation.internal.DisabledResourceManager.isDisabled(DisabledResourceManager.java:116)
	at org.eclipse.wst.validation.internal.ValBuilderJob$Visitor.visit(ValBuilderJob.java:295)
	at org.eclipse.core.internal.resources.Resource$2.visit(Resource.java:120)
	at org.eclipse.core.internal.resources.Resource$1.visitElement(Resource.java:84)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:82)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:87)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:87)
	at org.eclipse.core.internal.watson.ElementTreeIterator.iterate(ElementTreeIterator.java:129)
	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:94)
	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:52)
	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:117)
	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:105)
	at org.eclipse.wst.validation.internal.ValBuilderJob.fullBuild(ValBuilderJob.java:219)
	at org.eclipse.wst.validation.internal.ValBuilderJob.run(ValBuilderJob.java:178)
	at org.eclipse.wst.validation.internal.ValBuilderJob.runInWorkspace(ValBuilderJob.java:126)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)


!ENTRY org.eclipse.core.resources 2 10035 2017-07-19 06:38:48.620
!MESSAGE The workspace will exit with unsaved changes in this session.
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
```

**Comment by briandealwis** [comment]
Hmmm, `GpeConversionTest` doesn't use `TestProjectCreator` and its `#tearDown()` doesn't call `waitForProjects()`.  And `TestProjectCreator#tearDown()` only uses `waitForProject()` if the created  project is faceted and with the DWP facet.
