### ISSUE TITLE
Use project SDK when staging App Engine apps for deploy

### ISSUE THREAD

**Issue by NicolaSpreafico** [GoogleCloudPlatform/google-cloud-eclipse#2195]
- Eclipse version: _Oxygen Release (4.7.0)_
- Cloud Tools for Eclipse version: _1.2.0.201706082053_
- Google Cloud SDK version: _163.0.0_
- OS: _Windows 10 v1703_
- Java version: _jdk1.8.0_111_

I have a Maven App Engine standard project which contains jsp files (and this is the reason I think that the project is looking for JDK)

If I deploy the project with `appengine:deploy` works fine
If I deploy with the plugin I get
```
Unable to stage:
java.lang.RuntimeException: Cannot get the System Java Compiler. Please use a JDK, not a JRE.
	at com.google.appengine.tools.admin.Application.compileJspJavaFiles(Application.java:1201)
	at com.google.appengine.tools.admin.Application.compileJsps(Application.java:1178)
	at com.google.appengine.tools.admin.Application.populateStagingDirectory(Application.java:901)
	at com.google.appengine.tools.admin.Application.createStagingDirectory(Application.java:809)
	at com.google.appengine.tools.admin.AppAdminImpl.stageApplication(AppAdminImpl.java:539)
	at com.google.appengine.tools.admin.AppAdminImpl.stageApplicationWithDefaultResourceLimits(AppAdminImpl.java:492)
	at com.google.appengine.tools.admin.AppCfg$StagingAction.execute(AppCfg.java:2510)
	at com.google.appengine.tools.admin.AppCfg.executeAction(AppCfg.java:393)
	at com.google.appengine.tools.admin.AppCfg.<init>(AppCfg.java:216)
	at com.google.appengine.tools.admin.AppCfg.<init>(AppCfg.java:116)
	at com.google.appengine.tools.admin.AppCfg.main(AppCfg.java:112)
com.google.appengine.tools.admin.AdminException: Unable to stage app: Cannot get the System Java Compiler. Please use a JDK, not a JRE.
	at com.google.appengine.tools.admin.AppAdminImpl.stageApplication(AppAdminImpl.java:543)
	at com.google.appengine.tools.admin.AppAdminImpl.stageApplicationWithDefaultResourceLimits(AppAdminImpl.java:492)
	at com.google.appengine.tools.admin.AppCfg$StagingAction.execute(AppCfg.java:2510)
	at com.google.appengine.tools.admin.AppCfg.executeAction(AppCfg.java:393)
	at com.google.appengine.tools.admin.AppCfg.<init>(AppCfg.java:216)
	at com.google.appengine.tools.admin.AppCfg.<init>(AppCfg.java:116)
	at com.google.appengine.tools.admin.AppCfg.main(AppCfg.java:112)
Caused by: java.lang.RuntimeException: Cannot get the System Java Compiler. Please use a JDK, not a JRE.
	at com.google.appengine.tools.admin.Application.compileJspJavaFiles(Application.java:1201)
	at com.google.appengine.tools.admin.Application.compileJsps(Application.java:1178)
	at com.google.appengine.tools.admin.Application.populateStagingDirectory(Application.java:901)
	at com.google.appengine.tools.admin.Application.createStagingDirectory(Application.java:809)
	at com.google.appengine.tools.admin.AppAdminImpl.stageApplication(AppAdminImpl.java:539)
	... 6 more

```

I don't think it is a project or OS error because using directly Maven the deploy works fine

Here is my Java installation
![image](https://user-images.githubusercontent.com/12278553/28561856-59e39080-7120-11e7-9a53-7009e9952670.png)

Eclipse configuration
![image](https://user-images.githubusercontent.com/12278553/28561881-6f3689ba-7120-11e7-961e-366b6d93046b.png)

Project configuration
![image](https://user-images.githubusercontent.com/12278553/28561908-811800e6-7120-11e7-86e7-269988fc48fa.png)

**Comment by chanseokoh** [comment]
I suspect that JRE was used to start your Eclipse. Can you try changining it to JDK to see if that works? I believe you can configure it through eclipse.ini.

**Comment by NicolaSpreafico** [comment]
I found the JRE indeed
![image](https://user-images.githubusercontent.com/12278553/28572795-c61379a0-7148-11e7-9321-72da140f7366.png)

And I changed it to JDK
![image](https://user-images.githubusercontent.com/12278553/28572876-00fb342c-7149-11e7-9d68-db1574060676.png)

And the deploy worked.
Thanks for the tip

**Comment by patflynn** [comment]
The bug really needs to be that the staging jsp compiler needs to use the project configured jdk.  We've seen this problem in other plugins as well.

**Comment by patflynn** [comment]
@loosebazooka Does this bug get filed against App Engine SDK?

**Comment by chanseokoh** [comment]
Maybe it's the fault of CT4E that does not use the project JDK. I'll take a look first.

**Comment by loosebazooka** [comment]
It probably isn't the App Engine SDK's fault. I think we need to trigger "staging" or whatever using the project sdk, since it's just using the configuration that launched staging in the first place.

**Comment by briandealwis** [comment]
I think @chanseokoh's right: CT4E isn't configuring `javaHome()` on the `CloudSdk` instance.

**Comment by chanseokoh** [comment]
@NicolaSpreafico I think it's possible that your JSPs will be complied with Java 8 and this might cause a problem if deploying to App Engine standard Java 7. If so, please double-check you don't have any problem.

**Comment by NicolaSpreafico** [comment]
After updating Eclipse configuration from JRE to SDK the deploy problem is solved and I can confirm that the JSP are working fine

**Comment by briandealwis** [comment]
It's odd that AppCfg is wanting to use the JDK compiler where as Jasper at runtime uses an embedded ECJ (#590).

**Comment by chanseokoh** [comment]
Had an offline discussion with @briandealwis. We believe as long as it's not a JRE, using higher versions of Java compilers won't be a problem for compiling JSPs during staging (which is done through `-source 1.7`, although it shows a warning `warning: [options] bootstrap class path not set in conjunction with -source 1.7`).

So, the strategy is find a JDK will be like this:

1. get the project's JRE and check if it is a JDK (resolve the compiler class)
1. if not, cycle through the other installed JREs of that type and see if any of them are JDKs
1. if none, raise an error

**Comment by patflynn** [comment]
Why not just raise an error immediately after step 1?

**Comment by chanseokoh** [comment]
> Why not just raise an error immediately after step 1?

I think that's a simple and good idea. Users should have a JDK, and making them to set it to their project sounds right.

**Comment by chanseokoh** [comment]
Didn't expect this will be closed. (Striking words doesn't seem to work.)

**Comment by chanseokoh** [comment]
On second thought, I think we can close this now. If a project's JRE is not a JDK (which will be very unlikely anyway) or if it can't find a JDK anywhere, it will fail with the message that it's not a JDK. Users will then naturally configure the project's JRE to be a JDK.
