### ISSUE TITLE
Test hang observed: XsltSourceQuickFixTest.testApply()

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#2196]
I don't remember having seen this. I'll add `ThreadDumpingWatchdog` to see what's happening.

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.google.cloud.tools.eclipse.appengine.validation.XsltSourceQuickFixTest
log4j:WARN No appenders could be found for logger (freemarker.cache).
log4j:WARN Please initialize the log4j system properly.
Jul 25, 2017 5:17:17 PM com.google.cloud.tools.eclipse.appengine.facets.AppEngineStandardFacet createAppEngineServerRuntime
WARNING: RuntimeTypes: RuntimeType[org.eclipse.jst.server.core.runtimeType, J2EE Runtime Library]
!ENTRY org.eclipse.core.jobs 4 2 2017-07-25 17:17:17.472
!MESSAGE An internal error occurred during: "Install App Engine runtimes in "test0.32727819634294486"".
!STACK 0
java.lang.NullPointerException: Could not find App Engine Standard runtime type
	at com.google.cloud.tools.eclipse.appengine.facets.AppEngineStandardFacet.createAppEngineServerRuntime(AppEngineStandardFacet.java:412)
	at com.google.cloud.tools.eclipse.appengine.facets.AppEngineStandardFacet.createAppEngineFacetRuntime(AppEngineStandardFacet.java:424)
	at com.google.cloud.tools.eclipse.appengine.facets.AppEngineStandardFacet.installAllAppEngineRuntimes(AppEngineStandardFacet.java:381)
	at com.google.cloud.tools.eclipse.appengine.facets.StandardFacetInstallDelegate$AppEngineRuntimeInstallJob.run(StandardFacetInstallDelegate.java:112)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 8.92 sec - in com.google.cloud.tools.eclipse.appengine.validation.XsltSourceQuickFixTest
testApply(com.google.cloud.tools.eclipse.appengine.validation.XsltSourceQuickFixTest)  Time elapsed: 8.774 sec
Running com.google.cloud.tools.eclipse.appengine.validation.XsltQuickFixTest
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x40037a (User Opera)
Window manager warning: meta_window_activate called by a pager with a 0 timestamp; the pager needs to be fixed.
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x400021 (data - Res)
Window manager warning: meta_window_activate called by a pager with a 0 timestamp; the pager needs to be fixed.
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x4003a5 (File Not A)
Window manager warning: meta_window_activate called by a pager with a 0 timestamp; the pager needs to be fixed.
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x400021 (data - Res)
Window manager warning: meta_window_activate called by a pager with a 0 timestamp; the pager needs to be fixed.
[ERROR] Timeout 600 s exceeded. Process was killed.
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building com.google.cloud.tools.eclipse.appengine.ui.test 0.1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
```

**Comment by diegomarquezp** [comment]
Closing as not planned. cc: @blakeli0
