### ISSUE TITLE
Internal error ('Update Hierarchy') when creating new New Dataflow Pipeline launch configuration

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#2223]
Seen on 1.3.0 RC1.

Steps to repeat:
  1. Open launch configurations page (_Run >   Debug Configurations…_)
  2. Select _Dataflow Pipeline_ type.  Click on the _New_ button.
  3. See the error popup.

<img width="686" alt="screen shot 2017-08-02 at 3 47 44 pm" src="https://user-images.githubusercontent.com/202851/28892133-d9265b7c-779a-11e7-8250-658dcda76b3f.PNG">

Error logged to console:
```
!ENTRY org.eclipse.core.jobs 4 2 2017-08-02 15:47:36.594
!MESSAGE An internal error occurred during: "Update Hierarchy".
!STACK 0
java.lang.IllegalArgumentException: Tried to create a TypeHierarchyPipelineOptionsHierarchy for a Java Project where no PipelineOptions type exists
	at com.google.cloud.tools.eclipse.dataflow.core.launcher.options.JavaProjectPipelineOptionsHierarchy.<init>(JavaProjectPipelineOptionsHierarchy.java:72)
	at com.google.cloud.tools.eclipse.dataflow.core.launcher.ClasspathPipelineOptionsHierarchyFactory.forProject(ClasspathPipelineOptionsHierarchyFactory.java:54)
	at com.google.cloud.tools.eclipse.dataflow.ui.launcher.PipelineArgumentsTab.getPipelineOptionsHierarchy(PipelineArgumentsTab.java:369)
	at com.google.cloud.tools.eclipse.dataflow.ui.launcher.PipelineArgumentsTab.access$6(PipelineArgumentsTab.java:364)
	at com.google.cloud.tools.eclipse.dataflow.ui.launcher.PipelineArgumentsTab$3.run(PipelineArgumentsTab.java:348)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
```

**Comment by chanseokoh** [comment]
I see the reason. This happens when a project selected is not a Dataflow project (when it cannot find a type `PipelineOptions`, to be specific).
