### ISSUE TITLE
GCS client library requires the App Engine API library

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#2350]
and it's not added automatically. I.e. it's not listed as a dependency in plugin.xml. Typical symptoms are when running locally

```
HTTP ERROR 500

Problem accessing /hello. Reason:

    Server Error
Caused by:

java.lang.RuntimeException: Google App Engine runtime detected (the environment variable "com.google.appengine.runtime.version" is set), but unable to resolve appengine-sdk classes. For more details see https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/APPENGINE.md
	at com.google.cloud.ServiceOptions.getAppEngineProjectId(ServiceOptions.java:398)
	at com.google.cloud.ServiceOptions.getDefaultProjectId(ServiceOptions.java:306)
	at com.google.cloud.ServiceOptions.getDefaultProject(ServiceOptions.java:284)
	at com.google.cloud.ServiceOptions.<init>(ServiceOptions.java:238)
	at com.google.cloud.storage.StorageOptions.<init>(StorageOptions.java:82)
	at com.google.cloud.storage.StorageOptions.<init>(StorageOptions.java:30)
	at com.google.cloud.storage.StorageOptions$Builder.build(StorageOptions.java:77)
	at com.google.cloud.storage.StorageOptions.getDefaultInstance(StorageOptions.java:128)
	at HelloAppEngine.doGet(HelloAppEngine.java:22)
```

**Comment by elharo** [comment]
FYI I think this is a case where the Maven dependency graph is incomplete, but I need to conform that. I.e. Eclipse needs to add this library dependency explicitly.

**Comment by elharo** [comment]
Yep, maven graph does not include this one. This means our eventual solution needs an option for us to include deps the Maven tree doesn't find.

**Comment by patflynn** [comment]
the app engine SDK is provided at runtime by the app engine environment.

**Comment by chanseokoh** [comment]
It seems like App Engine Standard Java 7 still needs the appengine-api SDK dependency to make `getProjectId()` (or `getAppEngineProjectId()`?) work, according to the following instructions:

https://github.com/GoogleCloudPlatform/google-cloud-java/commit/7a310c47d19dcfe71966276fe18a20914f332192
https://github.com/GoogleCloudPlatform/google-cloud-java/commit/f9f55bba7937305620e81126fc79921181a17ee3

**Comment by chanseokoh** [comment]
In my testing, the appengine-api SDK is not required on prod, regardless of Standard Java 7 or 8. Required only for the local dev sever.

**Comment by chanseokoh** [comment]
I verified that the Datastore library and the translate library also needs the App Engine API library for the same reason for local dev.
