### ISSUE TITLE
Can't create dataflow project 

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#2353]
Dataflow project creation failed in the release version with no message except in the error log. Both 1.9.1 and 2.1.0.

- Cloud Tools for Eclipse version: 1.3.0

```
eclipse.buildId=4.7.0.I20170612-0950
java.version=1.8.0_131
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.java.product -keyring /Users/elharo/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -product org.eclipse.epp.package.java.product -keyring /Users/elharo/.eclipse_keyring

org.eclipse.m2e.core
Error
Tue Sep 05 15:39:14 EDT 2017
Could not resolve archetype com.google.cloud.dataflow:google-cloud-dataflow-java-archetypes-starter:1.9.1 from any of the configured repositories.

org.eclipse.core.runtime.CoreException: Could not resolve artifact com.google.cloud.dataflow:google-cloud-dataflow-java-archetypes-starter:pom:1.9.1
	at org.eclipse.m2e.core.internal.embedder.MavenImpl$5.call(MavenImpl.java:776)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl$5.call(MavenImpl.java:1)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.resolve(MavenImpl.java:743)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.resolve(MavenImpl.java:720)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.resolveArchetype(ProjectConfigurationManager.java:902)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.createArchetypeProjects0(ProjectConfigurationManager.java:816)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$5.call(ProjectConfigurationManager.java:791)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$5.call(ProjectConfigurationManager.java:1)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1355)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.createArchetypeProjects(ProjectConfigurationManager.java:789)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.createArchetypeProjects(ProjectConfigurationManager.java:775)
	at com.google.cloud.tools.eclipse.dataflow.core.project.DataflowProjectCreator.run(DataflowProjectCreator.java:235)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
Contains: Missing com.google.cloud.dataflow:google-cloud-dataflow-java-archetypes-starter:pom:1.9.1
```

```
eclipse.buildId=4.7.0.I20170612-0950
java.version=1.8.0_131
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.java.product -keyring /Users/elharo/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -product org.eclipse.epp.package.java.product -keyring /Users/elharo/.eclipse_keyring

org.eclipse.equinox.p2.metadata.repository
Error
Tue Sep 05 15:51:26 EDT 2017
No repository found at http://download.eclipse.org/technology/m2e/releases-for-indigo/1.4/.
```

**Comment by chanseokoh** [comment]
> `No repository found at http://download.eclipse.org/technology/m2e/releases-for-indigo/1.4/`

It seems off to see the Indigo version in the log.

**Comment by chanseokoh** [comment]
This is happening at `master/HEAD` too.

**Comment by chanseokoh** [comment]
This is because new versions of Dataflow v1 and v2 were released recently. 

![selection_002](https://user-images.githubusercontent.com/10523105/30082841-32531c10-925a-11e7-9679-dc637e639a77.png)

![selection_001](https://user-images.githubusercontent.com/10523105/30082887-6715838e-925a-11e7-8e35-d7939b3a4c8a.png)

Previously, the dropdown listed "2.0.0" and "1.9.0", which matched the versions of the sample project archetypes.

It is not immediately clear if we can continue to use the "2.0.0" (and "1.9.0") archetype with Dataflow >= "2.1.0" (and >= "1.9.1"), or if the Dataflow team should release new sample archetypes corresponding to the new Dataflow SDK releases. In any case, the solution should be future-proof when more newer SDK are released. @tgroh?

**Comment by chanseokoh** [comment]
For now as a stop-gap, I'll let the wizard use "2.0.0" (and "1.9.0") samples for all Dataflow SDK v2 (and v1) versions, as the samples seem to work at least with the recent new SDK releases. However, I'm still waiting for @tgroh's answer for clarification.

**Comment by chanseokoh** [comment]
I realized the Dataflow SDK versions are explicitly stated in sample archetypes. Since we have only the 2.0.0 and 1.9.0 sample archetypes, we are stuck with 2.0.0 and 1.9.0 SDK versions. Therefore, for now, we should hardcode 2.0.0 and 1.9.0 in the Dataflow version selection combo box in the wizard.

In the current design that we use archetypes for sample generation, we need new archetypes whenever new SDK versions are released. Maybe existing archetypes could be parameterized to some extent.

**Comment by elharo** [comment]
Agreed. Let's hardcode the 2.0.0 and 1.9.0 versions, and if nothing else critical is outstanding I'll start cutting a release on Thursday.
