### ISSUE TITLE
Flaky RunOptionsDefaultsComponentTest

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#2378]
Seen this twice on Kokoro today. The offending assertion was added into an existing test in #2375.

```
testEnablement_existingStagingLocation(com.google.cloud.tools.eclipse.dataflow.ui.preferences.RunOptionsDefaultsComponentTest)  Time elapsed: 0.094 sec  <<< FAILURE!
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.google.cloud.tools.eclipse.dataflow.ui.preferences.RunOptionsDefaultsComponentTest.testEnablement_existingStagingLocation(RunOptionsDefaultsComponentTest.java:264)
```

**Comment by chanseokoh** [comment]
Also happens on Travis.

**Comment by briandealwis** [comment]
Annoying.  I'm actively improving these tests with #2362, but I should be able to avoid this by manually invoking `#validate()`.

**Comment by briandealwis** [comment]
`master` failed on `eclipse-mars` with:
```
testEnablement_selectedProject(com.google.cloud.tools.eclipse.dataflow.ui.preferences.RunOptionsDefaultsComponentTest)  Time elapsed: 0.075 sec  <<< FAILURE!
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.google.cloud.tools.eclipse.dataflow.ui.preferences.RunOptionsDefaultsComponentTest.testEnablement_selectedProject(RunOptionsDefaultsComponentTest.java:293)
```

**Comment by chanseokoh** [comment]
I saw this timeout error several times on Travis and Kokoro. At first I thought it could be a rare transient network error, but now this happens multiple times, we need to do something.

```
Running com.google.cloud.tools.eclipse.dataflow.ui.preferences.RunOptionsDefaultsComponentTest
Tests run: 18, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 33.69 sec <<< FAILURE! - in com.google.cloud.tools.eclipse.dataflow.ui.preferences.RunOptionsDefaultsComponentTest
testBucketNameStatus_gcsUrlPathWithObjectIsOk(com.google.cloud.tools.eclipse.dataflow.ui.preferences.RunOptionsDefaultsComponentTest)  Time elapsed: 31.072 sec  <<< ERROR!
org.eclipse.swtbot.swt.finder.widgets.TimeoutException: Timeout after: 30000 ms.: RuntimeOptions project was never resolved
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:522)
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:496)
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:484)
	at com.google.cloud.tools.eclipse.dataflow.ui.preferences.RunOptionsDefaultsComponentTest.waitUntilResolvedProject(RunOptionsDefaultsComponentTest.java:470)
	at com.google.cloud.tools.eclipse.dataflow.ui.preferences.RunOptionsDefaultsComponentTest.testBucketNameStatus_gcsUrlPathWithObjectIsOk(RunOptionsDefaultsComponentTest.java:408)
```

**Comment by chanseokoh** [comment]
> _If_ I remember correctly, this is always `testBucketNameStatus_gcsUrlPathWithObjectIsOk`.

No, the timeout can happen in other places.

```
Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 30.47 sec <<< FAILURE! - in com.google.cloud.tools.eclipse.projectselector.MiniSelectorTest
testListenerFired(com.google.cloud.tools.eclipse.projectselector.MiniSelectorTest)  Time elapsed: 30.323 sec  <<< ERROR!
org.eclipse.swtbot.swt.finder.widgets.TimeoutException: Timeout after: 30000 ms.: MiniSelector project was never resolved
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:437)
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:411)
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:399)
	at com.google.cloud.tools.eclipse.projectselector.MiniSelectorTest.waitUntilResolvedProject(MiniSelectorTest.java:124)
	at com.google.cloud.tools.eclipse.projectselector.MiniSelectorTest.testListenerFired(MiniSelectorTest.java:112)
```

**Comment by briandealwis** [comment]
I see it a log with `RunOptionsDefaultsComponentTest#testPartialValidity_account_project`.  These all boil down to the  use of `ProjectProvider#resolve(projectId,callback)` which waits for the current projects-list request to complete and then sets the selection.  This is required to select a particular project (e.g., restoring from preferences) and to preserve the selected project if the credential changes and the new credential can still access the previously-selected project.  From the logs, it seems that somehow the ComboViewer's input is being changed to `null`.

(This feels like it will be a :facepalm: 🤦‍♂️ moment.)

I'm reworking the other tests to take a mock ProjectProvider that doesn't issue jobs to make these tests more predictable.

**Comment by briandealwis** [comment]
Oh, I think this is what happens:
  1. A new credential is supplied to `MiniSelector#setCredential()`, resulting in an `inputChanged()` and triggering a fetch-project-list, with a callback to refresh the `MiniSelector`'s `ComboViewer` on completion.
  2. The project name is supplied to `MiniSelector#setProject()`, which adds a callback on the fetch-project-list to set the selection to the resolved project on completion

And the second is somehow occurring before the first, or the combo items aren't quite set so the selection is discarded.

Unfortunately `ComboViewer` doesn't support lazy content providers…

**Comment by briandealwis** [comment]
Saw another:
```
testBucketNameStatus_gcsPathWithObjectIsOk(com.google.cloud.tools.eclipse.dataflow.ui.preferences.RunOptionsDefaultsComponentTest)  Time elapsed: 30.067 sec  <<< ERROR!
org.eclipse.swtbot.swt.finder.widgets.TimeoutException: Timeout after: 30000 ms.: RuntimeOptions project was never resolved
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:437)
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:411)
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:399)
	at com.google.cloud.tools.eclipse.dataflow.ui.preferences.RunOptionsDefaultsComponentTest.waitUntilResolvedProject(RunOptionsDefaultsComponentTest.java:470)
	at com.google.cloud.tools.eclipse.dataflow.ui.preferences.RunOptionsDefaultsComponentTest.testBucketNameStatus_gcsPathWithObjectIsOk(RunOptionsDefaultsComponentTest.java:398)
```

**Comment by briandealwis** [comment]
The branch was missing the fix from #2412.

**Comment by chanseokoh** [comment]
The Kokoro build at commit https://github.com/GoogleCloudPlatform/google-cloud-eclipse/pull/2409/commits/183d80127467425df97e3382268b39b254898d6e (with the commit message of "libraryFile occurs at least once") in #2409 failed with the following error. The commit contains #2412.

```
testEnablement_selectedProject(com.google.cloud.tools.eclipse.dataflow.ui.preferences.RunOptionsDefaultsComponentTest)  Time elapsed: 0.563 sec  <<< FAILURE!
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.google.cloud.tools.eclipse.dataflow.ui.preferences.RunOptionsDefaultsComponentTest.testEnablement_selectedProject(RunOptionsDefaultsComponentTest.java:286)
```

**Comment by chanseokoh** [comment]
Oh, a Travis build in #2412 also failed in the same test: https://travis-ci.org/GoogleCloudPlatform/google-cloud-eclipse/jobs/279050305

**Comment by chanseokoh** [comment]
```
testEnablement_existingStagingLocation(com.google.cloud.tools.eclipse.dataflow.ui.preferences.RunOptionsDefaultsComponentTest)  Time elapsed: 0.181 sec  <<< FAILURE!
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.google.cloud.tools.eclipse.dataflow.ui.preferences.RunOptionsDefaultsComponentTest.testEnablement_existingStagingLocation(RunOptionsDefaultsComponentTest.java:320)
```

**Comment by chanseokoh** [comment]
This is a new one.
```
testAccountSelector_loadBucketCombo(com.google.cloud.tools.eclipse.dataflow.ui.preferences.RunOptionsDefaultsComponentTest)  Time elapsed: 30.092 sec  <<< ERROR!
org.eclipse.swtbot.swt.finder.widgets.TimeoutException: Timeout after: 30000 ms.: missing staging buckets
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:437)
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:411)
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:399)
	at com.google.cloud.tools.eclipse.dataflow.ui.preferences.RunOptionsDefaultsComponentTest.assertStagingLocationCombo(RunOptionsDefaultsComponentTest.java:371)
	at com.google.cloud.tools.eclipse.dataflow.ui.preferences.RunOptionsDefaultsComponentTest.testAccountSelector_loadBucketCombo(RunOptionsDefaultsComponentTest.java:362)
```

**Comment by chanseokoh** [comment]
I am monitoring Kokoro builds today. Saw https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/2378#issuecomment-331753903 and https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/2378#issuecomment-332985245 a few times on very recent Kokoro builds.

**Comment by chanseokoh** [comment]
Found a way to always reproduce https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/2378#issuecomment-332985245 (testAccountSelector_loadBucketCombo).

- Simulate a slow project fetching job:
```diff
@@ -221,6 +222,7 @@ public class MiniSelector implements ISelectionProvider {
     }
   }
 
+  public static Semaphore DEBUG_projectFetchJobBlocker;
   /**
    * Simple job for fetching projects accessible to the current account.
    */
@@ -234,6 +236,8 @@ public class MiniSelector implements ISelectionProvider {
 
     @Override
     protected GcpProject[] compute(IProgressMonitor monitor) throws Exception {
+      if (DEBUG_projectFetchJobBlocker != null) DEBUG_projectFetchJobBlocker.acquireUninterruptibly();
+
       List<GcpProject> projects = projectRepository.getProjects(credential);
       return projects.toArray(new GcpProject[projects.size()]);
     }
```
- Let the project fetching job finish at the following point. `projectInput.join()` will ensure firing a staging location fetch job. We'll simulate a slow staging location fetch going forward too.
```diff
@@ -581,6 +582,11 @@ public class RunOptionsDefaultsComponent {
     if (checkProjectConfigurationJob != null) {
       checkProjectConfigurationJob.join();
     }
+
+    if (MiniSelector.DEBUG_projectFetchJobBlocker != null) {
+      MiniSelector.DEBUG_projectFetchJobBlocker.release();
+      FetchStagingLocationsJob.DEBUG_fetchStagingLocationsJobBlocker = new Semaphore(0);
+    }
     projectInput.join();
   }
 }
```
- Simulate a slow staging location fetching job that is triggered by the completion of the project fetching job above:
```diff
@@ -46,8 +48,11 @@ public class FetchStagingLocationsJob extends FuturisticJob<SortedSet<String>> {
     return cloudProjectId;
   }
 
+  public static Semaphore DEBUG_fetchStagingLocationsJobBlocker;
   @Override
   protected SortedSet<String> compute(IProgressMonitor monitor) throws Exception {
+    if (DEBUG_fetchStagingLocationsJobBlocker != null)
+      DEBUG_fetchStagingLocationsJobBlocker.tryAcquire(5, TimeUnit.SECONDS);
     return gcsClient.getPotentialStagingLocations(cloudProjectId);
   }
 }
```
- Now, enable simulation:
```diff
@@ -366,14 +368,15 @@ public class RunOptionsDefaultsComponentTest {
 
   @Test
   public void testAccountSelector_loadBucketCombo() {
+    MiniSelector.DEBUG_projectFetchJobBlocker = new Semaphore(0);
     selector.selectAccount("alice@example.com");
     component.setCloudProjectText("project");
     join();
     assertStagingLocationCombo("gs://alice-bucket-1", "gs://alice-bucket-2");
 
-    selector.selectAccount("bob@example.com");
-    join();
-    assertStagingLocationCombo("gs://bob-bucket");
+//    selector.selectAccount("bob@example.com");
+//    join();
+//    assertStagingLocationCombo("gs://bob-bucket");
   }
 
   private void assertStagingLocationCombo(final String... buckets) {
```

**Comment by chanseokoh** [comment]
Observed this in one of recent Kokoro runs. It's not the first time (https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/2378#issuecomment-330934190), but we hadn't actually logged the exception in this issue.

```
testPartialValidity_account_project(com.google.cloud.tools.eclipse.dataflow.ui.preferences.RunOptionsDefaultsComponentTest)  Time elapsed: 0.062 sec  <<< FAILURE!
java.lang.AssertionError: should be complete with account and project
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.google.cloud.tools.eclipse.dataflow.ui.preferences.RunOptionsDefaultsComponentTest.testPartialValidity_account_project(RunOptionsDefaultsComponentTest.java:452)
```

**Comment by chanseokoh** [comment]
https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/2378#issuecomment-331753903 (`testEnablement_selectedProject`) is reproducible with a similar way. Set up the same way as https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/2378#issuecomment-351155572, but simulate slow `GcpProjectServicesJob` instead of `FetchStagingLocationsJob`.

```diff
@@ -73,9 +75,12 @@ public class GcpProjectServicesJob extends FuturisticJob<List<String>> {
     return credential;
   }
 
+  public static Semaphore DEBUG_gcpProjectServicesJobBlocker;
   @Override
   protected List<String> compute(IProgressMonitor monitor)
-      throws GoogleJsonResponseException, IOException {
+      throws GoogleJsonResponseException, IOException, InterruptedException {
+    if (DEBUG_gcpProjectServicesJobBlocker != null)
+      DEBUG_gcpProjectServicesJobBlocker.tryAcquire(5, TimeUnit.SECONDS);
     String projectId = this.projectId;
     ServiceManagement serviceManagement = apiFactory.newServiceManagementApi(credential);
     ListServicesResponse response = null;
```

The fix #2672 will eliminate these two cases.

**Comment by chanseokoh** [comment]
https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/2378#issuecomment-351186875 can simulate https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/2378#issuecomment-351182009 (`testPartialValidity_account_project`) too. So, hopefully, #2672 will fix everything.

**Comment by briandealwis** [comment]
Good detective work! 🔍

**Comment by briandealwis** [comment]
Closing as we haven't seen this for a while.
