### ISSUE TITLE
Flaky MiniSelectorTest on Kokoro

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#2393]
```
testWithCredential(com.google.cloud.tools.eclipse.projectselector.MiniSelectorTest)  Time elapsed: 0.046 sec  <<< FAILURE!
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at org.junit.Assert.assertFalse(Assert.java:74)
	at com.google.cloud.tools.eclipse.projectselector.MiniSelectorTest.testWithCredential(MiniSelectorTest.java:77)
```

**Comment by chanseokoh** [comment]
Okay, I see this happened twice on Kokoro.

**Comment by chanseokoh** [comment]
Dup of #2394.
