### ISSUE TITLE
Staging fails to publish external and other project dependencies

### ISSUE THREAD

**Issue by edwineve** [GoogleCloudPlatform/google-cloud-eclipse#2426]
- Cloud Tools for Eclipse version: 1.3.1.201709121426
- Google Cloud SDK version: 172.0.1
- OS:OSX 10.12.6 
- Java version:1.7.0_60

**What did you do?**
As i am trying to upgrade from the old google appengine plugin to google cloud tools, i try to deploy a webproject that has a dependency on another (plain java) project in eclipse using the "deploy to appengine standard" button

**What did you expect to see?**
deployment

**What did you see instead?**
/var/folders/yg/lqfxnjzx2hx54z1609vl5fb80000gn/T/1506502634400-0/org/apache/jsp/WEB_002dINF/jsp/contact_002dselection/page_002dtop_jsp.java:15: error: package nl.anp.aps.entities does not exist
import nl.anp.aps.entities.User;
                          ^
6 errors
Unable to stage app: Failed to compile the generated JSP java files.

Note: 
- the missing imports are from the dependend java project
- deployment with the previous "google plugin for eclipse 4.4/4.5/4.6" worked fine. 
- mvn appengine:deploy also works ok
- i have no spaces in my gcloud sdk path

**Comment by elharo** [comment]
Interesting. I can sort of guess how that might happen. We'll look into it.

**Comment by briandealwis** [comment]
> mvn appengine:deploy also works ok

So this is a Maven project?  Could you please provide us a sketch of your POMs?

**Comment by edwineve** [comment]
a sketch like this?

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>bla-bla</groupId>
  <artifactId>bla-bla</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <packaging>war</packaging>
  <properties>
		<gae.version>1.9.56</gae.version>
	</properties>
<dependencies>
......
      	<dependency>
  		<groupId>bla-bla</groupId>
  		<artifactId>dependend-eclipse-project</artifactId>
  		<version>0.0.1-SNAPSHOT</version>
  	</dependency>
....

**Comment by elharo** [comment]
This is not just deploy. It's also local run, and it's easy to repro:

1. Use wizard to create a Hello World project.
2. Create a new Java project in Eclipse with a simple utility class like this:

```
package com.foo;

public class BarUtility {

	public static String getMessage() {
		return "Hi There";
	}
	
}
```

3. Modify the HelloWorld code to call this utility class:

```
  public void doGet(HttpServletRequest request, HttpServletResponse response) 
      throws IOException {
      
    response.setContentType("text/plain");
    response.setCharacterEncoding("UTF-8");

    String message = BarUtility.getMessage();
    response.getWriter().print("Hello App Engine!\r\n");
  }
```

4. Fix project setup HelloWorld.java compiles. The quick fix works.
5. Local run and try to load the servlet:

```
WARNING: Error for /hello
java.lang.NoClassDefFoundError: com/foo/BarUtility
	at HelloAppEngine.doGet(HelloAppEngine.java:18)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at com.google.appengine.api.socket.dev.DevSocketFilter.doFilter(DevSocketFilter.java:74)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.tools.development.ResponseRewriterFilter.doFilter(ResponseRewriterFilter.java:134)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.tools.development.HeaderVerificationFilter.doFilter(HeaderVerificationFilter.java:34)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.api.blobstore.dev.ServeBlobFilter.doFilter(ServeBlobFilter.java:63)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:48)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.tools.development.StaticFileFilter.doFilter(StaticFileFilter.java:122)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.tools.development.DevAppServerModulesFilter.doDirectRequest(DevAppServerModulesFilter.java:366)
	at com.google.appengine.tools.development.DevAppServerModulesFilter.doDirectModuleRequest(DevAppServerModulesFilter.java:349)
	at com.google.appengine.tools.development.DevAppServerModulesFilter.doFilter(DevAppServerModulesFilter.java:116)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at com.google.appengine.tools.development.DevAppEngineWebAppContext.handle(DevAppEngineWebAppContext.java:95)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at com.google.appengine.tools.development.JettyContainerService$ApiProxyHandler.handle(JettyContainerService.java:508)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:409)
	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
Caused by: java.lang.ClassNotFoundException: com.foo.BarUtility
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at com.google.appengine.tools.development.IsolatedAppClassLoader.loadClass(IsolatedAppClassLoader.java:195)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 38 more
```

**Comment by elharo** [comment]
Not sure exactly how to deal with this, but I suspect `WarPublisher` is not finding and publishing dependencies in other projects.

**Comment by elharo** [comment]
And a separate but related bug. If I remove LibraryProject from my build path, then export the project as a jar to the file system, then add the jar to the build path, local run fails in exactly the same way. I.e. we're not exporting the referenced libraries container:

![image](https://user-images.githubusercontent.com/1005544/30916910-9a351f12-a368-11e7-8fd6-0a4d64499bdf.png)

**Comment by briandealwis** [comment]
@elharo We can reference native Java projects, but the war project has to be set up to pull in the project as an output `.jar` using the _Properties > Deployment Assembly > Add… > Project_.  

<img width="859" alt="screen shot 2017-09-27 at 12 03 41 pm" src="https://user-images.githubusercontent.com/202851/30924169-fb9d104e-a37b-11e7-910e-56270c5c01a6.PNG">

This should be auto-configured providing you're using m2e-wtp.  @edwineve could you confirm that you're using m2e-wtp?

**Comment by chanseokoh** [comment]
> This should be auto-configured providing you're using m2e-wtp. @edwineve could you confirm that you're using m2e-wtp?

Exactly. It should work as long as you have set up the deploy assembly (the screenshot above) correctly. m2e-wtp should probably auto-configure it. If it is not set up correctly for any reason, you can fix the configuration manually.

**Comment by elharo** [comment]
Note that I was able to reproduce this in a non-Maven project, so even if that works there's something to do here.

**Comment by edwineve** [comment]
my deployment assembly looks like this, configured automatically:

<img width="862" alt="screen shot 2017-09-27 at 19 42 14" src="https://user-images.githubusercontent.com/32326065/30928529-27526758-a3bc-11e7-92cf-1423d341e71b.png">

**Comment by chanseokoh** [comment]
I can reproduce this for a Maven project. Running locally on the dev appserver works fine, but for some unknown reason, WTP isn't placing the JAR from an external project into `WEB-INF/lib`.

**Comment by chanseokoh** [comment]
As is with the case of a web fragment, a dependent project is a child module of the root module:

![selection_012](https://user-images.githubusercontent.com/10523105/30930984-5f88d04c-a391-11e7-9d63-4680da457730.png)

We need to include this kind of child modules here:

```java

  private static IModuleResource[] flattenResources(...) ... {
    ...
    IModule[] modules = ServerUtil.getModules(project);
    for (IModule module : modules) {
      ModuleDelegate delegate = ...;
      ...

      // module references can either be as members or child modules (http://eclip.se/467759)
      Collections.addAll(resources, delegate.members());

      // now handle web fragment child modules, if they exist
      for (IModule child : delegate.getChildModules()) {
        ModuleDelegate childDelegate = (ModuleDelegate)
            child.loadAdapter(ModuleDelegate.class, monitor);
        IWebFragmentModule webFragmentModule = (IWebFragmentModule)
            child.loadAdapter(IWebFragmentModule.class, monitor);
        if (childDelegate == null || webFragmentModule == null || !webFragmentModule.isBinary()) {
          logger.log(Level.WARNING, "child modules other than binary web-fragments are not "
              + "supported: module=" + module + ", moduleType=" + module.getModuleType());
          //////////////////////////////////////////////////////////
          // We assumed we only expect a web fragment module, but
          // a dependent project can also be a child module.
          //////////////////////////////////////////////////////////
          continue;
        }
```

**Comment by chanseokoh** [comment]
BTW, the logging statement above should log the child module, but the root module (`module` should be `child`):

```java
logger.log(Level.WARNING, "child modules other than binary web-fragments are not "
    + "supported: module=" + module + ", moduleType=" + module.getModuleType());
```

The child module type in this error case is "jst.utility":
`WARNING: child modules other than binary web-fragments are not supported: module=Module[com.example.simple-dep-0.0.1-SNAPSHOT,org.eclipse.jst.j2ee.server:com.example.simple-dep-0.0.1-SNAPSHOT], moduleType=ModuleType[jst.utility, 1.0]`

**Comment by chanseokoh** [comment]
We flatten out child modules first (although we deal only with web fragments currently). That is, if there is a child web fragment, we augment the resources list of the root module so that the list contains the web fragment JAR. Then, we hand over the computed list to `PublishHelper.pubishFull()`. We try to fix up the list to be complete so that a one-time `publishFull()` includes the web fragment.

Now I think this approach feels like a hack, after noticing that a utility module ("jst.utility") may not be a binary.
```java
          IUtilityModule utilityModule = (IUtilityModule) child.loadAdapter(IUtilityModule.class, monitor);
          System.out.println("isBinary? " + utilityModule.isBinary());
          System.out.println("Destination: " + delegate.getPath(child));
          for (IModuleResource resource : childDelegate.members()) {
            System.out.println("Resource: " resource);
```
The code outputs
```
isBinary? false
Destination: WEB-INF/lib/simple-dep-0.0.1-SNAPSHOT.jar
Resource: META-INF
Resource: SimpleThing.class
```
That is, we get a list of resources for the child utility module, and we need to zip them and put it at the destination. I feel that this process is actually another publishing task. In other words, I think we should publish child modules as we would normally do with the root module (the main app to be deployed) using the `PublishHelper`.

**Comment by elharo** [comment]
This may be a general WTP issue.

**Comment by chanseokoh** [comment]
Got this fixed with a much more improved and simpler way. I'll put up a PR on Monday.

**Comment by chanseokoh** [comment]
Unfortunately, could have been simpler if it were not for the flex deploys requiring a zipped archive.

**Comment by edwineve** [comment]
Thanks for fixing! Any estimate when there will be a new release with the bugfix?
