### ISSUE TITLE
Entering absolute path or path outside project in flex deploy dialog does not work

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#2438]
![selection_004](https://user-images.githubusercontent.com/10523105/31024776-24f839b2-a50e-11e7-8f31-7f1ed0d7df87.png)

If users use the _Browse..._ button, the field will be automatically filled with a project-relative path. No problem in this case.

However, users can still type an absolute path manually. If the file exists, they can proceed to deploy, and it should work.

```
Caused by: org.eclipse.core.runtime.CoreException: L/flex/usr/local/home/user/yaml_files/app.yaml does not exist.
	at com.google.cloud.tools.eclipse.appengine.deploy.ui.flexible.FlexDeployCommandHandler.getStagingDelegate(FlexDeployCommandHandler.java:59)
	at com.google.cloud.tools.eclipse.appengine.deploy.ui.DeployCommandHandler.launchDeployJob(DeployCommandHandler.java:162)
	at com.google.cloud.tools.eclipse.appengine.deploy.ui.DeployCommandHandler.execute(DeployCommandHandler.java:99)
	... 45 more
```

Also, I believe entering an `app.yaml` path that is outside the project to be deployed is currently not supported. It will probably throw an error too. We can make it work too.

**Comment by elharo** [comment]
This is for existing flex WAR deployments? Not just jar deployments?

**Comment by chanseokoh** [comment]
This is for the existing flex. The new global WAR/JAR deployments (that I am working on now) isn't going to have this problem. (I already made it work.)
