### ISSUE TITLE
Dataflow wizard stopped working again

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#2478]
Could not resolve artifact com.google.cloud.dataflow:google-cloud-dataflow-java-archetypes-starter:pom:2.1.0

This is at head.

Here's the exception. Otherwise silent failure:

```
Caused by: org.eclipse.core.runtime.CoreException: Could not resolve artifact com.google.cloud.dataflow:google-cloud-dataflow-java-archetypes-starter:pom:2.1.0
	at org.eclipse.m2e.core.internal.embedder.MavenImpl$5.call(MavenImpl.java:776)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl$5.call(MavenImpl.java:1)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.resolve(MavenImpl.java:743)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.resolve(MavenImpl.java:720)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.resolveArchetype(ProjectConfigurationManager.java:870)
	... 10 more
```

**Comment by elharo** [comment]
Archetype seems to exist:

https://search.maven.org/#artifactdetails%7Ccom.google.cloud.dataflow%7Cgoogle-cloud-dataflow-java-archetypes-starter%7C2.1.0%7Cmaven-archetype

Maybe the pom?

**Comment by elharo** [comment]
Example pipelines works. It's only the starter project that fails.

**Comment by elharo** [comment]
At the command line the archetype works:

```
[INFO] Project created from Archetype in dir: /Users/elharo/tmp/first-dataflow
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.908 s
[INFO] Finished at: 2017-10-12T08:23:20-04:00
[INFO] Final Memory: 15M/181M
[INFO] ------------------------------------------------------------------------
elharo-macbookair99:tmp elharo$ mvn archetype:generate       -DarchetypeArtifactId=google-cloud-dataflow-java-archetypes-starter       -DarchetypeGroupId=com.google.cloud.dataflow       -DarchetypeVersion=2.1.0       -DgroupId=com.example       -DartifactId=first-dataflow       -Dversion="0.1"       -DinteractiveMode=false       -Dpackage=com.example
```

**Comment by elharo** [comment]
And in the debugger it just worked. I'm not sure what I changed.

**Comment by elharo** [comment]
Seems to be working reliably now. maybe some temporary glitch in the Maven repo? At the least we need to better message this to users. These are the lines where the failure occurs:

```
      try {
        projects = projectConfigurationManager.createArchetypeProjects(location, archetype,
            // TODO: Get the version string from the user as well.
            mavenGroupId, mavenArtifactId, "0.0.1-SNAPSHOT", packageString, archetypeProperties,
            projectImportConfiguration, progress.newChild(4));
        break;
      } catch (CoreException e) {
        failures.add(e);
      }
    }
    if (projects.isEmpty()) {
      // todo need to message the user here
      for (CoreException failure : failures) {
        DataflowCorePlugin.logError(failure, "CoreException while creating new Dataflow Project");
      }
    }
```

We need to pop up a dialog here rather than simply logging the error.

**Comment by chanseokoh** [comment]
I get the same error repeatedly. My guess is that, once you have downloaded the artifact in your local repo by other means (e.g., on the command-line), the problem goes away?

**Comment by elharo** [comment]
May have been fixed by running the archetype from the command line. Need to verify.
