### ISSUE TITLE
Silent failures when resolving libraries

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#2491]
On 1.3.1.  I was trying to reproduce #2490 on CT4E 1.3.1, forgetting that I had rebooted and so my proxy server for Maven Central wasn't running.  I created a new AESv8 project and then attempted to configure the Google Cloud Storage library.  All seemed to go well, but the library wasn't found.  On the log I found the following stack trace.  We should indicate an error to the user in such situations.
```
!ENTRY org.eclipse.equinox.p2.transport.ecf 4 1002 2017-10-13 14:26:14.732
!MESSAGE Unable to connect to repository http://nexus.mt.ca:8081/nexus/content/repositories/eclipse-oxygen/content.xml
!STACK 0
java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:120)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:179)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:328)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:612)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:447)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:884)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.eclipse.ecf.provider.filetransfer.httpclient4.HttpClientFileSystemBrowser.runRequest(HttpClientFileSystemBrowser.java:263)
	at org.eclipse.ecf.provider.filetransfer.browse.AbstractFileSystemBrowser$DirectoryJob.run(AbstractFileSystemBrowser.java:69)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
```

**Comment by chanseokoh** [comment]
The log may be irrelevant for our debugging, and probably we will not be able to clear it. It is not from our code.

Have you tried this at HEAD? Is #2454 related?

**Comment by briandealwis** [comment]
Closing as I don't see this on HEAD.
