### ISSUE TITLE
Error when initializing legacy library containers if JARs (including source JARs) do not exist locally

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#2496]
`ImportNativeAppEngineStandardProjectTest` is failing. As the class comment says, it tests if we can import projects created by the 1.3.1 release.

```
 * Test that we can import packaged native applications from previous versions of Cloud Tools for
 * Eclipse.
```

As such, the zipped projects that are imported have separate library containers (i.e., not the single master container). I tried running the integration test 10 times or so, but it always fails.

On my desktop, it's always the AESv7 test that fails. On the other hand, on my laptop, it's always the AESv8.

AESv8 failure:
```
Failed tests:
  ImportNativeAppEngineStandardProjectTest.importAppEngineStandardJava8_from1_3_1:89 Imported App Engine standard Java 8 project has errors
  /AESv8:-1: Invalid classpath publish/export dependency <...>/.m2/repository/com/google/api/api-common/1.1.0/api-common-1.1.0.jar. The project contains another dependency with the same archive name.
  /AESv8:-1: Invalid classpath publish/export dependency <...>/.m2/repository/com/google/guava/guava/20.0/guava-20.0.jar. The project contains another dependency with the same archive name.
  /AESv8:-1: Invalid classpath publish/export dependency <...>/.m2/repository/com/google/http-client/google-http-client/1.22.0/google-http-client-1.22.0.jar. The project contains another dependency with the same archive name.
  /AESv8:-1: Invalid classpath publish/export dependency <...>/.m2/repository/com/google/http-client/google-http-client-appengine/1.22.0/google-http-client-appengine-1.22.0.jar. The project contains another dependency with the same archive name.
  /AESv8:-1: Invalid classpath publish/export dependency <...>/.m2/repository/com/google/http-client/google-http-client-jackson/1.22.0/google-http-client-jackson-1.22.0.jar. The project contains another dependency with the same archive name.
  /AESv8:-1: Invalid classpath publish/export dependency <...>/.m2/repository/com/google/http-client/google-http-client-jackson2/1.22.0/google-http-client-jackson2-1.22.0.jar. The project contains another dependency with the same archive name.
  /AESv8:-1: Invalid classpath publish/export dependency <...>/.m2/repository/com/google/oauth-client/google-oauth-client/1.22.0/google-oauth-client-1.22.0.jar. The project contains another dependency with the same archive name.
  /AESv8:-1: Invalid classpath publish/export dependency <...>/.m2/repository/joda-time/joda-time/2.9.2/joda-time-2.9.2.jar. The project contains another dependency with the same archive name.
  /AESv8:-1: Invalid classpath publish/export dependency <...>/.m2/repository/org/json/json/20160810/json-20160810.jar. The project contains another dependency with the same archive name.
  /AESv8:-1: Invalid classpath publish/export dependency <...>/.m2/repository/org/threeten/threetenbp/1.3.3/threetenbp-1.3.3.jar. The project contains another dependency with the same archive name.
  /AESv8:-1: Invalid classpath publish/export dependency <...>/.m2/repository/com/google/api-client/google-api-client/1.22.0/google-api-client-1.22.0.jar. The project contains another dependency with the same archive name.

Tests run: 22, Failures: 1, Errors: 0, Skipped: 0
```

Will update the AESv7 failure from my laptop, but basically, the same error.

**Comment by chanseokoh** [comment]
AESv7 failure on my laptop. I guess the same error.
```
Failed tests:
  ImportNativeAppEngineStandardProjectTest.importAppEngineStandardJava7_from1_3_1:63 Imported App Engine standard Java 7 project has errors
/AESv7:-1: Invalid classpath publish/export dependency /home/chanseok/.m2/repository/com/google/api/api-common/1.1.0/api-common-1.1.0.jar. The project contains another dependency with the same archive name.
/AESv7:-1: Invalid classpath publish/export dependency /home/chanseok/.m2/repository/com/google/guava/guava/20.0/guava-20.0.jar. The project contains another dependency with the same archive name.
/AESv7:-1: Invalid classpath publish/export dependency /home/chanseok/.m2/repository/com/google/http-client/google-http-client/1.22.0/google-http-client-1.22.0.jar. The project contains another dependency with the same archive name.
/AESv7:-1: Invalid classpath publish/export dependency /home/chanseok/.m2/repository/com/google/http-client/google-http-client-appengine/1.22.0/google-http-client-appengine-1.22.0.jar. The project contains another dependency with the same archive name.
/AESv7:-1: Invalid classpath publish/export dependency /home/chanseok/.m2/repository/com/google/http-client/google-http-client-jackson/1.22.0/google-http-client-jackson-1.22.0.jar. The project contains another dependency with the same archive name.
/AESv7:-1: Invalid classpath publish/export dependency /home/chanseok/.m2/repository/com/google/http-client/google-http-client-jackson2/1.22.0/google-http-client-jackson2-1.22.0.jar. The project contains another dependency with the same archive name.
/AESv7:-1: Invalid classpath publish/export dependency /home/chanseok/.m2/repository/com/google/oauth-client/google-oauth-client/1.22.0/google-oauth-client-1.22.0.jar. The project contains another dependency with the same archive name.
/AESv7:-1: Invalid classpath publish/export dependency /home/chanseok/.m2/repository/joda-time/joda-time/2.9.2/joda-time-2.9.2.jar. The project contains another dependency with the same archive name.
/AESv7:-1: Invalid classpath publish/export dependency /home/chanseok/.m2/repository/org/json/json/20160810/json-20160810.jar. The project contains another dependency with the same archive name.
/AESv7:-1: Invalid classpath publish/export dependency /home/chanseok/.m2/repository/org/threeten/threetenbp/1.3.3/threetenbp-1.3.3.jar. The project contains another dependency with the same archive name.
/AESv7:-1: Invalid classpath publish/export dependency /home/chanseok/.m2/repository/com/google/api-client/google-api-client/1.22.0/google-api-client-1.22.0.jar. The project contains another dependency with the same archive name.
```

**Comment by chanseokoh** [comment]
Something interesting.

AESv8 on my desktop has "Google Cloud Datastore", and it contains a lot of JARs.
![selection_019](https://user-images.githubusercontent.com/10523105/31628559-0f17c256-b27f-11e7-9d10-06dfcefdbe7b.png)
It includes, e.g., guava-20.0.jar, which conflicts with the same JAR in "Google Cloud Core Client Library for Java".

Now, on my laptop, AESv8 has a slight different container "Cloud Datastore Client Library for Java", which has only three JARs.
![selection_001](https://user-images.githubusercontent.com/10523105/31628708-88bbae9c-b27f-11e7-8137-77a82acd996a.png)

**Comment by briandealwis** [comment]
Sounds like #2481, doesn't it!

**Comment by briandealwis** [comment]
When I run locally on OS X, I hit errors in .deploy.tests:
```
Running com.google.cloud.tools.eclipse.appengine.deploy.flex.FlexMavenPackagedProjectStagingDelegateTest
Tests run: 5, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.315 sec <<< FAILURE! - in com.google.cloud.tools.eclipse.appengine.deploy.flex.FlexMavenPackagedProjectStagingDelegateTest
testCreateMavenPackagingLaunchConfiguration(com.google.cloud.tools.eclipse.appengine.deploy.flex.FlexMavenPackagedProjectStagingDelegateTest)  Time elapsed: 0.14 sec  <<< ERROR!
org.eclipse.core.runtime.CoreException: Project test0.9294576137242408 does not have JRE configured.
	at com.google.cloud.tools.eclipse.appengine.deploy.flex.FlexMavenPackagedProjectStagingDelegate.getJreContainerPath(FlexMavenPackagedProjectStagingDelegate.java:80)
	at com.google.cloud.tools.eclipse.appengine.deploy.flex.FlexMavenPackagedProjectStagingDelegate.createMavenPackagingLaunchConfiguration(FlexMavenPackagedProjectStagingDelegate.java:140)
	at com.google.cloud.tools.eclipse.appengine.deploy.flex.FlexMavenPackagedProjectStagingDelegateTest.testCreateMavenPackagingLaunchConfiguration(FlexMavenPackagedProjectStagingDelegateTest.java:62)

testWaitUntilLaunchTerminates_atLeastOneNonZeroExit(com.google.cloud.tools.eclipse.appengine.deploy.flex.FlexMavenPackagedProjectStagingDelegateTest)  Time elapsed: 0.01 sec
testJreContainerPath(com.google.cloud.tools.eclipse.appengine.deploy.flex.FlexMavenPackagedProjectStagingDelegateTest)  Time elapsed: 0.145 sec  <<< ERROR!
org.eclipse.core.runtime.CoreException: Project test0.7091517137483115 does not have JRE configured.
	at com.google.cloud.tools.eclipse.appengine.deploy.flex.FlexMavenPackagedProjectStagingDelegate.getJreContainerPath(FlexMavenPackagedProjectStagingDelegate.java:80)
	at com.google.cloud.tools.eclipse.appengine.deploy.flex.FlexMavenPackagedProjectStagingDelegateTest.testJreContainerPath(FlexMavenPackagedProjectStagingDelegateTest.java:51)
```

**Comment by chanseokoh** [comment]
We should open a separate issue for https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/2496#issuecomment-336992407.

**Comment by chanseokoh** [comment]
Steps to reproduce:

1. Just in case, delete all existing projects.
1. Delete `~/.m2/repository/com/google/cloud/datastore/datastore-v1-proto-client/`.
    - Make sure you don't accidentally download the library while doing this.
1. _Import..._ > _Existing Projects into Workspace_.
1. _Select archive file:_ > _Browse..._. Select `plugins/com.google.cloud.tools.eclipse.integration.appengine/test-projects/cte-1_3_1-appengine-standard-java8.zip` in our source repo. _Finish_.

**Comment by chanseokoh** [comment]
In `LibraryClasspathContainerInitializer.initialize`, when loading containers,

```java
      LibraryClasspathContainer container = serializer.loadContainer(...);
      if (container != null && jarPathsAreValid(container)) {
        JavaCore.setClasspathContainer(...)
      } else {
        resolverService.resolveContainer(project, containerPath, new NullProgressMonitor());
      }
```

if we find that the local .m2 repo has all the JARs defined in the JSON, we will just set the classpath container, and we're good. However, if any of the JARs do not exist, we call `resolveContainer()`, and this will load all transitive deps into the container. That's why we see a lot of JARs in https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/2496#issuecomment-336988439, leading to the export conflicts.

**Comment by chanseokoh** [comment]
I discovered that this also happens when restarting Eclipse (i.e., quit, delete some JARs, start again), but very interestingly, I don't get the same-name-JAR-export conflict this way.

**Comment by chanseokoh** [comment]
> I discovered that this also happens when restarting Eclipse (i.e., quit, delete some JARs, start again), but very interestingly, I don't get the same-name-JAR-export conflict this way.

Cleaning the project will trigger adding the export conflict error markers.

**Comment by chanseokoh** [comment]
Some more observations:
- I haven't figured out yet how the container name changes from "Cloud Datastore Client Library for Java" to "Google Cloud Datastore".
   - Looking at `libraries.json`, "Cloud Datastore Client Library for Java" is the client library name, while "Google Cloud Datastore" is the library name. Maybe because we use the same ID for the legacy library (container) and the library in `libraries.json`.
- Even if you successfully imported old projects with the legacy containers (i.e., you had all the JARs ready in the local repo), if you add a new library with the master container, the legacy containers are likewise resolved to have transitive dependencies as a side-effect.
- When adding a new library, the master container will usually have duplicate dependencies such as guava, but it doesn't always result in the export conflict errors, as artifact versions can be different. For example, the legacy container in the AESv8 example has guava-20.0.jar, but the master library will have guava-23.0.jar. That means, it will export guava-20.0.jar and guava-23.0.jar together, which is another problem.

**Comment by briandealwis** [comment]
> Cleaning the project will trigger adding the export conflict error markers.

The AES projects include the .class files which likely accounts for the sporadic nature.

**Comment by briandealwis** [comment]
#2509 provides a project updater to fix this issue.
