### ISSUE TITLE
Convert to App Engine Standard menu should configure Java 8 instead of Java 7

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#2572]
Currently, it's always Java 7.

It may be OK for Java 7 projects to remain on the Java 7 runtime, although they will have no problem being deployed to the Java 8 runtime.

**Comment by elharo** [comment]
Given the whitelist in Java 7, I suspect we should just convert all projects to the Java 8 runtime.

**Comment by patflynn** [comment]
+1 that enabling a project to work in app engine standard should default to the latest runtime.

I wouldn't automatically convert existing projects to the Java 8 runtime but you can certainly give the user the option to.

**Comment by elharo** [comment]
`AppEngineStandardProjectConvertJob`

**Comment by chanseokoh** [comment]
FYI, the reason it resulted in Java 7 was because there was no `appengine-web.xml` in a project or it did not have `<java>runtime8</java>`. In the former case, we create `appengine-web.xml` during the conversion, but I'm sure we don't currently put `<java>runtime8</java>`. In the latter case, if we still want to force Java8, we should put `runtime8` in the existing `appengine-web.xml`. I think if we just put the element there, the conversion process will automatically convert it to Java8. Hopefully nothing else we need to do.

**Comment by elharo** [comment]
Doesn't look quite that simple. We can add the runtime, but something is taking it out again. Here's two dumps while I was debugging:

```
elharo-macbookair99:google-cloud-eclipse elharo$ more /Users/elharo/workspaces/runtime-gcloud-eclipse/plain/WebContent/WEB-INF/appengine-web.xml
<?xml version="1.0" encoding="utf-8"?>
<appengine-web-app xmlns="http://appengine.google.com/ns/1.0">

  <threadsafe>true</threadsafe>
  <sessions-enabled>false</sessions-enabled>
  <runtime>java8</runtime>

</appengine-web-app>
elharo-macbookair99:google-cloud-eclipse elharo$ more /Users/elharo/workspaces/runtime-gcloud-eclipse/plain/WebContent/WEB-INF/appengine-web.xml
<?xml version="1.0" encoding="UTF-8"?>
<appengine-web-app xmlns="http://appengine.google.com/ns/1.0">

  <threadsafe>true</threadsafe>
  <sessions-enabled>false</sessions-enabled>
  

</appengine-web-app>
```

**Comment by elharo** [comment]
forced an exception to reveal what's removing the runtime after we add it:


```
SEVERE: Unable to remove runtime:java8 from L/lockme/WebContent/WEB-INF/appengine-web.xml
org.eclipse.core.internal.resources.ResourceException: File /lockme/WebContent/WEB-INF/appengine-web.xml is read-only.
	at org.eclipse.core.internal.resources.Workspace.validateSave(Workspace.java:2545)
	at org.eclipse.core.internal.resources.File.setContents(File.java:323)
	at org.eclipse.core.internal.resources.File.setContents(File.java:426)
	at com.google.cloud.tools.eclipse.util.Xslt.transformInPlace(Xslt.java:46)
	at com.google.cloud.tools.eclipse.appengine.standard.java8.AppEngineDescriptorTransform.removeJava8Runtime(AppEngineDescriptorTransform.java:41)
	at com.google.cloud.tools.eclipse.appengine.standard.java8.AppEngineStandardFacetChangeListener.handleEvent(AppEngineStandardFacetChangeListener.java:83)
	at org.eclipse.wst.common.project.facet.core.events.internal.DelayedClassLoadingListener.handleEvent(DelayedClassLoadingListener.java:62)
	at org.eclipse.wst.common.project.facet.core.events.internal.ProjectListenerRegistry.notifyListeners(ProjectListenerRegistry.java:76)
	at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.notifyListeners(FacetedProject.java:1327)
	at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.modifyInternal(FacetedProject.java:454)
	at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.mergeChangesInternal(FacetedProject.java:1181)
	at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.access$2(FacetedProject.java:1117)
	at org.eclipse.wst.common.project.facet.core.internal.FacetedProject$1.run(FacetedProject.java:324)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2241)
	at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.modify(FacetedProject.java:339)
	at com.google.cloud.tools.eclipse.appengine.facets.FacetUtil.install(FacetUtil.java:240)
	at com.google.cloud.tools.eclipse.appengine.facets.AppEngineStandardFacet.installAppEngineFacet(AppEngineStandardFacet.java:312)
	at com.google.cloud.tools.eclipse.appengine.facets.convert.AppEngineStandardProjectConvertJob.convert(AppEngineStandardProjectConvertJob.java:60)
	at com.google.cloud.tools.eclipse.appengine.facets.convert.AppEngineStandardProjectConvertJob.run(AppEngineStandardProjectConvertJob.java:48)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by briandealwis** [comment]
Either removing or changing [the default version of the facet](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/master/plugins/com.google.cloud.tools.eclipse.appengine.facets/plugin.xml#L14) should do the trick.  If it's removed, then the faceted project framework should choose the latest version, which will be our Java 8.

**Comment by elharo** [comment]
No, that doesn't seem to be sufficient. The runtime is still added and then removed. :-(

**Comment by briandealwis** [comment]
I get the expected results by either (1) removing the `<default-version version='JRE7'/>` or (2) changing the default-version to 'JRE8'.  I create convert a Java project with a Java 7 execution environment, choose _Configure > Convert to an App Engine Standard Project_, and I get an App Engine project with `<runtime>java8</runtime>`.

The project has its Java execution environment changed to Java 8, though that's the WTP `JavaFacetDetector` at work though: if the project doesn't have a Java facet then it sets the default version for the Java facet (which will be the latest) rather than try to detect the appropriate Java version.  Which may be a problem for us when WTP's Java facet supports Java 9.

**Comment by elharo** [comment]
That's not what I see though there are other weirdnesses; i.e. Tests failing on Travis but not locally. Let's move this discussion to PR #2591 or if you have a working PR, upload it, though as usual please don't push changes to same branch since that confuses the CLA bot. :-(
