### ISSUE TITLE
Provide feedback on login-related failures

### ISSUE THREAD

**Issue by NashPL** [GoogleCloudPlatform/google-cloud-eclipse#2589]
(please ensure you are running the latest version of CT4E with _Help > Check for Updates_)
- Cloud Tools for Eclipse version: 1.4.1.201710261936
- Google Cloud SDK version: 180.0.0
- Eclipse version: 4.7.1.v20171009-0410
- OS: Linux 4.10.0-38-generic
- Java version: 1.8.0_151

**What did you do?**
Pressed Sign In button

So I have pressed sign in button which open a new chrome window asking which account you want to log in as. I have pressed account I wanted then it took me to Localhost where I got "Received key success" message. When I went back to eclipse it didn't sign in on that end

Any Idea why?

**Comment by chanseokoh** [comment]
![sign in to google _045](https://user-images.githubusercontent.com/10523105/32906057-d273bfe0-cac9-11e7-839c-c00d43f7e928.png)

Did the wait dialog automatically disappear, or it disappeared but nothing happened? Can you also check _Windows_ > _Show View_ > _Error Log_?

**Comment by NashPL** [comment]
Yeah the popup have disappeared it self.
Error Log shows me
```
null
org.eclipse.ui
Error
Thu Nov 16 17:32:40 GMT 2017
Unhandled event loop exception

org.eclipse.e4.core.di.InjectionException: java.lang.SecurityException: Could not lock User prefs. Lock file access denied.
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:65)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:305)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:239)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:494)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:431)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:446)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:472)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5268)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1348)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4522)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4107)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
Caused by: java.lang.SecurityException: Could not lock User prefs. Lock file access denied.
	at java.util.prefs.FileSystemPreferences.checkLockFile0ErrorCode(FileSystemPreferences.java:937)
	at java.util.prefs.FileSystemPreferences.lockFile(FileSystemPreferences.java:925)
	at java.util.prefs.FileSystemPreferences.sync(FileSystemPreferences.java:729)
	at java.util.prefs.FileSystemPreferences.flush(FileSystemPreferences.java:824)
	at com.google.cloud.tools.login.JavaPreferenceOAuthDataStore.saveOAuthData(JavaPreferenceOAuthDataStore.java:90)
	at com.google.cloud.tools.login.GoogleLoginState.persistCredentials(GoogleLoginState.java:387)
	at com.google.cloud.tools.login.GoogleLoginState.logInHelper(GoogleLoginState.java:222)
	at com.google.cloud.tools.login.GoogleLoginState.logInWithLocalServer(GoogleLoginState.java:215)
	at com.google.cloud.tools.eclipse.login.GoogleLoginService.logIn(GoogleLoginService.java:120)
	at com.google.cloud.tools.eclipse.login.ui.GoogleLoginCommandHandler.execute(GoogleLoginCommandHandler.java:37)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:291)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
	... 37 more
```

**Comment by chanseokoh** [comment]
Seems like your Eclipse process doesn't have permission to access your Java preference files, which I believe will be under `$HOME/.java/.userPrefs`. Check the Linux user that you use to run your Eclipse and the user:group ownership of the Java pref directory.

**Comment by elharo** [comment]
The stack trace is helpful. We can catch this exception and provide a more informative message to the end user when this happens.

**Comment by NashPL** [comment]
Yeah that works simple chown on a directory seems it fixed the problem
Thanks for support :)

**Comment by briandealwis** [comment]
I guess the `GoogleLoginState` could throw an exception and pretend the login failed.  Even though the login succeeded and it's just the persisting that failed: the actual credential is good.

**Comment by briandealwis** [comment]
Ah, we can use the `UiFacade#showErrorDialog()`.

**Comment by briandealwis** [comment]
Moved to `ide-login`.
