### ISSUE TITLE
Fetching projects fails silently when there is problem

### ISSUE THREAD

**Issue by parkjam4** [GoogleCloudPlatform/google-cloud-eclipse#2607]
Trying to select a project from a project selector in a debug instance, but the projects wouldn't show up.  ~~It turns out that we were trying to refresh the access token but the refresh token was either a revoked or somehow invalid, leading to a~~ logged exception but otherwise a silent failure.  

```
Nov 28, 2017 12:28:53 PM com.google.cloud.tools.eclipse.appengine.localserver.ui.GcpLocalRunTab$6 run
WARNING: Could not retrieve GCP project information from server.
com.google.cloud.tools.eclipse.projectselector.ProjectRepositoryException: com.google.api.client.auth.oauth2.TokenResponseException: 401 Unauthorized
	at com.google.cloud.tools.eclipse.projectselector.ProjectRepository.getProjects(ProjectRepository.java:77)
	at com.google.cloud.tools.eclipse.appengine.localserver.ui.GcpLocalRunTab$6.run(GcpLocalRunTab.java:273)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at com.google.cloud.tools.eclipse.appengine.localserver.ui.GcpLocalRunTab.updateProjectSelector(GcpLocalRunTab.java:269)
	at com.google.cloud.tools.eclipse.appengine.localserver.ui.GcpLocalRunTab.access$0(GcpLocalRunTab.java:262)
	at com.google.cloud.tools.eclipse.appengine.localserver.ui.GcpLocalRunTab$1.run(GcpLocalRunTab.java:161)
	at com.google.cloud.tools.eclipse.login.ui.AccountSelector.fireSelectionListeners(AccountSelector.java:144)
	at com.google.cloud.tools.eclipse.login.ui.AccountSelector.access$4(AccountSelector.java:142)
	at com.google.cloud.tools.eclipse.login.ui.AccountSelector$LogInOnSelect.widgetSelected(AccountSelector.java:177)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:248)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4230)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1491)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1514)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1499)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1299)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4072)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3698)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:827)
	at org.eclipse.jface.window.Window.open(Window.java:803)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationsDialog.open(LaunchConfigurationsDialog.java:1154)
	at org.eclipse.debug.ui.DebugUITools$2.run(DebugUITools.java:619)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.debug.ui.DebugUITools.openLaunchConfigurationDialogOnGroup(DebugUITools.java:627)
	at org.eclipse.debug.ui.DebugUITools.openLaunchConfigurationDialogOnGroup(DebugUITools.java:560)
	at org.eclipse.debug.ui.actions.OpenLaunchDialogAction.run(OpenLaunchDialogAction.java:82)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:473)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:595)
	at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:511)
	at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:420)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4230)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1491)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1514)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1499)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1299)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4072)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3698)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:694)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:606)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1488)
Caused by: com.google.api.client.auth.oauth2.TokenResponseException: 401 Unauthorized
	at com.google.api.client.auth.oauth2.TokenResponseException.from(TokenResponseException.java:105)
	at com.google.api.client.auth.oauth2.TokenRequest.executeUnparsed(TokenRequest.java:287)
	at com.google.api.client.auth.oauth2.TokenRequest.execute(TokenRequest.java:307)
	at com.google.api.client.auth.oauth2.Credential.executeRefreshToken(Credential.java:570)
	at com.google.api.client.googleapis.auth.oauth2.GoogleCredential.executeRefreshToken(GoogleCredential.java:372)
	at com.google.api.client.auth.oauth2.Credential.refreshToken(Credential.java:489)
	at com.google.api.client.auth.oauth2.Credential.intercept(Credential.java:217)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:868)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
	at com.google.cloud.tools.eclipse.projectselector.ProjectRepository.getProjects(ProjectRepository.java:70)
	... 59 more
```

**Comment by elharo** [comment]
We can catch `TokenResponseException` in `getProjects()` like this:

```
    } catch (TokenResponseException ex) {
     // and do what?
    }
    } catch (IOException ex) {
      throw new ProjectRepositoryException(ex);
    }
```

Not immediately sure what we should do in response to it.

**Comment by elharo** [comment]
see https://developers.google.com/api-client-library/java/google-api-java-client/oauth2

**Comment by elharo** [comment]
see https://github.com/GoogleCloudPlatform/ide-login/issues/28

**Comment by elharo** [comment]
Credential is supposed to be refreshed automatically:

https://github.com/google/google-oauth-java-client/blob/dev/google-oauth-client/src/main/java/com/google/api/client/auth/oauth2/Credential.java#L217

 Maybe that failed in this case? If so, what should we do?

**Comment by chanseokoh** [comment]
We learned that this particular problem was because @parkjam4 set up wrong OAuth client ID and secret. When the login module is loading credentials saved locally when starting up, it was injecting the wrong info when building his credential object.

**Comment by elharo** [comment]
OK, in that case:

1. It's a low priority since presumably releases will have the correct credentials.
2. Nothing the user could have done would have fixed this.
2. It may not happen at all with a correct build.

**Comment by briandealwis** [comment]
I suspect this would also happen if the user revoked access for CT4E via their account permissions page (https://myaccount.google.com/permissions).

**Comment by elharo** [comment]
Let me check that. If that's the case, then at least a better error message here would make sense.

**Comment by lqiu96** [comment]
Closing as part of cleanup. Please re-open if it's still relevant
