### ISSUE TITLE
Widget is Disposed An internal error occurred during: "Google User Profile Picture Fetch Job".

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#2627]
An internal error occurred during: "Google User Profile Picture Fetch Job".

![image](https://user-images.githubusercontent.com/1005544/33623724-f422f5f2-d9bf-11e7-80b5-2aaac9217784.png)

1.5.0B when trying to login for the first time (Mars, Mac OS X)

```
org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4491)
	at org.eclipse.swt.SWT.error(SWT.java:4406)
	at org.eclipse.swt.SWT.error(SWT.java:4377)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:799)
	at org.eclipse.swt.widgets.Widget.getDisplay(Widget.java:923)
	at com.google.cloud.tools.eclipse.login.ui.LabelImageLoadJob.run(LabelImageLoadJob.java:50)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by chanseokoh** [comment]
This is a regression introduced at https://github.com/GoogleCloudPlatform/google-cloud-eclipse/pull/2581/files#diff-b09b52dc477acbb6cc51d20d6328b579L48. My bad. I was wary of this issue originially and had a test for it, but the test wasn't perfect.

**Comment by briandealwis** [comment]
There is little that an `isDisposed()` check can't fix :-)

**Comment by chanseokoh** [comment]
To be perfect, `isDisposed()` should be done inside a UI thread. There is still a possibility that a widget is disposed right after the `isDisposed()` check. That said, the prefect solution here would be to save `Display` early.
