### ISSUE TITLE
Creating new service account key may not be working on Windows

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#2636]
Had a chance to look into Kokoro and found the following failure. The problem is that `Paths.get("/T:/src/github/...")` throws an error. We make this call in the main bundle, so we should probably fix this.

```
java.nio.file.InvalidPathException: Illegal char <:> at index 2: /T:/src/github/google-cloud-eclipse/plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/target/work/configuration/
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.nio.file.Paths.get(Paths.java:84)
	at com.google.cloud.tools.eclipse.appengine.localserver.ui.GcpLocalRunTabTest.testGetServiceAccountKeyPath(GcpLocalRunTabTest.java:453)
```

**Comment by elharo** [comment]
https://stackoverflow.com/questions/9834776/java-nio-file-path-issue

**Comment by chanseokoh** [comment]
That's right. I just tested these on Windows:

```java
                System.out.println(Paths.get("C:\\a\\b\\c"));  // prints "C:\a\b\c"
                System.out.println(Paths.get("C:/a/b/c"));  // prints "C:\a\b\c"
                System.out.println(Paths.get("\\C:\\a\\b\\c"));  // the exception above
                System.out.println(Paths.get("/C:/a/b/c"));  // the exception above
```
