### ISSUE TITLE
getProjects() from Projects API sometimes returns null

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#2655]
I've seen this infrequently, but it does happen. ~~It might be the fault of the API returning null,~~ but since it happens, we need to be prepared.

```java
        Projects.List listRequest = projects.list().setPageSize(...);
        ...
        ListProjectsResponse response = listRequest.execute();
        projectList.addAll(response.getProjects());
```
```
Dec 08, 2017 12:00:10 PM com.google.cloud.tools.eclipse.projectselector.MiniSelector$4 accept
SEVERE: Unable to fetch project list
java.lang.NullPointerException
	at java.util.ArrayList.addAll(ArrayList.java:559)
	at com.google.cloud.tools.eclipse.projectselector.ProjectRepository.getProjects(ProjectRepository.java:71)
	at com.google.cloud.tools.eclipse.projectselector.MiniSelector$FetchProjectsJob.compute(MiniSelector.java:237)
	at com.google.cloud.tools.eclipse.projectselector.MiniSelector$FetchProjectsJob.compute(MiniSelector.java:1)
	at com.google.cloud.tools.eclipse.util.jobs.FuturisticJob.run(FuturisticJob.java:295)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by chanseokoh** [comment]
Actually, I can always reproduce this.

**Comment by elharo** [comment]
This API does document returning null. That's a bad design decision, but it is what it does:

https://developers.google.com/resources/api-libraries/documentation/cloudresourcemanager/v1beta1/java/latest/com/google/api/services/cloudresourcemanager/model/ListProjectsResponse.html#getProjects()
