### ISSUE TITLE
Flaky GpeFacetedMigratorTest: loaded GPE project doesn't have (old) App Engine facet

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#2678]
I don't remember having seen this.

The GPE test project certainly has the old GPE facet by its setup, but at the failure point, Eclipse did not think the project had it. Maybe giving Eclipse a bit more time would have made it work?

```
testRemoveGpeRuntimeAndFacets_facetsRemoved(com.google.cloud.tools.eclipse.appengine.compat.gpe.GpeFacetedMigratorTest)  Time elapsed: 2.108 sec  <<< FAILURE!
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.google.cloud.tools.eclipse.appengine.compat.gpe.GpeFacetedMigratorTest.testRemoveGpeRuntimeAndFacets_facetsRemoved(GpeFacetedMigratorTest.java:79)
```

**Comment by diegomarquezp** [comment]
Closing as not planned since Java 8 is not supported in GAE. cc: @blakeli0
