### ISSUE TITLE
Tests in CloudLibrariesInPluginXmlTest will fail in the future when new artifact versions are released

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#2691]
Builds are currently failing. Looks like Endpoints made a new release. We need to fix this test to be future-proof.

```
Tests run: 6, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.006 sec <<< FAILURE! - in com.google.cloud.tools.eclipse.appengine.libraries.model.CloudLibrariesInPluginXmlTest
testObjectifyLibraryConfig(com.google.cloud.tools.eclipse.appengine.libraries.model.CloudLibrariesInPluginXmlTest)  Time elapsed: 0 sec
testServletApiLibraryConfig(com.google.cloud.tools.eclipse.appengine.libraries.model.CloudLibrariesInPluginXmlTest)  Time elapsed: 0 sec
testLibrarySize(com.google.cloud.tools.eclipse.appengine.libraries.model.CloudLibrariesInPluginXmlTest)  Time elapsed: 0.001 sec
testAppEngineApiLibraryConfig(com.google.cloud.tools.eclipse.appengine.libraries.model.CloudLibrariesInPluginXmlTest)  Time elapsed: 0.001 sec
testEndpointsLibraryConfig(com.google.cloud.tools.eclipse.appengine.libraries.model.CloudLibrariesInPluginXmlTest)  Time elapsed: 0.002 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: is "2.0.9"
     but: was "2.0.10"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at com.google.cloud.tools.eclipse.appengine.libraries.model.CloudLibrariesInPluginXmlTest.testEndpointsLibraryConfig(CloudLibrariesInPluginXmlTest.java:117)
```

**Comment by chanseokoh** [comment]
Initially it's certainly 2.0.9 as we fix the version in `plugin.xml`. The `Library` instance is created with 2.0.9 can cached in the global "immutable" map.

```
  // Note: LibraryFile versions of Libraries in the map can be updated dynamically, e.g., to latest
  // available release versions.
  private static final ImmutableMap<String, Library> libraries = loadLibraryDefinitions();
```

However, as the comment says, if we ever call `Library.getAllDepedencies()` (which we always do), it will in turn call `LibraryFile.updateVersion()`, which updates the version.

So, this isn't the problem of only Endpoints.
