### ISSUE TITLE
GAE std deployment fails after 10mins (Windows path length limitation)

### ISSUE THREAD

**Issue by andryfailli** [GoogleCloudPlatform/google-cloud-eclipse#2701]
Hi, weeks ago I've raised a ticket #14211385 on Google Cloud Support, they suggested me to open this issue.

- Cloud Tools for Eclipse version:   Google Cloud Platform for Eclipse 4.5 and later	1.5.0.201712061945
- Google Cloud SDK version: _(run `gcloud version`)_
Google Cloud SDK 183.0.0
app-engine-java 1.9.59
app-engine-python 1.9.64
beta 2017.09.15
bq 2.0.27
core 2017.12.08
gsutil 4.28

- Eclipse version: Eclipse Java EE IDE for Web Developers Oxygen.2 Release (4.7.2) 20171218-0600
- OS: Win10 Pro x64
- Java version:
java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)

**What did you do?**
Deploy a java7 project into App Engine Standard env.

**What did you expect to see?**
Deployment success in a few seconds/minutes

**What did you see instead?**
After 10mins the deployment process fails with _An internal error occurred. (error code 13)_ (see_ log attached [ko.log](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/files/1606380/ko.log))
On Stackdriver logs I see a lot of 500s saying

```
java.lang.NoClassDefFoundError: com/google/teampot/helper/objectify/EnumTaskPrioritySortingTranslatorFactory$EnumSortingTranslator
	at com.google.teampot.helper.objectify.EnumTaskPrioritySortingTranslatorFactory.create(EnumTaskPrioritySortingTranslatorFactory.java:17)
	at com.googlecode.objectify.impl.translate.TranslateTranslatorFactory.create(TranslateTranslatorFactory.java:36)
	at com.googlecode.objectify.impl.translate.Translators.create(Translators.java:138)
	at com.googlecode.objectify.impl.translate.Translators.get(Translators.java:117)
	at com.googlecode.objectify.impl.translate.CreateContext.getTranslator(CreateContext.java:27)
	at com.googlecode.objectify.impl.translate.ClassPopulator.<init>(ClassPopulator.java:88)
	at com.googlecode.objectify.impl.translate.ClassTranslatorFactory.createEntityClassTranslator(ClassTranslatorFactory.java:66)
	at com.googlecode.objectify.impl.translate.ClassTranslatorFactory.create(ClassTranslatorFactory.java:49)
	at com.googlecode.objectify.impl.translate.ClassTranslatorFactory.create(ClassTranslatorFactory.java:36)
	at com.googlecode.objectify.impl.translate.Translators.create(Translators.java:138)
	at com.googlecode.objectify.impl.translate.Translators.get(Translators.java:117)
	at com.googlecode.objectify.impl.translate.Translators.getRoot(Translators.java:129)
	at com.googlecode.objectify.impl.EntityMetadata.<init>(EntityMetadata.java:49)
	at com.googlecode.objectify.impl.Registrar.register(Registrar.java:70)
	at com.googlecode.objectify.ObjectifyFactory.register(ObjectifyFactory.java:185)
	at com.google.teampot.service.OfyService.registerAll(OfyService.java:43)
	at com.google.teampot.servlet.listener.OfyListener.contextInitialized(OfyListener.java:12)
	at org.mortbay.jetty.handler.ContextHandler.startContext(ContextHandler.java:548)
	at org.mortbay.jetty.servlet.Context.startContext(Context.java:136)
	at org.mortbay.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1250)
	at org.mortbay.jetty.handler.ContextHandler.doStart(ContextHandler.java:517)
	at org.mortbay.jetty.webapp.WebAppContext.doStart(WebAppContext.java:467)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.createHandler(AppVersionHandlerMap.java:203)
	at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.getHandler(AppVersionHandlerMap.java:176)
	at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:134)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchServletRequest(JavaRuntime.java:680)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchRequest(JavaRuntime.java:642)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:612)
	at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:454)
	at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:461)
	at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:297)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:320)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:312)
	at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:458)
	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:274)
	at java.lang.Thread.run(Thread.java:745)
```

Same error occurs also if I deploy using gcloud or maven from command line.
I'm able to deploy using old appcfg command in GAE sdk.

Same code on same project was succesfully ( [ok.txt](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/files/1606364/ok.txt) ) deployed with from another PC with the following tools
- java 1.8
- gcloud 176
- google plugin for eclipse 1.4.1
- eclipse oxygen
- OS Mac OS high sierra

**Comment by elharo** [comment]
If you get the same error with gcloud or maven, then it's not a cloud tools for Eclipse issue. From the stack trace, I'd guess it has something to do with your classpath.

**Comment by andryfailli** [comment]
Hi, the project is running fine on local server.

Previously I've tried gcloud app deploy command a few weeks ago without success.
I've tried again now and it worked
- succesful deployment
- strackdriver logs ok

**Comment by chanseokoh** [comment]
@andryfailli you said in the earlier ticket that "mvn clean package" fails. Can you elaborate on that and also fix any error to make it work? I think "mvn clean package" should not fail locally first.

You also said that using another Windows machine to deploy the code with your account fails. Can you try it on the Windows machine with another user? Also, can you try deploying on your machine with another user? I'd like to check if it's your account that's somehow causing the problem.

**Comment by andryfailli** [comment]
@chanseokoh local build is ok using `mvn clean appengine:endpoints_get_discovery_doc package`; and now also `mvn appengine:update` is succesful, I think because the appcfg command now works fine.

But deployment from google cloud tools for eclipse is still failing with message `(gcloud.app.deploy) Error Response: [13] An internal error occurred.` [09.36.27.324000.log](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/files/1614414/09.36.27.324000.log)

**Comment by elharo** [comment]
It looks like you're using the old App Engine Java SDK based Maven plugin. That is:

```
<plugin>
   <groupId>com.google.appengine</groupId>
   <artifactId>appengine-maven-plugin</artifactId>
   <version>1.9.60</version>
</plugin>
```

Eclipse is closer to the new plugin:

```
<plugin>
   <groupId>com.google.cloud.tools</groupId>
   <artifactId>appengine-maven-plugin</artifactId>
   <version>1.3.1</version>
</plugin>
```

Can you confirm from your pom.xml? This is probably a big clue.

**Comment by andryfailli** [comment]
Hi @elharo, yes I'm using the `com.google.appengine appengine-maven-plugin 1.9.48`.
Maybe this is the root cause of the error? But a collegue of mine is able to deploy the same code on the same project - but from a different environment.

I see that the new plugin doesn't have the `endpoints_get_discovery_doc `goal.
I'm currently using endpoints v1 (I know, I should migrate to v2...): how can I generate endpoints discovery docs using the new maven plugin?

Thanks

**Comment by elharo** [comment]
To the best of my knowledge, you can't. I don't think the new plugin supports endpoints v1. Cloud Tools for Eclipse doesn't specifically support Endpoints, so if that's the source of your problem then this is the wrong repo to report the issue in.

**Comment by patflynn** [comment]
https://github.com/GoogleCloudPlatform/endpoints-framework-maven-plugin/

**Comment by chanseokoh** [comment]
@andryfailli I think I know what happened. From your log you provided in the original ticket, I noticed that there are many other classes files missing besides `EnumTaskPrioritySortingTranslatorFactory`. What is common among such files is that they have long path length and go over some length threshold. However, Windows can handle only up to 260 characters.

For example, the length of the following path is 263.
```
C:\Users\...\...\Eclipse\workspace-oxygen\.metadata\.plugins\com.google.cloud.tools.eclipse.appengine.deploy\tmp\1513173234844\staging-work\exploded-war\WEB-INF\classes\com\google\teampot\helper\objectify\EnumTaskPrioritySortingTranslatorFactory.class
```

On Windows 10, there is a way to [lift the length limitation](https://social.msdn.microsoft.com/Forums/en-US/fc85630e-5684-4df6-ad2f-5a128de3deef/260-character-explorer-path-length-limit?forum=windowsgeneraldevelopmentissues), although I am not sure if it will cause any compatibility issue with old software.

Cross ref: https://github.com/GoogleCloudPlatform/app-maven-plugin/issues/241

**Comment by andryfailli** [comment]
Oh my!
Thank you all, I'll try to deploy from another folder trying to have
filenames < 260 chars.

I'll let you know.

2018-01-16 18:00 GMT+01:00 Chanseok Oh <notifications@github.com>:

**Comment by elharo** [comment]
Good catch. I wonder if we can do anything to either:

1. reduce the length of the path we use for our temp directory here
2. Notice that this is a problem and warn the user.

**Comment by andryfailli** [comment]
Hi there, I moved my eclipse workspace directly into "C:\" reducing the final path length and now the deployment is succesful, so I think we can confirm that the max filename length on Windows is the root cause that prevent the deployment.

Thank you

**Comment by JoeWang1127** [comment]
close as not planned
