### ISSUE TITLE
SocketTimeoutException in verify-feature-completeness when attempting to install ADT

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#2711]
Seeing occasional build failures on Travis in `verify-feature-completeness`, where we attempt to install CT4E alongside ADT, due to a timeout fetching from ADT's repository.  I suppose at some point we can get rid of this test as I doubt anybody is using ADT any more.

(This was on the Mars built target.)
```
[INFO] --- tycho-eclipserun-plugin:1.0.0:eclipse-run (default) @ verify-feature-completeness ---
[INFO] Adding repository file:/home/travis/build/GoogleCloudPlatform/google-cloud-eclipse/build/verify-feature-completeness//../../eclipse/ide-target-platform/target/repository
[INFO] Toolchain in tycho-eclipserun-plugin: JDK[/usr/lib/jvm/java-7-openjdk-amd64/jre]
[INFO] Expected eclipse log file: /home/travis/build/GoogleCloudPlatform/google-cloud-eclipse/build/verify-feature-completeness/target/eclipserun-work/data/.metadata/.log
[INFO] Command line:
	[/usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java, -Declipse.p2.mirrors=false, -jar, /home/travis/.m2/repository/p2/osgi/bundle/org.eclipse.equinox.launcher/1.3.100.v20150511-1540/org.eclipse.equinox.launcher-1.3.100.v20150511-1540.jar, -install, /home/travis/build/GoogleCloudPlatform/google-cloud-eclipse/build/verify-feature-completeness/target/eclipserun-work, -configuration, /home/travis/build/GoogleCloudPlatform/google-cloud-eclipse/build/verify-feature-completeness/target/eclipserun-work/configuration, -consoleLog, -nosplash, -application, org.eclipse.equinox.p2.director, -destination, /home/travis/build/GoogleCloudPlatform/google-cloud-eclipse/build/verify-feature-completeness/target/p2-installation, -repository, file:/home/travis/build/GoogleCloudPlatform/google-cloud-eclipse/build/verify-feature-completeness//../../eclipse/ide-target-platform/target/repository,file:/home/travis/build/GoogleCloudPlatform/google-cloud-eclipse/build/verify-feature-completeness//../../gcp-repo/target/repository,http://dl-ssl.google.com/android/eclipse/, -installIUs, org.eclipse.platform.feature.group,com.google.cloud.tools.eclipse.suite.e45.feature.feature.group,com.android.ide.eclipse.adt.feature.feature.group]
Picked up _JAVA_OPTIONS: -Xmx2048m -Xms512m
Installing org.eclipse.platform.feature.group 4.5.2.v20160212-1500.
Installing com.google.cloud.tools.eclipse.suite.e45.feature.feature.group 1.5.0.201801032218.
Installing com.android.ide.eclipse.adt.feature.feature.group 23.0.7.2120684.
Installation failed.
An error occurred while collecting items to be installed
 session context was:(profile=/home/travis/build/GoogleCloudPlatform/google-cloud-eclipse/build/verify-feature-completeness/target/p2-installation, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
 Unable to read repository at http://dl-ssl.google.com/android/eclipse/plugins/com.android.ide.eclipse.adt_23.0.7.2120684.jar.
Caused by:  java.net.SocketTimeoutException: Read timed out
Application failed, log file location: /home/travis/build/GoogleCloudPlatform/google-cloud-eclipse/build/verify-feature-completeness/target/eclipserun-work/configuration/1515555132845.log
!SESSION 2018-01-10 03:32:12.664 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.7.0_151
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -application org.eclipse.equinox.p2.director -destination /home/travis/build/GoogleCloudPlatform/google-cloud-eclipse/build/verify-feature-completeness/target/p2-installation -repository file:/home/travis/build/GoogleCloudPlatform/google-cloud-eclipse/build/verify-feature-completeness//../../eclipse/ide-target-platform/target/repository,file:/home/travis/build/GoogleCloudPlatform/google-cloud-eclipse/build/verify-feature-completeness//../../gcp-repo/target/repository,http://dl-ssl.google.com/android/eclipse/ -installIUs org.eclipse.platform.feature.group,com.google.cloud.tools.eclipse.suite.e45.feature.feature.group,com.android.ide.eclipse.adt.feature.feature.group
Command-line arguments:  -consoleLog -application org.eclipse.equinox.p2.director -destination /home/travis/build/GoogleCloudPlatform/google-cloud-eclipse/build/verify-feature-completeness/target/p2-installation -repository file:/home/travis/build/GoogleCloudPlatform/google-cloud-eclipse/build/verify-feature-completeness//../../eclipse/ide-target-platform/target/repository,file:/home/travis/build/GoogleCloudPlatform/google-cloud-eclipse/build/verify-feature-completeness//../../gcp-repo/target/repository,http://dl-ssl.google.com/android/eclipse/ -installIUs org.eclipse.platform.feature.group,com.google.cloud.tools.eclipse.suite.e45.feature.feature.group,com.android.ide.eclipse.adt.feature.feature.group

!ENTRY org.eclipse.equinox.p2.engine 4 4 2018-01-10 03:32:35.934
!MESSAGE An error occurred while collecting items to be installed
!SUBENTRY 1 org.eclipse.equinox.p2.engine 4 0 2018-01-10 03:32:35.934
!MESSAGE session context was:(profile=/home/travis/build/GoogleCloudPlatform/google-cloud-eclipse/build/verify-feature-completeness/target/p2-installation, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
!SUBENTRY 1 org.eclipse.equinox.p2.transport.ecf 4 1002 2018-01-10 03:32:35.934
!MESSAGE Unable to read repository at http://dl-ssl.google.com/android/eclipse/plugins/com.android.ide.eclipse.adt_23.0.7.2120684.jar.
!STACK 0
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.read(SocketInputStream.java:153)
	at java.net.SocketInputStream.read(SocketInputStream.java:122)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:235)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:275)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:334)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:721)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:664)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1389)
	at org.eclipse.ecf.provider.filetransfer.retrieve.UrlConnectionRetrieveFileTransfer.getDecompressedStream(UrlConnectionRetrieveFileTransfer.java:552)
	at org.eclipse.ecf.provider.filetransfer.retrieve.UrlConnectionRetrieveFileTransfer.openStreams(UrlConnectionRetrieveFileTransfer.java:322)
	at org.eclipse.ecf.provider.filetransfer.retrieve.AbstractRetrieveFileTransfer.sendRetrieveRequest(AbstractRetrieveFileTransfer.java:885)
	at org.eclipse.ecf.provider.filetransfer.retrieve.AbstractRetrieveFileTransfer.sendRetrieveRequest(AbstractRetrieveFileTransfer.java:576)
	at org.eclipse.ecf.provider.filetransfer.retrieve.MultiProtocolRetrieveAdapter.sendRetrieveRequest(MultiProtocolRetrieveAdapter.java:106)
	at org.eclipse.equinox.internal.p2.transport.ecf.FileReader.sendRetrieveRequest(FileReader.java:426)
	at org.eclipse.equinox.internal.p2.transport.ecf.FileReader.readInto(FileReader.java:358)
	at org.eclipse.equinox.internal.p2.transport.ecf.RepositoryTransport.download(RepositoryTransport.java:101)
	at org.eclipse.equinox.internal.p2.transport.ecf.RepositoryTransport.download(RepositoryTransport.java:156)
	at org.eclipse.equinox.internal.p2.artifact.repository.simple.SimpleArtifactRepository.downloadArtifact(SimpleArtifactRepository.java:669)
	at org.eclipse.equinox.internal.p2.artifact.repository.simple.SimpleArtifactRepository.downloadArtifact(SimpleArtifactRepository.java:591)
	at org.eclipse.equinox.internal.p2.artifact.repository.simple.SimpleArtifactRepository.getArtifact(SimpleArtifactRepository.java:723)
	at org.eclipse.equinox.internal.p2.artifact.repository.MirrorRequest.getArtifact(MirrorRequest.java:319)
	at org.eclipse.equinox.internal.p2.artifact.repository.MirrorRequest.transferSingle(MirrorRequest.java:288)
	at org.eclipse.equinox.internal.p2.artifact.repository.MirrorRequest.transfer(MirrorRequest.java:223)
	at org.eclipse.equinox.internal.p2.artifact.repository.MirrorRequest.perform(MirrorRequest.java:153)
	at org.eclipse.equinox.internal.p2.artifact.repository.simple.SimpleArtifactRepository.getArtifact(SimpleArtifactRepository.java:707)
	at org.eclipse.equinox.internal.p2.artifact.repository.simple.DownloadJob.run(DownloadJob.java:63)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by elharo** [comment]
Agreed. If this is causing us any trouble let's just get rid of it.

**Comment by briandealwis** [comment]
I wonder if we could use `Assume` to check that the repo was accessible.  But it might be simpler to use Travis' cron functionality and run this test on a nightly basis.

**Comment by elharo** [comment]
I'm not sure this test is worth that much effort. We should probably remove it.

**Comment by briandealwis** [comment]
Hitting this a lot today.

**Comment by chanseokoh** [comment]
I think this is not really worth. I'll remove it.
