### ISSUE TITLE
Stop logging could-not-find-runtime

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#2715]
Our build logs for `.deploy.test`, `.deploy.ui.test`,  are cluttered with entries like the following:
```
!ENTRY org.eclipse.core.jobs 4 2 2018-01-10 21:50:19.329
!MESSAGE An internal error occurred during: "Install App Engine runtimes in "test0.6152019114061741"".
!STACK 0
java.lang.NullPointerException: Could not find App Engine Standard runtime type
	at com.google.cloud.tools.eclipse.appengine.facets.AppEngineStandardFacet.createAppEngineServerRuntime(AppEngineStandardFacet.java:411)
	at com.google.cloud.tools.eclipse.appengine.facets.AppEngineStandardFacet.createAppEngineFacetRuntime(AppEngineStandardFacet.java:423)
	at com.google.cloud.tools.eclipse.appengine.facets.AppEngineStandardFacet.installAllAppEngineRuntimes(AppEngineStandardFacet.java:380)
	at com.google.cloud.tools.eclipse.appengine.facets.StandardFacetInstallDelegate$AppEngineRuntimeInstallJob.run(StandardFacetInstallDelegate.java:114)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

This happens as we add an App Engine Standard facet to a project, which attempts to install an App Engine server runtime on the project.  Our runtime definitions are in `.appengine.localserver`. Because Tycho attempts to minimize the bundles required, Tycho doesn't include `.appengine.localserver` when running these tests.

We could force these test projects to include `.appengine.localserver`, so the definition is available.

Or we could fix `.installAllAppEngineRuntimes()` to instead just do a simple log string that the runtime definition could not be found.

**Comment by elharo** [comment]
Including .appengine.localserver seems preferable. I'd prefer not to change the behavior of 
`installAllAppEngineRuntimes()` for non-test code.
