### ISSUE TITLE
DebugNativeAppEngineStandardProjectTest#testDebugLaunch is a bit flakey

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#2741]
Test failure seen on Neon:
```
com.google.cloud.tools.eclipse.integration.appengine.DebugNativeAppEngineStandardProjectTest
testDebugLaunch(com.google.cloud.tools.eclipse.integration.appengine.DebugNativeAppEngineStandardProjectTest)  Time elapsed: 9.039 sec  <<< FAILURE!
java.lang.AssertionError: App Engine console not active
Expected: a string containing "App Engine Standard at localhost"
     but: was "No consoles to display at this time."
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at com.google.cloud.tools.eclipse.integration.appengine.DebugNativeAppEngineStandardProjectTest.testDebugLaunch(DebugNativeAppEngineStandardProjectTest.java:123)
```

The relevant code section is:
```java
    SWTBotView consoleView = bot.viewById("org.eclipse.ui.console.ConsoleView"); // IConsoleConstants.ID_CONSOLE_VIEW
    consoleView.show();
    assertThat("App Engine console not active",
        consoleView.getViewReference().getContentDescription(),
        Matchers.containsString("App Engine Standard at localhost"));
```

From the screenshot, it looks like the app hadn't finished starting:
![travis-11443-11443 2-linux-20180119-1557-plugins-com google cloud tools eclipse integration appengine-screenshots-testdebuglaunch com google cloud tools eclipse integration appengine debugnativeappenginestandardprojecttest](https://user-images.githubusercontent.com/202851/35165418-3da7cf5c-fd1c-11e7-8811-54ce0ff10c43.jpeg)

(testing screenshots for the win!)

**Comment by briandealwis** [comment]
The wait further up needs some tweaking:
```
    SwtBotTreeUtilities.waitUntilTreeHasItems(bot, launchTree);
    SWTBotTreeItem[] allItems = launchTree.getAllItems();
    SwtBotTreeUtilities.waitUntilTreeContainsText(bot, allItems[0],
        "App Engine Standard at localhost");
```

**Comment by briandealwis** [comment]
Seen on Oxygen: looks slightly different — the blank tree item.
```
Running com.google.cloud.tools.eclipse.integration.appengine.DebugNativeAppEngineStandardProjectTest
[Watchdog] > testDebugLaunch(com.google.cloud.tools.eclipse.integration.appengine.DebugNativeAppEngineStandardProjectTest)
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x8002ce (New Projec)
Window manager warning: meta_window_activate called by a pager with a 0 timestamp; the pager needs to be fixed.
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x800021 (data - Ecl)
Window manager warning: meta_window_activate called by a pager with a 0 timestamp; the pager needs to be fixed.
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 39.343 sec <<< FAILURE! - in com.google.cloud.tools.eclipse.integration.appengine.DebugNativeAppEngineStandardProjectTest
testDebugLaunch(com.google.cloud.tools.eclipse.integration.appengine.DebugNativeAppEngineStandardProjectTest)  Time elapsed: 35.32 sec  <<< ERROR!
org.eclipse.swtbot.swt.finder.exceptions.WidgetNotFoundException: Timed out waiting for tree item Google App Engine Standard Java Project
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:522)
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:496)
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:484)
	at org.eclipse.swtbot.swt.finder.widgets.SWTBotTreeItem.getTreeItem(SWTBotTreeItem.java:863)
	at org.eclipse.swtbot.swt.finder.widgets.SWTBotTreeItem.select(SWTBotTreeItem.java:561)
	at org.eclipse.swtbot.swt.finder.widgets.SWTBotTreeItem.select(SWTBotTreeItem.java:611)
	at com.google.cloud.tools.eclipse.integration.appengine.SwtBotAppEngineActions.createWebAppProject(SwtBotAppEngineActions.java:83)
	at com.google.cloud.tools.eclipse.integration.appengine.SwtBotAppEngineActions.createNativeWebAppProject(SwtBotAppEngineActions.java:54)
	at com.google.cloud.tools.eclipse.integration.appengine.DebugNativeAppEngineStandardProjectTest.testDebugLaunch(DebugNativeAppEngineStandardProjectTest.java:88)
```

![travis-11476-11476 3-linux-20180126-2054-plugins-com google cloud tools eclipse integration appengine-screenshots-testdebuglaunch com google cloud tools eclipse integration appengine debugnativeappenginestandardprojecttest](https://user-images.githubusercontent.com/202851/35461464-115dc128-02b6-11e8-9dd1-54d675273202.jpeg)

**Comment by chanseokoh** [comment]
Certainly, the second issue is different from the original "console-not-active" issue. It's rather #2657 and 2569. We hope both of which are practically fixed by trying once more if this happens. We could do the same for creating a new project.

**Comment by chanseokoh** [comment]
Seen the original "console-not-active" issue several times in the past couple weeks.

**Comment by elharo** [comment]
Just saw this again.

**Comment by briandealwis** [comment]
What's odd about the failure in [11575.2](https://console.cloud.google.com/storage/browser/travis_artifacts/travis/11575/11575.2-linux-20180202-1540/plugins/com.google.cloud.tools.eclipse.integration.appengine/screenshots/?project=google.com:gcloud-for-eclipse-testing&authuser=0) is that the console shows the server status is _stopped_ rather than _starting_.

**Comment by chanseokoh** [comment]
I wonder if the screenshot doesn't always reflect the precise moment of an error. The test runs in a thread different from the UI thread.

Anyway, I think a dumb but permanent solution is to simply wait until the console displays what we want.
