### ISSUE TITLE
Flaky WebProjectUtilTest.testCreateWebInfFile_dynamicWebProject

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#2781]
On Mars.

```
Running com.google.cloud.tools.eclipse.appengine.facets.WebProjectUtilTest
Importing 1 projects:
    /home/travis/build/GoogleCloudPlatform/google-cloud-eclipse/plugins/com.google.cloud.tools.eclipse.appengine.facets.test/target/work/data/test-dynamic-web-project-dynamicrootsource/.project
Importing 1 projects:
    /home/travis/build/GoogleCloudPlatform/google-cloud-eclipse/plugins/com.google.cloud.tools.eclipse.appengine.facets.test/target/work/data/test-dynamic-web-project-dynamicrootsource/.project
Importing 1 projects:
    /home/travis/build/GoogleCloudPlatform/google-cloud-eclipse/plugins/com.google.cloud.tools.eclipse.appengine.facets.test/target/work/data/test-dynamic-web-project-dynamicrootsource/.project
Tests run: 18, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 15.7 sec <<< FAILURE! - in com.google.cloud.tools.eclipse.appengine.facets.WebProjectUtilTest
testCreateWebInfFolder_plainMavenLikeProject(com.google.cloud.tools.eclipse.appengine.facets.WebProjectUtilTest)  Time elapsed: 0.019 sec
testCreateWebInfFolder_plainWtpLikeProject(com.google.cloud.tools.eclipse.appengine.facets.WebProjectUtilTest)  Time elapsed: 0.026 sec
testFindWebInfFile_plainEmpty(com.google.cloud.tools.eclipse.appengine.facets.WebProjectUtilTest)  Time elapsed: 0.017 sec
testCreateWebInfFile_dynamicWebProject(com.google.cloud.tools.eclipse.appengine.facets.WebProjectUtilTest)  Time elapsed: 3.072 sec  <<< ERROR!
java.lang.NullPointerException: null
	at org.eclipse.wst.common.componentcore.internal.impl.WorkbenchComponentImpl.findResourcesByRuntimePath(WorkbenchComponentImpl.java:551)
	at org.eclipse.wst.common.componentcore.internal.resources.VirtualFolder.getFirstTaggedResource(VirtualFolder.java:185)
	at org.eclipse.jst.j2ee.componentcore.J2EEModuleVirtualComponent.getDefaultDeploymentDescriptorFolder(J2EEModuleVirtualComponent.java:544)
	at com.google.cloud.tools.eclipse.appengine.facets.WebProjectUtil.findWebInfForNewResource(WebProjectUtil.java:124)
	at com.google.cloud.tools.eclipse.appengine.facets.WebProjectUtil.createFileInWebInf(WebProjectUtil.java:81)
	at com.google.cloud.tools.eclipse.appengine.facets.WebProjectUtilTest.testCreateWebInfFile_dynamicWebProject(WebProjectUtilTest.java:249)

testFindWebInfFile_dynamicWebProject(com.google.cloud.tools.eclipse.appengine.facets.WebProjectUtilTest)  Time elapsed: 3.01 sec
```

**Comment by chanseokoh** [comment]
See https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/2831#issuecomment-368094897.

**Comment by diegomarquezp** [comment]
Closing as not planned. cc: @blakeli0
