### ISSUE TITLE
NPE when there are non-faceted projects with any XML files

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#2863]
In `XmlSourceValidator.validate()`, we validate (any) XML files only if the project has the App Engine facet.

```java
      IFacetedProject facetedProject = ProjectFacetsManager.create(project);
      if (AppEngineStandardFacet.hasFacet(facetedProject)) {
        ...
        validate(reporter, source, bytes);
      }
```

However,  `hasFacet()` requires that `project` is faceted.
```java
  public static boolean hasFacet(IFacetedProject project) {
    Preconditions.checkNotNull(project);
    return project.hasProjectFacet(FACET);
  }
```

Not sure if we should check null inside `hasFacet()` or before calling it.

**Comment by chanseokoh** [comment]
```
java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770)
	at com.google.cloud.tools.eclipse.appengine.facets.AppEngineStandardFacet.hasFacet(AppEngineStandardFacet.java:102)
	at com.google.cloud.tools.eclipse.appengine.validation.XmlSourceValidator.validate(XmlSourceValidator.java:74)
	at org.eclipse.wst.sse.ui.internal.reconcile.validator.ReconcileStepForValidator.validate(ReconcileStepForValidator.java:250)
	at org.eclipse.wst.sse.ui.internal.reconcile.validator.ReconcileStepForValidator.reconcileModel(ReconcileStepForValidator.java:208)
	at org.eclipse.jface.text.reconciler.AbstractReconcileStep.reconcile(AbstractReconcileStep.java:89)
	at org.eclipse.wst.sse.ui.internal.reconcile.validator.ValidatorStrategy.reconcile(ValidatorStrategy.java:269)
	at org.eclipse.wst.sse.ui.internal.reconcile.DocumentRegionProcessor.process(DocumentRegionProcessor.java:321)
	at org.eclipse.wst.sse.ui.internal.reconcile.StructuredRegionProcessor.process(StructuredRegionProcessor.java:258)
	at org.eclipse.wst.sse.ui.internal.reconcile.DirtyRegionProcessor$BackgroundThread.run(DirtyRegionProcessor.java:691)
```

**Comment by chanseokoh** [comment]
Others calling `hasFacet()` either explicitly checks null or is in the context of a faceted project. I'll check null here too.
