### ISSUE TITLE
Flaky DebugNativeAppEngineStandardProjectTest.testDebugLaunch()

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#2867]
On Neon.

We had seen flaky behaviors of this test method (e.g., #2741) and fixed them, but this time, it's a new one at

```java
    SwtBotTestingUtilities.waitUntilStyledTextContains(bot,
        "Module instance default is running at http://localhost:8080", consoleContents);
```

```
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 85.551 sec <<< FAILURE! - in com.google.cloud.tools.eclipse.integration.appengine.DebugNativeAppEngineStandardProjectTest

testDebugLaunch(com.google.cloud.tools.eclipse.integration.appengine.DebugNativeAppEngineStandardProjectTest)  Time elapsed: 84.926 sec  <<< ERROR!

org.eclipse.swtbot.swt.finder.widgets.TimeoutException: Timeout after: 30000 ms.: Text not found!
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:522)
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:496)
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:484)
	at com.google.cloud.tools.eclipse.swtbot.SwtBotTestingUtilities.waitUntilStyledTextContains(SwtBotTestingUtilities.java:158)
	at com.google.cloud.tools.eclipse.integration.appengine.DebugNativeAppEngineStandardProjectTest.testDebugLaunch(DebugNativeAppEngineStandardProjectTest.java:127)
```

This may or may not be related to the error that logged just before the above stacktrace.
```
WARNING: Error terminating server: http://localhost:8080/_ah/admin/quit responded with Service Unavailable.

com.google.cloud.tools.appengine.api.AppEngineException: http://localhost:8080/_ah/admin/quit responded with Service Unavailable.
	at com.google.cloud.tools.appengine.cloudsdk.CloudSdkAppEngineDevServer1.stop(CloudSdkAppEngineDevServer1.java:176)
	at com.google.cloud.tools.eclipse.appengine.localserver.server.LocalAppEngineServerBehaviour.stop(LocalAppEngineServerBehaviour.java:150)
	at com.google.cloud.tools.eclipse.appengine.localserver.server.LocalAppEngineServerLaunchConfigurationDelegate$CloudSdkDebugTarget.terminate(LocalAppEngineServerLaunchConfigurationDelegate.java:759)
	at org.eclipse.debug.core.Launch.terminate(Launch.java:226)
	at org.eclipse.debug.internal.core.LaunchManager.terminateMappedConfigurations(LaunchManager.java:2449)
	at org.eclipse.debug.internal.core.LaunchManager.projectClosed(LaunchManager.java:2217)
	at org.eclipse.debug.internal.core.LaunchManager$LaunchManagerVisitor.visit(LaunchManager.java:373)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:64)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:75)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:48)
	at org.eclipse.debug.internal.core.LaunchManager.resourceChanged(LaunchManager.java:2302)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:299)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:289)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:152)
	at org.eclipse.core.internal.resources.Workspace.broadcastPostChange(Workspace.java:374)
	at org.eclipse.core.internal.resources.Workspace.endOperation(Workspace.java:1469)
	at org.eclipse.core.internal.resources.Project.close(Project.java:201)
	at com.google.cloud.tools.eclipse.integration.appengine.BaseProjectTest.tearDown(BaseProjectTest.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at com.google.cloud.tools.eclipse.test.util.ThreadDumpingWatchdog$1.evaluate(ThreadDumpingWatchdog.java:94)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.eclipse.swtbot.swt.finder.junit.SWTBotJunit4ClassRunner.runChild(SWTBotJunit4ClassRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.swtbot.swt.finder.junit.SWTBotJunit4ClassRunner.run(SWTBotJunit4ClassRunner.java:61)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:156)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:82)
	at org.eclipse.tycho.surefire.osgibooter.OsgiSurefireBooter.run(OsgiSurefireBooter.java:95)
	at org.eclipse.tycho.surefire.osgibooter.AbstractUITestApplication.runTests(AbstractUITestApplication.java:44)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Testable$1.run(E4Testable.java:73)
	at java.lang.Thread.run(Thread.java:748)

Feb 27, 2018 7:37:49 PM com.google.cloud.tools.eclipse.appengine.localserver.server.LocalAppEngineServerBehaviour terminate

INFO: forced stop: destroying associated processes
```

**Comment by chanseokoh** [comment]
Turns out, there is no `1 Debug on Server` at all at the time of the failure. Only does "1 App Engine" exist.

```
==== menu items of Run > Debug As ====
1 App Engine
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x8009af (Delete Res)
Window manager warning: meta_window_activate called by a pager with a 0 timestamp; the pager needs to be fixed.
00:18:50.852 [main] WARN  o.e.s.s.finder.widgets.SWTBotButton - Widget is not enabled: (of type 'Button' and with mnemonic 'OK' and with style 'SWT.PUSH')
00:18:50.853 [main] WARN  o.e.s.s.finder.widgets.SWTBotButton - Widget is not enabled: (of type 'Button' and with mnemonic 'OK' and with style 'SWT.PUSH')
00:18:50.854 [main] WARN  o.e.s.s.finder.widgets.SWTBotButton - Widget is not enabled: (of type 'Button' and with mnemonic 'OK' and with style 'SWT.PUSH')
00:18:50.854 [main] WARN  o.e.s.s.finder.widgets.SWTBotButton - Widget is not enabled: (of type 'Button' and with mnemonic 'OK' and with style 'SWT.PUSH')
00:18:50.854 [main] WARN  o.e.s.s.finder.widgets.SWTBotButton - Widget is not enabled: (of type 'Button' and with mnemonic 'OK' and with style 'SWT.PUSH')
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x800021 (data - Ecl)
Window manager warning: meta_window_activate called by a pager with a 0 timestamp; the pager needs to be fixed.
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 60.653 sec <<< FAILURE! - in com.google.cloud.tools.eclipse.integration.appengine.DebugNativeAppEngineStandardProjectTest

testDebugLaunch(com.google.cloud.tools.eclipse.integration.appengine.DebugNativeAppEngineStandardProjectTest)  Time elapsed: 57.181 sec  <<< ERROR!
org.eclipse.swtbot.swt.finder.exceptions.WidgetNotFoundException: Could not find menu item matching: with mnemonic '1 Debug on Server'
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:522)
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:496)
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:484)
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntilWidgetAppears(SWTBotFactory.java:466)
	at org.eclipse.swtbot.swt.finder.widgets.SWTBotMenu.menu(SWTBotMenu.java:272)
	at org.eclipse.swtbot.swt.finder.widgets.SWTBotMenu.menu(SWTBotMenu.java:255)
	at org.eclipse.swtbot.swt.finder.widgets.SWTBotMenu.menu(SWTBotMenu.java:217)
	at com.google.cloud.tools.eclipse.integration.appengine.DebugNativeAppEngineStandardProjectTest.lambda$testDebugLaunch$0(DebugNativeAppEngineStandardProjectTest.java:97)
```

**Comment by briandealwis** [comment]
The context menu may take time to populate, I guess.

**Comment by chanseokoh** [comment]
Saw this three times today.

**Comment by briandealwis** [comment]
Saw this just now on Oxygen:
```
[Watchdog] > testDebugLaunch(com.google.cloud.tools.eclipse.integration.appengine.DebugNativeAppEngineStandardProjectTest)
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x8002c0 (New Projec)
Window manager warning: meta_window_activate called by a pager with a 0 timestamp; the pager needs to be fixed.
18:54:46.256 [main] WARN  o.e.s.s.finder.widgets.SWTBotButton - Widget is not enabled: (of type 'Button' and with mnemonic 'Next >' and with style 'SWT.PUSH')
18:54:46.261 [main] WARN  o.e.s.s.finder.widgets.SWTBotButton - Widget is not enabled: (of type 'Button' and with mnemonic 'Next >' and with style 'SWT.PUSH')
18:54:46.263 [main] WARN  o.e.s.s.finder.widgets.SWTBotButton - Widget is not enabled: (of type 'Button' and with mnemonic 'Next >' and with style 'SWT.PUSH')
18:54:46.266 [main] WARN  o.e.s.s.finder.widgets.SWTBotButton - Widget is not enabled: (of type 'Button' and with mnemonic 'Next >' and with style 'SWT.PUSH')
18:54:46.268 [main] WARN  o.e.s.s.finder.widgets.SWTBotButton - Widget is not enabled: (of type 'Button' and with mnemonic 'Next >' and with style 'SWT.PUSH')
18:54:46.398 [main] WARN  o.e.s.s.finder.widgets.SWTBotButton - Widget is not enabled: (of type 'Button' and with mnemonic 'Finish' and with style 'SWT.PUSH')
18:54:46.399 [main] WARN  o.e.s.s.finder.widgets.SWTBotButton - Widget is not enabled: (of type 'Button' and with mnemonic 'Finish' and with style 'SWT.PUSH')
18:54:46.400 [main] WARN  o.e.s.s.finder.widgets.SWTBotButton - Widget is not enabled: (of type 'Button' and with mnemonic 'Finish' and with style 'SWT.PUSH')
18:54:46.400 [main] WARN  o.e.s.s.finder.widgets.SWTBotButton - Widget is not enabled: (of type 'Button' and with mnemonic 'Finish' and with style 'SWT.PUSH')
18:54:46.401 [main] WARN  o.e.s.s.finder.widgets.SWTBotButton - Widget is not enabled: (of type 'Button' and with mnemonic 'Finish' and with style 'SWT.PUSH')
18:54:46.981 [ModalContext] DEBUG c.g.c.t.e.a.f.AppEngineStandardFacet - testapp_java8: current facets: []
18:54:47.266 [ModalContext] DEBUG c.g.c.t.e.a.f.AppEngineStandardJre7ProjectFacetDetector - skipping testapp_java8: appengine-web.xml is not java7
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x80042a (User Opera)
Window manager warning: meta_window_activate called by a pager with a 0 timestamp; the pager needs to be fixed.
18:54:47.735 [ModalContext] DEBUG c.g.c.t.e.a.f.AppEngineStandardFacet - testapp_java8: detector changes: [INSTALL[com.google.cloud.tools.eclipse.appengine.facets.standard JRE8], INSTALL[jst.web 3.1], INSTALL[java 1.8]]
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x8002c0 (New App En)
Window manager warning: meta_window_activate called by a pager with a 0 timestamp; the pager needs to be fixed.
18:54:49.729 [ModalContext] DEBUG c.g.c.t.e.a.s.j.AppEngineStandardFacetChangeListener - Facet change: App Engine Java Standard Environment
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x800021 (data - tes)
Window manager warning: meta_window_activate called by a pager with a 0 timestamp; the pager needs to be fixed.
18:55:29.362 [WorkbenchTestable] WARN  o.e.s.s.f.widgets.SWTBotTreeItem - Tree item TreeItem with text {testapp_java8} is already collapsed. Won't collapse it again.
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x800995 (Delete Res)
Window manager warning: meta_window_activate called by a pager with a 0 timestamp; the pager needs to be fixed.
18:55:30.660 [main] WARN  o.e.s.s.finder.widgets.SWTBotButton - Widget is not enabled: (of type 'Button' and with mnemonic 'OK' and with style 'SWT.PUSH')
18:55:30.663 [main] WARN  o.e.s.s.finder.widgets.SWTBotButton - Widget is not enabled: (of type 'Button' and with mnemonic 'OK' and with style 'SWT.PUSH')
18:55:30.665 [main] WARN  o.e.s.s.finder.widgets.SWTBotButton - Widget is not enabled: (of type 'Button' and with mnemonic 'OK' and with style 'SWT.PUSH')
18:55:30.671 [main] WARN  o.e.s.s.finder.widgets.SWTBotButton - Widget is not enabled: (of type 'Button' and with mnemonic 'OK' and with style 'SWT.PUSH')
18:55:30.674 [main] WARN  o.e.s.s.finder.widgets.SWTBotButton - Widget is not enabled: (of type 'Button' and with mnemonic 'OK' and with style 'SWT.PUSH')
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x800021 (data - Ecl)
Window manager warning: meta_window_activate called by a pager with a 0 timestamp; the pager needs to be fixed.
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 50.911 sec <<< FAILURE! - in com.google.cloud.tools.eclipse.integration.appengine.DebugNativeAppEngineStandardProjectTest
testDebugLaunch(com.google.cloud.tools.eclipse.integration.appengine.DebugNativeAppEngineStandardProjectTest)  Time elapsed: 47.013 sec  <<< ERROR!
org.eclipse.swtbot.swt.finder.widgets.TimeoutException: Timeout after: 30000 ms.: Never matched menu with a string ending with "Debug on Server"
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:522)
	at org.eclipse.swtbot.swt.finder.SWTBot.waitUntil(SWTBot.java:1)
	at org.eclipse.swtbot.eclipse.finder.SWTWorkbenchBot.waitUntil(SWTWorkbenchBot.java:1)
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:496)
	at org.eclipse.swtbot.swt.finder.SWTBot.waitUntil(SWTBot.java:1)
	at org.eclipse.swtbot.eclipse.finder.SWTWorkbenchBot.waitUntil(SWTWorkbenchBot.java:1)
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:484)
	at org.eclipse.swtbot.swt.finder.SWTBot.waitUntil(SWTBot.java:1)
	at org.eclipse.swtbot.eclipse.finder.SWTWorkbenchBot.waitUntil(SWTWorkbenchBot.java:1)
	at com.google.cloud.tools.eclipse.swtbot.SwtBotTestingUtilities.waitUntilMenuHasItem(SwtBotTestingUtilities.java:184)
	at com.google.cloud.tools.eclipse.integration.appengine.DebugNativeAppEngineStandardProjectTest.testDebugLaunch(DebugNativeAppEngineStandardProjectTest.java:93)
```

**Comment by briandealwis** [comment]
Screencap doesn't show anything interesting (https://console.cloud.google.com/storage/browser/travis_artifacts/travis/13421/13421.2-linux-20180709-1902/plugins/com.google.cloud.tools.eclipse.integration.appengine/screenshots/)

**Comment by chanseokoh** [comment]
From previous logs (https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/2867#issuecomment-391572806), we know that the menu contains "1 App Engine" and only that.

From the [screenshot above](https://console.cloud.google.com/storage/browser/travis_artifacts/travis/13421/13421.2-linux-20180709-1902/plugins/com.google.cloud.tools.eclipse.integration.appengine/screenshots/), although there is a dotted box around the test project, it may be that the project is not actually selected. At least that is true in my Eclipse instance. In the screenshot below, the closed "_BlobstoreTest" project has a dotted box below, but _Run_ > _Debug As_ is showing "1 App Engine" and XSLT items. When the project is explicitly selected, it rather shows a single item "(none applicable)".

![selection_001](https://user-images.githubusercontent.com/10523105/42477637-e1bb03ca-839f-11e8-914e-36211c820426.png)

Of course, the _Properties_ menu is disabled too.

![selection_002](https://user-images.githubusercontent.com/10523105/42477635-de502698-839f-11e8-9aa8-64350093c816.png)

It's worth trying to select the test project before checking the menu, or instead just right-click on the project for the menu.

**Comment by briandealwis** [comment]
Happened on Oxygen.  From the screen cap, it looks like the selection hasn't taken.

```
Running com.google.cloud.tools.eclipse.integration.appengine.DebugNativeAppEngineStandardProjectTest
16:01:25.125 [WorkbenchTestable] DEBUG c.g.c.t.a.o.cloudsdk.PathResolver - Resolved SDK path : /home/travis/google-cloud-sdk
[Watchdog] > testDebugLaunch(com.google.cloud.tools.eclipse.integration.appengine.DebugNativeAppEngineStandardProjectTest)
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x8002c3 (New Projec)
Window manager warning: meta_window_activate called by a pager with a 0 timestamp; the pager needs to be fixed.
16:01:28.542 [main] WARN  o.e.s.s.finder.widgets.SWTBotButton - Widget is not enabled: (of type 'Button' and with mnemonic 'Next >' and with style 'SWT.PUSH')
16:01:28.546 [main] WARN  o.e.s.s.finder.widgets.SWTBotButton - Widget is not enabled: (of type 'Button' and with mnemonic 'Next >' and with style 'SWT.PUSH')
16:01:28.547 [main] WARN  o.e.s.s.finder.widgets.SWTBotButton - Widget is not enabled: (of type 'Button' and with mnemonic 'Next >' and with style 'SWT.PUSH')
16:01:28.549 [main] WARN  o.e.s.s.finder.widgets.SWTBotButton - Widget is not enabled: (of type 'Button' and with mnemonic 'Next >' and with style 'SWT.PUSH')
16:01:28.550 [main] WARN  o.e.s.s.finder.widgets.SWTBotButton - Widget is not enabled: (of type 'Button' and with mnemonic 'Next >' and with style 'SWT.PUSH')
16:01:28.685 [main] WARN  o.e.s.s.finder.widgets.SWTBotButton - Widget is not enabled: (of type 'Button' and with mnemonic 'Finish' and with style 'SWT.PUSH')
16:01:28.686 [main] WARN  o.e.s.s.finder.widgets.SWTBotButton - Widget is not enabled: (of type 'Button' and with mnemonic 'Finish' and with style 'SWT.PUSH')
16:01:28.686 [main] WARN  o.e.s.s.finder.widgets.SWTBotButton - Widget is not enabled: (of type 'Button' and with mnemonic 'Finish' and with style 'SWT.PUSH')
16:01:28.686 [main] WARN  o.e.s.s.finder.widgets.SWTBotButton - Widget is not enabled: (of type 'Button' and with mnemonic 'Finish' and with style 'SWT.PUSH')
16:01:28.686 [main] WARN  o.e.s.s.finder.widgets.SWTBotButton - Widget is not enabled: (of type 'Button' and with mnemonic 'Finish' and with style 'SWT.PUSH')
16:01:29.033 [ModalContext] DEBUG c.g.c.t.e.a.f.AppEngineStandardFacet - testapp_java8: current facets: []
16:01:29.804 [ModalContext] DEBUG c.g.c.t.e.a.f.AppEngineStandardJre7ProjectFacetDetector - skipping testapp_java8: appengine-web.xml is not java7
16:01:29.927 [ModalContext] DEBUG c.g.c.t.e.a.f.AppEngineStandardFacet - testapp_java8: detector changes: [INSTALL[java 1.8], INSTALL[com.google.cloud.tools.eclipse.appengine.facets.standard JRE8], INSTALL[jst.web 3.1]]
16:01:30.907 [ModalContext] DEBUG c.g.c.t.e.a.s.j.AppEngineStandardFacetChangeListener - Facet change: App Engine Java Standard Environment
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x800021 (data - tes)
Window manager warning: meta_window_activate called by a pager with a 0 timestamp; the pager needs to be fixed.
16:02:14.096 [WorkbenchTestable] WARN  o.e.s.s.f.widgets.SWTBotTreeItem - Tree item TreeItem with text {testapp_java8} is already collapsed. Won't collapse it again.
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x80095b (Delete Res)
Window manager warning: meta_window_activate called by a pager with a 0 timestamp; the pager needs to be fixed.
16:02:15.215 [main] WARN  o.e.s.s.finder.widgets.SWTBotButton - Widget is not enabled: (of type 'Button' and with mnemonic 'OK' and with style 'SWT.PUSH')
16:02:15.217 [main] WARN  o.e.s.s.finder.widgets.SWTBotButton - Widget is not enabled: (of type 'Button' and with mnemonic 'OK' and with style 'SWT.PUSH')
16:02:15.219 [main] WARN  o.e.s.s.finder.widgets.SWTBotButton - Widget is not enabled: (of type 'Button' and with mnemonic 'OK' and with style 'SWT.PUSH')
16:02:15.220 [main] WARN  o.e.s.s.finder.widgets.SWTBotButton - Widget is not enabled: (of type 'Button' and with mnemonic 'OK' and with style 'SWT.PUSH')
16:02:15.222 [main] WARN  o.e.s.s.finder.widgets.SWTBotButton - Widget is not enabled: (of type 'Button' and with mnemonic 'OK' and with style 'SWT.PUSH')
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x800021 (data - Ecl)
Window manager warning: meta_window_activate called by a pager with a 0 timestamp; the pager needs to be fixed.
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 51.508 s <<< FAILURE! - in com.google.cloud.tools.eclipse.integration.appengine.DebugNativeAppEngineStandardProjectTest
testDebugLaunch(com.google.cloud.tools.eclipse.integration.appengine.DebugNativeAppEngineStandardProjectTest)  Time elapsed: 48.467 s  <<< ERROR!
org.eclipse.swtbot.swt.finder.widgets.TimeoutException: Timeout after: 30000 ms.: Never matched menu with a string ending with "Debug on Server"
	at com.google.cloud.tools.eclipse.integration.appengine.DebugNativeAppEngineStandardProjectTest.testDebugLaunch(DebugNativeAppEngineStandardProjectTest.java:89)
```

![travis-14105-14105 1-linux-20190212-1608-plugins-com google cloud tools eclipse integration appengine-screenshots-testdebuglaunch com google cloud tools eclipse integration appengine debugnativeappenginestandardprojecttest](https://user-images.githubusercontent.com/202851/52650389-2c15d800-2eb8-11e9-9c78-db726d608d55.jpeg)

**Comment by JoeWang1127** [comment]
close as not planned
