### ISSUE TITLE
I am using JDK not JRE. I checked this hundred times

### ISSUE THREAD

**Issue by Blasanka** [GoogleCloudPlatform/google-cloud-eclipse#2884]
Before reporting a possible bug:

1. Please ensure you are running the latest version of CT4E with _Help > Check for Updates_
2. If the problem occurs when you deploy or after the application has been deployed, try deploying from the command line using gcloud or Maven. If the problem does not go away, then the issue is likely not with Cloud Tools for Eclipse.

- Cloud Tools for Eclipse version: 1.5.1.201801292341
- Google Cloud SDK version: 185.0.0
- Eclipse version: 4.6.3.v20170301-0400
- OS: Windows 10 10.0
- Java version: 1.8.0_131

**What did you do?**
Deployed my standard app to AppEngine

**What did you expect to see?**
I wanted to see Successfully deployed

**What did you see instead?**
but, Unable to stage app: Cannot get the System Java Compiler. Please use a JDK, not a JRE.

Stackoverflow answers are also saying to use JDK and I am using the JDK. Below is my JAVA_HOME
C:\Program Files (x86)\Java\jdk1.8.0_40

eclipse.ini

-startup
plugins/org.eclipse.equinox.launcher_1.3.201.v20161025-1711.jar
--launcher.library
C:\Users\BLiyanage\.p2\pool\plugins\org.eclipse.equinox.launcher.win32.win32.x86_1.1.401.v20161122-1740
-product
org.eclipse.epp.package.jee.product
--launcher.defaultAction
openFile
-showsplash
org.eclipse.platform
--launcher.appendVmargs
-vmargs
-Dosgi.requiredJavaVersion=1.8
-XX:+UseG1GC
-XX:+UseStringDeduplication
-Dosgi.requiredJavaVersion=1.8
-Xms256m
-Xmx1024m
-Declipse.p2.max.threads=10
-Doomph.update.url=http://download.eclipse.org/oomph/updates/milestone/latest
-Doomph.redirection.index.redirection=index:/->http://git.eclipse.org/c/oomph/org.eclipse.oomph.git/plain/setups/
-vm
C:\Program Files (x86)\Java\jdk1.8.0_40\bin\javaw.exe

log file

Unable to stage:
java.lang.RuntimeException: Cannot get the System Java Compiler. Please use a JDK, not a JRE.
	at com.google.appengine.tools.admin.Application.compileJspJavaFiles(Application.java:1287)
	at com.google.appengine.tools.admin.Application.compileJsps(Application.java:1264)
	at com.google.appengine.tools.admin.Application.populateStagingDirectory(Application.java:975)
	at com.google.appengine.tools.admin.Application.createStagingDirectory(Application.java:872)
	at com.google.appengine.tools.admin.AppAdminImpl.stageApplication(AppAdminImpl.java:539)
	at com.google.appengine.tools.admin.AppAdminImpl.stageApplicationWithDefaultResourceLimits(AppAdminImpl.java:492)
	at com.google.appengine.tools.admin.AppCfg$StagingAction.execute(AppCfg.java:2530)
	at com.google.appengine.tools.admin.AppCfg.executeAction(AppCfg.java:391)
	at com.google.appengine.tools.admin.AppCfg.<init>(AppCfg.java:214)
	at com.google.appengine.tools.admin.AppCfg.<init>(AppCfg.java:120)
	at com.google.appengine.tools.admin.AppCfg.main(AppCfg.java:116)
com.google.appengine.tools.admin.AdminException: Unable to stage app: Cannot get the System Java Compiler. Please use a JDK, not a JRE.
	at com.google.appengine.tools.admin.AppAdminImpl.stageApplication(AppAdminImpl.java:543)
	at com.google.appengine.tools.admin.AppAdminImpl.stageApplicationWithDefaultResourceLimits(AppAdminImpl.java:492)
	at com.google.appengine.tools.admin.AppCfg$StagingAction.execute(AppCfg.java:2530)
	at com.google.appengine.tools.admin.AppCfg.executeAction(AppCfg.java:391)
	at com.google.appengine.tools.admin.AppCfg.<init>(AppCfg.java:214)
	at com.google.appengine.tools.admin.AppCfg.<init>(AppCfg.java:120)
	at com.google.appengine.tools.admin.AppCfg.main(AppCfg.java:116)
Caused by: java.lang.RuntimeException: Cannot get the System Java Compiler. Please use a JDK, not a JRE.
	at com.google.appengine.tools.admin.Application.compileJspJavaFiles(Application.java:1287)
	at com.google.appengine.tools.admin.Application.compileJsps(Application.java:1264)
	at com.google.appengine.tools.admin.Application.populateStagingDirectory(Application.java:975)
	at com.google.appengine.tools.admin.Application.createStagingDirectory(Application.java:872)
	at com.google.appengine.tools.admin.AppAdminImpl.stageApplication(AppAdminImpl.java:539)
	... 6 more

Screenshots and stacktraces are helpful.

**Comment by elharo** [comment]
Not sure but this might be a clue.  I notice that Eclipse is running with

Java version: 1.8.0_131

but JAVA_HOME is pointing to jdk1.8.0_40

so there are at least two Java VMs on this system and maybe it isn't using the one you think it is.

**Comment by chanseokoh** [comment]
Regardless of your JDK you use to execute your Eclipse, your project may have been configured to use a difference JDK or JRE.

https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/2548#issuecomment-341203524

> You need to ensure that your project's selected option is pointing to a JDK. My guess is that it's pointing to a JRE.

**Comment by briandealwis** [comment]
So the crux here is: can we programatically check whether a JDT VM installation (listed in the _Java > Installed JREs_ preference page) has a Java System Compiler.  As near as I can tell, the App Engine tools JSP compiler uses the [`ToolProvider.getSystemJavaCompiler()`](https://stackoverflow.com/a/7833634/600339) approach to get the compiler.

On Java 7 and Java 8 installs, this call tries to resolve a class `com.sun.tools.javac.api.JavacTool`, first through the classloader, and then by grovelling for a `lib/tools.jar` and loading it from there.  (I wonder if this would work with OpenJ9?)

On Java 9 (and later, I hope), the compiler is in the `java.compiler` module, and we can check if there's a `java.compiler.jmod` module in `<VMHOME>/jmods`.

My proposal is to have apply these heuristics and prompt the user with an option to ignore the error. Either via a builder that creates an error marker, or at deploy time (report via `MessageDialogWithToggle`).
