### ISSUE TITLE
Deleting a project in a server may lead to long hang

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#2922]
In testing, I somehow got into this odd situation where there was a _Stopping App Engine Standard on localhost_ job kicking around for several minutes.  I had deleted AES projects that had been launched; I *think* I had stopped the servers, but it's possible I hadn't.

A `jstack` on the process showed a single job:
```
"Worker-16" #269 prio=5 os_prio=31 tid=0x00007fc2dd18a000 nid=0x1fb6f in Object.wait() [0x0000700011c11000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at org.eclipse.wst.server.core.internal.Server.stopImpl(Server.java:3657)
	- locked <0x00000006c495f9b0> (a java.lang.Object)
	at org.eclipse.wst.server.core.internal.Server$StopJob.run(Server.java:403)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by chanseokoh** [comment]
I think this is a dup of #1729.
