### ISSUE TITLE
can't deploy to GAE - 500 error

### ISSUE THREAD

**Issue by Rob46** [GoogleCloudPlatform/google-cloud-eclipse#2976]
- Cloud Tools for Eclipse version: 1.6.0.201803071812
- Google Cloud SDK version: 194.0.0
- Eclipse version: 4.6.3.v20170301-0400
- OS: Windows 10 10.0
- Java version: 1.8.0_121

For some reason I stopped being able to deploy on Sunday 3/25 (and still cannot). More correctly, I could deploy seemingly without errors, but the site won't load and just gives a 500 error. I don't believe anything has changed on my end (a new deploy to a new version was being tested with a single minor change css change).

Output from deploy:

```
Mar 26, 2018 11:31:51 AM java.util.prefs.WindowsPreferences <init>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
Reading application configuration data...
Mar 26, 2018 11:31:51 AM com.google.apphosting.utils.config.IndexesXmlReader readConfigXml
INFO: Successfully processed C:/Users/rober/Software Development/Eclipse Workspace/.metadata/.plugins/com.google.cloud.tools.eclipse.appengine.deploy/tmp/1522078303549/staging-work/exploded-war\WEB-INF/datastore-indexes.xml


Beginning interaction for module default...
0% Scanning for jsp files.
0% Compiling jsp files.
Mar 26, 2018 11:31:59 AM org.apache.jasper.servlet.TldScanner scanJars
INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
Mar 26, 2018 11:32:00 AM org.apache.jasper.JspC processFile
INFO: Built File: \overview.jsp
Mar 26, 2018 11:32:00 AM org.apache.jasper.JspC processFile
INFO: Built File: \about\about-us.jsp
Mar 26, 2018 11:32:00 AM org.apache.jasper.JspC processFile
INFO: Built File: \about\best-practices.jsp
Mar 26, 2018 11:32:00 AM org.apache.jasper.JspC processFile
INFO: Built File: \about\change-log.jsp
Mar 26, 2018 11:32:00 AM org.apache.jasper.JspC processFile
INFO: Built File: \about\confirm-accept-invite.jsp
Mar 26, 2018 11:32:00 AM org.apache.jasper.JspC processFile
INFO: Built File: \about\create-account-form.jsp
Mar 26, 2018 11:32:00 AM org.apache.jasper.JspC processFile
INFO: Built File: \about\create-account.jsp
Mar 26, 2018 11:32:00 AM org.apache.jasper.JspC processFile
INFO: Built File: \about\dedicated-server.jsp
Mar 26, 2018 11:32:00 AM org.apache.jasper.JspC processFile
INFO: Built File: \about\error.jsp
Mar 26, 2018 11:32:00 AM org.apache.jasper.JspC processFile
INFO: Built File: \about\eu-gdpr.jsp
Mar 26, 2018 11:32:00 AM org.apache.jasper.JspC processFile
INFO: Built File: \about\integration.jsp
Mar 26, 2018 11:32:00 AM org.apache.jasper.JspC processFile
INFO: Built File: \about\license.jsp
Mar 26, 2018 11:32:00 AM org.apache.jasper.JspC processFile
INFO: Built File: \about\ms-access-alternative.jsp
Mar 26, 2018 11:32:00 AM org.apache.jasper.JspC processFile
INFO: Built File: \about\pricing-old.jsp
Mar 26, 2018 11:32:00 AM org.apache.jasper.JspC processFile
INFO: Built File: \about\pricing.jsp
Mar 26, 2018 11:32:00 AM org.apache.jasper.JspC processFile
INFO: Built File: \about\privacy.jsp
Mar 26, 2018 11:32:00 AM org.apache.jasper.JspC processFile
INFO: Built File: \about\request-trial-account.jsp
Mar 26, 2018 11:32:00 AM org.apache.jasper.JspC processFile
INFO: Built File: \about\rest-api.jsp
Mar 26, 2018 11:32:00 AM org.apache.jasper.JspC processFile
INFO: Built File: \about\sla.jsp
Mar 26, 2018 11:32:00 AM org.apache.jasper.JspC processFile
INFO: Built File: \about\support-forum.jsp
Mar 26, 2018 11:32:00 AM org.apache.jasper.JspC processFile
INFO: Built File: \about\support.jsp
Mar 26, 2018 11:32:00 AM org.apache.jasper.JspC processFile
INFO: Built File: \about\thank-you.jsp
Mar 26, 2018 11:32:00 AM org.apache.jasper.JspC processFile
INFO: Built File: \about\videos.jsp
Mar 26, 2018 11:32:00 AM org.apache.jasper.JspC processFile
INFO: Built File: \about\why.jsp
Mar 26, 2018 11:32:00 AM org.apache.jasper.JspC processFile
INFO: Built File: \about\include\core-message.jsp
Mar 26, 2018 11:32:00 AM org.apache.jasper.JspC processFile
INFO: Built File: \about\include\core-top-right.jsp
Mar 26, 2018 11:32:00 AM org.apache.jasper.JspC processFile
INFO: Built File: \about\include\create-trial-account-box.jsp
Mar 26, 2018 11:32:00 AM org.apache.jasper.JspC processFile
INFO: Built File: \about\include\footer.jsp
Mar 26, 2018 11:32:00 AM org.apache.jasper.JspC processFile
INFO: Built File: \about\include\header.jsp
Mar 26, 2018 11:32:00 AM org.apache.jasper.JspC processFile
INFO: Built File: \about\include\request-form.jsp
Mar 26, 2018 11:32:00 AM org.apache.jasper.JspC processFile
INFO: Built File: \about\ad\RAD.jsp
Success.
Temporary staging for module default directory left in C:\Users\rober\Software Development\Eclipse Workspace\.metadata\.plugins\com.google.cloud.tools.eclipse.appengine.deploy\tmp\1522078303549\staging
Services to deploy:

descriptor:      [C:\Users\rober\Software Development\Eclipse Workspace\.metadata\.plugins\com.google.cloud.tools.eclipse.appengine.deploy\tmp\1522078303549\staging\app.yaml]
source:          [C:\Users\rober\Software Development\Eclipse Workspace\.metadata\.plugins\com.google.cloud.tools.eclipse.appengine.deploy\tmp\1522078303549\staging]
target project:  [parasql-app]
target service:  [default]
target version:  [69]
target url:      [https://69-dot-parasql-app.appspot.com]


     (add --promote if you also want to make this service available from
     [https://parasql-app.appspot.com])

Configurations to update:

descriptor:      [C:\Users\rober\Software Development\Eclipse Workspace\.metadata\.plugins\com.google.cloud.tools.eclipse.appengine.deploy\tmp\1522078303549\staging\WEB-INF\appengine-generated\cron.yaml]
type:            [cron jobs]
target project:  [parasql-app]


descriptor:      [C:\Users\rober\Software Development\Eclipse Workspace\.metadata\.plugins\com.google.cloud.tools.eclipse.appengine.deploy\tmp\1522078303549\staging\WEB-INF\appengine-generated\dos.yaml]
type:            [DoS blacklist]
target project:  [parasql-app]


descriptor:      [C:\Users\rober\Software Development\Eclipse Workspace\.metadata\.plugins\com.google.cloud.tools.eclipse.appengine.deploy\tmp\1522078303549\staging\WEB-INF\appengine-generated\index.yaml]
type:            [datastore indexes]
target project:  [parasql-app]


descriptor:      [C:\Users\rober\Software Development\Eclipse Workspace\.metadata\.plugins\com.google.cloud.tools.eclipse.appengine.deploy\tmp\1522078303549\staging\WEB-INF\appengine-generated\queue.yaml]
type:            [task queues]
target project:  [parasql-app]


Beginning deployment of service [default]...
Some files were skipped. Pass `--verbosity=info` to see which ones.
You may also view the gcloud log file, found at
[C:\Users\rober\AppData\Roaming\gcloud\logs\2018.03.26\11.32.03.520000.log].
#============================================================#
#= Uploading 2 files to Google Cloud Storage                =#
#============================================================#
File upload done.
Updating service [default]...
...........................done.
Deployed service [default] to [https://69-dot-parasql-app.appspot.com]
Updating config [cron]...
done.
Updating config [dos]...
done.
Updating config [index]...
done.
Updating config [queue]...
done.

Cron jobs have been updated.

DoS protection has been updated.

To delete all blacklist entries, redeploy the dos.yaml file with the following content:
    blacklist:

Task queues have been updated.

Visit the Cloud Platform Console Task Queues page to view your queues and cron jobs.

Indexes are being rebuilt. This may take a moment.

You can stream logs from the command line by running:
  $ gcloud app logs tail -s default

To view your application in the web browser run:
  $ gcloud app browse
```

And all I get when I try to access is a 500 error:

![image](https://user-images.githubusercontent.com/25462429/37916454-debb6e5c-30e9-11e8-870d-a6c66807054a.png)

**Comment by elharo** [comment]
I think this is a Java bug on Windows:
https://stackoverflow.com/questions/16428098/groovy-shell-warning-could-not-open-create-prefs-root-node

**Comment by chanseokoh** [comment]
You may (or may not) be hitting https://issuetracker.google.com/76144204. For the 500 error, you'll be able to check the exact error message on https://console.cloud.google.com/. (Select your project and navigate to _Logging_.)

**Comment by Rob46** [comment]
It sure looks like the same issue. Stack trace:

```
2018-03-26 15:04:06.452 EDT
org.eclipse.jetty.servlet.ServletHandler doHandle:  (ServletHandler.java:624)
javax.servlet.ServletException: java.lang.NoClassDefFoundError: com/google/appengine/api/users/UserServiceFactory
	at org.apache.jasper.runtime.PageContextImpl.doHandlePageException(PageContextImpl.java:909)
	at org.apache.jasper.runtime.PageContextImpl.handlePageException(PageContextImpl.java:838)
	at org.apache.jsp.about.include.header_jsp._jspService(header_jsp.java:169)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:848)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:584)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:566)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)

```

**Comment by chanseokoh** [comment]
@Rob46 please see https://issuetracker.google.com/76144204#comment46 and https://issuetracker.google.com/76144204#comment47 for a fix or a workaround.

The server has made a breaking change (precisely speaking, fixed a long-overdue bug). The bug always provided the App Engine API, and now you need to explicitly place the `appengine-api-1.0-sdk` JAR into your `WEB-INF/lib`. (Precisely speaking, the JAR `appengine-api-1.0-sdk` in your `WEB-INF/lib` still won't get deployed, but if such a JAR is there, the server will continue to auto-provide the App Engine API in that case.)

Cross-ref: #2972

**Comment by elharo** [comment]
@patflynn The release QA process does include the use of appengine API classes that would have caught this when we next cut a release. However the change was made on the server between releases. I don't think we currently have any automated tests that touch production.

**Comment by Rob46** [comment]
For whatever reason, when I try **_today_** to deploy & run using v193 I am getting the same problem as v194 yesterday. Yesterday, v193 worked multiple times. Stumped. Will try the above fix by including the lib

**Comment by chanseokoh** [comment]
@Rob46 the server change is not instantaneous. Looks like it depends on to which server you app is deploy. I think the gcloud version doesn't matter here.

**Comment by Rob46** [comment]
It _seems_ to work. I placed appengine-api-1.0-sdk-1.9.31.jar into WEB-INF/lib and did nothing else except re-deploy. To make sure I understand, the presence of this file enables it somehow, but the version (1.9.31) doesn't matter and doesn't need to be kept current for the most up to date file to be used on the server.

Is that correct?

**Comment by chanseokoh** [comment]
@Rob46 that's right. The JAR in your `WEB-INF/lib` is removed anyway at the staging step locally before deployed, but the staging step will auto-generate `app.yaml` containing `api_version: '1.0'` if the JAR is present in `WEB-INF/lib`. Without the JAR, `app.yaml` will say `api_version: 'none'`.

You can actually check the staged app in Eclipse. When deploying, you'll see in the log at the beginning where the staged app lives.
```
Beginning interaction for module default...
0% Scanning for jsp files.
...
Success.
Temporary staging for module default directory left in <...>/workspace_eclipse/.metadata/.plugins/com.google.cloud.tools.eclipse.appengine.deploy/tmp/1522178503690/staging
Services to deploy:
```
`app.yaml` will be under `WEB-INF/appengine-generated/app.yaml` in that directory.
