### ISSUE TITLE
com.google.cloud.tools.eclipse.appengine.libraries.BuildPathTest.testCheckLibraries flakes

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#2980]
This has happened twice on the last two runs in different targets:

```
Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.6 sec <<< FAILURE! - in com.google.cloud.tools.eclipse.appengine.libraries.BuildPathTest

testAddNativeLibrary(com.google.cloud.tools.eclipse.appengine.libraries.BuildPathTest)  Time elapsed: 0.526 sec

testCheckLibraries(com.google.cloud.tools.eclipse.appengine.libraries.BuildPathTest)  Time elapsed: 0.564 sec  <<< FAILURE!

java.lang.AssertionError: null

	at org.junit.Assert.fail(Assert.java:86)

	at org.junit.Assert.assertTrue(Assert.java:41)

	at org.junit.Assert.assertFalse(Assert.java:64)

	at org.junit.Assert.assertFalse(Assert.java:74)

	at com.google.cloud.tools.eclipse.appengine.libraries.BuildPathTest.testCheckLibraries(BuildPathTest.java:108)

```

This is the line that fails:

    assertFalse(project.getProject().exists(librariesIdPath));

**Comment by briandealwis** [comment]
Dup #2758

**Comment by chanseokoh** [comment]
Dup. Closing. I've seen this many times lately.
