### ISSUE TITLE
Exception while loading Cloud Library cache LibraryClasspathContainerResolverService.libraryEntries

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#3055]
Can't reproduce it. Just noticed this is logged in my console. Might be just my hosted dev instance have gone borked, but at least I haven't touched code related to this.

The offending precondition violation:
```
                  ISchedulingRule currentRule = Job.getJobManager().currentRule();
                  Preconditions.checkState(
                      currentRule != null && currentRule.contains(MavenUtils.mavenResolvingRule()));
```

```
May 11, 2018 11:55:27 AM com.google.common.cache.LocalCache$Segment$1 run
WARNING: Exception thrown during refresh
java.util.concurrent.ExecutionException: java.lang.IllegalStateException
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:502)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:461)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:78)
	at com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:142)
	at com.google.common.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2461)
	at com.google.common.cache.LocalCache$Segment$1.run(LocalCache.java:2439)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:902)
	at com.google.common.util.concurrent.AbstractFuture.addListener(AbstractFuture.java:636)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.addListener(AbstractFuture.java:100)
	at com.google.common.cache.LocalCache$Segment.loadAsync(LocalCache.java:2434)
	at com.google.common.cache.LocalCache$Segment.refresh(LocalCache.java:2508)
	at com.google.common.cache.LocalCache$Segment.scheduleRefresh(LocalCache.java:2486)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2891)
	at com.google.common.cache.LocalCache.getIfPresent(LocalCache.java:4135)
	at com.google.common.cache.LocalCache$LocalManualCache.getIfPresent(LocalCache.java:5054)
	at com.google.cloud.tools.eclipse.appengine.libraries.repository.LibraryClasspathContainerResolverService.resolveLibraryAttachSources(LibraryClasspathContainerResolverService.java:155)
	at com.google.cloud.tools.eclipse.appengine.localserver.ServletClasspathProvider.resolveClasspathContainer(ServletClasspathProvider.java:77)
	at org.eclipse.jst.server.core.RuntimeClasspathProviderDelegate.resolveClasspathContainerImpl(RuntimeClasspathProviderDelegate.java:133)
	at org.eclipse.jst.server.core.internal.RuntimeClasspathProviderWrapper.resolveClasspathContainerImpl(RuntimeClasspathProviderWrapper.java:155)
	at org.eclipse.jst.server.core.internal.RuntimeClasspathContainer.getClasspathEntries(RuntimeClasspathContainer.java:77)
	at org.eclipse.jdt.internal.ui.packageview.ClassPathContainer.getChildren(ClassPathContainer.java:140)
	at org.eclipse.jdt.internal.ui.packageview.PackageExplorerContentProvider.getContainerPackageFragmentRoots(PackageExplorerContentProvider.java:373)
	at org.eclipse.jdt.internal.ui.packageview.PackageExplorerContentProvider.getChildren(PackageExplorerContentProvider.java:302)
	at org.eclipse.jdt.ui.StandardJavaElementContentProvider.hasChildren(StandardJavaElementContentProvider.java:236)
	at org.eclipse.jface.viewers.AbstractTreeViewer.isExpandable(AbstractTreeViewer.java:2107)
	at org.eclipse.jface.viewers.TreeViewer.isExpandable(TreeViewer.java:537)
	at org.eclipse.jdt.internal.ui.viewsupport.ProblemTreeViewer.isExpandable(ProblemTreeViewer.java:236)
	at org.eclipse.jface.viewers.AbstractTreeViewer.isExpandable(AbstractTreeViewer.java:2137)
	at org.eclipse.jface.viewers.AbstractTreeViewer.updatePlus(AbstractTreeViewer.java:2821)
	at org.eclipse.jface.viewers.TreeViewer.updatePlus(TreeViewer.java:785)
	at org.eclipse.jface.viewers.AbstractTreeViewer.createTreeItem(AbstractTreeViewer.java:841)
	at org.eclipse.jface.viewers.AbstractTreeViewer.lambda$0(AbstractTreeViewer.java:817)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.jface.viewers.AbstractTreeViewer.createChildren(AbstractTreeViewer.java:792)
	at org.eclipse.jface.viewers.TreeViewer.createChildren(TreeViewer.java:595)
	at org.eclipse.jface.viewers.AbstractTreeViewer.createChildren(AbstractTreeViewer.java:763)
	at org.eclipse.jface.viewers.AbstractTreeViewer.handleTreeExpand(AbstractTreeViewer.java:1482)
	at org.eclipse.jface.viewers.TreeViewer.handleTreeExpand(TreeViewer.java:880)
	at org.eclipse.jface.viewers.AbstractTreeViewer$3.treeExpanded(AbstractTreeViewer.java:1494)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:133)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5348)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1348)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1374)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1357)
	at org.eclipse.swt.widgets.Tree.gtk_test_expand_row(Tree.java:2396)
	at org.eclipse.swt.widgets.Widget.windowProc(Widget.java:2008)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5614)
	at org.eclipse.swt.internal.gtk.OS._gtk_main_do_event(Native Method)
	at org.eclipse.swt.internal.gtk.OS.gtk_main_do_event(OS.java:9282)
	at org.eclipse.swt.widgets.Display.eventProc(Display.java:1328)
	at org.eclipse.swt.internal.gtk.OS._g_main_context_iteration(Native Method)
	at org.eclipse.swt.internal.gtk.OS.g_main_context_iteration(OS.java:2116)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4181)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
Caused by: java.lang.IllegalStateException
	at com.google.common.base.Preconditions.checkState(Preconditions.java:429)
	at com.google.cloud.tools.eclipse.appengine.libraries.repository.LibraryClasspathContainerResolverService$1.load(LibraryClasspathContainerResolverService.java:96)
	at com.google.cloud.tools.eclipse.appengine.libraries.repository.LibraryClasspathContainerResolverService$1.load(LibraryClasspathContainerResolverService.java:1)
	at com.google.common.cache.CacheLoader.reload(CacheLoader.java:93)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3719)
	at com.google.common.cache.LocalCache$Segment.loadAsync(LocalCache.java:2433)
	... 66 more
```

**Comment by chanseokoh** [comment]
We should break the precondition into two.

**Comment by chanseokoh** [comment]
This seems to be happening repeatedly. Just don't know how to reproduce it consistently.

The code was recently (after our last 1.6.1 release) introduced in https://github.com/GoogleCloudPlatform/google-cloud-eclipse/pull/2999/files#diff-fc1c2e05d6b6df601fac069fab38320dR89.

**Comment by chanseokoh** [comment]
Easily reproducible at HEAD, when reducing the refresh time drastically. You'll need an App Engine project around. Refreshing the project will most likely surface the exception.
```diff
-          .refreshAfterWrite(10, TimeUnit.MINUTES)
+          .refreshAfterWrite(5, TimeUnit.SECONDS)
```

It's `Job.getJobManager().currentRule()` returning null.

**Comment by chanseokoh** [comment]
The loading is done in the main UI thread, but since `Job.getJobManager().getCurrentRule()` returns null, it means the main thread is not holding any scheduling rule. The Javadoc of `getCurrentRule()`:

```java
	 * Returns the scheduling rule currently held by this thread, or <code>null</code>
	 * if the current thread does not hold any scheduling rule.
```

I can reproduce this problem when interacting with the Package Explorer, which matches the stack trace:
```
	at org.eclipse.jst.server.core.RuntimeClasspathProviderDelegate.resolveClasspathContainerImpl(RuntimeClasspathProviderDelegate.java:133)
	at org.eclipse.jst.server.core.internal.RuntimeClasspathProviderWrapper.resolveClasspathContainerImpl(RuntimeClasspathProviderWrapper.java:155)
	at org.eclipse.jst.server.core.internal.RuntimeClasspathContainer.getClasspathEntries(RuntimeClasspathContainer.java:77)
	at org.eclipse.jdt.internal.ui.packageview.ClassPathContainer.getChildren(ClassPathContainer.java:140)
	at org.eclipse.jdt.internal.ui.packageview.PackageExplorerContentProvider.getContainerPackageFragmentRoots(PackageExplorerContentProvider.java:373)
	at org.eclipse.jdt.internal.ui.packageview.PackageExplorerContentProvider.getChildren(PackageExplorerContentProvider.java:302)
```

So, when the cache reload is triggered from the Package Explorer, the main thread seems holding no scheduling lock. @briandealwis any thoughts on this, since it's from #2999?

**Comment by chanseokoh** [comment]
I feel we don't need the prerequisite to hold the Maven resolving rule. `MavenUtils.resolveArtifact` will acquire it if it's not being held.

**Comment by briandealwis** [comment]
The problem is here:
```
	at com.google.common.cache.LocalCache$Segment.loadAsync(LocalCache.java:2434)
	at com.google.common.cache.LocalCache$Segment.refresh(LocalCache.java:2508)
	at com.google.common.cache.LocalCache$Segment.scheduleRefresh(LocalCache.java:2486)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2891)
	at com.google.common.cache.LocalCache.getIfPresent(LocalCache.java:4135)
	at com.google.common.cache.LocalCache$LocalManualCache.getIfPresent(LocalCache.java:5054)
	at com.google.cloud.tools.eclipse.appengine.libraries.repository.LibraryClasspathContainerResolverService.resolveLibraryAttachSources(LibraryClasspathContainerResolverService.java:155)
	at com.google.cloud.tools.eclipse.appengine.localserver.ServletClasspathProvider.resolveClasspathContainer(ServletClasspathProvider.java:77)
```

`resolveLibraryAttachSources()` tries to avoid creating a job (with the appropriate rule) by trying to see if the resolved libraries are available.  Unfortunately the `librariesEntries`'s `getIfPresent()` may trigger a load — I'd expect (reasonably, IMHO) a stale item would *not* be present.

Ahh… we configure out library cache with `refreshAfterWrite()`, but I suspect we should use `refreshAfterWrite()`.

**Comment by briandealwis** [comment]
I think we can `expireAfterAccess()`, and indeed  I don't see any `IllegalStateException`s after changing `refreshAfterWrite()` to `expireAfterAccess()` (and reducing the time out to 5 seconds).

**Comment by briandealwis** [comment]
(2) is an optimization: due to the project-level scheduling rule issue, we have to be able to fork off the resolve to a different job.  But if we can combine this with `MavenUtils#MavenUtils.isArtifactAvailableLocally()` then I think we can greatly reduce the chances of this different rule problem.
