### ISSUE TITLE
Test failure in DeployPropertyPageForNonGaeProjectTest#testCorrectPanelIsShownForFacetedProject

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#3071]
Seen on Oxygen.  The console seems to have a few things mixed up into it.
```
Running com.google.cloud.tools.eclipse.appengine.deploy.ui.DeployPropertyPageForNonGaeProjectTest

13:45:05.690 [main] DEBUG c.g.c.t.e.a.f.AppEngineStandardFacet - test0.15957763650698464: current facets: []

13:45:05.693 [main] DEBUG c.g.c.t.e.a.f.AppEngineStandardJre7ProjectFacetDetector - skipping test0.15957763650698464: cannot find appengine-web.xml

13:45:05.696 [main] DEBUG c.g.c.t.e.a.f.AppEngineStandardFacet - test0.15957763650698464: detector changes: []

13:45:05.702 [main] DEBUG c.g.c.t.e.a.f.AppEngineStandardFacet - test0.15957763650698464: installing default AES facet App Engine Java Standard Environment JRE7

13:45:05.707 [main] DEBUG c.g.c.t.e.a.f.AppEngineStandardFacet - test0.15957763650698464: adding Java facet Java 1.7

13:45:05.717 [main] DEBUG c.g.c.t.e.a.f.AppEngineStandardFacet - test0.15957763650698464: adding DWP facet Dynamic Web Module 2.5

Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 4.772 sec <<< FAILURE! - in com.google.cloud.tools.eclipse.appengine.deploy.ui.DeployPropertyPageForNonGaeProjectTest

testCorrectPanelIsShownForFacetedProject(com.google.cloud.tools.eclipse.appengine.deploy.ui.DeployPropertyPageForNonGaeProjectTest)  Time elapsed: 4.538 sec  <<< FAILURE!

java.lang.AssertionError: Could not create project

	at org.eclipse.jst.jee.model.internal.common.AbstractMergedModelProvider.getLastModificationTimeOfDDFile(AbstractMergedModelProvider.java:235)

	at org.eclipse.jst.jee.model.internal.common.AbstractMergedModelProvider.initMergedModelResource(AbstractMergedModelProvider.java:292)

	at org.eclipse.jst.jee.model.internal.common.AbstractMergedModelProvider.loadProviders(AbstractMergedModelProvider.java:270)

	at org.eclipse.jst.jee.model.internal.common.AbstractMergedModelProvider.access$2(AbstractMergedModelProvider.java:255)

	at org.eclipse.jst.jee.model.internal.common.AbstractMergedModelProvider$LoadModelsWorkspaceRunnable.run(AbstractMergedModelProvider.java:278)

	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)

	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2267)

	at org.eclipse.jst.jee.model.internal.common.AbstractMergedModelProvider.loadModel(AbstractMergedModelProvider.java:249)

	at org.eclipse.jst.jee.model.internal.common.AbstractMergedModelProvider.getMergedModel(AbstractMergedModelProvider.java:219)

	at org.eclipse.jst.jee.model.internal.Web25MergedModelProvider.modify(Web25MergedModelProvider.java:80)

	at org.eclipse.jst.j2ee.web.project.facet.WebFaImporting 1 projects:

    /home/travis/build/GoogleCloudPlatform/google-cloud-eclipse/plugins/com.google.cloud.tools.eclipse.appengine.facets.test/target/work/data/test-dynamic-web-project/.project

cetInstallDelegate.populateDefaultContent(WebFacetInstallDelegate.java:332)

	at org.eclipse.jst.j2ee.web.project.facet.WebFacetInstallDelegate.createWeb25DeploymentDescriptor(WebFacetInstallDelegate.java:295)

	at org.eclipse.jst.j2ee.web.project.facet.WebFacetInstallDelegate.execute(WebFacetInstallDelegate.java:133)

	at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.callDelegate(FacetedProject.java:1477)

	at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.modifyInternal(FacetedProject.java:441)

	at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.mergeChangesInternal(FacetedProject.java:1181)

	at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.access$2(FacetedProject.java:1117)

	at org.eclipse.wst.common.project.facet.core.internal.FacetedProject$1.run(FacetedProject.java:324)

	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)

	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2267)

	at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.modify(FacetedProject.java:339)

	at com.google.cloud.tools.eclipse.appengine.facets.FacetUtil.install(FacetUtil.java:240)

	at com.google.cloud.tools.eclipse.test.util.project.TestProjectCreator.addFacets(TestProjectCreator.java:183)

	at com.google.cloud.tools.eclipse.test.util.project.TestProjectCreator.createProject(TestProjectCreator.java:156)

	at com.google.cloud.tools.eclipse.test.util.project.TestProjectCreator.createProjectIfNecessary(TestProjectCreator.java:142)

	at com.google.cloud.tools.eclipse.test.util.project.TestProjectCreat13:45:11.122 [main] DEBUG c.g.c.t.e.a.f.AppEngineStandardFacet - test-dynamic-web-project: current facets: [Dynamic Web Module 2.5, JavaScript 1.0, Java 1.7]

13:45:11.138 [main] DEBUG c.g.c.t.e.a.f.AppEngineStandardJre7ProjectFacetDetector - skipping test-dynamic-web-project: cannot find appengine-web.xml

13:45:11.143 [main] DEBUG c.g.c.t.e.a.f.AppEngineStandardFacet - test-dynamic-web-project: detector changes: []

13:45:11.155 [main] DEBUG c.g.c.t.e.a.f.AppEngineStandardFacet - test-dynamic-web-project: installing default AES facet App Engine Java Standard Environment JRE7

or.getProject(TestProjectCreator.java:129)

	at com.google.cloud.tools.eclipse.appengine.deploy.ui.DeployPropertyPageForNonGaeProjectTest.getProject(DeployPropertyPageForNonGaeProjectTest.java:34)


```

**Comment by diegomarquezp** [comment]
Closing as GAE does not support the Java 8 runtime and we don't plan to support later versions.
