### ISSUE TITLE
Flake in NewNativeAppEngineStandardProjectTest: Unbound classpath container

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#3098]
Seen on Neon:
```
Tests run: 3, Failures: 1, Errors: 0, Skipped: 2, Time elapsed: 6.739 sec <<< FAILURE! - in com.google.cloud.tools.eclipse.integration.appengine.NewNativeAppEngineStandardProjectTest
testWithPackage_java7(com.google.cloud.tools.eclipse.integration.appengine.NewNativeAppEngineStandardProjectTest)  Time elapsed: 5.966 sec  <<< FAILURE!
java.lang.AssertionError: New native project has errors
/appWithPackage_java7:-1: The project cannot be built until build path errors are resolved
/appWithPackage_java7:-1: Unbound classpath container: 'JRE System Library [JavaSE-1.7]' in project 'appWithPackage_java7'
	at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.assertTrue(Assert.java:41)
	at com.google.cloud.tools.eclipse.test.util.project.ProjectUtils.failIfBuildErrors(ProjectUtils.java:209)
	at com.google.cloud.tools.eclipse.integration.appengine.NewNativeAppEngineStandardProjectTest.createAndCheck(NewNativeAppEngineStandardProjectTest.java:111)
	at com.google.cloud.tools.eclipse.integration.appengine.NewNativeAppEngineStandardProjectTest.testWithPackage_java7(NewNativeAppEngineStandardProjectTest.java:74)
```

**Comment by diegomarquezp** [comment]
Closing as not planned since Java 8 is not supported in GAE. cc: @blakeli0
