### ISSUE TITLE
Track and fix warnings and NPEs from integration tests

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#3104]
Seeing errors and warnings in Travis build logs like:

<hr>

```
!ENTRY org.eclipse.jst.j2ee 4 0 2018-05-24 11:01:23.791
!MESSAGE No IModelProvider exists for project P/appWithPackageProject of version: null
!STACK 0
java.lang.NullPointerException: No IModelProvider exists for project P/appWithPackageProject of version: null
	at org.eclipse.jst.j2ee.model.ModelProviderManager.getModelProvider(ModelProviderManager.java:101)
	at org.eclipse.jst.j2ee.model.ModelProviderManager.getModelProvider(ModelProviderManager.java:281)
	at org.eclipse.jst.jee.ui.internal.navigator.JEE5ContentProvider.getCachedContentProvider(JEE5ContentProvider.java:98)
	at org.eclipse.jst.jee.ui.internal.navigator.Web25ContentProvider.getChildren(Web25ContentProvider.java:35)
	at org.eclipse.ui.internal.navigator.extensions.SafeDelegateTreeContentProvider.getChildren(SafeDelegateTreeContentProvider.java:95)
	at org.eclipse.ui.internal.navigator.NavigatorContentServiceContentProvider$1.run(NavigatorContentServiceContentProvider.java:157)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.navigator.NavigatorContentServiceContentProvider.internalGetChildren(NavigatorContentServiceContentProvider.java:143)
	at org.eclipse.ui.internal.navigator.NavigatorContentServiceContentProvider.getChildren(NavigatorContentServiceContentProvider.java:122)
	at org.eclipse.jst.jee.ui.internal.navigator.JEE5ContentProvider$1.run(JEE5ContentProvider.java:142)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:37)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4577)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4186)
```

<hr>

```
!ENTRY org.eclipse.core.resources 4 372 2018-05-24 11:01:38.524
!MESSAGE Project 'appWithPackageProjectInTemp' is not open.
```

<hr>

```
!ENTRY org.eclipse.core.resources 2 2 2018-05-24 11:02:05.979
!MESSAGE Save operation warnings.
!SUBENTRY 1 org.eclipse.core.resources 2 234 2018-05-24 11:02:05.979
!MESSAGE The project description file (.project) for 'projectContextMenuJava7' was missing.  This file contains important information about the project.  A new project description file has been created, but some information about the project may have been lost.
```

<hr>

And sometimes `WebFragmentWarPublishTest#testPublishExploded_childModulePublished()`, which usually takes < 1 sec, times out and the test is killed.

**Comment by briandealwis** [comment]
The `No IModelProvider exists for project` seems to be [WTP bug 511541](https://bugs.eclipse.org/bugs/show_bug.cgi?id=511541).
