### ISSUE TITLE
Flakey test: FlexWarStagingDelegateTest#testStage()

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#3107]
```
Running com.google.cloud.tools.eclipse.appengine.deploy.flex.FlexWarStagingDelegateTest
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 5.973 sec <<< FAILURE! - in com.google.cloud.tools.eclipse.appengine.deploy.flex.FlexWarStagingDelegateTest
testStage(com.google.cloud.tools.eclipse.appengine.deploy.flex.FlexWarStagingDelegateTest)  Time elapsed: 2.916 sec  <<< FAILURE!
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.google.cloud.tools.eclipse.appengine.deploy.flex.FlexWarStagingDelegateTest.testStage(FlexWarStagingDelegateTest.java:59)
```

**Comment by chanseokoh** [comment]
We need to see what went wrong by checking the resulting `status` first.

**Comment by briandealwis** [comment]
Drat, the take-screenshot-on-error requires the `SWTBotJunit4ClassRunner`, which isn't enabled.

**Comment by chanseokoh** [comment]
Looks like `WarPublisher.publishWar()` in FlexWarStagingDelegate` (which in turns calls `PublishUtil.publishZip()`) fails to leave the deployable WAR in the destination. I think most of the flakiness like this is due to a timing issue, e.g., publishing too fast while things have not been settled.

```java
  @Override
  protected IPath getDeployArtifact(IPath safeWorkDirectory, IProgressMonitor monitor)
      throws CoreException {
    IPath war = safeWorkDirectory.append("app-to-deploy.war");
    IPath tempDirectory = safeWorkDirectory.append("temp");
    WarPublisher.publishWar(project, war, tempDirectory, monitor);
    return war;
  }
```

**Comment by briandealwis** [comment]
Do you think we have a threading issue?  The `TestProjectCreator`'s `waitForProjects()` should ensure the project has reached a fixpoint.

**Comment by chanseokoh** [comment]
Can't say for sure, but looking through the code, it's hard to see where it can fail. It'd be worth logging the return value of `WarPublisher.flatternResources()` and the contents of `safeWorkDirectory` and `stagingDirectory`.

At least we know `waitForProjects()` is not perfect. For example, https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/1798#issuecomment-373767767 For that issue that some `.class` files are missing after `waitForProjects()` and `waitUntilNoBuildErrors()`, I've added code to explicitly wait until `.class` files exist, and I've not seen the error since then.

```java
    waitUntilCondition("Until fully built", this::classFilesExist, () -> Thread.sleep(100), 100);
```

**Comment by chanseokoh** [comment]
#3164 to log underlying errors paid off. The cause of the WAR publishing failure is due to `WarPublisher.flattenResources()` returning an empty list.

```
Contains: test0.36440166932041007 has no resources to publish
==== end of IStatus exception stack trace ====
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.google.cloud.tools.eclipse.appengine.deploy.flex.FlexWarStagingDelegateTest.testStage(FlexWarStagingDelegateTest.java:62)
```

I see one probable cause is `ServerUtil.getModules(project)` returning an empty module list, knowing that this was a cause of another flaky test (`LocalAppEnginePublishOperationTest`) that had annoyed us for a long time: https://github.com/GoogleCloudPlatform/google-cloud-eclipse/pull/3015

**Comment by briandealwis** [comment]
Seen on[ Eclipse 2018-09 with Java 8](https://api.travis-ci.org/v3/job/443383028/log.txt):
```
Running com.google.cloud.tools.eclipse.appengine.deploy.flex.FlexWarStagingDelegateTest

!ENTRY org.eclipse.wst.sse.core 1 1 2018-10-18 20:35:39.839
!MESSAGE Indexing project test0.8294660211943474 for JSP Index Manager

!ENTRY org.eclipse.wst.sse.core 1 1 2018-10-18 20:35:43.884
!MESSAGE Indexing project test0.39694102190128855 for JSP Index Manager

!ENTRY org.eclipse.wst.sse.core 1 1 2018-10-18 20:35:44.484

!MESSAGE Indexing project test0.18502983118759897 for JSP Index Manager

Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 4.738 sec <<< FAILURE! - in com.google.cloud.tools.eclipse.appengine.deploy.flex.FlexWarStagingDelegateTest
testStage(com.google.cloud.tools.eclipse.appengine.deploy.flex.FlexWarStagingDelegateTest)  Time elapsed: 4.07 sec  <<< FAILURE!
java.lang.AssertionError: 4: Staging failed. Check the error message in the Console View.
==== start of IStatus exception stack trace ====
org.eclipse.core.runtime.CoreException: problem publishing WAR
	at com.google.cloud.tools.eclipse.appengine.deploy.flex.FlexWarStagingDelegate.getDeployArtifact(FlexWarStagingDelegate.java:59)
	at com.google.cloud.tools.eclipse.appengine.deploy.flex.FlexStagingDelegate.stage(FlexStagingDelegate.java:60)
	at com.google.cloud.tools.eclipse.appengine.deploy.flex.FlexWarStagingDelegate.stage(FlexWarStagingDelegate.java:41)
	at com.google.cloud.tools.eclipse.appengine.deploy.flex.FlexWarStagingDelegateTest.testStage(FlexWarStagingDelegateTest.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:156)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:82)
	at org.eclipse.tycho.surefire.osgibooter.OsgiSurefireBooter.run(OsgiSurefireBooter.java:95)
	at org.eclipse.tycho.surefire.osgibooter.HeadlessTestApplication.run(HeadlessTestApplication.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.internal.app.EclipseAppContainer.callMethodWithException(EclipseAppContainer.java:590)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:201)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:391)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:246)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1474)
Contains: test0.8294660211943474 has no resources to publish
==== end of IStatus exception stack trace ====
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.google.cloud.tools.eclipse.appengine.deploy.flex.FlexWarStagingDelegateTest.testStage(FlexWarStagingDelegateTest.java:62)
```

**Comment by chanseokoh** [comment]
Looks like the exact same stack trace: the project has no resources to publish (https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/3107#issuecomment-401845584).

**Comment by JoeWang1127** [comment]
close as not planned
