### ISSUE TITLE
Cloud SDK install on Linux is failing

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#3157]
Might be the issue on the Cloud SDK?

```
[Installing Google Cloud SDK]
Welcome to the Google Cloud SDK!


Your current Cloud SDK version is: 205.0.0
Installing components from version: 204.0.0

+-------------------------------------------------+
|        These components will be updated.        |
+--------------------------+------------+---------+
|           Name           |  Version   |   Size  |
+--------------------------+------------+---------+
| Cloud SDK Core Libraries | 2018.06.04 | 7.6 MiB |
| gcloud cli dependencies  | 2018.05.25 | 2.3 MiB |
+--------------------------+------------+---------+
+----------------------------------------------------------------------------+
|                    These components will be installed.                     |
+-----------------------------------------------------+------------+---------+
|                         Name                        |  Version   |   Size  |
+-----------------------------------------------------+------------+---------+
| BigQuery Command Line Tool                          |     2.0.34 | < 1 MiB |
| BigQuery Command Line Tool (Platform Specific)      |     2.0.26 | < 1 MiB |
| Cloud SDK Core Libraries (Platform Specific)        | 2018.03.16 | < 1 MiB |
| Cloud Storage Command Line Tool                     |       4.31 | 3.5 MiB |
| Cloud Storage Command Line Tool (Platform Specific) |       4.27 | < 1 MiB |
| Default set of gcloud commands                      |            |         |
| gcloud cli dependencies                             | 2017.10.20 | 5.1 MiB |
+-----------------------------------------------------+------------+---------+

For the latest full release notes, please visit:
  https://cloud.google.com/sdk/release_notes

Performing in place update...

#============================================================#
#= Uninstalling: Cloud SDK Core Libraries                   =#
#============================================================#
#= Uninstalling: gcloud cli dependencies                    =#
#============================================================#
#= Installing: BigQuery Command Line Tool                   =#
#============================================================#
Traceback (most recent call last):
  File ".../.cache/google-cloud-tools-java/managed-cloud-sdk/LATEST/google-cloud-sdk/bin/bootstrapping/install.py", line 222, in <module>

This will install all the core command line tools necessary for working with
the Google Cloud Platform.

  File ".../.cache/google-cloud-tools-java/managed-cloud-sdk/LATEST/google-cloud-sdk/bin/bootstrapping/install.py", line 200, in main
  File ".../.cache/google-cloud-tools-java/managed-cloud-sdk/LATEST/google-cloud-sdk/bin/bootstrapping/install.py", line 141, in Install
  File ".../.cache/google-cloud-tools-java/managed-cloud-sdk/LATEST/google-cloud-sdk/bin/bootstrapping/install.py", line 184, in InstallOrUpdateComponents
  File ".../.cache/google-cloud-tools-java/managed-cloud-sdk/LATEST/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 870, in Execute
  File ".../.cache/google-cloud-tools-java/managed-cloud-sdk/LATEST/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 908, in _HandleAllErrors
  File ".../.cache/google-cloud-tools-java/managed-cloud-sdk/LATEST/google-cloud-sdk/lib/googlecloudsdk/calliope/exceptions.py", line 526, in HandleError
  File ".../.cache/google-cloud-tools-java/managed-cloud-sdk/LATEST/google-cloud-sdk/lib/googlecloudsdk/core/exceptions.py", line 137, in reraise
  File ".../.cache/google-cloud-tools-java/managed-cloud-sdk/LATEST/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 844, in Execute
  File ".../.cache/google-cloud-tools-java/managed-cloud-sdk/LATEST/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 767, in Run
  File ".../.cache/google-cloud-tools-java/managed-cloud-sdk/LATEST/google-cloud-sdk/lib/surface/components/update.py", line 109, in Run
  File ".../.cache/google-cloud-tools-java/managed-cloud-sdk/LATEST/google-cloud-sdk/lib/googlecloudsdk/core/updater/update_manager.py", line 963, in Update
  File ".../.cache/google-cloud-tools-java/managed-cloud-sdk/LATEST/google-cloud-sdk/lib/googlecloudsdk/core/updater/update_manager.py", line 804, in _UpdateWithProgressBar
  File ".../.cache/google-cloud-tools-java/managed-cloud-sdk/LATEST/google-cloud-sdk/lib/googlecloudsdk/core/updater/update_manager.py", line 811, in Inner
  File ".../.cache/google-cloud-tools-java/managed-cloud-sdk/LATEST/google-cloud-sdk/lib/googlecloudsdk/core/updater/local_state.py", line 105, in _TryFunc
  File ".../.cache/google-cloud-tools-java/managed-cloud-sdk/LATEST/google-cloud-sdk/lib/googlecloudsdk/core/updater/local_state.py", line 530, in Install
  File ".../.cache/google-cloud-tools-java/managed-cloud-sdk/LATEST/google-cloud-sdk/lib/googlecloudsdk/core/updater/installers.py", line 139, in Install
  File ".../.cache/google-cloud-tools-java/managed-cloud-sdk/LATEST/google-cloud-sdk/lib/googlecloudsdk/core/updater/installers.py", line 181, in _InstallTar
  File ".../.cache/google-cloud-tools-java/managed-cloud-sdk/LATEST/google-cloud-sdk/lib/googlecloudsdk/core/updater/installers.py", line 216, in DownloadAndExtractTar
  File ".../.cache/google-cloud-tools-java/managed-cloud-sdk/LATEST/google-cloud-sdk/lib/googlecloudsdk/core/updater/installers.py", line 293, in MakeRequest
  File ".../.cache/google-cloud-tools-java/managed-cloud-sdk/LATEST/google-cloud-sdk/lib/googlecloudsdk/core/updater/installers.py", line 337, in _RawRequest
  File ".../.cache/google-cloud-tools-java/managed-cloud-sdk/LATEST/google-cloud-sdk/lib/googlecloudsdk/core/util/retry.py", line 180, in RetryOnException
  File ".../.cache/google-cloud-tools-java/managed-cloud-sdk/LATEST/google-cloud-sdk/lib/googlecloudsdk/core/exceptions.py", line 137, in reraise
  File ".../.cache/google-cloud-tools-java/managed-cloud-sdk/LATEST/google-cloud-sdk/lib/googlecloudsdk/core/util/retry.py", line 161, in TryFunc
  File ".../.cache/google-cloud-tools-java/managed-cloud-sdk/LATEST/google-cloud-sdk/lib/googlecloudsdk/core/url_opener.py", line 78, in urlopen
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File ".../.cache/google-cloud-tools-java/managed-cloud-sdk/LATEST/google-cloud-sdk/lib/googlecloudsdk/core/url_opener.py", line 63, in https_open
  File "/usr/lib/python2.7/urllib2.py", line 1195, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File ".../.cache/google-cloud-tools-java/managed-cloud-sdk/LATEST/google-cloud-sdk/lib/third_party/httplib2/python2/httplib2/__init__.py", line 1097, in connect
  File ".../.cache/google-cloud-tools-java/managed-cloud-sdk/LATEST/google-cloud-sdk/lib/third_party/httplib2/python2/httplib2/__init__.py", line 96, in _ssl_wrap_socket
IOError: [Errno 2] No such file or directory
```

**Comment by chanseokoh** [comment]
Happens on the command line too.

```
$ wget  https://dl.google.com/dl/cloudsdk/channels/rapid/google-cloud-sdk.tar.gz`
$ tar zxvf google-cloud-sdk.tar.gz
$ cd google-cloud-sdk
$ ./install.sh
```

**Comment by elharo** [comment]
Cloud SDK team looking into this.

**Comment by cococlyde** [comment]
install.sh should be run from the directory where the seed tarball was extracted (the directory that contains ./google-cloud-sdk/):
```
  $ wget https://dl.google.com/dl/cloudsdk/channels/rapid/google-cloud-sdk.tar.gz
  $ tar zxvf google-cloud-sdk.tar.gz
  $ ./google-cloud-sdk/install.sh
```
If you post the instructions link I'll make sure they are explicit about this.

**Comment by chanseokoh** [comment]
OK, I verified that it works if I run the script outside the unzipped directory. The instructions (https://cloud.google.com/sdk/docs/downloads-versioned-archives) do show running `install.sh` outside the directory, but I think we should explicitly say you must do so.

@cococlyde it's still better to give a proper high-level message from the beginning rather than crashing with a unrelated error. I'll file an internal bug shortly.

**Comment by cococlyde** [comment]
Already filed one :)

**Comment by chanseokoh** [comment]
Thanks. FTR, internal bug number: 110147360

**Comment by patflynn** [comment]
Chanseok is this failing in the managed installation?

**Comment by chanseokoh** [comment]
Yes, failing when installing the managed SDK for the first time on all platforms, probably until next Wednesday when the SDK team releases the next version (or until we release the next appengine-plugins-core and then the next Eclipse and IntelliJ plugins, which may not be too much earlier than the next Wednesday at best).

**Comment by patflynn** [comment]
@loosebazooka I know we discussed doing some integration testing against cloud sdk pre-releases.  It seems like the rate of breakage here is high enough to prioritize that work ASAP. WDYT?

**Comment by elharo** [comment]
I don't know whether that would have caught this. The problem as I understand it was not with 205 so much as with the downgrade back to 204.

I'm still surprised by what @briandealwis said in the meeting this morning: that the zip file oublicly available is for 205 but it downgrades itself to 204. Can someone explain that? Or ask the Cloud SDK team, maybe @cococlyde to explain what's going on here?

**Comment by chanseokoh** [comment]
@cococlyde basically said the downgrading mechanism is in place for the users who had installed 205 before the rollback happened. Also technically the SDK team could ideally roll back the tar.gz at the download link too. They said they will improve the rollback process.
