### ISSUE TITLE
gcloud eclipse plugin - app engine dev server can't be started

### ISSUE THREAD

**Issue by srinurp** [GoogleCloudPlatform/google-cloud-eclipse#3193]
Before reporting a possible bug:

1. Please ensure you are running the latest version of CT4E with _Help > Check for Updates_
2. If the problem occurs when you deploy or after the application has been deployed, try deploying from the command line using gcloud or Maven. If the problem does not go away, then the issue is likely not with Cloud Tools for Eclipse.

- Cloud Tools for Eclipse version: 1.7.0.201805302000
- Google Cloud SDK version: 207.0.0 (auto-managed)
- Eclipse version: 4.8.0.v20180611-0500
- OS: Windows 10 10.0
- Java version: 1.8.0_131

**What did you do?**

Installed 
gcloud eclipse tools
create app engine standard project
trying to deploy

**What did you expect to see?**

app engine dev server should start

**What did you see instead?**

Could not publish to the server.
java.lang.IndexOutOfBoundsException

Screenshots and stacktraces are helpful.

![image](https://user-images.githubusercontent.com/29401372/42198468-c6e00b3a-7ea5-11e8-9f46-70fe9e0c368c.png)

**Comment by srinurp** [comment]
Here is stack trace of it from .log file....

java.lang.IndexOutOfBoundsException
	at java.io.BufferedInputStream.read(Unknown Source)
	at org.eclipse.jdt.internal.compiler.util.Util.getInputStreamAsByteArray(Util.java:506)
	at org.eclipse.jdt.core.ToolFactory.createDefaultClassFileReader(ToolFactory.java:311)
	at org.eclipse.jst.j2ee.internal.archive.JavaEEArchiveUtilities.isEJBArchive(JavaEEArchiveUtilities.java:923)
	at org.eclipse.jst.j2ee.internal.archive.JavaEEArchiveUtilities.refineForJavaEE(JavaEEArchiveUtilities.java:620)
	at org.eclipse.jst.j2ee.internal.archive.JavaEEArchiveUtilities.openArchive(JavaEEArchiveUtilities.java:381)
	at org.eclipse.jst.j2ee.internal.archive.JavaEEArchiveUtilities.openBinaryArchive(JavaEEArchiveUtilities.java:301)
	at org.eclipse.jst.j2ee.internal.componentcore.JavaEEBinaryComponentHelper$ArchiveCache.openArchive(JavaEEBinaryComponentHelper.java:612)
	at org.eclipse.jst.j2ee.internal.componentcore.JavaEEBinaryComponentHelper.openArchive(JavaEEBinaryComponentHelper.java:470)
	at org.eclipse.jst.j2ee.internal.componentcore.JavaEEBinaryComponentHelper.getUniqueArchive(JavaEEBinaryComponentHelper.java:422)
	at org.eclipse.jst.j2ee.internal.componentcore.JavaEEBinaryComponentHelper.getArchive(JavaEEBinaryComponentHelper.java:415)
	at org.eclipse.jst.j2ee.internal.componentcore.JavaEEBinaryComponentHelper.getJavaEEQuickPeek(JavaEEBinaryComponentHelper.java:98)
	at org.eclipse.jst.j2ee.project.JavaEEProjectUtilities.getJ2EEComponentType(JavaEEProjectUtilities.java:273)
	at org.eclipse.jst.j2ee.internal.common.exportmodel.JEEHeirarchyExportParticipant.isChildModule(JEEHeirarchyExportParticipant.java:42)
	at org.eclipse.wst.common.componentcore.internal.flat.GlobalHeirarchyParticipant.isChildModule(GlobalHeirarchyParticipant.java:41)
	at org.eclipse.wst.common.componentcore.internal.flat.FlatVirtualComponent.isChildModule(FlatVirtualComponent.java:367)
	at org.eclipse.wst.common.componentcore.internal.flat.FlatVirtualComponent.addUsedReferences(FlatVirtualComponent.java:305)
	at org.eclipse.wst.common.componentcore.internal.flat.FlatVirtualComponent.treeWalk(FlatVirtualComponent.java:235)
	at org.eclipse.wst.common.componentcore.internal.flat.FlatVirtualComponent.cacheResources(FlatVirtualComponent.java:188)
	at org.eclipse.wst.common.componentcore.internal.flat.FlatVirtualComponent.fetchResources(FlatVirtualComponent.java:118)
	at org.eclipse.wst.web.internal.deployables.FlatComponentDeployable.members(FlatComponentDeployable.java:234)
	at org.eclipse.jst.j2ee.internal.deployables.J2EEFlexProjDeployable.members(J2EEFlexProjDeployable.java:272)
	at org.eclipse.wst.server.core.internal.ModulePublishInfo.getDelta(ModulePublishInfo.java:407)
	at org.eclipse.wst.server.core.internal.ServerPublishInfo.getDelta(ServerPublishInfo.java:366)
	at org.eclipse.wst.server.core.internal.Server.getPublishedResourceDelta(Server.java:1588)
	at org.eclipse.wst.server.core.model.ServerBehaviourDelegate.getPublishedResourceDelta(ServerBehaviourDelegate.java:698)
	at com.google.cloud.tools.eclipse.appengine.localserver.server.LocalAppEngineServerBehaviour.getPublishedResourceDelta(LocalAppEngineServerBehaviour.java:175)
	at com.google.cloud.tools.eclipse.appengine.localserver.server.LocalAppEnginePublishOperation.getPublishedResourceDelta(LocalAppEnginePublishOperation.java:60)
	at com.google.cloud.tools.eclipse.jst.server.core.BasePublishOperation.publishDir(BasePublishOperation.java:186)
	at com.google.cloud.tools.eclipse.jst.server.core.BasePublishOperation.execute(BasePublishOperation.java:131)
	at org.eclipse.wst.server.core.model.ServerBehaviourDelegate.performTasks(ServerBehaviourDelegate.java:1335)
	at org.eclipse.wst.server.core.model.ServerBehaviourDelegate.publish(ServerBehaviourDelegate.java:954)
	at org.eclipse.wst.server.core.model.ServerBehaviourDelegate.publish(ServerBehaviourDelegate.java:774)
	at org.eclipse.wst.server.core.internal.Server.publishImpl(Server.java:3182)
	at org.eclipse.wst.server.core.internal.Server$PublishJob.run(Server.java:355)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)

**Comment by elharo** [comment]
Thanks. That's a weird one. BufferedInputStream.read really shouldn't throw an IndexOutOfBoundsException. Perhaps there's a thread bug somewhere?

**Comment by diegomarquezp** [comment]
Closing as not planned since GAE with Java 8 is not supported. cc: @blakeli0
