### ISSUE TITLE
NPE in DefaultRepositorySystem.resolveDependencies

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#3241]
I noticed in the tests that we had a failure in `CloudLibrariesInPluginXmlTest.testObjectify6LibraryConfig()` in the Oxygen build.  There were a raft of network resolving problems.

```
Running com.google.cloud.tools.eclipse.appengine.libraries.model.CloudLibrariesInPluginXmlTest
00:14:48.478 [main] ERROR c.g.c.t.e.a.libraries.model.Library - Could not load library MavenCoordinates [repository=central, com.googlecode.objectify:objectify:jar:null:6.0]
org.eclipse.core.runtime.CoreException: Possible corrupt artifact in local .m2 repository for com.googlecode.objectify:objectify:6.0
	at com.google.cloud.tools.eclipse.util.DependencyResolver._getTransitiveDependencies(DependencyResolver.java:109) ~[com.google.cloud.tools.eclipse.util-0.1.0-SNAPSHOT.jar:na]
	at com.google.cloud.tools.eclipse.util.DependencyResolver.lambda$getTransitiveDependencies$0(DependencyResolver.java:63) ~[com.google.cloud.tools.eclipse.util-0.1.0-SNAPSHOT.jar:na]
	at com.google.cloud.tools.eclipse.util.MavenUtils.lambda$runOperation$1(MavenUtils.java:124) ~[com.google.cloud.tools.eclipse.util-0.1.0-SNAPSHOT.jar:na]
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177) ~[org.eclipse.m2e.core-1.8.3.20180227-2137.jar:na]
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151) ~[org.eclipse.m2e.core-1.8.3.20180227-2137.jar:na]
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99) ~[org.eclipse.m2e.core-1.8.3.20180227-2137.jar:na]
	at com.google.cloud.tools.eclipse.util.MavenUtils.runOperation(MavenUtils.java:120) ~[com.google.cloud.tools.eclipse.util-0.1.0-SNAPSHOT.jar:na]
	at com.google.cloud.tools.eclipse.util.DependencyResolver.getTransitiveDependencies(DependencyResolver.java:60) ~[com.google.cloud.tools.eclipse.util-0.1.0-SNAPSHOT.jar:na]
	at com.google.cloud.tools.eclipse.appengine.libraries.model.LibraryFactory.loadTransitiveDependencies(LibraryFactory.java:120) ~[com.google.cloud.tools.eclipse.appengine.libraries-0.1.0-SNAPSHOT.jar:na]
	at com.google.cloud.tools.eclipse.appengine.libraries.model.Library.resolveDependencies(Library.java:211) [com.google.cloud.tools.eclipse.appengine.libraries-0.1.0-SNAPSHOT.jar:na]
	at com.google.cloud.tools.eclipse.appengine.libraries.model.Library.getAllDependencies(Library.java:117) [com.google.cloud.tools.eclipse.appengine.libraries-0.1.0-SNAPSHOT.jar:na]
	at com.google.cloud.tools.eclipse.appengine.libraries.model.CloudLibrariesInPluginXmlTest.testObjectify6LibraryConfig(CloudLibrariesInPluginXmlTest.java:207) [classes/:na]
[...]
Caused by: java.lang.NullPointerException: null
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:361) ~[aether-impl-1.0.2.v20150114.jar:na]
	at com.google.cloud.tools.eclipse.util.DependencyResolver._getTransitiveDependencies(DependencyResolver.java:95) ~[com.google.cloud.tools.eclipse.util-0.1.0-SNAPSHOT.jar:na]
```

We've seen this [NPE before](
https://github.com/GoogleCloudPlatform/google-cloud-eclipse/pull/2330#issuecomment-325740994).

I took a look at the [history for `DefaultRepositorySystem`](https://github.com/apache/maven-resolver/commits/master/maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultRepositorySystem.java) and noticed that there was a fix for [MRESOLVER-19](https://issues.apache.org/jira/browse/MRESOLVER-19) _DefaultRepositorySystem resolveDependencies() can yield a NullPointerException_.  Their JIRA shows it should be in Aether/Maven Resolver 1.1.0.

We're using Aether v1.0.2 jars that are bundled along with m2eclipse 1.8.3, specifically in `org.eclipse.m2e.maven.runtime` 1.8.3.

The good news is that m2eclipse 1.9.0, which is part of Eclipse Photon and 2018-09, ships with maven-resolver 1.1.1.  And indeed, we don't have an NPE in the Photon or 2018-09 builds.

**Comment by briandealwis** [comment]
Closing since this problem is rare, and will fix itself with the deprecation of Oxygen.  If this becomes higher-priority, we could consider pulling our own `maven-resolver` rather than relying on the version supplied by m2eclipse.
