### ISSUE TITLE
Failure in testNoJUnit4ClasspathIfUsingMaven: StaleMutableProjectRegistryException

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#3246]
Seen on Photon ([link to log](https://api.travis-ci.org/v3/job/425301761/log.txt))
Haven't seen this error logged before.

The full code in [m2e's `ProjectRegistryManager`](http://git.eclipse.org/c/m2e/m2e-core.git/tree/org.eclipse.m2e.core/src/org/eclipse/m2e/core/internal/project/registry/ProjectRegistryManager.java?h=master#n372) is:
```java
      if(newState.isStale() || (syncRefreshThread != null && syncRefreshThread != Thread.currentThread())) {
        throw new StaleMutableProjectRegistryException();
      }
```

`syncRefreshThread` is called set by [`ProjectRegistryManager#refresh()`](http://git.eclipse.org/c/m2e/m2e-core.git/tree/org.eclipse.m2e.core/src/org/eclipse/m2e/core/internal/project/registry/ProjectRegistryManager.java?h=master#n294) which obtains a workspace root rule.

Log:
```
[Watchdog] > testJstl12JarIfNonMavenProject(com.google.cloud.tools.eclipse.appengine.newproject.flex.CreateAppEngineFlexWtpProjectTest)



!ENTRY org.eclipse.wst.sse.core 1 1 2018-09-06 14:58:57.325

!MESSAGE Indexing project testproject0.8738283321394694 for JSP Index Manager

[Watchdog] > testNoJUnit4ClasspathIfUsingMaven(com.google.cloud.tools.eclipse.appengine.newproject.flex.CreateAppEngineFlexWtpProjectTest)
[...]
testNoJstl12JarIfMavenProject(com.google.cloud.tools.eclipse.appengine.newproject.flex.CreateAppEngineFlexWtpProjectTest)  Time elapsed: 16.365 sec  <<< ERROR!
org.eclipse.m2e.core.internal.project.registry.StaleMutableProjectRegistryException: null
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:457)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:351)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:298)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.configureNewMavenProjects(ProjectConfigurationManager.java:259)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$4.run(ProjectConfigurationManager.java:528)
	at org.eclipse.m2e.core.internal.embedder.AbstractRunnable.call(AbstractRunnable.java:26)
	at org.eclipse.m2e.core.internal.embedder.AbstractRunnable.call(AbstractRunnable.java:1)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1355)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.enableMavenNature(ProjectConfigurationManager.java:525)
	at com.google.cloud.tools.eclipse.appengine.newproject.CreateAppEngineWtpProject.enableMavenNature(CreateAppEngineWtpProject.java:193)
	at com.google.cloud.tools.eclipse.appengine.newproject.CreateAppEngineWtpProject.addAdditionalDependencies(CreateAppEngineWtpProject.java:147)
	at com.google.cloud.tools.eclipse.appengine.newproject.flex.CreateAppEngineFlexWtpProject.addAdditionalDependencies(CreateAppEngineFlexWtpProject.java:99)
	at com.google.cloud.tools.eclipse.appengine.newproject.CreateAppEngineWtpProject.execute(CreateAppEngineWtpProject.java:138)
	at com.google.cloud.tools.eclipse.appengine.newproject.CreateAppEngineWtpProjectTest.testNoJstl12JarIfMavenProject(CreateAppEngineWtpProjectTest.java:273)
[...]
```

**Comment by diegomarquezp** [comment]
Closing as not planned since we don't support GAE + Java 8.
