### ISSUE TITLE
Test failure on Travis Java 11

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#3268]
Just noticed the following failure, and it looks like it's not a falky failure, because the test says "... or string is exactly 11".
```
java.lang.AssertionError: 
Expected: (a string starting with "1.7." or a string starting with "1.8." or is "11")
     but: was "11.0.1"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at com.google.cloud.tools.eclipse.bugreport.ui.BugReportCommandHandlerTest.testFormatReportUrl(BugReportCommandHandlerTest.java:70)
```

**Comment by chanseokoh** [comment]
Dup of #3269.
