### ISSUE TITLE
Java 11 test failure

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#3269]
Travis build is failing.  I guess OpenJDK 11.0.1 has been released!
```
testFormatReportUrl(com.google.cloud.tools.eclipse.bugreport.ui.BugReportCommandHandlerTest)  Time elapsed: 0.224 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: (a string starting with "1.7." or a string starting with "1.8." or is "11")
     but: was "11.0.1"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at com.google.cloud.tools.eclipse.bugreport.ui.BugReportCommandHandlerTest.testFormatReportUrl(BugReportCommandHandlerTest.java:70)
```

**Comment by lqiu96** [comment]
Closing as part of cleanup. Please re-open if it's still relevant.

Seems to be fixed with this PR: https://github.com/GoogleCloudPlatform/google-cloud-eclipse/pull/3270
