### ISSUE TITLE
No icons on Welcome page entries on 2018-09

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#3374]
![selection_008](https://user-images.githubusercontent.com/10523105/51002403-26b41f00-1501-11e9-87fd-0e33c4b0fa02.png)

I guess the red box indicates the image failed to load, which fortunately feels like a bullet point. I can see our GCP/App Engine icons on the hosted debug instance (Photon), so this may only be on 2018-09. And it's not just us; some other 3rd-party entries fail to load icons too, I guess.

**Comment by chanseokoh** [comment]
Looking at https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/3332#issuecomment-453559352 and other third-part icons missing, it may not be our sole fault.

**Comment by elharo** [comment]
We should fix this if we can, but as you say it's probably not our fault and likely should not block the release. It's cosmetic.

**Comment by briandealwis** [comment]
Are there any messages in the logs @chanseokoh?  I don't see how this is our problem.

**Comment by chanseokoh** [comment]
Whenver I open _Weblcome_, I see the following two "the image could not be loaded" messages, but just those two. And the `gif` files don't seem to belong to us.

```
$ tail -f .metadata/.log | grep URLImage
!MESSAGE The image could not be loaded: URLImageDescriptor(file:<...>/chanseok/tmp/eclipse/configuration/org.eclipse.osgi/793/0/.cp/themes/solstice/graphics/icons/obj48/new_obj.gif)
org.eclipse.jface.resource.DeviceResourceException: Unable to create resource URLImageDescriptor(file:<...>/chanseok/tmp/eclipse/configuration/org.eclipse.osgi/793/0/.cp/themes/solstice/graphics/icons/obj48/new_obj.gif)
!MESSAGE The image could not be loaded: URLImageDescriptor(file:<...>/chanseok/tmp/eclipse/configuration/org.eclipse.osgi/793/0/.cp/themes/solstice/graphics/icons/obj48/newhov_obj.gif)
org.eclipse.jface.resource.DeviceResourceException: Unable to create resource URLImageDescriptor(file:<...>/chanseok/tmp/eclipse/configuration/org.eclipse.osgi/793/0/.cp/themes/solstice/graphics/icons/obj48/newhov_obj.gif)
```
Anyways, the top of the stack is
```
org.eclipse.jface.resource.DeviceResourceException: Unable to create resource URLImageDescriptor(file:<...>/chanseok/tmp/eclipse/configuration/org.eclipse.osgi/793/0/.cp/themes/solstice/graphics/icons/obj48/newhov_obj.gif)
    at org.eclipse.jface.resource.ImageDescriptor.createResource(ImageDescriptor.java:185)
    at org.eclipse.jface.resource.DeviceResourceManager.allocate(DeviceResourceManager.java:55)
    at org.eclipse.jface.resource.AbstractResourceManager.create(AbstractResourceManager.java:88)
    at org.eclipse.jface.resource.ResourceManager.createImageWithDefault(ResourceManager.java:195)
    at org.eclipse.jface.resource.ImageRegistry.get(ImageRegistry.java:206)
    at org.eclipse.ui.internal.intro.impl.util.ImageUtil.getImage(ImageUtil.java:140)
    at org.eclipse.ui.internal.intro.impl.swt.SharedStyleManager.getImage(SharedStyleManager.java:216)
    at org.eclipse.ui.internal.intro.impl.swt.PageStyleManager.getImage(PageStyleManager.java:490)
    at org.eclipse.ui.internal.intro.impl.swt.PageWidgetFactory.createImageHyperlink(PageWidgetFactory.java:267)
    at org.eclipse.ui.internal.intro.impl.swt.PageWidgetFactory.createIntroElement(PageWidgetFactory.java:130)
    at org.eclipse.ui.internal.intro.impl.swt.PageWidgetFactory.createIntroElement(PageWidgetFactory.java:126)
    at org.eclipse.ui.internal.intro.impl.swt.PageWidgetFactory.createIntroElement(PageWidgetFactory.java:126)
    at org.eclipse.ui.internal.intro.impl.swt.PageWidgetFactory.createIntroElement(PageWidgetFactory.java:126)
    at org.eclipse.ui.internal.intro.impl.swt.PageContentForm.createPageChildren(PageContentForm.java:112)
    at org.eclipse.ui.internal.intro.impl.swt.PageContentForm.createPartControl(PageContentForm.java:99)
    at org.eclipse.ui.internal.intro.impl.swt.PageForm.showPage(PageForm.java:149)
    at org.eclipse.ui.internal.intro.impl.presentations.FormIntroPartImplementation.createMainPageBook(FormIntroPartImplementation.java:207)
    at org.eclipse.ui.internal.intro.impl.presentations.FormIntroPartImplementation.dynamicCreatePartControl(FormIntroPartImplementation.java:141)
    at org.eclipse.ui.internal.intro.impl.presentations.FormIntroPartImplementation.createPartControl(FormIntroPartImplementation.java:103)
    at org.eclipse.ui.internal.intro.impl.model.IntroPartPresentation.createPartControl(IntroPartPresentation.java:233)
    at org.eclipse.ui.intro.config.CustomizableIntroPart.createPartControl(CustomizableIntroPart.java:204)
    at org.eclipse.ui.internal.ViewIntroAdapterPart.createPartControl(ViewIntroAdapterPart.java:138)
    at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.createPartControl(CompatibilityPart.java:156)
    at org.eclipse.ui.internal.e4.compatibility.CompatibilityView.createPartControl(CompatibilityView.java:152)
    at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create(CompatibilityPart.java:367)
```

**Comment by elharo** [comment]
Have we seen this for any plugins but our own?

**Comment by chanseokoh** [comment]
In the first screenshot, there are other plugins experiencing the same.

**Comment by elharo** [comment]
Can anyone find an Eclipse bug on this?

**Comment by briandealwis** [comment]
I can't reproduce this with Eclipse 2018-09.

Unfortunately `URLImageDescriptor` / `ImageDescriptor`'s `createResource()` masks the underlying problem.
```
    @Override
	public Object createResource(Device device) throws DeviceResourceException {
        Image result = createImage(false, device);
        if (result == null) {
            throw new DeviceResourceException(this);
        }
        return result;
    }
```

`createImage()` for `URLImageDescriptor ` and `ImageDescriptor` don't actually log the underlying SWT exceptions that occur when trying to load the given image.

So I guess there are two things to check:
  - Do these referenced pathnames exist?  (I.e., were the images successfully extracted from the bundles into Equinox/OSGi's per-bundle temp state directories?)
  - What is SWT unable to load the image files?

If you can, run Eclipse with JDWP enabled and connect from another Eclipse instance with an exception breakpoints on `org.eclipse.swt.SWTException` and `IllegalArgumentException`:
```
eclipse ... -vmargs -agentlib:jdwp=transport=dt_socket,server=y,address=5000
```

**Comment by elharo** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=439423 might be the same thing

**Comment by elharo** [comment]
org.eclipse.swt.SWTException: i/o error (java.io.FileNotFoundException: /usr/local/google/eclipse49_elharo/stable/configuration/org.eclipse.osgi/324/0/.cp/themes/solstice/graphics/icons/obj48/new_obj.gif (No such file or directory))

**Comment by elharo** [comment]
Tentative hypothesis: this is an Eclipse bug. When Eclipse is installed in a read-only location, plugins that are added later (not bundled in the inital install) have broken icons.

**Comment by elharo** [comment]
I'm currently seeing this in 4.7. It's not unique to 4.9.

**Comment by briandealwis** [comment]
I've been unable to reproduce as a shared-install.  [Bug 439423](https://bugs.eclipse.org/bugs/show_bug.cgi?id=439423) is about the actual Intro/Welcome viewport and isn't related to this.

**Comment by JoeWang1127** [comment]
close as not planned
