### ISSUE TITLE
google endpoints services deploy issue after the recent outage.

### ISSUE THREAD

**Issue by oarshad** [GoogleCloudPlatform/google-cloud-eclipse#3444]
I have been deploying few google endpoints services openapi specs without any issue but after there was some outage on Google Cloud yesterday, most of the services are back to normal but I am getting constant "13 - Internal Server Error" when trying to deploy endpoints. Command I had been using to deploy is the following:
```
gcloud endpoints services deploy openapi.audit.json openapi.data-cron.json openapi.auth.json
```
Output of the above command:
```
Waiting for async operation operations/rollouts.xxxxxxxxx.appspot.com:3bf1cfe5-b82a-4cac-a5f6-c58843b37750 to complete...
DEBUG: (gcloud.endpoints.services.deploy) The operation with ID rollouts.the-fa-api-dev.appspot.com:3bf1cfe5-b82a-4cac-a5f6-c58843b37750 resulted in a failure.
Traceback (most recent call last):
  File "/Users/omer/dev/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 985, in Execute
    resources = calliope_command.Run(cli=self, args=args)
  File "/Users/omer/dev/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 795, in Run
    resources = command_instance.Run(args)
  File "/Users/omer/dev/google-cloud-sdk/lib/surface/endpoints/services/deploy.py", line 393, in Run
    services_util.ProcessOperationResult(rollout_operation, args.async)
  File "/Users/omer/dev/google-cloud-sdk/lib/googlecloudsdk/api_lib/endpoints/services_util.py", line 481, in ProcessOperationResult
    op = GetProcessedOperationResult(result, is_async)
  File "/Users/omer/dev/google-cloud-sdk/lib/googlecloudsdk/api_lib/endpoints/services_util.py", line 526, in GetProcessedOperationResult
    op_ref, GetClientInstance()))
  File "/Users/omer/dev/google-cloud-sdk/lib/googlecloudsdk/api_lib/endpoints/services_util.py", line 583, in WaitForOperation
    'The operation with ID {0} resulted in a failure.'.format(operation_id))
OperationErrorException: The operation with ID rollouts.xxxxxxxxx.appspot.com:3bf1cfe5-b82a-4cac-a5f6-c58843b37750 resulted in a failure.
```

The describe operations command give me the following output:
```
done: true
error:
  code: 13
  message: Internal Error
metadata:
  '@type': type.googleapis.com/google.api.servicemanagement.v1.OperationMetadata
  auditData:
    '@type': type.googleapis.com/google.api.management.server.common.logging.AuditLoggingMetadata
    authenticationInfo:
      principal: 'xxxxxxxxxxx'
      principalEmail: xx@xx.com
    methodName: google.api.servicemanagement.v1.ServiceManager.CreateServiceRollout
    monitoredResource:
      labels:
        rollout_id: 2019-06-03r39
        service_name: xxxxxxxxx.appspot.com
      type: service_rollout
    recipient:
      projectNumber: '65185880855'
    resourceName: services/xxxxxxxxxx.appspot.com/rollouts/2019-06-03r39
  progressPercentage: 100
  resourceNames:
  - services/xxxxxxxxx.appspot.com/rollouts/2019-06-03r39
  startTime: 2019-06-03 16:18:56 BST
name: operations/rollouts.xxxxxxxx.appspot.com:3bf1cfe5-b82a-4cac-a5f6-c58843b37750
```

**Comment by briandealwis** [comment]
Hi @oarshad.  Your problem looks like [this issue](https://issuetracker.google.com/issues/134361013).  Please "star" it and you should receive updates.  If you think it's different, then please open a new issue at issuetracker.google.com.
