### ISSUE TITLE
Failure creating native AES project with Objectify

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#3449]
Eclipse 2019-03.  Create New _App Engine Standard_ project with Objectify fails: no Objectify library is loaded.  The project class path doesn't resolve properly.

```
	<classpathentry kind="con" path="com.google.cloud.tools.eclipse.appengine.libraries/master-container">
		<attributes>
			<attribute name="org.eclipse.jst.component.dependency" value="/WEB-INF/lib"/>
		</attributes>
	</classpathentry>
```
and the `.../.settings/com.google.cloud.tools.eclipse.appengine.libraries/_libraries.container` looks ok:
```
[
  "objectify"
]
```

Removing the cloud libraries container and re-adding Objectify fails with a stack-trace:
```
com.google.common.base.VerifyException: expected a non-null reference
	at com.google.common.base.Verify.verify(Verify.java:124)
	at com.google.common.base.Verify.verifyNotNull(Verify.java:500)
	at com.google.common.base.Verify.verifyNotNull(Verify.java:477)
	at com.google.cloud.tools.eclipse.appengine.libraries.ui.CloudLibrariesPage.finish(CloudLibrariesPage.java:177)
	at org.eclipse.jdt.internal.ui.wizards.buildpaths.ClasspathContainerWizard.performFinish(ClasspathContainerWizard.java:95)
```

**Comment by briandealwis** [comment]
The _Java Build Path_ isn't right either.
<img width="377" alt="Screen Shot 2019-06-05 at 11 01 43 AM" src="https://user-images.githubusercontent.com/202851/58967024-5e0dbb80-8781-11e9-8920-af8c5d6d4844.png">

**Comment by briandealwis** [comment]
Aha, the problem is that one of the artifacts couldn't be resolved (I use a local Nexus instance as a proxy/cache to Maven Central, and it wasn't running).  So the attempt to [load the `LibraryClasspathContainer` fails, but we're just silently dropping the Status error](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/master/plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/LibraryClasspathContainerInitializer.java#L83).

**Comment by briandealwis** [comment]
If I change the code to throw a CoreException then we at least get an error message:

<img width="604" alt="Screen Shot 2019-06-05 at 1 16 28 PM" src="https://user-images.githubusercontent.com/202851/58975914-28be9900-8794-11e9-8658-41be91aad21b.png">
