### ISSUE TITLE
UI freezes in log during test plan

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#3457]
eclipse.buildId=4.9.0.I20180906-0745
java.version=1.8.0_181-google-v7
java.vendor=Google Inc.
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -data file:/usr/local/google/home/elharo/workspaces/qa1/ -os linux -ws gtk -arch x86_64

This is a continuation of log file /usr/local/google/home/elharo/workspaces/qa1/.metadata/.bak_2.log
Created Time: 2019-06-06 14:53:17.201

org.eclipse.ui.monitoring
Error
Thu Jun 06 14:53:24 EDT 2019
UI freeze of 2.6s at 14:53:21.894

eclipse.buildId=4.9.0.I20180906-0745
java.version=1.8.0_181-google-v7
java.vendor=Google Inc.
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -data file:/usr/local/google/home/elharo/workspaces/qa1/ -os linux -ws gtk -arch x86_64

This is a continuation of log file /usr/local/google/home/elharo/workspaces/qa1/.metadata/.bak_2.log
Created Time: 2019-06-06 14:53:17.201

org.eclipse.ui.monitoring
Info
Thu Jun 06 14:53:24 EDT 2019
Sample at 14:53:24.012 (+0.785s)
Thread 'main' tid=1 (TIMED_WAITING)

Stack Trace
	at java.lang.Object.wait(Native Method)
	at org.eclipse.core.internal.jobs.ThreadJob.waitForRun(ThreadJob.java:318)
	at org.eclipse.core.internal.jobs.ThreadJob.joinRun(ThreadJob.java:205)
	at org.eclipse.core.internal.jobs.ImplicitJobs.begin(ImplicitJobs.java:95)
	at org.eclipse.core.internal.jobs.JobManager.beginRule(JobManager.java:311)
	at org.eclipse.core.internal.resources.WorkManager.checkIn(WorkManager.java:124)
	at org.eclipse.core.internal.resources.Workspace.prepareOperation(Workspace.java:2240)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2287)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2319)
	at org.eclipse.ui.actions.WorkspaceModifyOperation.run(WorkspaceModifyOperation.java:131)
	at org.eclipse.ui.internal.editors.text.WorkspaceOperationRunner.run(WorkspaceOperationRunner.java:76)
	at org.eclipse.ui.internal.editors.text.WorkspaceOperationRunner.run(WorkspaceOperationRunner.java:66)
	at org.eclipse.ui.editors.text.TextFileDocumentProvider.executeOperation(TextFileDocumentProvider.java:461)
	at org.eclipse.ui.editors.text.TextFileDocumentProvider.saveDocument(TextFileDocumentProvider.java:764)
	at org.eclipse.ui.texteditor.AbstractTextEditor.performSave(AbstractTextEditor.java:5006)
	at org.eclipse.jdt.internal.ui.javaeditor.CompilationUnitEditor.performSave(CompilationUnitEditor.java:1275)
	at org.eclipse.jdt.internal.ui.javaeditor.CompilationUnitEditor.doSave(CompilationUnitEditor.java:1329)
	at org.eclipse.ui.texteditor.AbstractTextEditor$TextEditorSavable.doSave(AbstractTextEditor.java:7114)
	at org.eclipse.ui.Saveable.doSave(Saveable.java:223)
	at org.eclipse.ui.internal.SaveableHelper.doSaveModel(SaveableHelper.java:343)
	at org.eclipse.ui.internal.SaveableHelper.lambda$1(SaveableHelper.java:196)
	at org.eclipse.ui.internal.SaveableHelper$$Lambda$638/662987014.run(Unknown Source)
	at org.eclipse.ui.internal.SaveableHelper.lambda$3(SaveableHelper.java:274)
	at org.eclipse.ui.internal.SaveableHelper$$Lambda$639/2037881941.run(Unknown Source)
	at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:440)
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:356)
	at org.eclipse.ui.internal.WorkbenchWindow.lambda$3(WorkbenchWindow.java:2254)
	at org.eclipse.ui.internal.WorkbenchWindow$$Lambda$611/530410675.run(Unknown Source)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:72)
	at org.eclipse.ui.internal.WorkbenchWindow.run(WorkbenchWindow.java:2252)
	at org.eclipse.ui.internal.SaveableHelper.runProgressMonitorOperation(SaveableHelper.java:281)
	at org.eclipse.ui.internal.SaveableHelper.runProgressMonitorOperation(SaveableHelper.java:262)
	at org.eclipse.ui.internal.SaveableHelper.saveModels(SaveableHelper.java:207)
	at org.eclipse.ui.internal.SaveableHelper.savePart(SaveableHelper.java:151)
	at org.eclipse.ui.internal.WorkbenchPage.saveSaveable(WorkbenchPage.java:3957)
	at org.eclipse.ui.internal.WorkbenchPage.saveEditor(WorkbenchPage.java:3971)
	at org.eclipse.ui.internal.handlers.SaveHandler.execute(SaveHandler.java:57)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:294)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:320)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:254)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:164)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:497)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:490)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:207)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.executeCommand(KeyBindingDispatcher.java:308)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.press(KeyBindingDispatcher.java:582)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.processKeyEvent(KeyBindingDispatcher.java:651)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.filterKeySequenceBindings(KeyBindingDispatcher.java:441)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.access$2(KeyBindingDispatcher.java:384)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher$KeyDownFilter.handleEvent(KeyBindingDispatcher.java:96)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.filterEvent(Display.java:1752)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1373)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1400)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1383)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1412)
	at org.eclipse.swt.widgets.Widget.gtk_key_press_event(Widget.java:787)
	at org.eclipse.swt.widgets.Control.gtk_key_press_event(Control.java:3794)
	at org.eclipse.swt.widgets.Composite.gtk_key_press_event(Composite.java:862)
	at org.eclipse.swt.widgets.Widget.windowProc(Widget.java:1990)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:6524)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6014)
	at org.eclipse.swt.internal.gtk.GTK._gtk_main_do_event(Native Method)
	at org.eclipse.swt.internal.gtk.GTK.gtk_main_do_event(GTK.java:4118)
	at org.eclipse.swt.widgets.Display.eventProc(Display.java:1414)
	at org.eclipse.swt.internal.gtk.OS._g_main_context_iteration(Native Method)
	at org.eclipse.swt.internal.gtk.OS.g_main_context_iteration(OS.java:1596)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4581)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:628)
	at org.eclipse.ui.internal.Workbench$$Lambda$36/349330286.run(Unknown Source)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:563)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:151)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:199)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:391)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:246)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1474)

**Comment by elharo** [comment]
[freeze.log](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/files/3263442/freeze.log)

**Comment by briandealwis** [comment]
I can't really figure out what's going on there.  Much further down there is a trace where we're launching a server:
```
!ENTRY org.eclipse.ui.monitoring 2 0 2019-06-06 15:04:26.311
!MESSAGE UI freeze of 0.89s at 15:04:25.421
!SUBENTRY 1 org.eclipse.ui.monitoring 1 0 2019-06-06 15:04:26.311
!MESSAGE Sample at 15:04:25.783 (+0.362s)
Thread 'main' tid=1 (RUNNABLE)
!STACK 0
Stack Trace
[...]
	at com.google.cloud.tools.eclipse.appengine.localserver.server.LocalAppEngineServerDelegate.getChildModules(LocalAppEngineServerDelegate.java:219)
	at org.eclipse.wst.server.core.internal.Server.getChildModules(Server.java:2647)
	at org.eclipse.wst.server.core.internal.ServerWorkingCopy.resetState(ServerWorkingCopy.java:622)
	at org.eclipse.wst.server.core.internal.ServerWorkingCopy.modifyModules(ServerWorkingCopy.java:564)
	at com.google.cloud.tools.eclipse.appengine.localserver.launching.LaunchHelper.createServer(LaunchHelper.java:130)
	at com.google.cloud.tools.eclipse.appengine.localserver.launching.LaunchHelper.launch(LaunchHelper.java:77)
	at com.google.cloud.tools.eclipse.appengine.localserver.launching.LocalAppEngineStandardLaunchShortcut.launch(LocalAppEngineStandardLaunchShortcut.java:55)
```

Maybe we could turn that launch shortcut into a background job.

**Comment by briandealwis** [comment]
Ah this one is part of my argument that `LibraryClasspathContainerInitializer` is too heavyweight:
```
!ENTRY org.eclipse.ui.monitoring 4 0 2019-06-06 15:10:08.433
!MESSAGE UI freeze of 3.8s at 15:10:04.589
!SUBENTRY 1 org.eclipse.ui.monitoring 1 0 2019-06-06 15:10:08.433
!MESSAGE Sample at 15:10:05.923 (+1.334s)
Thread 'main' tid=1 (RUNNABLE)
!STACK 0
Stack Trace
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:985)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:942)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at okio.Okio$2.read(Okio.java:140)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:355)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:227)
	at okhttp3.internal.http1.Http1Codec.readHeaderLine(Http1Codec.java:215)
	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at okhttp3.RealCall.execute(RealCall.java:77)
	at io.takari.aether.okhttp.OkHttpAetherClient.execute(OkHttpAetherClient.java:207)
	at io.takari.aether.okhttp.OkHttpAetherClient.get(OkHttpAetherClient.java:153)
	at io.takari.aether.connector.AetherRepositoryConnector$GetTask.getResponse(AetherRepositoryConnector.java:626)
	at io.takari.aether.connector.AetherRepositoryConnector$GetTask.resumableGet(AetherRepositoryConnector.java:571)
	at io.takari.aether.connector.AetherRepositoryConnector$GetTask.run(AetherRepositoryConnector.java:452)
	at io.takari.aether.connector.AetherRepositoryConnector.get(AetherRepositoryConnector.java:303)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:498)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:399)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:224)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:338)
	at com.google.cloud.tools.eclipse.util.DependencyResolver._getTransitiveDependencies(DependencyResolver.java:92)
	at com.google.cloud.tools.eclipse.util.DependencyResolver.lambda$0(DependencyResolver.java:63)
	at com.google.cloud.tools.eclipse.util.DependencyResolver$$Lambda$607/586688525.run(Unknown Source)
	at com.google.cloud.tools.eclipse.util.MavenUtils.lambda$1(MavenUtils.java:124)
	at com.google.cloud.tools.eclipse.util.MavenUtils$$Lambda$605/211078823.call(Unknown Source)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
	at com.google.cloud.tools.eclipse.util.MavenUtils.runOperation(MavenUtils.java:120)
	at com.google.cloud.tools.eclipse.util.DependencyResolver.getTransitiveDependencies(DependencyResolver.java:60)
	at com.google.cloud.tools.eclipse.appengine.libraries.model.LibraryFactory.loadTransitiveDependencies(LibraryFactory.java:120)
	at com.google.cloud.tools.eclipse.appengine.libraries.model.Library.resolveDependencies(Library.java:211)
	at com.google.cloud.tools.eclipse.appengine.libraries.model.Library.getAllDependencies(Library.java:117)
	at com.google.cloud.tools.eclipse.appengine.libraries.BuildPath.collectLibraryFiles(BuildPath.java:152)
	at com.google.cloud.tools.eclipse.appengine.libraries.ui.CloudLibrariesPage.finish(CloudLibrariesPage.java:173)
	at org.eclipse.jdt.internal.ui.wizards.buildpaths.ClasspathContainerWizard.performFinish(ClasspathContainerWizard.java:95)
	at org.eclipse.jdt.internal.ui.wizards.buildpaths.newsourcepage.AddLibraryToBuildpathAction$1.performFinish(AddLibraryToBuildpathAction.java:92)
	at org.eclipse.jface.wizard.WizardDialog.finishPressed(WizardDialog.java:775)
	at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:414)
	at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:622)
```
