### ISSUE TITLE
Error trying to create new GAE app; can't find IElementChangedListener

### ISSUE THREAD

**Issue by jtamplin** [GoogleCloudPlatform/google-cloud-eclipse#3475]
- Cloud Tools for Eclipse version: 1.8.0.201901101851
- Google Cloud SDK version: 250.0.0 (auto-managed)
- Eclipse version: 4.11.0.v20190308-0658
- OS: Linux 5.1.7-300.fc30.x86_64
- Java version: 1.8.0_212

**What did you do?**
Following https://cloud.google.com/eclipse/docs/creating-new-webapp I clicked on "Create New Project / Google App Engine Standard Java Project" (step 2 on the page).  This is on Fedora 30 with Eclipse (including eclipse-mpc so I could install Google Cloud from Eclipse Marketplace) installed via dnf.  I also tried with a completely new workspace with the same results.

**What did you expect to see?**
I expected to see the dialog box asking for information to create the app.

**What did you see instead?**
Nothing happened.  Looking in the Eclipse Error log, I see:

```
An error occurred while automatically activating bundle com.google.cloud.tools.eclipse.appengine.libraries (829).

org.osgi.framework.BundleException: Error starting module.
	at org.eclipse.osgi.container.Module.doStart(Module.java:598)
	at org.eclipse.osgi.container.Module.start(Module.java:457)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:471)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:117)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:570)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:331)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:395)
	at org.eclipse.osgi.internal.loader.sources.SingleSourcePackage.loadClass(SingleSourcePackage.java:39)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:457)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:422)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:414)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:153)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
	at java.lang.Class.getDeclaredFields(Class.java:1916)
	at org.eclipse.e4.core.internal.di.InjectorImpl.getDeclaredFields(InjectorImpl.java:848)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processFields(InjectorImpl.java:711)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processClass(InjectorImpl.java:677)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processClassHierarchy(InjectorImpl.java:658)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalInject(InjectorImpl.java:115)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:411)
	at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:333)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:202)
	at com.google.cloud.tools.eclipse.util.service.ServiceContextFactory.create(ServiceContextFactory.java:63)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:265)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:63)
	at org.eclipse.ui.internal.WorkbenchPlugin.lambda$0(WorkbenchPlugin.java:291)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:72)
	at org.eclipse.ui.internal.WorkbenchPlugin.createExtension(WorkbenchPlugin.java:288)
	at org.eclipse.ui.internal.dialogs.WorkbenchWizardElement.createExecutableExtension(WorkbenchWizardElement.java:126)
	at org.eclipse.ui.internal.dialogs.WorkbenchWizardElement.createWizard(WorkbenchWizardElement.java:264)
	at org.eclipse.ui.internal.handlers.WizardHandler.execute(WizardHandler.java:304)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:294)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:320)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:254)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:497)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:490)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:438)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:449)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5783)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1411)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5051)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4579)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.dropdownEvent(AbstractContributionItem.java:425)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:436)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5783)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1411)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5051)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4579)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:566)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:661)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1476)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1449)
Caused by: java.lang.NoClassDefFoundError: org/eclipse/jdt/core/IElementChangedListener
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.getConstructor(Class.java:1825)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.loadBundleActivator(BundleContextImpl.java:799)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:752)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1005)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:357)
	at org.eclipse.osgi.container.Module.doStart(Module.java:589)
	... 84 more
Caused by: java.lang.ClassNotFoundException: org.eclipse.jdt.core.IElementChangedListener cannot be found by com.google.cloud.tools.eclipse.appengine.libraries_0.1.0.201812192346
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:460)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:422)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:414)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:153)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 93 more
Root exception:
java.lang.NoClassDefFoundError: org/eclipse/jdt/core/IElementChangedListener
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.getConstructor(Class.java:1825)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.loadBundleActivator(BundleContextImpl.java:799)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:752)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1005)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:357)
	at org.eclipse.osgi.container.Module.doStart(Module.java:589)
	at org.eclipse.osgi.container.Module.start(Module.java:457)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:471)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:117)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:570)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:331)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:395)
	at org.eclipse.osgi.internal.loader.sources.SingleSourcePackage.loadClass(SingleSourcePackage.java:39)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:457)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:422)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:414)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:153)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
	at java.lang.Class.getDeclaredFields(Class.java:1916)
	at org.eclipse.e4.core.internal.di.InjectorImpl.getDeclaredFields(InjectorImpl.java:848)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processFields(InjectorImpl.java:711)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processClass(InjectorImpl.java:677)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processClassHierarchy(InjectorImpl.java:658)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalInject(InjectorImpl.java:115)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:411)
	at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:333)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:202)
	at com.google.cloud.tools.eclipse.util.service.ServiceContextFactory.create(ServiceContextFactory.java:63)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:265)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:63)
	at org.eclipse.ui.internal.WorkbenchPlugin.lambda$0(WorkbenchPlugin.java:291)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:72)
	at org.eclipse.ui.internal.WorkbenchPlugin.createExtension(WorkbenchPlugin.java:288)
	at org.eclipse.ui.internal.dialogs.WorkbenchWizardElement.createExecutableExtension(WorkbenchWizardElement.java:126)
	at org.eclipse.ui.internal.dialogs.WorkbenchWizardElement.createWizard(WorkbenchWizardElement.java:264)
	at org.eclipse.ui.internal.handlers.WizardHandler.execute(WizardHandler.java:304)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:294)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:320)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:254)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:497)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:490)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:438)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:449)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5783)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1411)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5051)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4579)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.dropdownEvent(AbstractContributionItem.java:425)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:436)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5783)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1411)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5051)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4579)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:566)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:661)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1476)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1449)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jdt.core.IElementChangedListener cannot be found by com.google.cloud.tools.eclipse.appengine.libraries_0.1.0.201812192346
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:460)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:422)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:414)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:153)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 93 more

```

**Comment by chanseokoh** [comment]
This seems odd, as I _think_ `IElementChangedListener` is such a core part that must exist in your Eclipse installation.

In any case, Google Cloud Tools for Eclipse (CT4E) nonetheless requires _Eclipse IDE for Java EE Developers_ (that for example comes with WTP): https://cloud.google.com/eclipse/docs/quickstart) Can you try again after installing CT4E on _Eclipse IDE for Java EE Developers_?

**Comment by briandealwis** [comment]
Very odd: `org.eclipse.jdt.core` is a pretty fundamental bundle, and `org.eclipse.jdt.core.IElementChangedListener` is a very fundamental class.  Could you please try the following:
  1. Open the _Console_ view via Ctrl-3 (Quick Access) > Console
  2. Use the _Open Console_ button (icon with a little plus in the upper-right) to open a _Host OSGi Console_
  3. At the `osgi>` prompt, type `ss com.google.cloud.tools.eclipse.appengine.libraries` to identify the Bundle ID.
  4. Then type `diag ID#` where `ID#` is the Bundle ID
  5. And then please repeat 3 and 4 for `org.eclipse.jdt.core`.

For example, this is what I see when I examine `com.google.cloud.tools.eclipse.appengine.libraries`:
```
osgi> ss com.google.cloud.tools.eclipse.appengine.libraries
"Framework is launched."

id	State       Bundle
28	ACTIVE      com.google.cloud.tools.eclipse.appengine.libraries_0.1.0.201905101625
29	STARTING    com.google.cloud.tools.eclipse.appengine.libraries.ui_0.1.0.201902071901

osgi> diag 28
com.google.cloud.tools.eclipse.appengine.libraries [28]
  No resolution report for the bundle.
```

The "_No resolution report_" means that there are no bundle resolution problems.  Given that you're hitting a runtime problem, I expect you'll see a similar report.

I wonder if your `org.eclipse.jdt.core` bundle file is corrupt?  Could you find the matching `org.eclipse.jdt.core_*.` file and use `unzip -v .../org.eclipse.jdt.core_xxx.jar` and verify that the archive is ok?  For example, on my machine:
```sh
$ unzip -v /usr/local/installs/e4-dev/plugins/org.eclipse.jdt.core_3.18.0.v20190522-0428.jar | grep org.eclipse.jdt.core.IElementChangedListener
     221  Defl:N      150  32% 05-22-2019 06:40 5570067f  org/eclipse/jdt/core/IElementChangedListener.class
```

**Comment by jtamplin** [comment]
```
g! ss com.google.cloud.tools.eclipse.appengine.libraries
"Framework is launched."


id	State       Bundle
829	RESOLVED    com.google.cloud.tools.eclipse.appengine.libraries_0.1.0.201812192346
830	STARTING    com.google.cloud.tools.eclipse.appengine.libraries.ui_0.1.0.201812142008
g! diag 829
com.google.cloud.tools.eclipse.appengine.libraries [829]
  No resolution report for the bundle.
g! diag 830
com.google.cloud.tools.eclipse.appengine.libraries.ui [830]
  No resolution report for the bundle.
g! ss org.eclipse.jdt.core
"Framework is launched."


id	State       Bundle
141	RESOLVED    org.eclipse.jdt.core.compiler.batch_3.17.0.v20190308-0658
345	ACTIVE      org.eclipse.jdt.core_3.17.0.v20190308-0658
	            Fragments=343, 344
346	ACTIVE      org.eclipse.jdt.core.manipulation_1.11.100.v20190308-0658
g! diag 141
org.eclipse.jdt.core.compiler.batch [141]
  No resolution report for the bundle.
g! diag 345
org.eclipse.jdt.core [345]
  No resolution report for the bundle.
g! diag 346
org.eclipse.jdt.core.manipulation [346]
  No resolution report for the bundle.
```
The Google plugin is much older than yours, but I installed it from the Eclipse marketplace just a few days ago.

```
[jat@jat mysql]$ unzip -v /usr/share/eclipse/droplets/eclipse-jdt/plugins/org.eclipse.jdt.core_3.17.0.v20190308-0658.jar | grep org.eclipse.jdt.core.IElementChangedListener
     221  Defl:N      150  32% 04-10-2019 16:06 5570067f  org/eclipse/jdt/core/IElementChangedListener.class
```
These are the Eclipse packages I have installed.  It would be a shame if the Google plugin won't actually work with the packages managed by the distribution.
```
[jat@jat mysql]$ rpm -qa | fgrep eclipse | sort
eclipse-abrt-0.0.3-9.fc30.noarch
eclipse-avr-2.4.2-8.fc30.noarch
eclipse-cdt-9.7.0-1.fc30.x86_64
eclipse-cdt-arduino-9.7.0-1.fc30.x86_64
eclipse-cdt-llvm-9.7.0-1.fc30.x86_64
eclipse-cdt-native-9.7.0-1.fc30.x86_64
eclipse-cdt-qt-9.7.0-1.fc30.x86_64
eclipse-checkstyle-7.6.0-7.fc30.noarch
eclipse-dtp-1.14.102-4.fc30.noarch
eclipse-ecf-core-3.14.4-2.fc30.noarch
eclipse-egit-5.3.0-2.fc30.noarch
eclipse-egit-github-5.3.0-1.fc30.noarch
eclipse-emf-core-2.16.0-2.fc30.noarch
eclipse-emf-runtime-2.16.0-2.fc30.noarch
eclipse-emf-xsd-2.16.0-2.fc30.noarch
eclipse-epic-0.7.5-4.fc30.noarch
eclipse-epp-logging-2.0.7-8.fc30.noarch
eclipse-equinox-osgi-4.11-4.fc30.x86_64
eclipse-findbugs-3.0.1-18.fc30.noarch
eclipse-findbugs-contrib-7.4.5-1.fc30.noarch
eclipse-gef-3.11.0-9.fc30.noarch
eclipse-jdt-4.11-4.fc30.noarch
eclipse-jgit-5.3.0-5.fc30.noarch
eclipse-launchbar-2.2.3-1.fc30.noarch
eclipse-linuxtools-7.2.0-5.fc30.noarch
eclipse-linuxtools-gcov-7.2.0-5.fc30.noarch
eclipse-linuxtools-libhover-7.2.0-5.fc30.noarch
eclipse-m2e-core-1.11.0-1.fc30.noarch
eclipse-m2e-mavenarchiver-0.17.2-0.5.git5a285e5.fc30.noarch
eclipse-m2e-mavendev-0.3.0.201506181201-8.fc30.noarch
eclipse-m2e-sourcelookup-1.1.0.201506181114-8.fc30.noarch
eclipse-m2e-workspace-0.4.0-10.fc30.noarch
eclipse-m2e-wtp-1.4.1-3.fc30.noarch
eclipse-mpc-1.7.5-2.fc30.noarch
eclipse-mylyn-3.25.0-0.6.fc30.noarch
eclipse-mylyn-tasks-bugzilla-3.25.0-0.6.fc30.noarch
eclipse-p2-discovery-4.11-4.fc30.noarch
eclipse-pde-4.11-4.fc30.x86_64
eclipse-platform-4.11-4.fc30.x86_64
eclipse-remote-3.0.1-2.fc30.noarch
eclipse-swt-4.11-4.fc30.x86_64
eclipse-tm-terminal-4.5.100-1.fc30.noarch
eclipse-tm-terminal-connectors-4.5.100-1.fc30.noarch
eclipse-tm-terminal-rse-4.5.100-1.fc30.noarch
eclipse-usage-4.11.0-1.fc30.noarch
eclipse-webtools-common-3.13.0-1.fc30.noarch
eclipse-webtools-dali-3.13.0-1.fc30.noarch
eclipse-webtools-javaee-3.13.0-1.fc30.noarch
eclipse-webtools-servertools-3.13.0-1.fc30.noarch
eclipse-webtools-sourceediting-3.13.0-1.fc30.noarch
maven-eclipse-plugin-2.9-22.fc30.noarch
```

**Comment by elharo** [comment]
Your google plugin is the most recent released version. @briandealwis is running a newer build we're in the process of QA'ing, but I doubt anything has changed that's relevant to this problem.

**Comment by briandealwis** [comment]
@jtamplin would it be possible to attach your `...workspace.../.metadata/.log` file here?

And could you also try quitting and restarting with `-clean`?  That should cause Eclipse to rebuild any cache files.

**Comment by jtamplin** [comment]
Ok, after starting with -clean I get the dialog.  There are still a bunch of complaints in .metadata/.log, but the Google plugin is working now.  Thanks for your help.

[.metadata/.log](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/files/3297983/eclipse-metadata.log)
