### ISSUE TITLE
Test flake in testDynamicChanges_appEngineWebXml_appYaml

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#3492]
Seen on Travis for [Photon on Java 8](https://api.travis-ci.org/v3/job/549877616/log.txt):
```
testDynamicChanges_appEngineWebXml_appYaml(com.google.cloud.tools.eclipse.appengine.facets.ui.navigator.AppEngineContentProviderTest)  Time elapsed: 6.186 s  <<< FAILURE!
java.lang.AssertionError: back to appengine-web.xml expected:<L/test0.6650029576374151/WebContent/WEB-INF/appengine-web.xml> but was:<L/test0.6650029576374151/WebContent/WEB-INF/app.yaml>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at com.google.cloud.tools.eclipse.appengine.facets.ui.navigator.AppEngineContentProviderTest.testDynamicChanges_appEngineWebXml_appYaml(AppEngineContentProviderTest.java:415)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
```

**Comment by briandealwis** [comment]
Seen again on Photon

**Comment by JoeWang1127** [comment]
close as not planned
