### ISSUE TITLE
Missing Dependencies In AppEngine?

### ISSUE THREAD

**Issue by mhopkins-dynactive** [GoogleCloudPlatform/google-cloud-eclipse#3555]
- Cloud Tools for Eclipse version:  1.8.2.201906242031	
- Google Cloud SDK version: 

Google Cloud SDK 272.0.0
app-engine-java 1.9.77
app-engine-python 1.9.87
cloud-datastore-emulator 2.1.0
core 2019.11.16
gcloud 
gsutil 4.46

- Eclipse version: 2018-12 (4.10.0)
- OS: OSX mojave
- Java version: 1.8

**What did you do?**

Removed old App-engine dependencies from the classpath thinking that they were being added by the plugin.

**What did you expect to see?**

I expected dependencies to be present and they were not. 

**What did you see instead?**

ClassDefNotFound Errors on live of missing dependencies.

I removed a old jar file google-api-client-appengine-1.18.0-rc.jar assuming that the new google-api-client-appengine-1.30.4 would be loaded in by the plugin but it is not. Now I see that other files that I expect to see are not being loaded in. The following is a list of files I expected to be loaded by the plugin and which ones are missing.

google-api-client-1.30.4.jar
google-api-client-appengine-1.30.4.jar **Missing**
google-api-client-servlet-1.30.4.jar **Missing**
google-oauth-client-1.30.3.jar 
google-oauth-client-appengine-1.30.3.jar **Missing**
google-oauth-client-servlet-1.30.3.jar **Missing**
google-http-client-1.32.1.jar 
google-http-client-appengine-1.32.1.jar
gson-2.8.6.jar
jackson-core-2.9.5.jar
jdo2-api-2.3-eb.jar **Missing**
jsr305-3.0.2.jar
protobuf-java-3.10.0.jar
transaction-api-1.1.jar **Missing**
xpp3-1.1.4c.jar **Missing**

Here is the stack trace:

java.lang.NoClassDefFoundError: com/google/api/client/googleapis/extensions/appengine/auth/oauth2/AppIdentityCredential
	at com.google.appengine.tools.cloudstorage.oauth.OauthRawGcsService.<init>(OauthRawGcsService.java:174)
	at com.google.appengine.tools.cloudstorage.oauth.OauthRawGcsServiceFactory.createOauthRawGcsService(OauthRawGcsServiceFactory.java:41)
	at com.google.appengine.tools.cloudstorage.GcsServiceFactory.createRawGcsService(GcsServiceFactory.java:59)
	at com.google.appengine.tools.cloudstorage.GcsServiceFactory.createGcsService(GcsServiceFactory.java:44)
	at com.google.appengine.tools.cloudstorage.GcsServiceFactory.createGcsService(GcsServiceFactory.java:40)
	at com.dynactivesoftware.gaerdvark.core.tasks.CSVFileGenerator.generate(CSVFileGenerator.java:79)
	at com.dynactivesoftware.gaerdvark.core.tasks.CreateUserReportTask.createReportForNamespaces(CreateUserReportTask.java:221)
	at com.dynactivesoftware.gaerdvark.core.tasks.CreateUserReportTask.run(CreateUserReportTask.java:147)

<img width="553" alt="Screen Shot 2019-11-22 at 6 18 41 PM" src="https://user-images.githubusercontent.com/9939007/69470555-98c9d700-0d54-11ea-95c1-1e6f7f146f86.png">

**Comment by elharo** [comment]
google-api-client-appengine-1.18.0-rc.jar  is not one of the libraries directly managed by the plugin. If you add, or perhaps remove and add, one of the libraries that depends on it, it should be added back in.
