### ISSUE TITLE
Creating a new Maven project can't download sources with Java 11:

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#3573]
While creating a new Maven project per test plan, I was using JDK 11 and got:

An internal error occurred during: "Download sources and javadoc".
clientBuilder.sslSocketFactory(SSLSocketFactory) not supported on JDK 9+

**Comment by elharo** [comment]
![image](https://user-images.githubusercontent.com/1005544/70460672-e2206300-1a84-11ea-9b9d-caaf2d9058bb.png)

**Comment by elharo** [comment]
I'm using Eclipse 4.11.0 which should be comfortable with Java 11. Perhaps  Maven, m2e, or our own code is referring to older Aether classes?

**Comment by elharo** [comment]
confirmed that when I modify eclipse.ini with -vm to run under Java 8 instead of Java 11 this does not occur.

**Comment by elharo** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=517113

**Comment by elharo** [comment]
stack trace:

java.lang.UnsupportedOperationException: clientBuilder.sslSocketFactory(SSLSocketFactory) not supported on JDK 9+
	at okhttp3.internal.platform.Jdk9Platform.trustManager(Jdk9Platform.java:78)
	at okhttp3.OkHttpClient$Builder.sslSocketFactory(OkHttpClient.java:650)
	at io.takari.aether.okhttp.OkHttpAetherClient.<init>(OkHttpAetherClient.java:98)
	at io.takari.aether.connector.AetherRepositoryConnector.newAetherClient(AetherRepositoryConnector.java:276)
	at io.takari.aether.connector.AetherRepositoryConnector.<init>(AetherRepositoryConnector.java:191)
	at io.takari.aether.connector.AetherRepositoryConnectorFactory.newInstance(AetherRepositoryConnectorFactory.java:89)
	at org.eclipse.aether.internal.impl.DefaultRepositoryConnectorProvider.newRepositoryConnector(DefaultRepositoryConnectorProvider.java:113)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:516)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:294)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl$5.call(MavenImpl.java:753)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl$5.call(MavenImpl.java:1)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.resolve(MavenImpl.java:743)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.resolve(MavenImpl.java:720)
	at org.eclipse.m2e.jdt.internal.DownloadSourcesJob.download(DownloadSourcesJob.java:264)
	at org.eclipse.m2e.jdt.internal.DownloadSourcesJob.downloadAttachments(DownloadSourcesJob.java:243)
	at org.eclipse.m2e.jdt.internal.DownloadSourcesJob.downloadMaven(DownloadSourcesJob.java:217)
	at org.eclipse.m2e.jdt.internal.DownloadSourcesJob.run(DownloadSourcesJob.java:161)
	at org.eclipse.m2e.jdt.internal.DownloadSourcesJob$1.call(DownloadSourcesJob.java:137)
	at org.eclipse.m2e.jdt.internal.DownloadSourcesJob$1.call(DownloadSourcesJob.java:1)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1355)
	at org.eclipse.m2e.jdt.internal.DownloadSourcesJob.run(DownloadSourcesJob.java:135)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by elharo** [comment]
Looks like I have m2e 1.8.0 and the fix for this doesn't happen until 1.8.1. Is this something we do or can control?

**Comment by elharo** [comment]
Eclipse seems to have trouble upgrading m2e, now sure why:

![image](https://user-images.githubusercontent.com/1005544/70462870-c9ff1280-1a89-11ea-982d-1cf88acbc383.png)

**Comment by briandealwis** [comment]
1.8.3 was released in Oxygen!  I wonder if you have something else loaded that's pinning m2e to a lower version.

**Comment by elharo** [comment]
Possibly. I'd to know what though.

**Comment by elharo** [comment]
This is an issue with m2e 1.8.0 or earlier, not our bug.
