### ISSUE TITLE
CI flaky due to 403s in LibraryFactorytest

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#3591]
```
22:21:30.702 [main] WARN  c.g.c.t.e.util.ArtifactRetriever - Could not retrieve version for artifact com.google.guava:guava

java.io.IOException: Server returned HTTP response code: 403 for URL: https://repo1.maven.org/maven2/com/google/guava/guava/maven-metadata.xml

	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1913) ~[na:na]

	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509) ~[na:na]

	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:245) ~[na:na]

	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:678) ~[na:na]

	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineDocVersion(XMLVersionDetector.java:150) ~[na:na]

	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:860) ~[na:na]

	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824) ~[na:na]

	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141) ~[na:na]

	at java.xml/com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:246) ~[na:na]

	at java.xml/com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339) ~[na:na]

	at java.xml/javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:178) ~[na:na]

	at com.google.cloud.tools.eclipse.util.ArtifactRetriever.getMetadataDocument(ArtifactRetriever.java:216) ~[com.google.cloud.tools.eclipse.util-0.1.0-SNAPSHOT.jar:na]

	at com.google.cloud.tools.eclipse.util.ArtifactRetriever.access$000(ArtifactRetriever.java:59) ~[com.google.cloud.tools.eclipse.util-0.1.0-SNAPSHOT.jar:na]

	at com.google.cloud.tools.eclipse.util.ArtifactRetriever$1.load(ArtifactRetriever.java:86) ~[com.google.cloud.tools.eclipse.util-0.1.0-SNAPSHOT.jar:na]

	at com.google.cloud.tools.eclipse.util.ArtifactRetriever$1.load(ArtifactRetriever.java:82) ~[com.google.cloud.tools.eclipse.util-0.1.0-SNAPSHOT.jar:na]

	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529) ~[guava-28.1-jre.jar:na]

	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278) ~[guava-28.1-jre.jar:na]

	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155) ~[guava-28.1-jre.jar:na]

	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045) ~[guava-28.1-jre.jar:na]

	at com.google.common.cache.LocalCache.get(LocalCache.java:3953) ~[guava-28.1-jre.jar:na]

	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3976) ~[guava-28.1-jre.jar:na]

	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4960) ~[guava-28.1-jre.jar:na]

	at com.google.cloud.tools.eclipse.util.ArtifactRetriever.getLatestVersion(ArtifactRetriever.java:185) ~[com.google.cloud.tools.eclipse.util-0.1.0-SNAPSHOT.jar:na]

	at com.google.cloud.tools.eclipse.util.ArtifactRetriever.getBestVersion(ArtifactRetriever.java:141) ~[com.google.cloud.tools.eclipse.util-0.1.0-SNAPSHOT.jar:na]

	at com.google.cloud.tools.eclipse.appengine.libraries.model.LibraryFile.updateVersion(LibraryFile.java:123) ~[com.google.cloud.tools.eclipse.appengine.libraries-0.1.0-SNAPSHOT.jar:na]

	at com.google.cloud.tools.eclipse.appengine.libraries.model.LibraryFactory.getLibraryFiles(LibraryFactory.java:110) ~[com.google.cloud.tools.eclipse.appengine.libraries-0.1.0-SNAPSHOT.jar:na]

	at com.google.cloud.tools.eclipse.appengine.libraries.model.LibraryFactory.create(LibraryFactory.java:78) ~[com.google.cloud.tools.eclipse.appengine.libraries-0.1.0-SNAPSHOT.jar:na]

	at com.google.cloud.tools.eclipse.appengine.libraries.model.LibraryFactoryTest.testCreate_useLatestVersion(LibraryFactoryTest.java:62) ~[classes/:na]

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]

	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]

	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]

	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50) ~[junit.jar:4.12]

	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) ~[junit.jar:4.12]

	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47) ~[junit.jar:4.12]

	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) ~[junit.jar:4.12]

	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26) ~[junit.jar:4.12]

	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325) ~[junit.jar:4.12]

	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78) ~[junit.jar:4.12]

	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57) ~[junit.jar:4.12]

	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) ~[junit.jar:4.12]

	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71) ~[junit.jar:4.12]

	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) ~[junit.jar:4.12]

	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) ~[junit.jar:4.12]

	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) ~[junit.jar:4.12]

	at org.junit.runners.ParentRunner.run(ParentRunner.java:363) ~[junit.jar:4.12]

	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365) ~[org.eclipse.tycho.surefire.junit4-1.3.0.jar:na]

	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273) ~[org.eclipse.tycho.surefire.junit4-1.3.0.jar:na]

	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238) ~[org.eclipse.tycho.surefire.junit4-1.3.0.jar:na]

	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159) ~[org.eclipse.tycho.surefire.junit4-1.3.0.jar:na]

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]

	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]

	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]

	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:206) ~[surefire-api-2.22.0.jar:2.22.0]

	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:161) ~[surefire-booter-2.22.0.jar:2.22.0]

	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:84) ~[surefire-booter-2.22.0.jar:2.22.0]

	at org.eclipse.tycho.surefire.osgibooter.OsgiSurefireBooter.run(OsgiSurefireBooter.java:110) ~[org.eclipse.tycho.surefire.osgibooter-1.3.0.jar:na]

	at org.eclipse.tycho.surefire.osgibooter.HeadlessTestApplication.run(HeadlessTestApplication.java:21) ~[org.eclipse.tycho.surefire.osgibooter-1.3.0.jar:na]

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]

	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]

	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]

	at org.eclipse.equinox.internal.app.EclipseAppContainer.callMethodWithException(EclipseAppContainer.java:590) ~[org.eclipse.equinox.app-1.3.600.v20180827-1235.jar:na]

	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:201) ~[org.eclipse.equinox.app-1.3.600.v20180827-1235.jar:na]

	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137) ~[org.eclipse.osgi-3.13.100.v20180827-1536.jar:na]

	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107) ~[org.eclipse.osgi-3.13.100.v20180827-1536.jar:na]

	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:391) ~[org.eclipse.osgi-3.13.100.v20180827-1536.jar:na]

	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:246) ~[org.eclipse.osgi-3.13.100.v20180827-1536.jar:na]

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]

	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]

	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]

	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659) ~[org.eclipse.equinox.launcher-1.5.100.v20180827-1352.jar:na]

	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595) ~[org.eclipse.equinox.launcher-1.5.100.v20180827-1352.jar:na]

	at org.eclipse.equinox.launcher.Main.run(Main.java:1501) ~[org.eclipse.equinox.launcher-1.5.100.v20180827-1352.jar:na]

	at org.eclipse.equinox.launcher.Main.main(Main.java:1474) ~[org.eclipse.equinox.launcher-1.5.100.v20180827-1352.jar:na]

Tests run: 6, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.828 s <<< FAILURE! - in com.google.cloud.tools.eclipse.appengine.libraries.model.LibraryFactoryTest

testCreate_nonDefaults(com.google.cloud.tools.eclipse.appengine.libraries.model.LibraryFactoryTest)  Time elapsed: 0.116 s

testCreate_null(com.google.cloud.tools.eclipse.appengine.libraries.model.LibraryFactoryTest)  Time elapsed: 0.078 s

testCreate_useSpecificVersion(com.google.cloud.tools.eclipse.appengine.libraries.model.LibraryFactoryTest)  Time elapsed: 0.058 s

testCreate_nonLibrary(com.google.cloud.tools.eclipse.appengine.libraries.model.LibraryFactoryTest)  Time elapsed: 0.054 s

testCreate_useLatestVersion(com.google.cloud.tools.eclipse.appengine.libraries.model.LibraryFactoryTest)  Time elapsed: 0.483 s  <<< FAILURE!
```

**Comment by chanseokoh** [comment]
Sometimes Maven Central is unreliable and returns 403.
