### ISSUE TITLE
Test failure in CloudSdkPreferenceAreaTest.testInvalidPath:115 on Kokoro

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#3595]
Haven't seen this test failure previously:
https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/59f03831047d1f6524c070abf0720aefbeaeb484/plugins/com.google.cloud.tools.eclipse.sdk.ui.test/src/com/google/cloud/tools/eclipse/sdk/ui/preferences/CloudSdkPreferenceAreaTest.java#L105-L116

```
Running com.google.cloud.tools.eclipse.sdk.ui.preferences.CloudSdkPreferenceAreaTest
14:16:39.524 [main] DEBUG c.g.c.t.a.o.cloudsdk.PathResolver - Resolved SDK path : C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk
14:16:39.571 [main] DEBUG c.g.c.t.a.o.cloudsdk.PathResolver - Resolved SDK path : C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk
14:16:39.602 [main] DEBUG c.g.c.t.a.o.cloudsdk.PathResolver - Resolved SDK path : C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk
14:16:39.649 [main] DEBUG c.g.c.t.a.o.cloudsdk.PathResolver - Resolved SDK path : C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk
14:16:39.680 [main] DEBUG c.g.c.t.a.o.cloudsdk.PathResolver - Resolved SDK path : C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk
14:16:39.696 [main] DEBUG c.g.c.t.a.o.cloudsdk.PathResolver - Resolved SDK path : C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk
14:16:39.727 [main] DEBUG c.g.c.t.a.o.cloudsdk.PathResolver - Resolved SDK path : C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk
14:16:39.743 [main] DEBUG c.g.c.t.a.o.cloudsdk.PathResolver - Resolved SDK path : C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk
14:16:39.758 [main] DEBUG c.g.c.t.a.o.cloudsdk.PathResolver - Resolved SDK path : C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk
14:16:39.774 [main] DEBUG c.g.c.t.a.o.cloudsdk.PathResolver - Resolved SDK path : C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk
Tests run: 12, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.078 s <<< FAILURE! - in com.google.cloud.tools.eclipse.sdk.ui.preferences.CloudSdkPreferenceAreaTest
testControlStates_automaticSdk(com.google.cloud.tools.eclipse.sdk.ui.preferences.CloudSdkPreferenceAreaTest)  Time elapsed: 0.063 s
testUpdateSdk_manualSdkDisabled(com.google.cloud.tools.eclipse.sdk.ui.preferences.CloudSdkPreferenceAreaTest)  Time elapsed: 0.031 s
testInvalidPath(com.google.cloud.tools.eclipse.sdk.ui.preferences.CloudSdkPreferenceAreaTest)  Time elapsed: 0.032 s  <<< FAILURE!
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.google.cloud.tools.eclipse.sdk.ui.preferences.CloudSdkPreferenceAreaTest.testInvalidPath(CloudSdkPreferenceAreaTest.java:115)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.mockito.internal.runners.JUnit45AndHigherRunnerImpl.run(JUnit45AndHigherRunnerImpl.java:37)
	at org.mockito.runners.MockitoJUnitRunner.run(MockitoJUnitRunner.java:62)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:206)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:161)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:84)
	at org.eclipse.tycho.surefire.osgibooter.OsgiSurefireBooter.run(OsgiSurefireBooter.java:113)
	at org.eclipse.tycho.surefire.osgibooter.AbstractUITestApplication$1.run(AbstractUITestApplication.java:35)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:37)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3906)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3537)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1170)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1059)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:667)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:597)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.tycho.surefire.osgibooter.UITestApplication.runApplication(UITestApplication.java:31)
	at org.eclipse.tycho.surefire.osgibooter.AbstractUITestApplication.run(AbstractUITestApplication.java:120)
	at org.eclipse.tycho.surefire.osgibooter.UITestApplication.start(UITestApplication.java:37)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:656)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:592)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1498)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1471)

testValidationStatus_switchManagementOption(com.google.cloud.tools.eclipse.sdk.ui.preferences.CloudSdkPreferenceAreaTest)  Time elapsed: 0.594 s
testApply_automatic(com.google.cloud.tools.eclipse.sdk.ui.preferences.CloudSdkPreferenceAreaTest)  Time elapsed: 0.062 s
testUi_sdkManagementFeature(com.google.cloud.tools.eclipse.sdk.ui.preferences.CloudSdkPreferenceAreaTest)  Time elapsed: 0.016 s
testVersion(com.google.cloud.tools.eclipse.sdk.ui.preferences.CloudSdkPreferenceAreaTest)  Time elapsed: 0.032 s
testUpdateSdk_autoSdkEnabled(com.google.cloud.tools.eclipse.sdk.ui.preferences.CloudSdkPreferenceAreaTest)  Time elapsed: 0.047 s
testControlStates_manualSdk(com.google.cloud.tools.eclipse.sdk.ui.preferences.CloudSdkPreferenceAreaTest)  Time elapsed: 0.031 s
testNonExistentPath(com.google.cloud.tools.eclipse.sdk.ui.preferences.CloudSdkPreferenceAreaTest)  Time elapsed: 0.016 s
testPerformApply_preferencesSaved(com.google.cloud.tools.eclipse.sdk.ui.preferences.CloudSdkPreferenceAreaTest)  Time elapsed: 0.016 s
testSearchSdkIfSdkLocationIsEmpty(com.google.cloud.tools.eclipse.sdk.ui.preferences.CloudSdkPreferenceAreaTest)  Time elapsed: 0.016 s

Results:

Failures:
  CloudSdkPreferenceAreaTest.testInvalidPath:115
```

**Comment by JoeWang1127** [comment]
close as not planned
