### ISSUE TITLE
DebugNativeAppEngineStandardProjectTest.testDebugLaunch() not passing on Kokoro

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#3596]
It failed for the last three nightly release builds.

```
Running com.google.cloud.tools.eclipse.integration.appengine.DebugNativeAppEngineStandardProjectTest
00:44:37.700 [WorkbenchTestable] DEBUG c.g.c.t.a.o.cloudsdk.PathResolver - Resolved SDK path : /opt/google-cloud-sdk
[Watchdog] > testDebugLaunch(com.google.cloud.tools.eclipse.integration.appengine.DebugNativeAppEngineStandardProjectTest)
00:44:40.244 [main] WARN  o.e.s.s.finder.widgets.SWTBotButton - Widget is not enabled: (of type 'Button' and with mnemonic 'Next >' and with style 'SWT.PUSH')
00:44:40.247 [main] WARN  o.e.s.s.finder.widgets.SWTBotButton - Widget is not enabled: (of type 'Button' and with mnemonic 'Next >' and with style 'SWT.PUSH')
00:44:40.247 [main] WARN  o.e.s.s.finder.widgets.SWTBotButton - Widget is not enabled: (of type 'Button' and with mnemonic 'Next >' and with style 'SWT.PUSH')
00:44:40.248 [main] WARN  o.e.s.s.finder.widgets.SWTBotButton - Widget is not enabled: (of type 'Button' and with mnemonic 'Next >' and with style 'SWT.PUSH')
00:44:40.248 [main] WARN  o.e.s.s.finder.widgets.SWTBotButton - Widget is not enabled: (of type 'Button' and with mnemonic 'Next >' and with style 'SWT.PUSH')
00:44:40.296 [main] WARN  o.e.s.s.finder.widgets.SWTBotButton - Widget is not enabled: (of type 'Button' and with mnemonic 'Finish' and with style 'SWT.PUSH')
00:44:40.296 [main] WARN  o.e.s.s.finder.widgets.SWTBotButton - Widget is not enabled: (of type 'Button' and with mnemonic 'Finish' and with style 'SWT.PUSH')
00:44:40.296 [main] WARN  o.e.s.s.finder.widgets.SWTBotButton - Widget is not enabled: (of type 'Button' and with mnemonic 'Finish' and with style 'SWT.PUSH')
00:44:40.296 [main] WARN  o.e.s.s.finder.widgets.SWTBotButton - Widget is not enabled: (of type 'Button' and with mnemonic 'Finish' and with style 'SWT.PUSH')
00:44:40.297 [main] WARN  o.e.s.s.finder.widgets.SWTBotButton - Widget is not enabled: (of type 'Button' and with mnemonic 'Finish' and with style 'SWT.PUSH')
00:44:40.494 [ModalContext] DEBUG c.g.c.t.e.a.f.AppEngineStandardFacet - testapp_java8: current facets: []
00:44:40.979 [ModalContext] DEBUG c.g.c.t.e.a.f.AppEngineStandardJre7ProjectFacetDetector - skipping testapp_java8: appengine-web.xml is not java7
00:44:41.022 [ModalContext] DEBUG c.g.c.t.e.a.f.AppEngineStandardFacet - testapp_java8: detector changes: [INSTALL[com.google.cloud.tools.eclipse.appengine.facets.standard JRE8], INSTALL[jst.web 3.1], INSTALL[java 1.8]]
00:44:41.366 [ModalContext] DEBUG c.g.c.t.e.a.s.j.AppEngineStandardFacetChangeListener - Facet change: App Engine Java Standard Environment

!ENTRY org.eclipse.wst.sse.core 1 1 2020-01-11 00:44:46.022
!MESSAGE Fully reindexing for org.eclipse.jst.jsp.core.internal.java.search.JSPIndexManager
00:44:46.886 [main] DEBUG c.g.c.t.a.o.cloudsdk.PathResolver - Resolved SDK path : /opt/google-cloud-sdk
00:44:46.890 [main] DEBUG c.g.c.t.a.o.cloudsdk.PathResolver - Resolved SDK path : /opt/google-cloud-sdk
00:44:46.895 [main] DEBUG c.g.c.t.a.o.cloudsdk.PathResolver - Resolved SDK path : /opt/google-cloud-sdk
00:44:46.897 [main] DEBUG c.g.c.t.a.o.cloudsdk.PathResolver - Resolved SDK path : /opt/google-cloud-sdk
00:44:46.909 [main] DEBUG c.g.c.t.a.o.cloudsdk.PathResolver - Resolved SDK path : /opt/google-cloud-sdk
00:44:46.915 [main] DEBUG c.g.c.t.a.o.cloudsdk.PathResolver - Resolved SDK path : /opt/google-cloud-sdk
00:44:46.917 [main] DEBUG c.g.c.t.a.o.cloudsdk.PathResolver - Resolved SDK path : /opt/google-cloud-sdk
00:44:46.919 [main] DEBUG c.g.c.t.a.o.cloudsdk.PathResolver - Resolved SDK path : /opt/google-cloud-sdk
00:44:46.921 [main] DEBUG c.g.c.t.a.o.cloudsdk.PathResolver - Resolved SDK path : /opt/google-cloud-sdk
00:44:46.927 [main] DEBUG c.g.c.t.a.o.cloudsdk.PathResolver - Resolved SDK path : /opt/google-cloud-sdk
00:44:46.928 [main] DEBUG c.g.c.t.a.o.cloudsdk.PathResolver - Resolved SDK path : /opt/google-cloud-sdk
00:44:46.929 [main] DEBUG c.g.c.t.a.o.cloudsdk.PathResolver - Resolved SDK path : /opt/google-cloud-sdk
00:44:47.247 [main] DEBUG c.g.c.t.a.o.cloudsdk.PathResolver - Resolved SDK path : /opt/google-cloud-sdk
00:44:47.252 [main] DEBUG c.g.c.t.a.o.cloudsdk.PathResolver - Resolved SDK path : /opt/google-cloud-sdk
00:45:17.004 [WorkbenchTestable] WARN  o.e.s.s.f.widgets.SWTBotTreeItem - Tree item TreeItem with text {testapp_java8} is already collapsed. Won't collapse it again.
00:45:18.208 [main] WARN  o.e.s.s.finder.widgets.SWTBotButton - Widget is not enabled: (of type 'Button' and with mnemonic 'OK' and with style 'SWT.PUSH')
00:45:18.208 [main] WARN  o.e.s.s.finder.widgets.SWTBotButton - Widget is not enabled: (of type 'Button' and with mnemonic 'OK' and with style 'SWT.PUSH')
00:45:18.208 [main] WARN  o.e.s.s.finder.widgets.SWTBotButton - Widget is not enabled: (of type 'Button' and with mnemonic 'OK' and with style 'SWT.PUSH')
00:45:18.208 [main] WARN  o.e.s.s.finder.widgets.SWTBotButton - Widget is not enabled: (of type 'Button' and with mnemonic 'OK' and with style 'SWT.PUSH')
00:45:18.208 [main] WARN  o.e.s.s.finder.widgets.SWTBotButton - Widget is not enabled: (of type 'Button' and with mnemonic 'OK' and with style 'SWT.PUSH')
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 40.408 s <<< FAILURE! - in com.google.cloud.tools.eclipse.integration.appengine.DebugNativeAppEngineStandardProjectTest
testDebugLaunch(com.google.cloud.tools.eclipse.integration.appengine.DebugNativeAppEngineStandardProjectTest)  Time elapsed: 38.397 s  <<< ERROR!
org.eclipse.swtbot.swt.finder.widgets.TimeoutException: Timeout after: 30000 ms.: Shell data - testapp_java8/src/main/java/app/engine/test/HelloAppEngine.java - Eclipse Platform did not become inactive
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:522)
	at org.eclipse.swtbot.swt.finder.SWTBot.waitUntil(SWTBot.java:1)
	at org.eclipse.swtbot.eclipse.finder.SWTWorkbenchBot.waitUntil(SWTWorkbenchBot.java:1)
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:496)
	at org.eclipse.swtbot.swt.finder.SWTBot.waitUntil(SWTBot.java:1)
	at org.eclipse.swtbot.eclipse.finder.SWTWorkbenchBot.waitUntil(SWTWorkbenchBot.java:1)
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:484)
	at org.eclipse.swtbot.swt.finder.SWTBot.waitUntil(SWTBot.java:1)
	at org.eclipse.swtbot.eclipse.finder.SWTWorkbenchBot.waitUntil(SWTWorkbenchBot.java:1)
	at com.google.cloud.tools.eclipse.swtbot.SwtBotTestingUtilities.waitUntilShellIsNotActive(SwtBotTestingUtilities.java:116)
	at com.google.cloud.tools.eclipse.swtbot.SwtBotTestingUtilities.performAndWaitForWindowChange(SwtBotTestingUtilities.java:81)
	at com.google.cloud.tools.eclipse.integration.appengine.DebugNativeAppEngineStandardProjectTest.testDebugLaunch(DebugNativeAppEngineStandardProjectTest.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.eclipse.swtbot.swt.finder.junit.internal.CapturingFrameworkMethod.invokeExplosively(CapturingFrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.eclipse.swtbot.swt.finder.junit.SWTBotJunit4ClassRunner.runChild(SWTBotJunit4ClassRunner.java:75)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.swtbot.swt.finder.junit.SWTBotJunit4ClassRunner.run(SWTBotJunit4ClassRunner.java:60)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:206)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:161)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:84)
	at org.eclipse.tycho.surefire.osgibooter.OsgiSurefireBooter.run(OsgiSurefireBooter.java:113)
	at org.eclipse.tycho.surefire.osgibooter.AbstractUITestApplication.runTests(AbstractUITestApplication.java:44)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Testable.lambda$0(E4Testable.java:76)
	at java.lang.Thread.run(Thread.java:748)

Running com.google.cloud.tools.eclipse.integration.appengine.DeployPropertyPageTest
```

**Comment by chanseokoh** [comment]
This is the nightly release builds on Kokoro Ubuntu. The Kokoro Windows continuous build may run fine: the last two Windows builds on Jan 11 (which came after the first Ubuntu build failure) succeeded.
