### ISSUE TITLE
Windowx 10 (2020) Localhost DevAppServer cannot start

### ISSUE THREAD

**Issue by SlawoKleeb** [GoogleCloudPlatform/google-cloud-eclipse#3617]
gcloud is uptodate
eclipse newly installed with jdk14
i have googled entire evening (and i am 40, grew up on google) but nothing reasonable. There looks to be an issue with VM but no StackOverflow or GitHub solution worked. Many were even not implementable. So it looks like some major conceptual change. I have fond that gcp tools for eclipse support vm 7 but 8 nomore. However than the same guys talks about 1.7.

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.appengine.tools.development.StreamHandlerFactory (file:/C:/Users/slawo/AppData/Local/Google/Cloud%20SDK/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/lib/impl/appengine-local-runtime.jar) to method java.net.URL.getURLStreamHandler(java.lang.String)
WARNING: Please consider reporting this to the maintainers of com.google.appengine.tools.development.StreamHandlerFactory
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
java.lang.RuntimeException: Unable to create a DevAppServer
	at com.google.appengine.tools.development.DevAppServerFactory.doCreateDevAppServer(DevAppServerFactory.java:369)
	at com.google.appengine.tools.development.DevAppServerFactory.createDevAppServer(DevAppServerFactory.java:301)
	at com.google.appengine.tools.development.DevAppServerMain$StartAction.apply(DevAppServerMain.java:383)
	at com.google.appengine.tools.util.Parser$ParseResult.applyArgs(Parser.java:45)
	at com.google.appengine.tools.development.DevAppServerMain.run(DevAppServerMain.java:257)
	at com.google.appengine.tools.development.DevAppServerMain.main(DevAppServerMain.java:248)
Caused by: java.lang.ExceptionInInitializerError
	at com.google.appengine.tools.development.DevAppServerImpl.<init>(DevAppServerImpl.java:124)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at com.google.appengine.tools.development.DevAppServerFactory.doCreateDevAppServer(DevAppServerFactory.java:354)
	... 5 more
Caused by: java.lang.IllegalStateException: java.lang.NoSuchMethodException: java.net.SocksSocketImpl.<init>()
	at com.google.appengine.tools.development.DevSocketImplFactory.<clinit>(DevSocketImplFactory.java:76)
	... 12 more
Caused by: java.lang.NoSuchMethodException: java.net.SocksSocketImpl.<init>()
	at java.base/java.lang.Class.getConstructor0(Class.java:3427)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2631)
	at com.google.appengine.tools.development.DevSocketImplFactory.<clinit>(DevSocketImplFactory.java:72)
	... 12 more

So i am not saying it is a bug. But it looks like some major paradigm change so the gcp manual:
https://cloud.google.com/eclipse/docs?hl=de
simply does not work (the hello world).

best regards
Slawo

**Comment by elharo** [comment]
@ludoch  Looks like the devappserver isn't compatible with Java 14. AppEngine does not promise anything past Java 11 at this point in time.

**Comment by ludoch** [comment]
Right. The DevAppServer is intended to emulate the Java8 GAE runtime, not even the Java11 runtime...
So forget about Java14, which is anyway not a supported version by anyone (non LTS version).
We need the missing api in java.net.SocksSocketImpl for Java8 devappserver.

**Comment by elharo** [comment]
I do wonder if maybe CT4E should notice it's running in JDK 14 and give a nicer error somehow.

**Comment by SlawoKleeb** [comment]
I have downloaded JDK11 (and the paradigm change was that you need to create a free oracle account and log in to download any old version, sorry guys this probably the covid-19 mutated to hit logics).
So it works beautifully. Thanks a lot.

best regards
Slawo

PS
And yes: I also do love error messages telling some random stuff. Especially on a HelloWorld example ;-)
