### ISSUE TITLE
Can't Run API on Local Application Engine from Eclipse

### ISSUE THREAD

**Issue by SubutaDan** [GoogleCloudPlatform/google-cloud-eclipse#3630]
CT4E version: Check for Updates_.: No updates found. (Google Cloud Tools for Eclipse Version: 1.8.4.202002191941)
gcloud version: Google Cloud SDK 315.0.0 bq 2.0.62 core 2020.10.16gsutil 4.53
Eclipse version: 2020-09 (4.17.0)
OS: Ubuntu 18.04
Java version:  "14.0.2" 2020-07-14

Hello,
I am developing a Google Cloud Endpoints Java 8 API which I intend to run on Google Application Engine Standard. I want to be able to test the API using App Engine's local server.  I am able to deploy the API to a local server and access it from a client (curl) as expected using maven:

    export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/
    mvn clean package
    mvn appengine:run
```
.
.
.
[INFO] GCLOUD: Nov 03, 2020 5:27:49 AM com.google.appengine.tools.development.AbstractModule startup
[INFO] GCLOUD: INFO: The admin console is running at http://localhost:8080/_ah/admin
[INFO] GCLOUD: Nov 03, 2020 5:27:49 AM com.google.appengine.tools.development.DevAppServerImpl doStart
[INFO] GCLOUD: INFO: Dev App Server is now running
```

Compilation source and target are set to 1.8 in my pom.xml:
```
		<maven.compiler.source>1.8</maven.compiler.source>
		<maven.compiler.target>1.8</maven.compiler.target>
.
.
.
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.8.1</version>
				<configuration>
					<source>${maven.compiler.source}</source>
					<target>${maven.compiler.target}</target>
				</configuration>
			</plugin>
```
and the Java execution version is enforced at 1.8:
```
					<execution>
						<id>enforce-java</id>
						<goals>
							<goal>enforce</goal>
						</goals>
						<configuration>
							<rules>
								<requireJavaVersion>
									<version>1.8.0</version>
								</requireJavaVersion>
							</rules>
						</configuration>
					</execution>
```
I would like also to be able to deploy and run it from Eclipse using the Google Cloud Platform  plugin.   When I run my program from Eclipse using the Google plugin **without setting JAVA_HOME in the run configuration to 1.8** I get this error:

    com.google.apphosting.utils.config.AppEngineConfigException: Invalid configuration
    	at com.google.appengine.tools.development.DevAppServerImpl.reportDeferredConfigurationException(DevAppServerImpl.java:431)
    	at com.google.appengine.tools.development.DevAppServerImpl.doStart(DevAppServerImpl.java:232)
    	at com.google.appengine.tools.development.DevAppServerImpl.access$000(DevAppServerImpl.java:44)
    	at com.google.appengine.tools.development.DevAppServerImpl$1.run(DevAppServerImpl.java:219)
    	at com.google.appengine.tools.development.DevAppServerImpl$1.run(DevAppServerImpl.java:217)
    	at java.security.AccessController.doPrivileged(Native Method)
    	at com.google.appengine.tools.development.DevAppServerImpl.start(DevAppServerImpl.java:217)
    	at com.google.appengine.tools.development.DevAppServerMain$StartAction.apply(DevAppServerMain.java:404)
    	at com.google.appengine.tools.util.Parser$ParseResult.applyArgs(Parser.java:45)
    	at com.google.appengine.tools.development.DevAppServerMain.run(DevAppServerMain.java:257)
    	at com.google.appengine.tools.development.DevAppServerMain.main(DevAppServerMain.java:248)
    Caused by: com.google.apphosting.utils.config.AppEngineConfigException: Missing required element 'application'.
    	at com.google.apphosting.utils.config.AppYaml.getApplication(AppYaml.java:803)
    	at com.google.apphosting.utils.config.AppYaml.generateAppEngineWebXml(AppYaml.java:1287)
I have tried to remedy this by referring to these pages:

https://cloud.google.com/appengine/docs/standard/java/tools/migrate-maven

https://cloud.google.com/appengine/docs/standard/java/maven-reference

Here is what I think is the critical portion of my pom.xml:

 			<plugin>
				<groupId>com.google.cloud.tools</groupId>
				<artifactId>endpoints-framework-maven-plugin</artifactId>
				<version>1.0.2</version>
				<configuration>
					
					<hostname>${endpoints.project.id}.appspot.com</hostname>
				</configuration>
			</plugin>

If I add a services line:

    <services>build/exploded-app</services>

then "mvn appengine:run" says:

    [ERROR] Failed to execute goal com.google.cloud.tools:appengine-maven-plugin:2.2.0:run (default-cli) on project kokodoko: appengine:run is only available for appengine-web.xml based projects, the service defined in: /home/dan/repos/kokodoko20191207/Kokodoko - Dec 7/build/exploded-app cannot be run by the dev appserver. -> [Help 1]
    [ERROR]

If I **set JAVA_HOME to 1.8** in the run configuration, I get:

```
org.eclipse.debug.core
Error
Tue Nov 03 05:17:18 GMT 2020
Problems occurred when invoking code from plug-in: "org.eclipse.debug.core".

java.lang.NullPointerException
	at org.eclipse.ui.console.IOConsole.dispose(IOConsole.java:323)
	at com.google.cloud.tools.eclipse.appengine.localserver.ui.LocalAppEngineConsole.dispose(LocalAppEngineConsole.java:99)
```
and:
```
com.google.cloud.tools.eclipse.appengine.localserver
Error
Tue Nov 03 05:17:19 GMT 2020
Google Cloud SDK: Error starting server: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
```
and:
```
Error
Tue Nov 03 05:48:58 GMT 2020
Server App Engine Standard at localhost failed to start.
```
I am happy to provide more information and would greatly appreciate help.

Thanks.

-Dan

**Comment by diego92sigma6** [comment]
Closing due to cleanup. Please reopen if needed
