### ISSUE TITLE
NPE when stopping App Engine

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#3637]
- Cloud Tools for Eclipse version: 1.8.4
- Google Cloud SDK version: 334.0.0
- Eclipse version: 2021‑03
- OS: macOS 11.2.3 for Apple M1
- Java version: 15.0.2

**What did you do?**

Launched an App Engine Java 8 standard edition app.  Some time after terminating, I noticed an error on my console:
```
!ENTRY org.eclipse.debug.core 4 2 2021-04-01 10:26:01.148
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.debug.core".
!STACK 0
java.lang.NullPointerException: Cannot invoke "org.eclipse.jface.text.IDocument.setDocumentPartitioner(org.eclipse.jface.text.IDocumentPartitioner)" because "document" is null
	at org.eclipse.ui.console.IOConsole.dispose(IOConsole.java:323)
	at com.google.cloud.tools.eclipse.appengine.localserver.ui.LocalAppEngineConsole.dispose(LocalAppEngineConsole.java:99)
	at org.eclipse.ui.console.AbstractConsole.destroy(AbstractConsole.java:265)
	at com.google.cloud.tools.eclipse.appengine.localserver.server.LocalAppEngineServerLaunchConfigurationDelegate$CloudSdkDebugTarget.removeConsole(LocalAppEngineServerLaunchConfigurationDelegate.java:698)
	at com.google.cloud.tools.eclipse.appengine.localserver.server.LocalAppEngineServerLaunchConfigurationDelegate$CloudSdkDebugTarget.access$5(LocalAppEngineServerLaunchConfigurationDelegate.java:694)
	at com.google.cloud.tools.eclipse.appengine.localserver.server.LocalAppEngineServerLaunchConfigurationDelegate$CloudSdkDebugTarget$2.launchesRemoved(LocalAppEngineServerLaunchConfigurationDelegate.java:659)
	at org.eclipse.debug.internal.core.LaunchManager$LaunchesNotifier.run(LaunchManager.java:276)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.debug.internal.core.LaunchManager$LaunchesNotifier.notify(LaunchManager.java:262)
	at org.eclipse.debug.internal.core.LaunchManager.fireUpdate(LaunchManager.java:1038)
	at org.eclipse.debug.internal.core.LaunchManager.removeLaunch(LaunchManager.java:2201)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationManager.removeTerminatedLaunches(LaunchConfigurationManager.java:327)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationManager.launchAdded(LaunchConfigurationManager.java:315)
	at org.eclipse.debug.internal.core.LaunchManager$LaunchNotifier.run(LaunchManager.java:425)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.debug.internal.core.LaunchManager$LaunchNotifier.notify(LaunchManager.java:415)
	at org.eclipse.debug.internal.core.LaunchManager.fireUpdate(LaunchManager.java:1027)
	at org.eclipse.debug.internal.core.LaunchManager.addLaunch(LaunchManager.java:678)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:760)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:716)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:711)
	at org.eclipse.wst.server.core.internal.Server.startImpl2(Server.java:3568)
	at org.eclipse.wst.server.core.internal.Server.startImpl(Server.java:3504)
	at org.eclipse.wst.server.core.internal.Server$StartJob.run(Server.java:379)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by Ihernandezpi** [comment]
I have the same issue but with 
Cloud Tools for Eclipse version: 1.8.4
Google Cloud SDK version: 438.0.0
IDE: Spring Tool Suite 4 
IDE: Version: 4.14.1.RELEASE
IDE: Build Id: 202204250734
OS: macOS Version 13.4.1 (c) (22F770820d) 3 GHz 6-Core Intel Core i5
Java version: Java SE 8 [1.8.0_202]

**Comment by chanseokoh** [comment]
@Ihernandezpi `Unrecognized option: --add-opens` means the `--add-opens` flag (which was added in Java 9+) was passed to Java 8 JVM. Try using recent Java versions.

**Comment by Ihernandezpi** [comment]
I have test with java 11 and i tworks, but my project runs on java 1.8 in the server. I don´t know if I can upgrated the version

**Comment by diegomarquezp** [comment]
Closing as not planned since we don't support GAE + Java 8.
