### ISSUE TITLE
SWT exception after dismissing App Engine Flexible deployment dialog

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#3639]
- Cloud Tools for Eclipse version: 1.8.4
- Google Cloud SDK version: 334.0.0
- Eclipse version: 2021‑03
- OS: macOS 11.2.3 for Apple M1
- Java version: 15.0.2

**What did you do?**

I saw the following stack trace appear several seconds after trying to deploy an App Engine Flexible app:

```
!ENTRY org.eclipse.ui.ide 4 4 2021-04-01 10:35:23.870
!MESSAGE Not properly disposed SWT resource
!STACK 0
java.lang.Error: SWT Resource was not properly disposed
	at org.eclipse.swt.graphics.Resource.initNonDisposeTracking(Resource.java:172)
	at org.eclipse.swt.graphics.Resource.<init>(Resource.java:120)
	at org.eclipse.swt.graphics.Image.<init>(Image.java:771)
	at org.eclipse.jface.resource.URLImageDescriptor.createImage(URLImageDescriptor.java:274)
	at org.eclipse.jface.resource.ImageDescriptor.createImage(ImageDescriptor.java:307)
	at com.google.cloud.tools.eclipse.appengine.deploy.ui.AppEngineDeployPreferencesPanel.<init>(AppEngineDeployPreferencesPanel.java:115)
	at com.google.cloud.tools.eclipse.appengine.deploy.ui.flexible.FlexDeployPreferencesPanel.<init>(FlexDeployPreferencesPanel.java:50)
	at com.google.cloud.tools.eclipse.appengine.deploy.ui.flexible.FlexDeployPreferencesPanel.<init>(FlexDeployPreferencesPanel.java:43)
	at com.google.cloud.tools.eclipse.appengine.deploy.ui.flexible.FlexDeployPreferencesDialog.createDeployPreferencesPanel(FlexDeployPreferencesDialog.java:71)
	at com.google.cloud.tools.eclipse.appengine.deploy.ui.DeployPreferencesDialog.createDialogArea(DeployPreferencesDialog.java:95)
	at com.google.cloud.tools.eclipse.appengine.deploy.ui.flexible.FlexDeployPreferencesDialog.createDialogArea(FlexDeployPreferencesDialog.java:48)
	at org.eclipse.jface.dialogs.TitleAreaDialog.createContents(TitleAreaDialog.java:157)
	at com.google.cloud.tools.eclipse.appengine.deploy.ui.DeployPreferencesDialog.createContents(DeployPreferencesDialog.java:71)
```

**Comment by diegomarquezp** [comment]
We haven't seen any similar reports or observations. Closing as non-reproducible
