### ISSUE TITLE
CommandExitException: Process failed with exit code: 127

### ISSUE THREAD

**Issue by craigdetter** [GoogleCloudPlatform/google-cloud-eclipse#3682]
<img width="404" alt="Screen Shot 2022-08-12 at 10 55 04 AM" src="https://user-images.githubusercontent.com/15794819/184428921-fbe0569e-6f9d-4927-ab20-f5d5cc842f05.png">

- Cloud Tools for Eclipse version: 1.8.5.202108061424
- Google Cloud SDK version: 396.0.0 (auto-managed)
- Eclipse version: 4.21.0.v20210906-0500
- OS: Mac OS X 11.5
- Java version: 16.0.2
- Python 3.9.10

**What did you do?**
I changed nothing in the project. MacOS may have done an update overnight, however.

Click on Project in Eclipse, Click on Google Cloud Tools Icon, select Deploy to App Engine Standard -> select Project from List -> Click "Deploy" button. See error message below. This happens to 2 of 2 projects I have in Eclipse.

**What did you expect to see?**
Project Deploys successfully

**What did you see instead?**

Window (see attachment) shows:
**Deploy failed: cannot install Google Cloud SDK
Failed to install the Google Cloud SDK.
com.google.cloud.tools.managedcloudsdk.command.CommandExitException: Process failed with exit code: 127**

**What Have you tried?**
1.) uninstalling gcloud tools, reinstalling - still fails.
2.) uninstalling eclipse (2021-09), reinstalling, then reinstalling the GCT plug-in.
3.)  checked for any kind of console logs, none are in the drop down.
4.) Checked version of python (3.9.10)
5.) Tried restarting eclipse, several times.

Manual upload command:
gcloud app deploy ~/my-workspace/myproject-net-v4/src/main/webapp/WEB-INF/appengine-web.xml

Note: the manual deploy does work, but only uploaded the static (.html and .js) content, it didn't upload servlets. But this is first time I've ever tried a manual deploy. I assume there is a setting to include all the servlet content.

**Comment by craigdetter** [comment]
Found this additional detail log entry:

com.google.cloud.tools.managedcloudsdk.ManagedSdkVerificationException: com.google.cloud.tools.managedcloudsdk.command.CommandExitException: Process failed with exit code: 127
	at com.google.cloud.tools.managedcloudsdk.ManagedCloudSdk.hasComponent(ManagedCloudSdk.java:133)
	at com.google.cloud.tools.eclipse.sdk.internal.CloudSdkInstallJob.modifySdk(CloudSdkInstallJob.java:82)
	at com.google.cloud.tools.eclipse.sdk.internal.CloudSdkModifyJob.run(CloudSdkModifyJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: com.google.cloud.tools.managedcloudsdk.command.CommandExitException: Process failed with exit code: 127
	at com.google.cloud.tools.managedcloudsdk.command.CommandCaller.call(CommandCaller.java:70)
	at com.google.cloud.tools.managedcloudsdk.ManagedCloudSdk.hasComponent(ManagedCloudSdk.java:125)
	... 3 more


Session Data:

eclipse.buildId=4.21.0.I20210906-0500
java.version=16.0.2
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.jee.product -keyring /Users/myname/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -product org.eclipse.epp.package.jee.product -keyring /Users/myname/.eclipse_keyring


Second Log entry:

Not properly disposed SWT resource

java.lang.Error: SWT Resource was not properly disposed
	at org.eclipse.swt.graphics.Resource.initNonDisposeTracking(Resource.java:172)
	at org.eclipse.swt.graphics.Resource.<init>(Resource.java:120)
	at org.eclipse.swt.graphics.Image.<init>(Image.java:771)
	at org.eclipse.jface.resource.URLImageDescriptor.createImage(URLImageDescriptor.java:274)
	at org.eclipse.jface.resource.ImageDescriptor.createImage(ImageDescriptor.java:307)
	at com.google.cloud.tools.eclipse.appengine.deploy.ui.AppEngineDeployPreferencesPanel.<init>(AppEngineDeployPreferencesPanel.java:115)
	at com.google.cloud.tools.eclipse.appengine.deploy.ui.standard.StandardDeployPreferencesPanel.<init>(StandardDeployPreferencesPanel.java:34)
	at com.google.cloud.tools.eclipse.appengine.deploy.ui.standard.StandardDeployPreferencesDialog.createDeployPreferencesPanel(StandardDeployPreferencesDialog.java:40)
	at com.google.cloud.tools.eclipse.appengine.deploy.ui.DeployPreferencesDialog.createDialogArea(DeployPreferencesDialog.java:95)
	at org.eclipse.jface.dialogs.TitleAreaDialog.createContents(TitleAreaDialog.java:162)
	at com.google.cloud.tools.eclipse.appengine.deploy.ui.DeployPreferencesDialog.createContents(DeployPreferencesDialog.java:71)
	at org.eclipse.jface.window.Window.create(Window.java:431)
	at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1094)
	at org.eclipse.jface.window.Window.open(Window.java:788)
	at com.google.cloud.tools.eclipse.appengine.deploy.ui.DeployCommandHandler.execute(DeployCommandHandler.java:112)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:317)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:251)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:438)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:449)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4524)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1522)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1545)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1530)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1324)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4310)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3883)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1041)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)


Session Data

eclipse.buildId=4.21.0.I20210906-0500
java.version=16.0.2
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.jee.product -keyring /Users/myname/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -product org.eclipse.epp.package.jee.product -keyring /Users/myname/.eclipse_keyring

**Comment by craigdetter** [comment]
I had upgraded XCode previous day, didn't realize there is some kind of dependency between xcode and gcloud, but there clearly is...

I was able to fix it, using the following:

// remove xcode command line tools
$ sudo rm -rf /Library/Developer/CommandLineTools

// reinstall command line tools
$ xcode-select --install

$ gcloud components list --only-local-state --format=json --filter=id:app-engine-java
xcrun: error: active developer path ("/Applications/Xcode.app/Contents/Developer") does not exist

$ ls -al ~/.cache/google-cloud-tools-java/managed-cloud-sdk    
ls: /Users/myname/.cache/google-cloud-tools-java/managed-cloud-sdk: No such file or directory

$ gcloud components list --only-local-state --format=json --filter=id:app-engine-java
xcrun: error: active developer path ("/Applications/Xcode.app/Contents/Developer") does not exist
Use `sudo xcode-select --switch path/to/Xcode.app` to specify the Xcode that you wish to use for command line developer tools, or use `xcode-select --install` to install the standalone command line developer tools.
See `man xcode-select` for more details.

// path to new Xcode version .... 
$ sudo xcode-select --switch /Applications/Xcode13.4.app 

$ gcloud components list --only-local-state --format=json --filter=id:app-engine-java
2022-08-12 15:47:36.713 xcodebuild[88788:783597] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
2022-08-12 15:47:36.713 xcodebuild[88788:783597] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore

Your current Google Cloud CLI version is: 397.0.0
[
  {
    "current_version_string": "1.9.98",
    "id": "app-engine-java",
    "is_configuration": false,
    "is_hidden": false,
    "name": "gcloud app Java Extensions",
......
