### ISSUE TITLE
After I upgrade to Google Cloud SDK version: 398.0.0, Google App Engine. Attached is the stack trace

### ISSUE THREAD

**Issue by binshu2013** [GoogleCloudPlatform/google-cloud-eclipse#3683]
- Cloud Tools for Eclipse version: 1.8.5.202108061424
- Google Cloud SDK version: 398.0.0 (auto-managed)
- Eclipse version: 4.23.0.v20220308-0310
- OS: Mac OS X 12.5
- Java version: 18.0.1

**What did you do?**

**What did you expect to see?**

**What did you see instead?**

java.lang.RuntimeException: Unable to create a DevAppServer
	at com.google.appengine.tools.development.DevAppServerFactory.doCreateDevAppServer(DevAppServerFactory.java:378)
	at com.google.appengine.tools.development.DevAppServerFactory.createDevAppServer(DevAppServerFactory.java:310)
	at com.google.appengine.tools.development.DevAppServerMain$StartAction.apply(DevAppServerMain.java:384)
	at com.google.appengine.tools.util.Parser$ParseResult.applyArgs(Parser.java:58)
	at com.google.appengine.tools.development.DevAppServerMain.run(DevAppServerMain.java:258)
	at com.google.appengine.tools.development.DevAppServerMain.main(DevAppServerMain.java:249)
Caused by: java.lang.ExceptionInInitializerError
	at com.google.appengine.tools.development.DevAppServerImpl.<init>(DevAppServerImpl.java:135)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:483)
	at com.google.appengine.tools.development.DevAppServerFactory.doCreateDevAppServer(DevAppServerFactory.java:363)
	... 5 more
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make static java.net.URLStreamHandler java.net.URL.getURLStreamHandler(java.lang.String) accessible: module java.base does not "opens java.net" to unnamed module @3d8c7aca
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:200)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:194)
	at com.google.appengine.tools.development.StreamHandlerFactory.<clinit>(StreamHandlerFactory.java:52)
	... 10 more

**Comment by elefeint** [comment]
Could you check this with Java 11 (or anything < Java 17)? I suspect you won't see this issue. It should not depend on Cloud SDK version.

**Comment by binshu2013** [comment]
Elena,

Below is the Java version installed on my local machine. By the way, I use
Mac studio with an ARM chip. Thank you for your help!

java -version

openjdk version "11.0.15" 2022-04-19

OpenJDK Runtime Environment Homebrew (build 11.0.15+0)

OpenJDK 64-Bit Server VM Homebrew (build 11.0.15+0, mixed mode)

**Comment by binshu2013** [comment]
Elena,

Thank you for following up. I upgraded my eclipse to the latest version (
4.23.0) and now everything is fine.

Thanks again for your help!

**Comment by elefeint** [comment]
Thanks!
