### ISSUE TITLE
ITs Failing both on release and CI checks

### ISSUE THREAD

**Issue by diegomarquezp** [GoogleCloudPlatform/google-cloud-eclipse#3702]
`DebugNativeAppEngineStandardProjectTest` Fails due to a widget not being found. Subsequent tests in `integration.appengine` fail due to failing `tearDown()`.
```
testDebugLaunch(com.google.cloud.tools.eclipse.integration.appengine.DebugNativeAppEngineStandardProjectTest)  Time elapsed: 53.146 s  <<< ERROR!
2022-11-24T16:38:27.7803674Z org.eclipse.swtbot.swt.finder.exceptions.WidgetNotFoundException: Could not find widget matching: (of type 'Button' and with style 'SWT.CHECK')
2022-11-24T16:38:27.7804588Z 	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntilWidgetAppears(SWTBotFactory.java:474)
2022-11-24T16:38:27.7953106Z 	at org.eclipse.swtbot.swt.finder.SWTBot.waitUntilWidgetAppears(SWTBot.java:1)
2022-11-24T16:38:27.7953811Z 	at org.eclipse.swtbot.eclipse.finder.SWTWorkbenchBot.waitUntilWidgetAppears(SWTWorkbenchBot.java:1)
2022-11-24T16:38:27.7954431Z 	at org.eclipse.swtbot.swt.finder.SWTBotFactory.widget(SWTBotFactory.java:421)
2022-11-24T16:38:27.7954912Z 	at org.eclipse.swtbot.swt.finder.SWTBot.widget(SWTBot.java:1)
2022-11-24T16:38:27.7955412Z 	at org.eclipse.swtbot.eclipse.finder.SWTWorkbenchBot.widget(SWTWorkbenchBot.java:1)
2022-11-24T16:38:27.7955951Z 	at org.eclipse.swtbot.swt.finder.SWTBot.checkBox(SWTBot.java:860)
2022-11-24T16:38:27.7956557Z 	at com.google.cloud.tools.eclipse.swtbot.SwtBotProjectActions.deleteProject(SwtBotProjectActions.java:126)
2022-11-24T16:38:27.7957296Z 	at com.google.cloud.tools.eclipse.integration.appengine.BaseProjectTest.tearDown(BaseProjectTest.java:79)
2022-11-24T16:38:27.7957948Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-11-24T16:38:27.7958539Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2022-11-24T16:38:27.7959194Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-11-24T16:38:27.7959719Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2022-11-24T16:38:27.7960183Z 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
2022-11-24T16:38:27.7961048Z 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
2022-11-24T16:38:27.7961660Z 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
2022-11-24T16:38:27.7962209Z 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
2022-11-24T16:38:27.7962680Z 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
2022-11-24T16:38:27.7963068Z 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
2022-11-24T16:38:27.7963475Z 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
2022-11-24T16:38:27.7964054Z 	at org.eclipse.swtbot.swt.finder.junit.SWTBotJunit4ClassRunner.runChild(SWTBotJunit4ClassRunner.java:75)
2022-11-24T16:38:27.7964682Z 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
2022-11-24T16:38:27.7965164Z 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
2022-11-24T16:38:27.7965569Z 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
2022-11-24T16:38:27.7966024Z 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
2022-11-24T16:38:27.7966477Z 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
2022-11-24T16:38:27.7966896Z 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
2022-11-24T16:38:27.7967390Z 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
2022-11-24T16:38:27.7967878Z 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
2022-11-24T16:38:27.7968425Z 	at org.eclipse.swtbot.swt.finder.junit.SWTBotJunit4ClassRunner.run(SWTBotJunit4ClassRunner.java:60)
2022-11-24T16:38:27.7969027Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
2022-11-24T16:38:27.7969623Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
2022-11-24T16:38:27.7970244Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
2022-11-24T16:38:27.7970956Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
2022-11-24T16:38:27.7971509Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-11-24T16:38:27.7972097Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2022-11-24T16:38:27.7972757Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-11-24T16:38:27.7973285Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2022-11-24T16:38:27.7973833Z 	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:206)
2022-11-24T16:38:27.7974478Z 	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:161)
2022-11-24T16:38:27.7975086Z 	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:84)
2022-11-24T16:38:27.7975717Z 	at org.eclipse.tycho.surefire.osgibooter.OsgiSurefireBooter.run(OsgiSurefireBooter.java:128)
2022-11-24T16:38:27.7976992Z 	at org.eclipse.tycho.surefire.osgibooter.AbstractUITestApplication.runTests(AbstractUITestApplication.java:46)
2022-11-24T16:38:27.7977699Z 	at org.eclipse.e4.ui.internal.workbench.swt.E4Testable.lambda$0(E4Testable.java:76)
2022-11-24T16:38:27.7978131Z 	at java.base/java.lang.Thread.run(Thread.java:829)
2022-11-24T16:38:27.7979043Z Caused by: org.eclipse.swtbot.swt.finder.widgets.TimeoutException: Timeout after: 30000 ms.: Could not find widget matching: (of type 'Button' and with style 'SWT.CHECK')
2022-11-24T16:38:27.7979688Z 	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:524)
2022-11-24T16:38:27.7980193Z 	at org.eclipse.swtbot.swt.finder.SWTBot.waitUntil(SWTBot.java:1)
2022-11-24T16:38:27.7980710Z 	at org.eclipse.swtbot.eclipse.finder.SWTWorkbenchBot.waitUntil(SWTWorkbenchBot.java:1)
2022-11-24T16:38:27.7981284Z 	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:498)
2022-11-24T16:38:27.7981952Z 	at org.eclipse.swtbot.swt.finder.SWTBot.waitUntil(SWTBot.java:1)
2022-11-24T16:38:27.7982488Z 	at org.eclipse.swtbot.eclipse.finder.SWTWorkbenchBot.waitUntil(SWTWorkbenchBot.java:1)
2022-11-24T16:38:27.7983056Z 	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:486)
2022-11-24T16:38:27.7983547Z 	at org.eclipse.swtbot.swt.finder.SWTBot.waitUntil(SWTBot.java:1)
2022-11-24T16:38:27.7984067Z 	at org.eclipse.swtbot.eclipse.finder.SWTWorkbenchBot.waitUntil(SWTWorkbenchBot.java:1)
2022-11-24T16:38:27.7984674Z 	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntilWidgetAppears(SWTBotFactory.java:468)
2022-11-24T16:38:27.7985100Z 	... 44 more
```

_NOTE_: This IT started failing on commits that had all checks passed - it's likely to be a non-deterministic aspect of the IT setup.

_Analysis_
A window has taken focus, making the swtbot unable to find the expected widget. PTOS was disabled in every test (#3700), suggesting that there may be another popup. Best way to confirm this is by running the IT locally, which brings in the problem of GTK compatibility:
* GTK is expected to be in a linux machine running the tests. However it is not found (even if it's installed and checked with `ldd`):
  ```
  java.lang.UnsatisfiedLinkError: 
  Could not load SWT library. Reasons: 
	/home/user/Desktop/google-cloud-eclipse/plugins/com.google.cloud.tools.eclipse.appengine.compat.test/target/work/configuration/org.eclipse.osgi/26/0/.cp/libswt-pi3-gtk-4919.so: libgtk-3.so.0: cannot open shared object file: No such file or directory
	no swt-pi3-gtk in java.library.path: [/usr/lib/mesa-diverted/x86_64-linux-gnu, /usr/lib/x86_64-linux-gnu/mesa, /usr/lib/x86_64-linux-gnu/dri, /usr/lib/x86_64-linux-gnu/gallium-pipe, /usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
	/home/user/.swt/lib/linux/x86_64/libswt-pi3-gtk-4919.so: libgtk-3.so.0: cannot open shared object 
  file: No such file or directory
	Can't load library: /home/user/.swt/lib/linux/x86_64/libswt-pi3-gtk.so

  ``` 
* This occurs independently of the value of `-Dswt.gtk3`

**Comment by blakeli0** [comment]
This integration test module is now disabled per @diegomarquezp.
