### ISSUE TITLE
Won't install on latest Eclipse

### ISSUE THREAD

**Issue by bcwhite-code** [GoogleCloudPlatform/google-cloud-eclipse#3706]
Cloud Tools for Eclipse version: 1.8.4
Google Cloud SDK version: 413.0.0
Eclipse version: 2022-12 (4.26.0)
OS: Win10
Java version:
org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_17.0.5.v20221102-0933/jre/bin\server\jvm.dll

**What did you do?**

Dragged the "Install" button to my workspace.

**What did you expect to see?**

A successful install.

**What did you see instead?**

```
Cannot complete the install because one or more required items could not be found.
  Software being installed: Google Cloud Platform for Eclipse 1.9.1.202211291623 (com.google.cloud.tools.eclipse.suite.feature.feature.group 1.9.1.202211291623)
  Missing requirement: Cloud Tools for Eclipse App Engine Local Server 0.1.0.202108052157 (com.google.cloud.tools.eclipse.appengine.localserver 0.1.0.202108052157) requires 'osgi.bundle; javax.servlet 2.5.0' but it could not be found
  Cannot satisfy dependency:
    From: Google Cloud Platform for Eclipse 1.9.1.202211291623 (com.google.cloud.tools.eclipse.suite.feature.feature.group 1.9.1.202211291623)
    To: org.eclipse.equinox.p2.iu; com.google.cloud.tools.eclipse.appengine.localserver [0.1.0.202108052157,0.1.0.202108052157]

```

**Comment by bcwhite-code** [comment]
I completely removed Eclipse and installed the 2021-09 version (1.5y old!) and now the GCP install was successful.

I was then able to create a "standard" App Engine project.  Or mostly so as it repeatedly gives an error dialog:

```
An error has occurred. See error log for more details.
'boolean com.ibm.icu.text.UTF16.isSurrogate(char)'
```

I had to force-close Eclipse and restart it.

Details:

```
java.lang.NoSuchMethodError: 'boolean com.ibm.icu.text.UTF16.isSurrogate(char)'
	at org.eclipse.jdt.internal.ui.text.JavaWordFinder.findWord(JavaWordFinder.java:61)
	at org.eclipse.jdt.internal.ui.javaeditor.JavaEditor.updateOccurrenceAnnotations(JavaEditor.java:3300)
	at org.eclipse.jdt.internal.ui.javaeditor.JavaEditor$ActivationListener.windowActivated(JavaEditor.java:1216)
	at org.eclipse.ui.internal.Workbench$8.run(Workbench.java:1005)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.internal.Workbench.fireWindowActivated(Workbench.java:1002)
	at org.eclipse.ui.internal.WorkbenchWindow$6.shellActivated(WorkbenchWindow.java:2459)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:92)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4237)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1060)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1084)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1069)
	at org.eclipse.swt.widgets.Decorations.WM_ACTIVATE(Decorations.java:1521)
	at org.eclipse.swt.widgets.Shell.WM_ACTIVATE(Shell.java:2292)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4750)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:340)
	at org.eclipse.swt.widgets.Decorations.windowProc(Decorations.java:1480)
	at org.eclipse.swt.widgets.Shell.windowProc(Shell.java:2264)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4958)
	at org.eclipse.swt.internal.win32.OS.DestroyWindow(Native Method)
	at org.eclipse.swt.widgets.Control.destroyWidget(Control.java:782)
	at org.eclipse.swt.widgets.Shell.destroyWidget(Shell.java:710)
	at org.eclipse.swt.widgets.Widget.release(Widget.java:826)
	at org.eclipse.swt.widgets.Widget.dispose(Widget.java:423)
	at org.eclipse.swt.widgets.Decorations.dispose(Decorations.java:392)
	at org.eclipse.jface.window.Window.close(Window.java:335)
```

**Comment by bcwhite-code** [comment]
After telling Eclipse to "Check for updates" and installing everything (main Eclipse version is still 2021-09), the created App Engine project is now broken.

For example, `HttpServletRequest` is underlined in red saying "HttpServletRequest cannot be resolved to a type".

**Comment by bcwhite-code** [comment]
Oh, I see by the .md file that "versions since 4.22 are currently not supported".  That should be mentioned in the GCP docs that tell how to install this since they don't link to the .md file.

Eclipse v4.21 is nearly 18 months old.  If this plugin has been abandoned, I suggest documenting that.

**Comment by suztomo** [comment]
@bcwhite-code Thank you for the report. I'm able to reproduce the installation issue:

<img width="571" alt="Screenshot 2023-01-20 at 4 04 23 PM" src="https://user-images.githubusercontent.com/28604/213810761-76a22133-a51f-4fa5-8f3a-c6c3507a6eca.png">

We'll discuss the actions and will update this issue.

**Comment by suztomo** [comment]
The documentation https://cloud.google.com/eclipse/docs/quickstart has been updated to reflect that "Install the Eclipse IDE for Enterprise Java and Web Developers, version 4.8 - 4.21 (later versions are not supported)".

**Comment by ldhasson** [comment]
Is this going to be fixed? I mean, i have to update Eclipse to stay current. I can't be stuck with an 18-months old version.

**Comment by Ihernandezpi** [comment]
Same issue :(

**Comment by ldhasson** [comment]
Why was this closed? Is there no intention to fix? What should be people do who have a whole bunch of projects using that feature? What is the migration path for such projects to remove the dependency on the plugin, upgrade to the latest and greatest eclipse, and the app still works?

**Comment by bcwhite-code** [comment]
My read is that they've deprecated it internally.

It's also likely that, now that the bug is closed, nobody inside will see
our comments.  Best would be to open a new bug.

-- Brian
(sent from my Android; expect typos and brevity)
