### ISSUE TITLE
Integration test - Cannot modify a deleted project

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#594]
It may be that it is trying to do something on an already deleted project.

```
!ENTRY org.eclipse.ui 4 4 2016-08-19 15:16:11.555
!MESSAGE Plug-in 'org.eclipse.pde.ui' contributed an invalid Menu Extension (Path: 'org.eclipse.ui.projectConfigure' is invalid): org.eclipse.pde.ui.ConvertedProjectWizard
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x801bb6 (Delete Res)
Window manager warning: meta_window_activate called by a pager with a 0 timestamp; the pager needs to be fixed.
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x80001b (Java - Ecl)
Window manager warning: meta_window_activate called by a pager with a 0 timestamp; the pager needs to be fixed.
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x801ecb (New Projec)
Window manager warning: meta_window_activate called by a pager with a 0 timestamp; the pager needs to be fixed.
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x801f66 (User Opera)
Window manager warning: meta_window_activate called by a pager with a 0 timestamp; the pager needs to be fixed.
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x801ecb (New Maven-)
Window manager warning: meta_window_activate called by a pager with a 0 timestamp; the pager needs to be fixed.
[INFO] ----------------------------------------------------------------------------
[INFO] Using following parameters for creating project from Archetype: appengine-skeleton-archetype:2.1.0-1.9.38
[INFO] ----------------------------------------------------------------------------
[INFO] Parameter: groupId, Value: test
[INFO] Parameter: artifactId, Value: appWithPackage
[INFO] Parameter: version, Value: 0.1.0-SNAPSHOT
[INFO] Parameter: package, Value: app.engine.test
[INFO] Parameter: packageInPathFormat, Value: app/engine/test
[INFO] Parameter: gcloud-version, Value: 2.0.9.106.v20160420
[INFO] Parameter: appengine-version, Value: 1.9.37
[INFO] Parameter: application-id, Value: appWithPackage
[INFO] project created from Archetype in dir: /home/travis/build/GoogleCloudPlatform/gcloud-eclipse-tools/plugins/com.google.cloud.tools.eclipse.integration.appengine/target/work/data/appWithPackage
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x80001b (Java - Ecl)
Window manager warning: meta_window_activate called by a pager with a 0 timestamp; the pager needs to be fixed.
!ENTRY org.eclipse.ui 4 4 2016-08-19 15:16:17.249
!MESSAGE Plug-in 'org.eclipse.pde.ui' contributed an invalid Menu Extension (Path: 'org.eclipse.ui.projectConfigure' is invalid): org.eclipse.pde.ui.ConvertedProjectWizard
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x8020da (Delete Res)
Window manager warning: meta_window_activate called by a pager with a 0 timestamp; the pager needs to be fixed.
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x80001b (Java - Ecl)
Window manager warning: meta_window_activate called by a pager with a 0 timestamp; the pager needs to be fixed.
!ENTRY org.eclipse.wst.jsdt.web.core 4 4 2016-08-19 15:16:17.940
!MESSAGE Cannot modify a deleted project.
!STACK 1
org.eclipse.core.runtime.CoreException: Cannot modify a deleted project.
    at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.validateNotDeleted(FacetedProject.java:1863)
    at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.setTargetedRuntimesInternal(FacetedProject.java:673)
    at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.mergeChangesInternal(FacetedProject.java:1161)
    at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.access$2(FacetedProject.java:1117)
    at org.eclipse.wst.common.project.facet.core.internal.FacetedProject$5.run(FacetedProject.java:1099)
    at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2241)
    at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.mergeChanges(FacetedProject.java:1109)
    at org.eclipse.wst.common.project.facet.core.internal.FacetedProjectWorkingCopy.commitChanges(FacetedProjectWorkingCopy.java:2020)
    at org.eclipse.wst.jsdt.web.core.internal.project.ConvertJob.runInWorkspace(ConvertJob.java:66)
    at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
!SUBENTRY 1 org.eclipse.wst.common.project.facet.core 4 0 2016-08-19 15:16:17.940
!MESSAGE Cannot modify a deleted project.
Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 46.571 sec <<< FAILURE! - in com.google.cloud.tools.eclipse.integration.appengine.NewMavenBasedAppEngineProjectWizardTest
testGuestbookExampleNoProjectId(com.google.cloud.tools.eclipse.integration.appengine.NewMavenBasedAppEngineProjectWizardTest)  Time elapsed: 21.125 sec
testGuestbookExampleWithProjectId(com.google.cloud.tools.eclipse.integration.appengine.NewMavenBasedAppEngineProjectWizardTest)  Time elapsed: 19.352 sec
testHelloWorld(com.google.cloud.tools.eclipse.integration.appengine.NewMavenBasedAppEngineProjectWizardTest)  Time elapsed: 5.78 sec  <<< ERROR!
java.lang.NullPointerException: facetedProject is null
    at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:229)
    at com.google.cloud.tools.eclipse.util.FacetedProjectHelper.projectHasFacet(FacetedProjectHelper.java:31)
    at com.google.cloud.tools.eclipse.integration.appengine.NewMavenBasedAppEngineProjectWizardTest.createAndCheck(NewMavenBasedAppEngineProjectWizardTest.java:103)
    at com.google.cloud.tools.eclipse.integration.appengine.NewMavenBasedAppEngineProjectWizardTest.testHelloWorld(NewMavenBasedAppEngineProjectWizardTest.java:51)
Results :
Tests in error: 
  NewMavenBasedAppEngineProjectWizardTest.testHelloWorld:51->createAndCheck:103 » NullPointer
Tests run: 6, Failures: 0, Errors: 1, Skipped: 0
```

**Comment by chanseokoh** [comment]
Some job is executed later after a project is deleted? Do we also need to ensure that all jobs are finished before deleting a project?

**Comment by briandealwis** [comment]
I suspect that job is the install-facets job that's initiated after setting the App Engine runtime.  The `waitForIdle()` should ensure it's executed before the project-creation helper returns.

**Comment by chanseokoh** [comment]
Haven't seen for a while. Closing.

**Comment by akerekes** [comment]
I have seen this many times, quite recently as well, but tests pass, so I'm OK with keeping it closed.

**Comment by chanseokoh** [comment]
I think I should have changed the title. The error is in fact

```
java.lang.NullPointerException: facetedProject is null
    at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:229)
    at com.google.cloud.tools.eclipse.util.FacetedProjectHelper.projectHasFacet(FacetedProjectHelper.java:31)
    at com.google.cloud.tools.eclipse.integration.appengine.NewMavenBasedAppEngineProjectWizardTest.createAndCheck(NewMavenBasedAppEngineProjectWizardTest.java:103)
    at com.google.cloud.tools.eclipse.integration.appengine.NewMavenBasedAppEngineProjectWizardTest.testHelloWorld(NewMavenBasedAppEngineProjectWizardTest.java:51)
Results :
```

I thought for this problem, the deleted project could be a cause.

**Comment by briandealwis** [comment]
Hmm, this is being called within `createAndCheck()` within the test itself, before the project will be deleted.
