### ISSUE TITLE
Integration test - testGuestbookExampleNoProjectId:63->createAndCheck:109

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#595]
Investigate why that's null.

```
[INFO] ----------------------------------------------------------------------------
[INFO] Using following parameters for creating project from Archetype: appengine-skeleton-archetype:2.1.0-1.9.38
[INFO] ----------------------------------------------------------------------------
[INFO] Parameter: groupId, Value: test
[INFO] Parameter: artifactId, Value: appWithPackage
[INFO] Parameter: version, Value: 0.1.0-SNAPSHOT
[INFO] Parameter: package, Value: app.engine.test
[INFO] Parameter: packageInPathFormat, Value: app/engine/test
[INFO] Parameter: gcloud-version, Value: 2.0.9.106.v20160420
[INFO] Parameter: appengine-version, Value: 1.9.37
[INFO] Parameter: application-id, Value: appWithPackage
[INFO] project created from Archetype in dir: /home/travis/build/GoogleCloudPlatform/gcloud-eclipse-tools/plugins/com.google.cloud.tools.eclipse.integration.appengine/target/work/data/appWithPackage
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x80001b (data - Jav)
Window manager warning: meta_window_activate called by a pager with a 0 timestamp; the pager needs to be fixed.
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x801db1 (Delete Res)
Window manager warning: meta_window_activate called by a pager with a 0 timestamp; the pager needs to be fixed.
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x80001b (data - Jav)
Window manager warning: meta_window_activate called by a pager with a 0 timestamp; the pager needs to be fixed.
Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 77.656 sec <<< FAILURE! - in com.google.cloud.tools.eclipse.integration.appengine.NewMavenBasedAppEngineProjectWizardTest
testGuestbookExampleNoProjectId(com.google.cloud.tools.eclipse.integration.appengine.NewMavenBasedAppEngineProjectWizardTest)  Time elapsed: 42.674 sec  <<< FAILURE!
java.lang.AssertionError: null
    at org.junit.Assert.fail(Assert.java:86)
    at org.junit.Assert.assertTrue(Assert.java:41)
    at org.junit.Assert.assertFalse(Assert.java:64)
    at org.junit.Assert.assertFalse(Assert.java:74)
    at com.google.cloud.tools.eclipse.integration.appengine.NewMavenBasedAppEngineProjectWizardTest.createAndCheck(NewMavenBasedAppEngineProjectWizardTest.java:109)
    at com.google.cloud.tools.eclipse.integration.appengine.NewMavenBasedAppEngineProjectWizardTest.testGuestbookExampleNoProjectId(NewMavenBasedAppEngineProjectWizardTest.java:63)
testGuestbookExampleWithProjectId(com.google.cloud.tools.eclipse.integration.appengine.NewMavenBasedAppEngineProjectWizardTest)  Time elapsed: 7.891 sec
testHelloWorld(com.google.cloud.tools.eclipse.integration.appengine.NewMavenBasedAppEngineProjectWizardTest)  Time elapsed: 27.088 sec
Results :
Failed tests: 
  NewMavenBasedAppEngineProjectWizardTest.testGuestbookExampleNoProjectId:63->createAndCheck:109 null
```

**Comment by elharo** [comment]
@chanseokoh still relevant?

**Comment by chanseokoh** [comment]
This was a record of an instance of flaky tests. I think I've not seen this particular test failure recently.
