### ISSUE TITLE
Unable to connecto to Google Cloud SQL from development environment

### ISSUE THREAD

**Issue by NicolaSpreafico** [GoogleCloudPlatform/google-cloud-eclipse#615]
Hello,
I'm getting a python exception with a simple code which use JDBC driver to connect to Google Cloud SQL instances

At first I created a new `Hello World Example` Maven project.
I addes this dependency
```
<!-- https://mvnrepository.com/artifact/mysql/mysql-connector-java -->
<dependency>
	<groupId>mysql</groupId>
	<artifactId>mysql-connector-java</artifactId>
	<version>5.1.39</version>
</dependency>
```

And I created this sample code inside the `HelloAppEngine` servlet
```
private void testSql() throws ClassNotFoundException, SQLException {
	String driver = "com.mysql.jdbc.Driver";
	Class.forName(driver);

	String host = "xxxx";
	String schema = "xxxx";
	String user = "xxxx";
	String password = "xxxxx";
	String table = "xxxxx";

	Connection con = DriverManager.getConnection("jdbc:mysql://" + host + ":3306/" + schema, user, password);
	Statement cmd = con.createStatement();

	String qry = "SELECT * FROM " + table + " LIMIT 10";
	ResultSet res = cmd.executeQuery(qry);

	while (res.next()) {
		System.out.println(res.getInt("id"));
	}

	res.close();
	cmd.close();
	con.close();
}
```

There is a massive stacktrace when the DriverManager.getConnection method is hitted.

Here is the main stacktrace
```
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
	at com.mysql.jdbc.Util.getInstance(Util.java:387)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:917)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:896)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:885)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:860)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2330)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2083)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:806)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:410)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:328)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
	at java.sql.DriverManager.getConnection(DriverManager.java:215)
	at it.noovle.testsql.HelloAppEngine.testSql(HelloAppEngine.java:54)
```

And here is the original cause
```
com.google.appengine.tools.remoteapi.RemoteApiException: response was a python exception:
cgoogle.appengine.runtime.apiproxy_errors
ApplicationError
p0
(I1
tp1
Rp2
(dp3
S'application_error'
p4
I1
sS'error_detail'
p5
S'system_error:10049 error_detail:"Indirizzo richiesto non valido nel proprio contesto"'
(the english counterpart should be "request address not valid in its context")
p6
sb.
	at com.google.appengine.tools.development.devappserver2.RemoteRpc.call(RemoteRpc.java:65)
```

I first got this error from my main project (which I'm still try to make it run with this new plugin, I'm getting several errors which I'm opening different issues on this tracker, one by one I'm moving on). But after I made this simple test project without anything else I can relate that the error is genuine.

Due to a python error I can guess the problem is with GCloud installation itself (and not this plugin, or even my local PC configuration) but at first I would like to have a confirmation by other users.

**Comment by elharo** [comment]
@NicolaSpreafico I suspect this is not Eclipse specific. Have you tried it at the command line with maven?

**Comment by NicolaSpreafico** [comment]
Do you mean the `gcloud:run` command from the `gcloud-maven-plugin`?
Yes, I tried but I had blocking error starting the server in this way:
```
[INFO] <<< gcloud-maven-plugin:2.0.9.121.v20160815:run (default-cli) < package @ testsql <<<
[INFO] 
[INFO] --- gcloud-maven-plugin:2.0.9.121.v20160815:run (default-cli) @ testsql ---
[INFO] 
[INFO] Running gcloud app run...
[INFO] Creating staging directory in: C:\Users\Francesco\workspace_neon\testsql\target\appengine-staging
[INFO] Running appcfg --disable_update_check -A notused stage C:\Users\Francesco\workspace_neon\testsql\target/testsql-1 C:\Users\Francesco\workspace_neon\testsql\target\appengine-staging
Reading application configuration data...


Beginning interaction for module default...
0% Scanning for jsp files.
Success.
Temporary staging for module default directory left in C:\Users\Francesco\workspace_neon\testsql\target\appengine-staging
[INFO] Running python.exe -S C:\Users\Francesco\AppData\Local\Google\Cloud SDK\google-cloud-sdk/platform/google_appengine/dev_appserver.py --skip_sdk_update_check=true -A app C:\Users\Francesco\workspace_neon\testsql\target\testsql-1/app.yaml
[ERROR] 
org.apache.maven.plugin.MojoExecutionException: Could not start the dev app server
	at com.google.appengine.gcloudapp.AbstractGcloudMojo.startCommand(AbstractGcloudMojo.java:472)
	at com.google.appengine.gcloudapp.GCloudAppRun.execute(GCloudAppRun.java:280)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.io.IOException: Cannot run program "python.exe" (in directory "C:\Users\Francesco\workspace_neon\testsql\target\testsql-1"): CreateProcess error=2, Impossibile trovare il file specificato
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at com.google.appengine.gcloudapp.AbstractGcloudMojo.startCommand(AbstractGcloudMojo.java:392)
	... 23 more
Caused by: java.io.IOException: CreateProcess error=2, Impossibile trovare il file specificato
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 24 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.769 s
[INFO] Finished at: 2016-08-26T21:20:54+02:00
[INFO] Final Memory: 21M/268M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.google.appengine:gcloud-maven-plugin:2.0.9.121.v20160815:run (default-cli) on project testsql: Execution error: org.apache.maven.plugin.MojoExecutionException: Could not start the dev app server -> [Help 1]
[ERROR] 
```

I thought was because I did not have the python folder inside my `PATH` variable, so I added the `C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\bundledpython` folder to the `PATH`.
The `python.exe` line is correct, if I use that directly from the cmd-prompt I get the python instance
```
C:\Users\Francesco>python.exe
Python 2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

So I tried the maven command again and the server started
```
[INFO] <<< gcloud-maven-plugin:2.0.9.121.v20160815:run (default-cli) < package @ testsql <<<
[INFO] 
[INFO] --- gcloud-maven-plugin:2.0.9.121.v20160815:run (default-cli) @ testsql ---
[INFO] 
[INFO] Running gcloud app run...
[INFO] Creating staging directory in: C:\Users\Francesco\workspace_neon\testsql\target\appengine-staging
[INFO] Running appcfg --disable_update_check -A notused stage C:\Users\Francesco\workspace_neon\testsql\target/testsql-1 C:\Users\Francesco\workspace_neon\testsql\target\appengine-staging
Reading application configuration data...


Beginning interaction for module default...
0% Scanning for jsp files.
Success.
Temporary staging for module default directory left in C:\Users\Francesco\workspace_neon\testsql\target\appengine-staging
[INFO] Running python.exe -S C:\Users\Francesco\AppData\Local\Google\Cloud SDK\google-cloud-sdk/platform/google_appengine/dev_appserver.py --skip_sdk_update_check=true -A app C:\Users\Francesco\workspace_neon\testsql\target\testsql-1/app.yaml
[INFO] INFO     2016-08-26 21:26:49,526 devappserver2.py:769] Skipping SDK update check.
[INFO] WARNING  2016-08-26 21:26:50,575 simple_search_stub.py:1146] Could not read search indexes from c:\users\france~1\appdata\local\temp\appengine.app\search_indexes
[INFO] INFO     2016-08-26 21:26:50,582 api_server.py:205] Starting API server at: http://localhost:55261
[INFO] INFO     2016-08-26 21:26:50,588 dispatcher.py:197] Starting module "default" running at: http://localhost:8080
[INFO] INFO     2016-08-26 21:26:50,592 admin_server.py:116] Starting admin server at: http://localhost:8000
[INFO] ago 26, 2016 9:26:52 PM com.google.appengine.tools.development.SystemPropertiesManager setSystemProperties
..... more server start log .....
```

I hitted the test servlet and indeed the error is still there
```
Caused by: com.google.appengine.tools.remoteapi.RemoteApiException: response was a python exception:
cgoogle.appengine.runtime.apiproxy_errors
ApplicationError
p0
(I1
tp1
Rp2
(dp3
S'application_error'
p4
I1
sS'error_detail'
p5
S'system_error:10049 error_detail:"Indirizzo richiesto non valido nel proprio contesto"'
p6
sb.
	at com.google.appengine.tools.development.devappserver2.RemoteRpc.call(RemoteRpc.java:65)
	at com.google.appengine.tools.development.devappserver2.RemoteApiDelegate.makeSyncCall(RemoteApiDelegate.java:45)
	at com.google.appengine.tools.development.devappserver2.DevAppServer2Delegate.makeSyncCall(DevAppServer2Delegate.java:58)
	at com.google.apphosting.api.ApiProxy.makeSyncCall(ApiProxy.java:118)
	at com.google.apphosting.api.ApiProxy.makeSyncCall(ApiProxy.java:67)
	at com.google.appengine.api.socket.SocketApiHelper.apiProxyMakeSyncCall(SocketApiHelper.java:81)
	at com.google.appengine.api.socket.SocketApiHelper.makeSyncCall(SocketApiHelper.java:52)
	at com.google.appengine.api.socket.AppEngineSocketImpl.connectSocket(AppEngineSocketImpl.java:397)
	at com.google.appengine.api.socket.AppEngineSocketImpl.connectToAddress(AppEngineSocketImpl.java:348)
	at com.google.appengine.api.socket.AppEngineSocketImpl.connect(AppEngineSocketImpl.java:332)
	at java.net.Socket.connect(Socket.java:579)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:211)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:300)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2251)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2284)
```

This is a confirmation that the problem is gcloud related, and not strictly to Eclipse.
Thanks you on suggesting the alternative way on start the server.

**Comment by patflynn** [comment]
Could this be because the user hasn't exported application default
credentials?

https://developers.google.com/identity/protocols/application-default-credentials

**Comment by NicolaSpreafico** [comment]
Hello @patflynn ,
I did configured the application-default-credentials,
```
:\WINDOWS\system32>gcloud beta auth application-default login
Your browser has been opened to visit:

    https://accounts.google.com/o/oauth2/auth?redirect_uri=.............&access_type=offline



Application Default Credentials are now saved, and will
use the provided account.

This does not affect any credentials that you may have
set up for the Google Cloud SDK.
```
but the error remains the same

**Comment by patflynn** [comment]
OK. Thanks Nicola.

**Comment by rdayal** [comment]
Should we close this issue since it's not specifically Eclipse related and re-open an issue on the Cloud SDK issue tracker?

**Comment by rdayal** [comment]
https://code.google.com/p/google-cloud-sdk/issues/list

**Comment by elharo** [comment]
filed as https://code.google.com/p/google-cloud-sdk/issues/detail?id=1221&thanks=1221&ts=1475719515

**Comment by vilasj** [comment]
Turns out this is not a Cloud SDK issue and is WAI. However, there could perhaps be better tool support to detect this issue for the user and/or help overcome it.
