### ISSUE TITLE
[Travis] Test failure: problems view has errors

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#665]
We've had a couple of jobs fail with the following exception; forcing a rebuild sometimes works.  The failure line corresponds to a check that the "Problems" view has no errors.

```
testGuestbookExampleWithProjectId(com.google.cloud.tools.eclipse.integration.appengine.NewMavenBasedAppEngineProjectWizardTest)  Time elapsed: 19.998 sec  <<< FAILURE!
java.lang.AssertionError: null
    at org.junit.Assert.fail(Assert.java:86)
    at org.junit.Assert.assertTrue(Assert.java:41)
    at org.junit.Assert.assertFalse(Assert.java:64)
    at org.junit.Assert.assertFalse(Assert.java:74)
    at com.google.cloud.tools.eclipse.integration.appengine.NewMavenBasedAppEngineProjectWizardTest.createAndCheck(NewMavenBasedAppEngineProjectWizardTest.java:111)
```

**Comment by briandealwis** [comment]
We now have `SwtBotProjectActions#getAllBuildErrors()` that returns a list of all error markers.
