### ISSUE TITLE
No app id supplied and XML files have no <application> element

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#737]
Appears we may not be providing the project ID on deploy as expected:

$ more /var/folders/w7/bslwhm5548g8lk3qb0q1c2080028bc/T/appcfg417199038230121024.log
com.google.apphosting.utils.config.AppEngineConfigException: No app id supplied and XML files have no <application> element
        at com.google.appengine.tools.admin.Application.<init>(Application.java:234)
        at com.google.appengine.tools.admin.Application.readApplication(Application.java:421)
        at com.google.appengine.tools.admin.AppCfg.readWar(AppCfg.java:297)
        at com.google.appengine.tools.admin.AppCfg.readApplication(AppCfg.java:288)
        at com.google.appengine.tools.admin.AppCfg.<init>(AppCfg.java:217)
        at com.google.appengine.tools.admin.AppCfg.<init>(AppCfg.java:119)
        at com.google.appengine.tools.admin.AppCfg.main(AppCfg.java:115)

**Comment by elharo** [comment]
see here: https://github.com/GoogleCloudPlatform/app-maven-plugin/issues/67

**Comment by elharo** [comment]
Waiting on a release of gcloud/appcfg to fix this.

**Comment by rdayal** [comment]
We need a new release of the App Engine SDK to fix this, right?

**Comment by elharo** [comment]
Correct. This has been blocked on the release of 1.9.44 for a while.

**Comment by elharo** [comment]
fixed now that gcloud 131.0 is out
