### ISSUE TITLE
com.google.cloud.tools.eclipse.appengine.newproject.CreateAppEngineStandardWtpProjectTest.testUnitTestCreated() flaky

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/google-cloud-eclipse#743]
This test seems to be flaky.

```
testUnitTestCreated(com.google.cloud.tools.eclipse.appengine.newproject.CreateAppEngineStandardWtpProjectTest)  Time elapsed: 14.056 sec  <<< ERROR!
java.lang.NullPointerException: null
    at com.google.cloud.tools.eclipse.appengine.newproject.CreateAppEngineStandardWtpProjectTest.assertJunitAndHamcrestAreOnClasspath(CreateAppEngineStandardWtpProjectTest.java:79)
    at com.google.cloud.tools.eclipse.appengine.newproject.CreateAppEngineStandardWtpProjectTest.testUnitTestCreated(CreateAppEngineStandardWtpProjectTest.java:72)
```

**Comment by elharo** [comment]
Tests in error: 
  CreateAppEngineStandardWtpProjectTest.testAppEngineLibrariesAdded:95 » Core Pr...
  CreateAppEngineStandardWtpProjectTest.testUnitTestCreated:78->assertJunitAndHamcrestAreOnClasspath:85 NullPointer

Tests run: 36, Failures: 0, Errors: 2, Skipped: 0


!ENTRY org.eclipse.jdt.core 4 4 2016-09-30 16:58:13.575
!MESSAGE Error while creating a link for external folder :/home/travis/build/GoogleCloudPlatform/google-cloud-eclipse/plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/target/work/configuration/org.eclipse.osgi/424/0/.cp/
!STACK 1
org.eclipse.core.internal.resources.ResourceException: Cannot create linked resource '/.org.eclipse.jdt.core.external.folders/.link4'.  The parent resource is not accessible.
	at org.eclipse.core.internal.resources.Resource.assertLinkRequirements(Resource.java:175)
	at org.eclipse.core.internal.resources.Resource.createLink(Resource.java:658)
	at org.eclipse.core.internal.resources.Resource.createLink(Resource.java:632)
	at org.eclipse.jdt.internal.core.ExternalFoldersManager.createLinkFolder(ExternalFoldersManager.java:177)
	at org.eclipse.jdt.internal.core.ExternalFoldersManager.createPendingFolders(ExternalFoldersManager.java:206)
	at org.eclipse.jdt.core.JavaCore.initializeAfterLoad(JavaCore.java:4240)
	at org.eclipse.jdt.internal.ui.InitializeAfterLoadJob$RealJob.run(InitializeAfterLoadJob.java:36)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
!SUBENTRY 1 org.eclipse.core.resources 4 77 2016-09-30 16:58:13.575
!MESSAGE Cannot create linked resource '/.org.eclipse.jdt.core.external.folders/.link4'.  The parent resource is not accessible.

!ENTRY org.eclipse.jdt.core 4 4 2016-09-30 16:58:13.576
!MESSAGE Error while creating a link for external folder :/home/travis/build/GoogleCloudPlatform/google-cloud-eclipse/plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/target/work/configuration/org.eclipse.osgi/403/0/.cp/
!STACK 1
org.eclipse.core.internal.resources.ResourceException: Cannot create linked resource '/.org.eclipse.jdt.core.external.folders/.link5'.  The parent resource is not accessible.
	at org.eclipse.core.internal.resources.Resource.assertLinkRequirements(Resource.java:175)
	at org.eclipse.core.internal.resources.Resource.createLink(Resource.java:658)
	at org.eclipse.core.internal.resources.Resource.createLink(Resource.java:632)
	at org.eclipse.jdt.internal.core.ExternalFoldersManager.createLinkFolder(ExternalFoldersManager.java:177)
	at org.eclipse.jdt.internal.core.ExternalFoldersManager.createPendingFolders(ExternalFoldersManager.java:206)
	at org.eclipse.jdt.core.JavaCore.initializeAfterLoad(JavaCore.java:4240)
	at org.eclipse.jdt.internal.ui.InitializeAfterLoadJob$RealJob.run(InitializeAfterLoadJob.java:36)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
!SUBENTRY 1 org.eclipse.core.resources 4 77 2016-09-30 16:58:13.576
!MESSAGE Cannot create linked resource '/.org.eclipse.jdt.core.external.folders/.link5'.  The parent resource is not accessible.

**Comment by elharo** [comment]
It seems to consistently be a problem on neon, oraclejdk8, and push.

**Comment by elharo** [comment]
perhaps relevant: https://bugs.eclipse.org/bugs/show_bug.cgi?id=241400

**Comment by elharo** [comment]
http://nerdposts.blogspot.com/2009/11/android-cannot-create-linked-resource.html suggests deleting and recreating the workspace. Maybe we can do that in setup/tearDown?

Any chance the workspace is shared between test methods in the same class? We could try moving the methods to different classes.

**Comment by briandealwis** [comment]
I wonder if this is related to the Travis matrix change in #720

**Comment by briandealwis** [comment]
> Any chance the workspace is shared between test methods in the same class? We could try moving the methods to different classes.

They're definitely shared: the workbench/workspace is present for the duration of the tests for that project

**Comment by briandealwis** [comment]
I wonder if we're deleting the folder too early, and the error is from a pending job that started executing later?  We may just need something like our [`SwtBotWorkbenchActions#waitForlIdle()`](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/master/plugins/com.google.cloud.tools.eclipse.swtbot/src/com/google/cloud/tools/eclipse/swtbot/SwtBotWorkbenchActions.java#L68):
```
public static void waitForIdle(SWTBot bot) {
    while (!Job.getJobManager().isIdle()) {
      bot.sleep(300);
    }
  }
```

**Comment by elharo** [comment]
Maybe related to #720, though the failures seem limited to two methods introduced in #744

**Comment by elharo** [comment]
FYI, I'm now seeing some builds that pass on oraclejdk8 and fail on openjdk7, so it may not be a JDK issue, just random flakiness.

**Comment by elharo** [comment]
I don't see any pending jobs. That is, I think CreateAppEngineStandardWtpProject is fairly synchronous. That said, I've changed the code to give a new name to the project for each test, so even if the old one isn't finished being deleted the new one can still be created.

**Comment by elharo** [comment]
seems to be cured these days, at least on travis
