### ISSUE TITLE
StringIndex out of bounds when entering Maven group ID

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#801]
To reproduce:

1. Open maven new project wizard
2. Type a letter into the group ID field.
3. Type a space into the group ID field.
3. Type another letter.

java.lang.StringIndexOutOfBoundsException: String index out of range: 2
	at java.lang.String.substring(String.java:1963)
	at com.google.cloud.tools.eclipse.appengine.newproject.maven.MavenAppEngineStandardWizardPage$AutoPackageNameSetterOnGroupIdChange.verifyText(MavenAppEngineStandardWizardPage.java:365)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:273)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4230)

**Comment by elharo** [comment]
Relevant code:

  private final class AutoPackageNameSetterOnGroupIdChange implements VerifyListener {
    @Override
    public void verifyText(VerifyEvent event) {
      // Below explains how to get text after modification:
      // http://stackoverflow.com/questions/32872249/get-text-of-swt-text-component-before-modification
      String newGroupId =
          getGroupId().substring(0, event.start) + event.text + getGroupId().substring(event.end);

      String oldPackageName = suggestPackageName(getGroupId());
      String newPackageName = suggestPackageName(newGroupId);
      adjustPackageName(oldPackageName, newPackageName);
    }
  }
