### ISSUE TITLE
Unterminatable dev_appserver.py

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#942]
Even after fixing #393, we cannot run two local servers simultaneously, since subsequent servers will try to use the same datastore that the first server is using. When the second server starts, it will seem to successfully go live initially. But after several seconds, the server goes down (STOPPED state in Eclipse) showing the following error:

`OperationalError: database is locked`

Note that this database lock is expected; it is said that dev_appserver.py is not designed to run concurrently, and we won't try to fix it.

The problem is that, the python process of the servers will not terminate, while they are marked as "stopped" in Eclipse. Terminating Eclipse doesn't terminate them either. Users have to kill the processes manually.

**Comment by briandealwis** [comment]
Similar problem seen if attempting to debug a server with an invalid Google Cloud SDK.  The launch fails silently, with the following on the log:

```
!ENTRY com.google.cloud.tools.eclipse.appengine.localserver 4 1 2016-11-03 15:52:17.259
!MESSAGE Google Cloud SDK: Error starting server: Validation Error: gcloud location '/tmp/bin/gcloud' is not a file.
Nov 03, 2016 3:52:17 PM com.google.cloud.tools.eclipse.appengine.localserver.server.LocalAppEngineServerBehaviour stop
WARNING: Error terminating server: java.net.ConnectException: Connection refused
com.google.cloud.tools.appengine.api.AppEngineException: java.net.ConnectException: Connection refused
	at com.google.cloud.tools.appengine.cloudsdk.CloudSdkAppEngineDevServer.stop(CloudSdkAppEngineDevServer.java:129)
	at com.google.cloud.tools.eclipse.appengine.localserver.server.LocalAppEngineServerBehaviour.stop(LocalAppEngineServerBehaviour.java:89)
	at com.google.cloud.tools.eclipse.appengine.localserver.server.LocalAppEngineServerBehaviour.startDebugDevServer(LocalAppEngineServerBehaviour.java:252)
	at com.google.cloud.tools.eclipse.appengine.localserver.server.LocalAppEngineServerLaunchConfigurationDelegate.launch(LocalAppEngineServerLaunchConfigurationDelegate.java:110)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:885)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:739)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:731)
	at org.eclipse.wst.server.core.internal.Server.startImpl2(Server.java:3556)
	at org.eclipse.wst.server.core.internal.Server.startImpl(Server.java:3492)
	at org.eclipse.wst.server.core.internal.Server$StartJob.run(Server.java:367)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
	at com.google.cloud.tools.appengine.cloudsdk.CloudSdkAppEngineDevServer.stop(CloudSdkAppEngineDevServer.java:121)
	... 10 more
```

And an unterminatable launch in the _Debug_ view.

**Comment by chanseokoh** [comment]
As a note https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/942#issue-187178649 and https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/942#issuecomment-258262378 are a bit different. For example, in the database lock issue, you can successfully stop and _delete_ a server in Eclipse, but the dev_appserver.py will still run on the machine.

**Comment by chanseokoh** [comment]
FTR, a discussion about why we don't fix the database lock issue itself can be found in #937.

**Comment by briandealwis** [comment]
An `Launch` can only be terminated if it has a terminatable `IProcess` or `IDebugTarget` (viz `org.eclipse.debug.core.Launch#canTerminate()`).  In these cases we have no process nor debug target associated, resulting in a zombie launch.

The cause is that in _debug_ mode, we only associate a launch to a process or debug target once the remote VM connects back to us.  We don't actually record any information about the `dev_appserver` process.  If something occurs prevents a VM from connecting back, then our launch has no associated information and becomes a zombie.

We could follow what we do in the _run_ mode and [always associate an `IDebugTarget`](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/master/plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerLaunchConfigurationDelegate.java#L113).

**Comment by chanseokoh** [comment]
My guess for the bug in the database lock case is like this (needs verification):

The output listener checks a specific line to determine if an error happened: https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/master/plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerBehaviour.java#L311

We set the server state to STOPPED with the assumption that the dev_appserver.py process is terminated when an error occurs. The assumption is true in some cases, but not always. In the database lock case, the server is active and serves HTTP requests (although it will return 500).

**Comment by briandealwis** [comment]
> We could follow what we do in the run mode and always associate an IDebugTarget.

I did this.  Our current `LocalAppEngineDebugTarget` currently shows the server name (_gwt single module_ in the screenshot below).
<img width="341" alt="screen shot 2016-11-04 at 11 29 25 pm" src="https://cloud.githubusercontent.com/assets/202851/20027295/add648f8-a2e6-11e6-9424-08a03caaf325.PNG">

We could rename this entry to indicate that it's the server application, or prepend _dev_appserver_.  Debug targets do support a properties page and we could include additional information such as the command-line used:

<img width="766" alt="screen shot 2016-11-04 at 11 32 43 pm" src="https://cloud.githubusercontent.com/assets/202851/20027319/2a4de698-a2e7-11e6-8d6c-d7f9f11d3d7a.PNG">

**Comment by branflake2267** [comment]
https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/915 - this may be related too.

**Comment by chanseokoh** [comment]
For clarification at this point, this issue actually contains two different issues:

- one reported by me related to the database lock, and ;
- the other reported by @briandealwis related to an invalid Cloud SDK.

The causes for these two are different, and the solutions for these will be different.
