### ISSUE TITLE
Silent failure when creating new native project with no Google Cloud SDK found on PATH

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#992]
This is the same situation when a user doesn't have a Google Cloud SDK installed.

The `appEngineJavaComponentExists()` implementations in #868 need to catch `AppEngineException` too.

Steps to repeat:

  1. Install new Eclipse with _Cloud Tools for Eclipse_
  2. Do not have _Google Cloud SDK_ in a standard location. Do not set `GOOGLE_CLOUD_SDK_HOME`.
  3. Start Eclipse
  4. _File > New > Google Cloud Platform > Google App Engine Standard Java Project_.

Nothing happens: the wizard doesn't progress, and there are no UI messages.  On the console, I see:

```
!ENTRY org.eclipse.ui 4 0 2016-11-17 15:50:28.663
!MESSAGE Unhandled event loop exception
!STACK 0
com.google.cloud.tools.appengine.api.AppEngineException: Google Cloud SDK path was not provided and could not be found in any known install locations.
	at com.google.cloud.tools.appengine.cloudsdk.CloudSdk$Builder.discoverSdkPath(CloudSdk.java:543)
	at com.google.cloud.tools.appengine.cloudsdk.CloudSdk$Builder.build(CloudSdk.java:485)
	at com.google.cloud.tools.eclipse.appengine.newproject.StandardProjectWizard.appEngineJavaComponentExists(StandardProjectWizard.java:119)
	at com.google.cloud.tools.eclipse.appengine.newproject.StandardProjectWizard.addPages(StandardProjectWizard.java:52)
	at org.eclipse.jface.wizard.WizardSelectionPage.getNextPage(WizardSelectionPage.java:116)
	at org.eclipse.ui.internal.dialogs.WorkbenchWizardSelectionPage.getNextPage(WorkbenchWizardSelectionPage.java:98)
	at org.eclipse.jface.wizard.WizardDialog.nextPressed(WizardDialog.java:869)
	at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:419)
	at org.eclipse.jface.dialogs.Dialog$2.widgetSelected(Dialog.java:618)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
```

**Comment by elharo** [comment]
I cannot reproduce this. I see

![image](https://cloud.githubusercontent.com/assets/1005544/20433462/acee3b2c-ad71-11e6-86ec-da95c06103e3.png)

**Comment by elharo** [comment]
I do suspect this should not be a yes-no dialog though. If you click no, you get an incorrect error message on the next page and are blocked from proceeding:

![image](https://cloud.githubusercontent.com/assets/1005544/20433541/064f88ba-ad72-11e6-848b-01e0f59cd711.png)

**Comment by briandealwis** [comment]
Ah, I hit this when installing the signed version into a brand-new Eclipse install.  That build must have been old. I can't reproduce when running from source.

**Comment by elharo** [comment]
Likely, that was a very old build from an unmerged branch. However there are some problems here I want to resolve.
